import type { LearningSessionDocument } from "./types.ts";
import { ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT, ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT, ACTE_UNION_BERMUDA_EXILE_DOCUMENT, ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT, ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT, ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT, ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT, ACTE_UNION_MAP_ADAPTATION_DRAFT, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT, ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT, ACTE_UNION_RUSSELL_POINT_OF_VIEW_DOCUMENT, PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT, PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT, PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT } from "../pedagogical-reference/historical-document-needs.ts";
import { ACTE_UNION_DURHAM_DOCUMENT, ACTE_UNION_DURHAM_PRESENTATIONS } from "../pedagogical-reference/historical-document-presentations.ts";
import { ACTE_UNION_DEBT_COMPARISON_CHART } from "../pedagogical-reference/historical-comparison-charts.ts";
import { ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM, ACTE_UNION_STUDENT_TIMELINE } from "../pedagogical-reference/responsible-government-iconography.ts";

const PUBLIC_DOMAIN_RIGHTS = "Texte original de 1840 dans le domaine public.";

const REBELLION_DOCUMENT_TYPE_LABELS: Record<string, string> = {
  "AU-T-006": "Suspension du régime représentatif",
  "AU-T-009": "Données sur les Patriotes emprisonnés",
};

export const ACTE_UNION_DURHAM_EXCERPT_DOCUMENTS: LearningSessionDocument[] = ACTE_UNION_DURHAM_PRESENTATIONS.map((presentation) => ({
  id: presentation.id,
  title: presentation.title,
  typeLabel: "Extrait du rapport Durham",
  dateLabel: ACTE_UNION_DURHAM_DOCUMENT.historicalDate,
  authorLabel: ACTE_UNION_DURHAM_DOCUMENT.creator,
  institutionLabel: ACTE_UNION_DURHAM_DOCUMENT.holdingInstitution,
  originalDocumentLabel: ACTE_UNION_DURHAM_DOCUMENT.title,
  sourceLabel: `${ACTE_UNION_DURHAM_DOCUMENT.sourceLocator} · ${presentation.sourceSegmentLocators.join(" · ")}`,
  sourceUrls: [...presentation.sourceUrls],
  rightsLabel: ACTE_UNION_DURHAM_DOCUMENT.rightsStatement,
  editorialNote: presentation.editorialNote,
  content: { kind: "historical_excerpt", excerpt: presentation.studentText },
  historicalKnowledgeIds: ["contexte-acte-union", "rapport-durham", "acte-union-1840"],
  intellectualOperationIds: [...presentation.operationIds],
}));

export const ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENTS: LearningSessionDocument[] = [ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT, ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT, ACTE_UNION_BERMUDA_EXILE_DOCUMENT, ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT].map((document) => ({
  id: document.id,
  title: document.title,
  typeLabel: REBELLION_DOCUMENT_TYPE_LABELS[document.id] ?? "Document sur les conséquences des Rébellions",
  dateLabel: document.historicalDate,
  authorLabel: document.creator,
  institutionLabel: document.holdingInstitution,
  sourceLabel: document.sourceLocator,
  sourceUrls: [document.sourceUrl, document.assetUrl],
  rightsLabel: document.rightsStatement,
  editorialNote: document.interpretationCautions[0],
  content: { kind: "historical_excerpt", excerpt: document.transcription },
  historicalKnowledgeIds: ["rebellions-1837-1838", "consequences-rebellions", "contexte-acte-union"],
  intellectualOperationIds: [...document.operationIds],
}));

export const ACTE_UNION_DOCUMENTS: LearningSessionDocument[] = [
  {
    id: ACTE_UNION_DEBT_COMPARISON_CHART.id, title: ACTE_UNION_DEBT_COMPARISON_CHART.title, typeLabel: ACTE_UNION_DEBT_COMPARISON_CHART.typeLabel, dateLabel: ACTE_UNION_DEBT_COMPARISON_CHART.dateLabel,
    sourceLabel: ACTE_UNION_DEBT_COMPARISON_CHART.sourceLabel, sourceUrls: [ACTE_UNION_DEBT_COMPARISON_CHART.sourceUrl], rightsLabel: "Présentation Socrato fondée sur des données historiques du domaine public.", editorialNote: ACTE_UNION_DEBT_COMPARISON_CHART.methodology,
    content: { kind: "comparison_table", caption: "Dette publique des deux colonies au moment de l’Union", headers: ["Colonie", "Dette publique"], rows: ACTE_UNION_DEBT_COMPARISON_CHART.items.map(({ label, displayValue }) => ({ label, value: displayValue })) },
    historicalKnowledgeIds: ["acte-union", "dette-publique"], intellectualOperationIds: ["differences_and_similarities", "relationships_between_facts", "causal_connections"],
  },
  {
    id: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id, title: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.title, typeLabel: "Schéma politique", dateLabel: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.historicalDate, authorLabel: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.creator,
    sourceLabel: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.sourceLocator, sourceUrls: [ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.sourceUrl], rightsLabel: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.rightsStatement, editorialNote: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.interpretationCautions[0],
    content: { kind: "political_structure_diagram" },
    historicalKnowledgeIds: ["acte-union", "institutions-politiques"], intellectualOperationIds: [...ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.operationIds],
  },
  {
    id: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.id,
    title: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.title,
    typeLabel: "Extrait d’un texte législatif",
    dateLabel: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.historicalDate,
    authorLabel: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.creator,
    institutionLabel: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.holdingInstitution,
    originalDocumentLabel: "Acte d’Union de 1840 — articles 50 et 56",
    sourceLabel: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.sourceLocator,
    sourceUrls: [ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.sourceUrl, ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.assetUrl],
    rightsLabel: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.rightsStatement,
    editorialNote: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.interpretationCautions[0],
    content: { kind: "historical_excerpt", excerpt: ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.transcription },
    historicalKnowledgeIds: ["acte-union", "fonds-revenus-reunis", "dette-publique"],
    intellectualOperationIds: [...ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.operationIds],
  },
  {
    id: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.id,
    title: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.title,
    typeLabel: "Extrait d’une lettre politique",
    dateLabel: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.historicalDate,
    authorLabel: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.creator,
    institutionLabel: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.holdingInstitution,
    originalDocumentLabel: "Lettre de Francis Hincks à Louis-Hippolyte La Fontaine",
    sourceLabel: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.sourceLocator,
    sourceUrls: [ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.sourceUrl],
    rightsLabel: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.rightsStatement,
    editorialNote: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.interpretationCautions[0],
    content: { kind: "historical_excerpt", excerpt: ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.transcription },
    historicalKnowledgeIds: ["acte-union", "gouvernement-responsable", "alliance-reformiste"],
    intellectualOperationIds: [...ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.operationIds],
  },
  {
    id: ACTE_UNION_STUDENT_TIMELINE.id, title: ACTE_UNION_STUDENT_TIMELINE.title, typeLabel: "Ligne du temps", dateLabel: ACTE_UNION_STUDENT_TIMELINE.periodLabel, authorLabel: ACTE_UNION_STUDENT_TIMELINE.creator,
    sourceLabel: "Ligne du temps pédagogique Socrato composée à partir des sources indiquées pour chaque événement.", sourceUrls: ACTE_UNION_STUDENT_TIMELINE.entries.map(({ sourceUrl }) => sourceUrl), rightsLabel: ACTE_UNION_STUDENT_TIMELINE.rightsStatement, editorialNote: ACTE_UNION_STUDENT_TIMELINE.interpretationCautions[0],
    content: { kind: "historical_timeline", entries: ACTE_UNION_STUDENT_TIMELINE.entries.map(({ date, phase, title, description, imageUrl, imageAlt, credit }) => ({ date, phase, title, description, imageUrl, imageAlt, credit })) },
    historicalKnowledgeIds: ["acte-union", "gouvernement-responsable"], intellectualOperationIds: [...ACTE_UNION_STUDENT_TIMELINE.operationIds],
  },
  ...ACTE_UNION_DURHAM_EXCERPT_DOCUMENTS,
  ...ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENTS,
  ...[ACTE_UNION_RUSSELL_POINT_OF_VIEW_DOCUMENT, ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT].map((document) => ({
    id: document.id,
    title: document.title,
    typeLabel: "Extrait d’un texte politique",
    dateLabel: document.historicalDate,
    authorLabel: document.creator,
    institutionLabel: document.holdingInstitution,
    sourceLabel: document.sourceLocator,
    sourceUrls: [document.sourceUrl, document.assetUrl],
    rightsLabel: document.rightsStatement,
    editorialNote: document.interpretationCautions[0],
    content: { kind: "historical_excerpt" as const, excerpt: document.transcription },
    historicalKnowledgeIds: ["acte-union", "points-de-vue-sur-union"],
    intellectualOperationIds: ["differences_and_similarities", "relationships_between_facts"],
  })),
  {
    id: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id, title: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.title, typeLabel: "Extrait d’un texte législatif", dateLabel: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.historicalDate, authorLabel: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.creator, institutionLabel: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.holdingInstitution,
    sourceLabel: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.sourceLocator, sourceUrls: [ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.sourceUrl, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.assetUrl], rightsLabel: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.rightsStatement, editorialNote: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.interpretationCautions[0],
    content: { kind: "historical_excerpt", excerpt: ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.transcription }, historicalKnowledgeIds: ["acte-union", "province-du-canada"], intellectualOperationIds: [...ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.operationIds],
  },
  {
    id: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.id,
    title: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.title,
    typeLabel: "Extrait adapté d’un texte législatif",
    dateLabel: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.historicalDate,
    authorLabel: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.creator,
    institutionLabel: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.holdingInstitution,
    sourceLabel: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.sourceLocator,
    sourceUrls: [ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.sourceUrl, ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.assetUrl],
    rightsLabel: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.rightsStatement,
    editorialNote: "Adaptation pédagogique assemblée par Socrato à partir de l’article 41.",
    content: { kind: "historical_excerpt", excerpt: ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.transcription },
    historicalKnowledgeIds: ["acte-union-1840", "langue-officielle", "canada-est"],
    intellectualOperationIds: [...ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.operationIds],
  },
  {
    id: ACTE_UNION_MAP_ADAPTATION_DRAFT.id,
    title: ACTE_UNION_MAP_ADAPTATION_DRAFT.title,
    typeLabel: "Carte historique modifiée",
    dateLabel: "Vers 1842",
    authorLabel: "James Wyld",
    institutionLabel: "The Huntington Library",
    originalDocumentLabel: "Map of the Province of Canada",
    sourceLabel: ACTE_UNION_MAP_ADAPTATION_DRAFT.attribution,
    sourceUrls: [ACTE_UNION_MAP_ADAPTATION_DRAFT.sourceUrl, ACTE_UNION_MAP_ADAPTATION_DRAFT.cartographicReferenceUrl],
    rightsLabel: ACTE_UNION_MAP_ADAPTATION_DRAFT.rightsAssessment,
    editorialNote: "Carte de Wyld modifiée à des fins pédagogiques; les aplats et les frontières représentées sont approximatifs.",
    content: { kind: "historical_image", localSrc: ACTE_UNION_MAP_ADAPTATION_DRAFT.previewUrl, alt: "Carte de Wyld modifiée montrant le Canada-Est, le Canada-Ouest, la Terre de Rupert, le Nouveau-Brunswick et les États-Unis.", description: "Le Canada-Est et le Canada-Ouest sont représentés comme deux sections territoriales de la Province du Canada." },
    historicalKnowledgeIds: ["acte-union-1840", "province-du-canada", "canada-est-canada-ouest"],
    intellectualOperationIds: ["time_and_space", "establish_facts"],
  },
  {
    id: "acte-union-population-table",
    title: "Population des deux Canadas au moment de l’Acte d’union",
    typeLabel: "Tableau comparatif",
    sourceLabel: "Débat à la Chambre des lords britannique, 30 juin 1840; Acte d’union, 1840.",
    sourceUrls: [],
    rightsLabel: PUBLIC_DOMAIN_RIGHTS,
    content: {
      kind: "population_table",
      rows: [
        { region: "Canada-Est", population: "environ 700 000 à 800 000 habitants", representatives: "42 députés" },
        { region: "Canada-Ouest", population: "environ 200 000 à 300 000 habitants", representatives: "42 députés" },
      ],
    },
    historicalKnowledgeIds: ["acte-union-1840", "populations-bas-haut-canada", "institutions-politiques"],
    intellectualOperationIds: ["establish_facts", "relate_facts"],
  },
  {
    id: "gosford-equal-representation",
    title: "Le comte de Gosford critique la représentation égale",
    typeLabel: "Extrait d’un débat parlementaire",
    dateLabel: "30 juin 1840",
    authorLabel: "Earl of Gosford",
    institutionLabel: "House of Lords",
    sourceLabel: "Earl of Gosford, “Government of Canada”, House of Lords, 30 juin 1840, Hansard.",
    sourceUrls: ["https://api.parliament.uk/historic-hansard/lords/1840/jun/30/government-of-canada"],
    rightsLabel: PUBLIC_DOMAIN_RIGHTS,
    editorialNote: "Traduction française et découpage adaptés à des fins pédagogiques à partir du débat original en anglais.",
    content: { kind: "historical_excerpt", excerpt: "Était-il juste d’accorder à une population de 200 000 ou 300 000 habitants la même représentation qu’à une population de 700 000 ou 800 000 habitants? À cette injustice s’ajoutait la dette du Haut-Canada que l’on voulait imposer au Bas-Canada, qui n’avait pas de dette comparable. Une telle mesure lui paraissait arbitraire et injuste." },
    historicalKnowledgeIds: ["contexte-acte-union", "populations-bas-haut-canada", "consequences-acte-union"],
    intellectualOperationIds: ["establish_facts", "causes-and-consequences"],
  },
  {
    id: "lafontaine-union-conditions",
    title: "La Fontaine dénonce les conditions de l’Union",
    typeLabel: "Extrait d’une adresse politique",
    dateLabel: "25 août 1840",
    authorLabel: "Louis-Hippolyte La Fontaine",
    originalDocumentLabel: "Adresse aux électeurs du comté de Terrebonne",
    publicationLabel: "L’Aurore des Canadas, 28 août 1840",
    sourceLabel: "Louis-Hippolyte La Fontaine, Adresse aux électeurs du comté de Terrebonne, 1840.",
    sourceUrls: ["https://books.openedition.org/pum/13049", "https://biblio.republiquelibre.org/Adresse_aux_%C3%A9lecteurs_du_comt%C3%A9_de_Terrebonne"],
    rightsLabel: PUBLIC_DOMAIN_RIGHTS,
    editorialNote: "Extrait abrégé. La ponctuation a été adaptée pour faciliter la lecture; les mots sont ceux de l’auteur.",
    content: { kind: "historical_excerpt", excerpt: "L’Union est un acte d’injustice. Elle nous est imposée sans notre consentement. Elle prive le Bas-Canada du nombre légitime de ses représentants." },
    historicalKnowledgeIds: ["acte-union-1840", "institutions-politiques", "consequences-acte-union"],
    intellectualOperationIds: ["relate_facts", "causes-and-consequences"],
  },
  {
    id: "duncan-parliament-interior",
    title: "Vue intérieure du Parlement",
    typeLabel: "Aquarelle historique",
    dateLabel: "Vers 1848",
    authorLabel: "James Duncan",
    institutionLabel: "Musée des beaux-arts du Canada",
    originalDocumentLabel: "Vue intérieure du Parlement",
    sourceLabel: "Fiche de l’œuvre sur Wikimedia Commons.",
    sourceUrls: ["https://commons.wikimedia.org/wiki/File:Parlement_Canada_Montr%C3%A9al_int%C3%A9rieur.jpg"],
    rightsLabel: "Domaine public",
    content: {
      kind: "historical_image",
      localSrc: "/documents/acte-union/parlement-canada-montreal-interieur.jpg",
      alt: "Intérieur du Parlement de la province du Canada installé au marché Sainte-Anne, à Montréal.",
      description: "Intérieur du Parlement de la province du Canada installé au marché Sainte-Anne, à Montréal.",
    },
    historicalKnowledgeIds: ["contexte-acte-union", "acte-union-1840", "institutions-politiques"],
    intellectualOperationIds: ["establish_facts", "relate_facts"],
  },
];

export const ACTE_UNION_CAUSAL_PILOT_DOCUMENTS: LearningSessionDocument[] = [
  { id: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.id, title: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.title, typeLabel: "Extrait d’un texte parlementaire", dateLabel: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.historicalDate, authorLabel: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.creator, institutionLabel: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.holdingInstitution, sourceLabel: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.sourceLocator, sourceUrls: [PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.sourceUrl, PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.assetUrl], rightsLabel: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.rightsStatement, editorialNote: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.interpretationCautions[1], content: { kind: "historical_excerpt", excerpt: PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.transcription }, historicalKnowledgeIds: ["contexte-acte-union", "causes-acte-union"], intellectualOperationIds: ["causal_connections"] },
  { id: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.id, title: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.title, typeLabel: "Extrait d’un texte parlementaire", dateLabel: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.historicalDate, authorLabel: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.creator, institutionLabel: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.holdingInstitution, sourceLabel: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.sourceLocator, sourceUrls: [PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.sourceUrl, PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.assetUrl], rightsLabel: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.rightsStatement, editorialNote: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.interpretationCautions[1], content: { kind: "historical_excerpt", excerpt: PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.transcription }, historicalKnowledgeIds: ["contexte-acte-union", "causes-acte-union"], intellectualOperationIds: ["causal_connections"] },
  { id: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.id, title: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.title, typeLabel: "Extrait d’un article de journal", dateLabel: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.historicalDate, authorLabel: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.creator, institutionLabel: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.holdingInstitution, publicationLabel: "La Minerve", sourceLabel: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.sourceLocator, sourceUrls: [PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.sourceUrl], rightsLabel: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.rightsStatement, editorialNote: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.interpretationCautions[0], content: { kind: "historical_excerpt", excerpt: PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT.transcription }, historicalKnowledgeIds: ["contexte-acte-union", "causes-acte-union"], intellectualOperationIds: ["causal_connections"] },
];
