import type { LearningSessionDocument } from "./types.ts";

const PUBLIC_DOMAIN_RIGHTS = "Texte original de 1840 dans le domaine public.";

export const ACTE_UNION_DOCUMENTS: LearningSessionDocument[] = [
  {
    id: "acte-union-population-table",
    title: "Population des deux Canadas au moment de l’Acte d’union",
    typeLabel: "Tableau comparatif",
    sourceLabel: "Débat à la Chambre des lords britannique, 30 juin 1840; Acte d’union, 1840.",
    sourceUrls: [],
    rightsLabel: PUBLIC_DOMAIN_RIGHTS,
    content: {
      kind: "population_table",
      rows: [
        { region: "Canada-Est", population: "environ 700 000 à 800 000 habitants", representatives: "42 députés" },
        { region: "Canada-Ouest", population: "environ 200 000 à 300 000 habitants", representatives: "42 députés" },
      ],
    },
    historicalKnowledgeIds: ["acte-union-1840", "populations-bas-haut-canada", "institutions-politiques"],
    intellectualOperationIds: ["establish_facts", "relate_facts"],
  },
  {
    id: "gosford-equal-representation",
    title: "Le comte de Gosford critique la représentation égale",
    typeLabel: "Extrait d’un débat parlementaire",
    dateLabel: "30 juin 1840",
    authorLabel: "Earl of Gosford",
    institutionLabel: "House of Lords",
    sourceLabel: "Earl of Gosford, “Government of Canada”, House of Lords, 30 juin 1840, Hansard.",
    sourceUrls: ["https://api.parliament.uk/historic-hansard/lords/1840/jun/30/government-of-canada"],
    rightsLabel: PUBLIC_DOMAIN_RIGHTS,
    editorialNote: "Traduction française et découpage adaptés à des fins pédagogiques à partir du débat original en anglais.",
    content: { kind: "historical_excerpt", excerpt: "Était-il juste d’accorder à une population de 200 000 ou 300 000 habitants la même représentation qu’à une population de 700 000 ou 800 000 habitants? À cette injustice s’ajoutait la dette du Haut-Canada que l’on voulait imposer au Bas-Canada, qui n’avait pas de dette comparable. Une telle mesure lui paraissait arbitraire et injuste." },
    historicalKnowledgeIds: ["contexte-acte-union", "populations-bas-haut-canada", "consequences-acte-union"],
    intellectualOperationIds: ["establish_facts", "causes-and-consequences"],
  },
  {
    id: "lafontaine-union-conditions",
    title: "La Fontaine dénonce les conditions de l’Union",
    typeLabel: "Extrait d’une adresse politique",
    dateLabel: "25 août 1840",
    authorLabel: "Louis-Hippolyte La Fontaine",
    originalDocumentLabel: "Adresse aux électeurs du comté de Terrebonne",
    publicationLabel: "L’Aurore des Canadas, 28 août 1840",
    sourceLabel: "Louis-Hippolyte La Fontaine, Adresse aux électeurs du comté de Terrebonne, 1840.",
    sourceUrls: ["https://books.openedition.org/pum/13049", "https://biblio.republiquelibre.org/Adresse_aux_%C3%A9lecteurs_du_comt%C3%A9_de_Terrebonne"],
    rightsLabel: PUBLIC_DOMAIN_RIGHTS,
    editorialNote: "Extrait abrégé. La ponctuation a été adaptée pour faciliter la lecture; les mots sont ceux de l’auteur.",
    content: { kind: "historical_excerpt", excerpt: "L’Union est un acte d’injustice. Elle nous est imposée sans notre consentement. Elle prive le Bas-Canada du nombre légitime de ses représentants." },
    historicalKnowledgeIds: ["acte-union-1840", "institutions-politiques", "consequences-acte-union"],
    intellectualOperationIds: ["relate_facts", "causes-and-consequences"],
  },
  {
    id: "duncan-parliament-interior",
    title: "Vue intérieure du Parlement",
    typeLabel: "Aquarelle historique",
    dateLabel: "Vers 1848",
    authorLabel: "James Duncan",
    institutionLabel: "Musée des beaux-arts du Canada",
    originalDocumentLabel: "Vue intérieure du Parlement",
    sourceLabel: "Fiche de l’œuvre sur Wikimedia Commons.",
    sourceUrls: ["https://commons.wikimedia.org/wiki/File:Parlement_Canada_Montr%C3%A9al_int%C3%A9rieur.jpg"],
    rightsLabel: "Domaine public",
    content: {
      kind: "historical_image",
      localSrc: "/documents/acte-union/parlement-canada-montreal-interieur.jpg",
      alt: "Intérieur du Parlement de la province du Canada installé au marché Sainte-Anne, à Montréal.",
      description: "Intérieur du Parlement de la province du Canada installé au marché Sainte-Anne, à Montréal.",
    },
    historicalKnowledgeIds: ["contexte-acte-union", "acte-union-1840", "institutions-politiques"],
    intellectualOperationIds: ["establish_facts", "relate_facts"],
  },
];
