import type {
  ExpectedLearningObjective,
  HistoricalClaim,
  HistoricalManualTableRow,
  HistoricalRecord,
  IntellectualOperationId,
  ReferenceSource,
} from "../types.ts";
import { ACTE_UNION_DOCUMENT_SOURCE_CATALOG } from "../acte-union-document-source-catalog.ts";

const SOURCES = {
  program: {
    id: "pfeq-hqc-2017",
    kind: "official-program",
    title: "Programme de formation de l’école québécoise – Histoire du Québec et du Canada",
    creator: "Ministère de l’Éducation",
    publisher: "Gouvernement du Québec",
    publicationYear: 2017,
    url: "https://cdn-contenu.quebec.ca/cdn-contenu/education/pfeq/secondaire/programmes/PFEQ-histoire-quebec-canada-secondaire.pdf",
    locator: "Précisions des connaissances, p. 46 du programme (p. 49 du PDF)",
    verificationStatus: "verified",
  },
  act: {
    id: "union-act-1840-official",
    kind: "government",
    title: "Acte d’Union, 1840 / The Union Act, 1840",
    creator: "Parlement du Royaume-Uni",
    publisher: "Gouvernement du Canada",
    publicationYear: 1840,
    url: "https://publications.gc.ca/collections/collection_2014/lois-statutes/YX44-1985-9-1.pdf",
    locator: "3 & 4 Victoria, ch. 35, p. 118-142 du PDF; art. I, III-XII, XXVI-XXVII, XXXVII-XLI et XLV-LVII",
    verificationStatus: "verified",
  },
  durham: {
    id: "durham-report-1839",
    kind: "government",
    title: "Report on the Affairs of British North America",
    creator: "John George Lambton, comte de Durham",
    publisher: "Parlement britannique; Canadiana",
    publicationYear: 1839,
    url: "https://www.canadiana.ca/view/oocihm.32374",
    locator: "p. 5-6, 84 et 93-101 de l’édition numérisée",
    verificationStatus: "verified",
  },
  specialCouncil: {
    id: "anq-special-council-1838-1841",
    kind: "government",
    title: "Bas-Canada – Le Conseil spécial (1838-1841)",
    creator: "Bibliothèque de l’Assemblée nationale du Québec",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.bibliotheque.assnat.qc.ca/guides/fr/documents-politiques-et-parlementaires-du-quebec/144-bas-canada-le-conseil-special-1838-1841-",
    locator: "« Contexte historique »; suspension de 1838 et résolutions des 13-14 novembre 1839",
    verificationStatus: "verified",
  },
  constitutionalActContext: {
    id: "anq-constitutional-act-1791-context",
    kind: "government",
    title: "Acte constitutionnel (1791)",
    creator: "Encyclopédie du parlementarisme québécois",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.assnat.qc.ca/fr/patrimoine/lexique/acte-constitutionnel-%281791%29.html",
    locator: "Sections « Une rupture et des rébellions » : 92 Résolutions, crise agricole, résolutions Russell, assemblées populaires, Rébellions et suspension de la Constitution",
    verificationStatus: "verified",
  },
  lowerCanada: {
    id: "anq-lower-canada-1791-1838",
    kind: "government",
    title: "Bas-Canada (1791-1838)",
    creator: "Bibliothèque de l’Assemblée nationale du Québec",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.bibliotheque.assnat.qc.ca/guides/fr/documents-politiques-et-parlementaires-du-quebec/139-bas-canada-1791-1838-",
    locator: "Contexte historique : liste civile, 92 Résolutions, résolutions Russell et impasse menant aux Rébellions",
    verificationStatus: "verified",
  },
  ninetyTwoResolutions: {
    id: "anq-ninety-two-resolutions",
    kind: "government",
    title: "Quatre-vingt-douze Résolutions",
    creator: "Encyclopédie du parlementarisme québécois",
    publisher: "Assemblée nationale du Québec",
    publicationYear: 1834,
    url: "https://www.assnat.qc.ca/fr/patrimoine/lexique/quatre-vingt-douze-resolutions.html",
    locator: "Définition : résolutions adoptées le 21 février 1834 pour exposer les griefs de la Chambre d’assemblée du Bas-Canada",
    verificationStatus: "verified",
  },
  ninetyTwoResolutionsPrimary: {
    id: "lower-canada-92-resolutions-1834-primary",
    kind: "government",
    title: "92 Résolutions de la Chambre d’assemblée du Bas-Canada",
    creator: "Chambre d’assemblée du Bas-Canada",
    publisher: "Journaux de la Chambre d’assemblée du Bas-Canada; reproduction numérique diffusée par PrimaryDocuments.ca",
    publicationYear: 1834,
    url: "https://primarydocuments.ca/lower-canada-house-of-assembly-92-resolutions-14th-parl-4th-sess-21-february-1834/",
    locator: "Résolutions 14, 21, 28, 55, 75 et 79 : Conseil législatif électif, influence de la population sur l’exécutif, contrôle des revenus, emplois publics et rappel de griefs",
    verificationStatus: "verified",
  },
  russellResolutionsPrimary: {
    id: "uk-russell-resolutions-1837-primary",
    kind: "government",
    title: "Résolutions Russell — Affairs of Canada",
    creator: "Lord John Russell; Chambre des communes du Royaume-Uni",
    publisher: "Historic Hansard; reproduction numérique diffusée par PrimaryDocuments.ca",
    publicationYear: 1837,
    url: "https://primarydocuments.ca/uk-hc-affairs-of-canada-vol-36-6-march-1837/",
    locator: "Résolutions 4, 5 et 8 : refus d’un Conseil législatif électif, refus de la responsabilité de l’exécutif et autorisation d’utiliser les revenus coloniaux",
    verificationStatus: "verified",
  },
  rebellionsChronology: {
    id: "anq-chronology-1837-1838",
    kind: "government",
    title: "Chronologie parlementaire depuis 1764 (1837-1838)",
    creator: "Assemblée nationale du Québec",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.assnat.qc.ca/fr/patrimoine/chronologie/chrono21.html",
    locator: "2 et 6 mars 1837 : refus du Conseil législatif électif et de la responsabilité de l’exécutif; autorisation de dépenser sans le consentement de l’Assemblée; événements de 1837-1838",
    verificationStatus: "verified",
  },
  canadaRebellions: {
    id: "canada-discover-rebellions-1837-1838",
    kind: "government",
    title: "Les rébellions de 1837 et 1838",
    creator: "Immigration, Réfugiés et Citoyenneté Canada",
    publisher: "Gouvernement du Canada",
    url: "https://www.canada.ca/fr/immigration-refugies-citoyennete/organisation/publications-guides/decouvrir-canada/lisez-ligne/histoire-canada.html",
    locator: "Section « Les rébellions de 1837 et 1838 » : défaite, pendaisons, exils et recommandations de Durham",
    verificationStatus: "verified",
  },
  upperCanada: {
    id: "anq-upper-canada-1791-1841",
    kind: "government",
    title: "Haut-Canada (Upper Canada) (1791-1841)",
    creator: "Bibliothèque de l’Assemblée nationale du Québec",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.bibliotheque.assnat.qc.ca/guides/fr/documents-politiques-et-parlementaires-du-quebec/123-haut-canada-upper-canada-1791-1841-",
    locator: "« Contexte historique »; résolutions du 24 février 1838 et débats de 1839",
    verificationStatus: "verified",
  },
  chronologyUnion: {
    id: "anq-chronology-1839-1841",
    kind: "government",
    title: "Chronologie parlementaire depuis 1764 (1839-1841)",
    creator: "Assemblée nationale du Québec",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.assnat.qc.ca/fr/patrimoine/chronologie/chrono22.html",
    locator: "8 et 11 février 1839; 13 novembre 1839; 23 mars, 18 juin et 23 juillet 1840; 10 février 1841",
    verificationStatus: "verified",
  },
  guide: {
    id: "anq-province-canada",
    kind: "government",
    title: "Province du Canada (1840-1867)",
    creator: "Bibliothèque de l’Assemblée nationale du Québec",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.bibliotheque.assnat.qc.ca/guides/fr/documents-politiques-et-parlementaires-du-quebec/146-province-du-canada-1840-1867-",
    locator: "« Contexte historique », « Acte d’Union de 1840 » et diagramme de gouvernance",
    verificationStatus: "verified",
  },
  actTopic: {
    id: "dbc-acte-union-topic",
    kind: "academic",
    title: "Acte d’Union (1840)",
    creator: "Dictionnaire biographique du Canada",
    publisher: "Université Laval et University of Toronto",
    url: "https://www.biographi.ca/fr/topics/topic-match-list.php?id=1459",
    locator: "Notice thématique et biographies connexes",
    verificationStatus: "verified",
  },
  sydenham: {
    id: "dbc-sydenham",
    kind: "academic",
    title: "THOMSON, CHARLES EDWARD POULETT, 1er baron SYDENHAM",
    creator: "Paul Knaplund et Michael S. Cross",
    publisher: "Dictionnaire biographique du Canada, Université Laval/University of Toronto",
    url: "https://www.biographi.ca/fr/bio/thomson_charles_edward_poulett_7E.html",
    locator: "Mission de 1839-1841, négociation de l’Union, circonscriptions, administration et proclamation",
    verificationStatus: "verified",
  },
  lafontaine: {
    id: "dbc-lafontaine",
    kind: "academic",
    title: "LA FONTAINE, sir Louis-Hippolyte",
    creator: "Jacques Monet",
    publisher: "Dictionnaire biographique du Canada, Université Laval/University of Toronto",
    url: "https://www.biographi.ca/fr/bio/la_fontaine_louis_hippolyte_9F.html",
    locator: "Adresse aux électeurs de Terrebonne de 1840 et réaction à l’Union",
    verificationStatus: "verified",
  },
  civilList: {
    id: "anq-liste-civile",
    kind: "government",
    title: "Liste civile",
    creator: "Encyclopédie du parlementarisme québécois",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.assnat.qc.ca/fr/patrimoine/lexique/liste-civile.html",
    locator: "Conflit financier avant 1837 et art. 54 de l’Acte d’Union; sommes de 45 000 £ et 30 000 £",
    verificationStatus: "verified",
  },
  electoralMap: {
    id: "anq-carte-electorale-union",
    kind: "government",
    title: "Carte électorale – L’Acte d’Union et la carte électorale",
    creator: "Encyclopédie du parlementarisme québécois",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.assnat.qc.ca/fr/patrimoine/lexique/carte-electorale.html",
    locator: "Réduction de 90 à 42 représentants au Bas-Canada et règle des deux tiers",
    verificationStatus: "verified",
  },
  names: {
    id: "anq-canada-est-ouest",
    kind: "government",
    title: "« Canada-Est, Canada-Ouest »",
    creator: "Encyclopédie du parlementarisme québécois",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.assnat.qc.ca/fr/patrimoine/lexique/canada-est-canada-ouest.html",
    locator: "« Définition » et « De 1841 à 1849 »",
    verificationStatus: "verified",
  },
  population: {
    id: "statcan-censuses-1800s",
    kind: "government",
    title: "Recensements du Canada, 1665 à 1871 — Les années 1800",
    creator: "Statistique Canada",
    publisher: "Gouvernement du Canada",
    url: "https://www150.statcan.gc.ca/n1/pub/98-187-x/4064809-fra.htm",
    locator: "Haut-Canada : 432 159 en 1840 et 455 688 en 1841; Bas-Canada : 697 084 en 1844",
    verificationStatus: "verified",
  },
  populationAtUnion: {
    id: "bac-population-at-union-1851",
    kind: "museum-or-archive",
    title: "The Origin, Composition, and Futurity of Political Parties in Canada",
    creator: "Texte traduit du Journal de Québec",
    publisher: "C. Donlevy, Mirror Office; exemplaire numérisé par Bibliothèque et Archives Canada",
    publicationYear: 1851,
    url: "https://www.collectionscanada.gc.ca/obj/023012/f2/nlc013168-full.pdf",
    locator: "p. 12 du document (vue 14 du PDF) : estimation de 650 000 habitants au Bas-Canada au moment de l’Union, calculée à partir des recensements de 1831 et de 1844",
    verificationStatus: "verified",
  },
  lafontaineCapitale: {
    id: "ccnq-lafontaine-population-union",
    kind: "government",
    title: "Sir Louis-Hippolyte La Fontaine",
    publisher: "Commission de la capitale nationale du Québec",
    url: "https://www.capitale.gouv.qc.ca/wp-content/uploads/2021/09/11_86_LaFontaine.pdf",
    locator: "p. 2 : 650 000 habitants au Bas-Canada et 450 000 au Haut-Canada au moment de l’entrée en vigueur de l’Acte d’Union",
    verificationStatus: "verified",
  },
  boundaries: {
    id: "canadian-heritage-boundaries-1840",
    kind: "government",
    title: "Frontières historiques du Canada",
    creator: "Patrimoine canadien",
    publisher: "Gouvernement du Canada",
    url: "https://www.canada.ca/fr/patrimoine-canadien/services/frontieres-historiques-canada.html",
    locator: "Carte et notice « 1840 »",
    verificationStatus: "verified",
  },
  responsible: {
    id: "anq-gouvernement-responsable",
    kind: "government",
    title: "Gouvernement responsable",
    creator: "Encyclopédie du parlementarisme québécois",
    publisher: "Assemblée nationale du Québec",
    url: "https://www.assnat.qc.ca/fr/patrimoine/lexique/gouvernement-responsable.html",
    locator: "Définition et distinction entre la recommandation de Durham, le régime de 1841 et l’application de 1848",
    verificationStatus: "verified",
  },
  languageRepeal: {
    id: "language-repeal-act-1848",
    kind: "government",
    title: "An Act to repeal so much of an Act … as relates to the Use of the English Language",
    creator: "Parlement du Royaume-Uni",
    publisher: "Canadiana",
    publicationYear: 1848,
    url: "https://www.canadiana.ca/view/oocihm.9_03558",
    locator: "11 & 12 Victoria, ch. 56, p. 649-650; sanction le 14 août 1848",
    verificationStatus: "verified",
  },
} as const satisfies Record<string, ReferenceSource>;

const CHRONOLOGICAL_MONOGRAPH_SECTION_ORDER = [
  "mono-before-union",
  "mono-secondary-three-bridge",
  "mono-durham",
  "mono-adoption",
  "mono-introduction",
  "mono-reactions",
  "mono-structure",
  "mono-representation",
  "mono-administration",
  "mono-language-territory",
  "mono-consequences",
] as const;

const ids = (...keys: (keyof typeof SOURCES)[]) => keys.map((key) => SOURCES[key].id);
const fact = (id: string, text: string, sourceIds: readonly string[]): HistoricalClaim => ({ id, text, sourceIds, claimKind: "fact" });
const nuance = (id: string, text: string, sourceIds: readonly string[]): HistoricalClaim => ({ id, text, sourceIds, claimKind: "nuance" });
const interpretation = (id: string, text: string, sourceIds: readonly string[]): HistoricalClaim => ({ id, text, sourceIds, claimKind: "interpretation" });
const statement = (id: string, text: string, sourceIds: readonly string[]) => ({ id, text, sourceIds });
const tableRow = (id: string, text: string, cells: readonly string[], sourceIds: readonly string[]): HistoricalManualTableRow => ({ id, text, cells, sourceIds });
const objective = (id: string, text: string, sourceIds: readonly string[], programBasis: string, knowledgeFocus: readonly string[], operationIds: readonly IntellectualOperationId[]): ExpectedLearningObjective => ({
  id,
  text,
  sourceIds,
  origin: "socrato-editorial-derivation",
  programBasis,
  knowledgeFocus,
  operationIds,
});

export const ACTE_UNION_HISTORICAL_RECORD: HistoricalRecord = {
  schemaVersion: 1,
  id: "historical-record:acte-union",
  knowledgeHeadingId: "acte-union",
  status: "draft",
  title: "L’Acte d’Union de 1840 : crise coloniale, union législative et transformations du régime",
  scope: "Monographie consacrée au contexte, à l’adoption, aux dispositions, aux changements, aux continuités et aux conséquences de l’Acte d’Union. La responsabilité ministérielle est définie et reliée causalement au nouveau régime, mais son obtention et les gouvernements LaFontaine-Baldwin relèvent de la notion suivante.",
  knowledgePrecisions: [
    { ...statement("precision-context", "La monographie traite l’impasse institutionnelle, les Rébellions, la suspension de la constitution du Bas-Canada, le rapport Durham, les finances, les travaux publics et la démographie.", ids("program", "durham", "specialCouncil", "population")), officialOrder: 1, officialLabel: "Contexte sociopolitique et économique", coverageStatus: "complete", linkedStatementIds: ["mono-old-regime-2", "mono-crisis-1", "bridge-consequence-constitutional", "bridge-transition-secondary-four", "mono-durham-3", "mono-economy-1", "mono-population-2"] },
    { ...statement("precision-structure", "La monographie distingue la Couronne, le gouverneur, le Conseil exécutif, le Conseil législatif nommé et l’Assemblée élue, ainsi que leurs rapports de pouvoir.", ids("program", "act", "guide")), officialOrder: 2, officialLabel: "Structure politique", coverageStatus: "complete", linkedStatementIds: ["mono-structure-1", "mono-structure-2", "mono-structure-3", "mono-structure-5", "table-structure-governor", "table-structure-assembly"] },
    { ...statement("precision-administration", "La monographie explique les revenus réunis, les dettes, la liste civile, la langue des documents législatifs et le maintien des lois, tribunaux et administrations existants.", ids("program", "act", "civilList", "guide")), officialOrder: 3, officialLabel: "Dispositions administratives", coverageStatus: "complete", linkedStatementIds: ["mono-finance-2", "mono-finance-3", "mono-civil-list-1", "mono-language-1", "mono-laws-1", "table-provision-revenue"] },
    { ...statement("precision-territory", "La monographie présente la Province du Canada comme une colonie unique réunissant les territoires des anciennes colonies, tout en expliquant la persistance de deux sections administratives et juridiques.", ids("program", "act", "guide", "names", "boundaries")), officialOrder: 4, officialLabel: "Territoire de la Province du Canada", coverageStatus: "complete", linkedStatementIds: ["mono-territory-1", "mono-territory-2", "mono-territory-3", "t-province", "t-east", "t-west"] },
  ],
  manual: {
    title: "Monographie historique interne — L’Acte d’Union de 1840",
    purpose: "Offrir à Socrato un texte historique substantiel, original et vérifiable pour préparer les fiches pédagogiques, les questions approuvées et les rétroactions encadrées. Cette monographie n’est ni un texte destiné automatiquement aux élèves ni une autorisation de produire du contenu sans validation.",
    audience: "internal-pedagogical-reference",
    editorialMethod: "Synthèse originale rédigée pour Socrato à partir de sources primaires, gouvernementales et universitaires recoupées. Les faits importants sont rattachés à des localisateurs précis; les interprétations sont signalées comme telles; toute citation directe éventuelle doit demeurer brève, clairement identifiée et justifiée.",
    scopeBoundary: "La monographie explique la responsabilité ministérielle afin de rendre compréhensible le problème constitutionnel laissé par l’Union. Les ministères LaFontaine-Baldwin, Bagot, Metcalfe, Elgin et l’obtention du gouvernement responsable sont réservés à la prochaine notion; ils ne figurent ici que comme horizon causal.",
    sections: [
      {
        id: "mono-introduction",
        title: "5. 1840-1841 — L’Acte d’Union : définition, vocabulaire et entrée en vigueur",
        purpose: "Définir précisément la loi une fois son processus d’adoption expliqué.",
        paragraphs: [
          fact("mono-definition-1", "L’Acte d’Union est une loi du Parlement du Royaume-Uni sanctionnée le 23 juillet 1840. Son titre officiel annonce son objet : réunir le Haut-Canada et le Bas-Canada et pourvoir au gouvernement du Canada. La loi autorise une proclamation fixant la date à laquelle les deux colonies formeront une seule province appelée Province du Canada.", ids("act", "chronologyUnion")),
          nuance("mono-definition-2", "Deux dates doivent être conservées. L’année 1840 correspond à l’adoption et à la sanction de la loi; le 10 février 1841 correspond à sa proclamation et à son entrée en vigueur. Dire seulement « l’Union de 1841 » efface donc l’étape législative de 1840, tandis que dire seulement « l’Union de 1840 » peut masquer le moment où le nouveau régime commence réellement.", ids("act", "guide", "chronologyUnion")),
          nuance("mono-definition-3", "Le terme « Canada-Uni » est fréquent dans les récits historiques, mais la loi nomme la nouvelle colonie « Province du Canada ». Les expressions Canada-Est et Canada-Ouest deviennent usuelles pour distinguer ses deux sections; elles ne désignent pas deux provinces autonomes créées par l’Acte.", ids("act", "names", "guide")),
        ],
      },
      {
        id: "mono-before-union",
        title: "1. 1791-1833 — Deux colonies et une crise institutionnelle",
        purpose: "Reconstituer les institutions et les conflits que Londres cherche à modifier.",
        paragraphs: [
          fact("mono-old-regime-1", "Depuis l’Acte constitutionnel de 1791, le Haut-Canada et le Bas-Canada possèdent chacun une législature. Une assemblée élue adopte des projets de loi et vote certaines dépenses, mais le gouverneur représente la Couronne, choisit les membres des conseils et conserve des pouvoirs importants sur la sanction des lois, les nominations et l’administration.", ids("upperCanada", "specialCouncil", "act")),
          fact("mono-old-regime-2", "Dans les deux colonies, des réformistes dénoncent l’influence de groupes proches du pouvoir exécutif. Au Bas-Canada, la majorité patriote de l’Assemblée réclame notamment un contrôle plus complet des revenus publics et une plus grande responsabilité des fonctionnaires. Au Haut-Canada, des réformistes s’opposent aussi à la concentration du pouvoir autour du gouverneur et du Family Compact.", ids("durham", "upperCanada", "civilList")),
          fact("mono-crisis-1", "Le conflit sur les subsides et la liste civile est central. L’Assemblée du Bas-Canada utilise le vote des crédits pour tenter de rendre l’administration plus responsable devant les représentants élus, tandis que le pouvoir impérial veut garantir des revenus permanents au gouverneur, aux juges et aux principaux services de l’État.", ids("civilList", "durham")),
        ],
      },
      {
        id: "mono-secondary-three-bridge",
        title: "2. 1834-1838 — Des 92 Résolutions aux Rébellions et à leur répression",
        purpose: "Réactiver les acquis sur les Rébellions de 1837-1838 et établir la chaîne causale qui mène au programme de 4e secondaire.",
        paragraphs: [
          fact("bridge-context-institutions", "Le point de départ se trouve dans le régime créé en 1791. Au Bas-Canada, la population élit une Chambre d’assemblée, mais le gouverneur et les conseils nommés conservent une influence déterminante sur l’exécutif, les nominations et l’adoption des lois. Cette division du pouvoir nourrit un conflit durable entre la majorité élue et l’administration coloniale.", ids("constitutionalActContext", "lowerCanada", "civilList")),
          fact("bridge-ninety-two-origin", "Le 21 février 1834, la Chambre d’assemblée du Bas-Canada adopte les 92 Résolutions. Ce long manifeste ne porte pas sur un seul problème : il rassemble les griefs accumulés contre l’administration coloniale et expose les réformes défendues par la majorité patriote. Il transmet donc à Londres une synthèse politique de l’impasse plutôt qu’une déclaration d’indépendance ou un appel immédiat aux armes.", ids("ninetyTwoResolutions", "ninetyTwoResolutionsPrimary", "lowerCanada")),
          fact("bridge-ninety-two-demands", "Parmi leurs revendications centrales, les 92 Résolutions demandent que le Conseil législatif devienne électif, dénoncent un pouvoir exécutif soustrait à l’influence de la population et réclament un contrôle réel de la Chambre sur les revenus et les dépenses. Elles critiquent également le cumul des fonctions, le favoritisme administratif et la faible présence des Canadiens français dans plusieurs emplois publics.", ids("ninetyTwoResolutionsPrimary", "rebellionsChronology", "civilList")),
          interpretation("bridge-ninety-two-meaning", "Ces demandes révèlent le cœur du conflit constitutionnel : une assemblée peut être élue sans gouverner réellement si les conseils nommés peuvent bloquer ses décisions et si l’exécutif n’a pas à conserver sa confiance. Les 92 Résolutions cherchent ainsi à transformer la représentation électorale en pouvoir politique effectif. Elles constituent une cause politique majeure des événements suivants parce que leur rejet convainc de nombreux Patriotes que les moyens parlementaires ordinaires ne suffisent plus.", ids("ninetyTwoResolutionsPrimary", "lowerCanada", "civilList")),
          fact("bridge-cause-economic-social", "La crise ne repose toutefois pas sur les institutions seulement. Les tensions autour des finances publiques, l’influence économique et administrative de la minorité britannique, les mauvaises récoltes et les difficultés agricoles aggravent le mécontentement. Les dimensions politiques, économiques, sociales, nationales et linguistiques se renforcent mutuellement sans toucher toute la population de la même façon.", ids("constitutionalActContext", "durham", "civilList")),
          fact("bridge-trigger-russell", "En mars 1837, les résolutions Russell répondent négativement aux principales demandes de 1834. Londres refuse de rendre le Conseil législatif électif et l’exécutif responsable devant l’Assemblée, puis autorise le gouverneur à utiliser certains revenus sans le consentement de la Chambre. Cette fin de non-recevoir ferme la voie aux réformes parlementaires immédiates et accélère la mobilisation patriote.", ids("russellResolutionsPrimary", "rebellionsChronology", "lowerCanada")),
          fact("bridge-mobilization-conflict", "Des assemblées populaires, le boycottage de produits britanniques et une rhétorique de résistance accompagnent alors la radicalisation. Les affrontements armés éclatent en 1837, puis une seconde insurrection survient en 1838. Les forces britanniques et leurs alliés coloniaux remportent la victoire; l’appui aux insurgés demeure inégal selon les régions et les groupes.", ids("constitutionalActContext", "canadaRebellions", "durham")),
          fact("bridge-consequence-human", "La répression entraîne des morts au combat, des arrestations, des procès, des pendaisons, des déportations et des départs en exil. Elle détruit aussi des propriétés et désorganise durablement le mouvement patriote. Ces conséquences humaines et politiques rappellent que les Rébellions ne sont pas uniquement un débat constitutionnel devenu violent.", ids("canadaRebellions", "durham")),
          fact("bridge-consequence-constitutional", "La conséquence constitutionnelle immédiate au Bas-Canada est la suspension, en février 1838, du régime parlementaire établi en 1791. Une Assemblée élue ne siège plus : le gouverneur et un Conseil spécial nommé administrent temporairement la colonie. Londres rétablit ainsi son autorité, mais doit encore chercher une solution durable à la crise.", ids("specialCouncil", "constitutionalActContext")),
          interpretation("bridge-transition-secondary-four", "Le lien avec le début de la 4e secondaire peut donc être formulé comme une chaîne causale : limites du régime de 1791 → revendications patriotes et 92 Résolutions → refus exprimé par les résolutions Russell → mobilisation et Rébellions → répression et suspension de l’Assemblée → enquête de Durham → recommandation d’unir les Canadas → Acte d’Union de 1840, appliqué en 1841. L’Union constitue ainsi une réponse impériale aux crises étudiées en 3e secondaire, et non un événement isolé.", ids("program", "rebellionsChronology", "specialCouncil", "durham", "act", "chronologyUnion")),
        ],
      },
      {
        id: "mono-durham",
        title: "3. 1838-1839 — Le rapport Durham : diagnostic, union, assimilation et responsabilité",
        purpose: "Distinguer les recommandations de Durham de ce que la loi de 1840 adopte réellement.",
        paragraphs: [
          fact("mono-durham-1", "John George Lambton, comte de Durham, arrive en 1838 avec le mandat d’enquêter sur les troubles dans l’Amérique du Nord britannique. Son rapport est rendu public à Londres en février 1839. Il cherche une solution générale aux problèmes du gouvernement colonial et consacre une attention particulière aux deux Canadas.", ids("durham", "chronologyUnion", "specialCouncil")),
          interpretation("mono-durham-2", "Durham décrit une administration fragmentée, des responsabilités mal définies et un exécutif capable de gouverner sans l’appui durable des représentants élus. Son analyse relie l’inefficacité administrative au conflit constitutionnel : lorsque les décisions sont prises par des personnes que l’Assemblée ne peut remplacer, la responsabilité politique demeure difficile à établir.", ids("durham", "responsible")),
          fact("mono-durham-3", "Durham recommande une union législative du Haut-Canada et du Bas-Canada. Il estime qu’une assemblée commune dominée à terme par une population anglophone favoriserait l’assimilation des Canadiens français. Cette intention d’anglicisation est explicite dans son rapport et constitue une dimension essentielle du contexte de l’Union.", ids("durham", "specialCouncil", "chronologyUnion")),
          fact("mono-durham-4", "Durham recommande également que les affaires intérieures soient conduites selon le principe du gouvernement responsable. Dans ce système, les principaux conseillers du gouverneur doivent pouvoir obtenir et conserver la confiance de l’Assemblée élue. Une défaite majeure devant cette assemblée entraîne normalement leur remplacement ou des élections.", ids("durham", "responsible")),
          nuance("mono-durham-5", "L’Acte d’Union reprend la recommandation d’unir les colonies, mais il n’inscrit pas le gouvernement responsable dans la loi. Cette différence est fondamentale : Durham associe les deux réformes dans son projet, alors que le Parlement britannique adopte une union qui laisse au gouverneur des pouvoirs étendus et ne l’oblige pas juridiquement à choisir ses conseillers parmi la majorité élue.", ids("act", "durham", "responsible")),
        ],
      },
      {
        id: "mono-adoption",
        title: "4. 1839-1841 — De la recommandation à la loi",
        purpose: "Suivre le rôle de Londres, des institutions coloniales et de Charles Poulett Thomson.",
        paragraphs: [
          fact("mono-adoption-1", "À l’automne 1839, Charles Edward Poulett Thomson devient gouverneur en chef avec pour mission principale de faire accepter l’Union et d’en préparer les modalités. Homme politique britannique ayant une expérience commerciale, il privilégie une administration centralisée, des finances ordonnées et un gouvernement capable de faire adopter son programme.", ids("sydenham", "chronologyUnion")),
          fact("mono-adoption-2", "Le 13 novembre 1839, quinze membres du Conseil spécial du Bas-Canada adoptent, sur division, six résolutions favorables à l’Union; une adresse les ratifie le lendemain. Cette acceptation institutionnelle survient pendant la suspension de l’Assemblée élue.", ids("specialCouncil", "chronologyUnion")),
          fact("mono-adoption-3", "Dans le Haut-Canada, l’idée d’Union est discutée avec des conditions touchant la dette, la représentation, la langue et le siège du gouvernement. Le Parlement haut-canadien accepte les propositions de Thomson en décembre 1839, mais les débats montrent que les partisans de l’Union n’en attendent pas tous les mêmes avantages.", ids("upperCanada", "sydenham", "civilList")),
          nuance("mono-adoption-consent", "L’Union n’est donc pas négociée par deux assemblées élues placées sur un pied d’égalité. Le Haut-Canada conserve son Parlement, tandis que le consentement institutionnel du Bas-Canada est donné par un Conseil spécial nommé pendant la suspension de sa Chambre d’assemblée.", ids("specialCouncil", "upperCanada", "chronologyUnion")),
          nuance("mono-adoption-4", "Thomson prépare un avant-projet visant à réunir les législatures tout en maintenant plusieurs institutions existantes. Au cours du processus britannique, certaines modalités électorales sont modifiées afin d’accroître la représentation de circonscriptions anglophones au Bas-Canada. Le texte final est donc le résultat d’arbitrages impériaux et coloniaux, non la simple transcription du rapport Durham.", ids("sydenham", "electoralMap")),
          fact("mono-adoption-5", "Lord John Russell présente le projet à la Chambre des communes britannique le 23 mars 1840. Les Communes l’adoptent le 18 juin, puis la reine Victoria lui accorde la sanction royale le 23 juillet. Thomson, devenu lord Sydenham, proclame l’Union le 10 février 1841.", ids("chronologyUnion", "act", "sydenham")),
        ],
      },
      {
        id: "mono-structure",
        title: "7. À partir de 1841 — La nouvelle structure politique",
        purpose: "Décrire les institutions de la Province du Canada et les pouvoirs qu’elles exercent.",
        paragraphs: [
          fact("mono-structure-1", "L’Acte abolit les législatures distinctes du Haut-Canada et du Bas-Canada et crée une seule législature pour la Province du Canada. Celle-ci réunit la Couronne, représentée par le gouverneur, un Conseil législatif nommé et une Assemblée législative élue.", ids("act", "guide", "boundaries")),
          fact("mono-structure-2", "Le Conseil législatif compte au moins vingt membres appelés par la Couronne sur l’autorisation donnée au gouverneur. Les conseillers ne sont pas élus. Cette continuité maintient une Chambre haute étroitement liée au pouvoir impérial et au gouverneur.", ids("act", "guide")),
          fact("mono-structure-3", "L’Assemblée législative compte 84 députés. Les circonscriptions de l’ancien Haut-Canada en élisent 42 et celles de l’ancien Bas-Canada en élisent également 42. Les députés doivent satisfaire aux conditions électorales de l’époque, notamment posséder des biens d’une valeur nette de 500 livres sterling.", ids("act", "electoralMap")),
          fact("mono-structure-4", "Un projet de loi doit franchir le Conseil législatif et l’Assemblée, puis recevoir la sanction du gouverneur au nom de la Couronne. Le gouverneur peut sanctionner, refuser ou réserver un projet pour la décision impériale; Londres conserve aussi un pouvoir de désaveu après la sanction coloniale.", ids("act")),
          fact("mono-structure-5", "Le Conseil exécutif assiste le gouverneur dans l’administration. L’Acte transfère au gouverneur de la Province du Canada les pouvoirs auparavant exercés dans les deux colonies, mais il ne prévoit pas que les conseillers exécutifs doivent être choisis parmi les députés majoritaires ni quitter leurs fonctions lorsqu’ils perdent leur confiance.", ids("act", "responsible")),
          interpretation("mono-structure-6", "La nouvelle constitution combine donc représentation et autorité coloniale. Les électeurs choisissent une Assemblée pouvant débattre, légiférer et voter des fonds, mais l’exécutif demeure juridiquement rattaché au gouverneur. Cette tension explique pourquoi la responsabilité ministérielle devient le problème constitutionnel suivant.", ids("act", "responsible", "guide")),
        ],
        tables: [{
          id: "table-structure",
          title: "Structure du pouvoir sous l’Union",
          introduction: "Le tableau distingue le mode de désignation et la fonction générale de chaque composante.",
          columns: ["Composante", "Mode de désignation", "Rôle principal", "Limite ou enjeu"],
          rows: [
            tableRow("table-structure-crown", "La Couronne britannique demeure la source formelle de l’autorité coloniale.", ["Couronne", "Héréditaire", "Autorité impériale et sanction des lois", "Le Parlement britannique conserve des pouvoirs sur la colonie"], ids("act")),
            tableRow("table-structure-governor", "Le gouverneur représente la Couronne et dirige l’exécutif colonial.", ["Gouverneur", "Nommé par Londres", "Convoque la législature, sanctionne ou réserve les lois, dirige l’exécutif", "N’est pas responsable devant les électeurs"], ids("act", "responsible")),
            tableRow("table-structure-executive", "Le Conseil exécutif conseille le gouverneur sans obligation légale de confiance parlementaire.", ["Conseil exécutif", "Nommé", "Administration et conseil au gouverneur", "La confiance de l’Assemblée n’est pas exigée par l’Acte"], ids("act", "responsible")),
            tableRow("table-structure-council", "Le Conseil législatif forme la Chambre haute nommée.", ["Conseil législatif", "Au moins 20 membres nommés", "Étudie et adopte les projets de loi", "Non élu"], ids("act", "guide")),
            tableRow("table-structure-assembly", "L’Assemblée est la Chambre élue de 84 députés.", ["Assemblée législative", "84 élus : 42 par section", "Débat, législation et vote des fonds", "Sous-représentation initiale de l’ancien Bas-Canada"], ids("act", "electoralMap")),
          ],
        }],
      },
      {
        id: "mono-representation",
        title: "8. À partir de 1841 — Représentation électorale et inégalité démographique",
        purpose: "Mesurer l’effet politique des 42 sièges attribués à chaque section.",
        paragraphs: [
          fact("mono-representation-1", "Avant l’Union, l’Assemblée du Bas-Canada comptait 90 députés. Dans la nouvelle Assemblée, la section correspondant à l’ancien Bas-Canada n’en élit plus que 42. L’ancien Haut-Canada obtient lui aussi 42 sièges, malgré une population moins nombreuse au moment de l’Union.", ids("electoralMap", "actTopic", "act")),
          interpretation("mono-representation-2", "L’égalité des sièges n’est donc pas une représentation égale des personnes. Elle donne aux deux sections le même poids collectif et réduit le poids électoral relatif de la population du Bas-Canada. Dans le contexte du projet d’assimilation, cette règle limite la capacité d’une majorité canadienne-française à dominer seule la nouvelle Assemblée.", ids("durham", "electoralMap", "actTopic")),
          nuance("mono-population-1", "Les données démographiques disponibles ne forment pas une photographie parfaitement simultanée. Pour l’année d’entrée en vigueur de l’Union, Statistique Canada indique 455 688 habitants au Haut-Canada en 1841. Pour le Bas-Canada, une estimation rétrospective publiée en 1851, calculée à partir des recensements de 1831 et de 1844, situe la population à environ 650 000 habitants au moment de l’Union. Il ne s’agit pas d’un recensement réalisé en 1841 : le premier total officiel rapproché est celui de 1844, soit 697 084 habitants. Une publication de la Commission de la capitale nationale du Québec confirme l’ordre de grandeur d’environ 650 000 contre 450 000.", ids("population", "populationAtUnion", "lafontaineCapitale")),
          fact("mono-population-2", "Même avec cette réserve méthodologique, l’ordre de grandeur est clair : la population de l’ancien Bas-Canada, estimée à environ 650 000 habitants au moment de l’Union, est nettement supérieure aux 455 688 habitants recensés au Haut-Canada en 1841. La représentation de 42 sièges contre 42 constitue donc une sous-représentation initiale de la section orientale.", ids("population", "populationAtUnion", "lafontaineCapitale", "electoralMap", "guide")),
          nuance("mono-representation-3", "L’Acte permet à la législature de modifier les circonscriptions et la répartition, mais protège l’équilibre initial par une exigence renforcée : les modifications concernées doivent obtenir l’appui des deux tiers du Conseil législatif et de l’Assemblée. L’égalité sectionnelle est ainsi difficile à changer rapidement.", ids("act", "electoralMap")),
        ],
        tables: [{
          id: "table-population",
          title: "Population et représentation au début de l’Union",
          introduction: "L’estimation du Bas-Canada pour 1841 permet de comparer les deux sections au moment de l’Union, mais elle doit rester distincte d’un résultat de recensement. Le total officiel de 1844 sert de point de contrôle.",
          columns: ["Territoire", "Population officielle disponible", "Année", "Sièges à l’Assemblée", "Précaution"],
          rows: [
            tableRow("table-pop-upper-1840", "Statistique Canada recense 432 159 habitants au Haut-Canada en 1840.", ["Ancien Haut-Canada", "432 159", "1840", "42", "Donnée la plus proche de la sanction"], ids("population", "act")),
            tableRow("table-pop-upper-1841", "Statistique Canada recense 455 688 habitants au Haut-Canada en 1841.", ["Ancien Haut-Canada", "455 688", "1841", "42", "Année de l’entrée en vigueur"], ids("population", "act")),
            tableRow("table-pop-lower-1841-estimate", "Une estimation rétrospective calculée à partir des recensements de 1831 et de 1844 situe la population du Bas-Canada à environ 650 000 habitants au moment de l’Union.", ["Ancien Bas-Canada", "environ 650 000", "1841 (estimation)", "42", "Estimation rétrospective, et non recensement de 1841"], ids("populationAtUnion", "lafontaineCapitale", "act")),
            tableRow("table-pop-lower-1844", "Statistique Canada recense 697 084 habitants au Bas-Canada en 1844.", ["Ancien Bas-Canada", "697 084", "1844", "42", "Ne doit pas être comparée comme si elle datait de 1841"], ids("population", "act")),
          ],
        }],
      },
      {
        id: "mono-administration",
        title: "9. À partir de 1841 — Finances, dette, liste civile et administration",
        purpose: "Expliquer la dimension économique et administrative de la nouvelle constitution.",
        paragraphs: [
          interpretation("mono-economy-1", "L’Union répond aussi à une logique économique. Le Haut-Canada a engagé des dépenses importantes dans les canaux et les travaux publics et porte une dette plus lourde. Londres et Thomson souhaitent réunir les ressources des deux colonies, soutenir le crédit public et compléter un réseau de transport reliant les Grands Lacs au Saint-Laurent.", ids("sydenham", "actTopic", "upperCanada")),
          fact("mono-finance-1", "L’Acte abolit les mécanismes antérieurs d’arbitrage de certaines réclamations financières entre les deux colonies. Il place leurs droits et revenus sous une structure commune, ce qui met fin à une partie des conflits sur le partage des recettes douanières et des charges.", ids("act")),
          fact("mono-finance-2", "Les revenus que les anciennes législatures pouvaient affecter sont réunis dans un Fonds de revenus consolidé de la Province du Canada. Ce fonds sert au service public de la colonie unie, suivant un ordre de charges fixé par la loi.", ids("act", "civilList")),
          fact("mono-finance-3", "Après les frais de perception, l’intérêt des dettes publiques de l’une ou l’autre ancienne province constitue la deuxième charge du fonds commun. Le mécanisme ne consiste donc pas en un simple transfert comptable de la dette du Haut-Canada au Bas-Canada : les revenus et le paiement des intérêts deviennent des responsabilités de la province unie.", ids("act", "actTopic")),
          fact("mono-civil-list-1", "L’Acte réserve aussi 45 000 livres sterling de façon permanente pour certains services, dont le gouverneur et l’administration de la justice, puis 30 000 livres pour d’autres dépenses gouvernementales pendant la vie de la reine Victoria et cinq années supplémentaires. Cette liste civile de 75 000 livres limite au départ le contrôle annuel de l’Assemblée sur une partie importante des dépenses.", ids("act", "civilList")),
          interpretation("mono-administration-1", "Pour l’administration impériale, ces mesures doivent rendre le gouvernement plus stable et plus efficace. Pour les opposants canadiens-français, elles font plutôt partager une dette qu’ils n’ont pas contractée et soustraient des dépenses au contrôle régulier des élus. Les mêmes dispositions ont donc une fonction administrative et une portée politique contestée.", ids("act", "civilList", "lafontaine", "sydenham")),
        ],
        tables: [{
          id: "table-provisions",
          title: "Principales dispositions et changements immédiats",
          introduction: "Le tableau relie chaque mesure au changement qu’elle produit et à son principal enjeu.",
          columns: ["Disposition", "Changement apporté", "Enjeu ou conséquence immédiate"],
          rows: [
            tableRow("table-provision-union", "L’Acte forme une seule Province du Canada.", ["Union exécutive et législative", "Deux colonies et deux législatures deviennent une colonie et une législature", "Centralisation du pouvoir politique"], ids("act", "boundaries")),
            tableRow("table-provision-seats", "Chaque ancienne province reçoit 42 députés.", ["Représentation égale des sections", "84 sièges répartis également", "Sous-représentation initiale de l’ancien Bas-Canada"], ids("act", "electoralMap", "population")),
            tableRow("table-provision-revenue", "Les revenus et le service des dettes sont réunis.", ["Fonds consolidé", "Mise en commun des recettes et des principales charges", "Partage de l’intérêt de la dette haut-canadienne et financement commun"], ids("act", "actTopic")),
            tableRow("table-provision-civil", "Une liste civile de 75 000 livres est protégée par la loi.", ["Liste civile", "Dépenses permanentes ou de longue durée", "Contrôle budgétaire limité de l’Assemblée"], ids("act", "civilList")),
            tableRow("table-provision-language", "L’anglais devient la langue des documents officiels de la législature.", ["Article XLI", "Originaux officiels en anglais; traductions possibles", "Exclusion juridique du français comme langue d’original officiel"], ids("act")),
            tableRow("table-provision-laws", "Les lois, tribunaux et administrations existants continuent jusqu’à modification.", ["Continuité juridique", "Pas d’uniformisation immédiate des deux sections", "Maintien de régimes juridiques et administratifs distincts"], ids("act", "guide")),
          ],
        }],
      },
      {
        id: "mono-language-territory",
        title: "10. De 1841 à 1848 — Langue, lois, territoire et continuités",
        purpose: "Montrer que l’Union centralise la législature sans effacer toutes les différences.",
        paragraphs: [
          fact("mono-language-1", "L’article XLI exige que les proclamations, les instruments convoquant ou dissolvant la législature, les journaux, les inscriptions et les documents officiels du Conseil législatif et de l’Assemblée soient en anglais. Des traductions peuvent être produites, mais elles ne sont pas conservées comme originaux officiels et n’en ont pas la même valeur.", ids("act")),
          nuance("mono-language-2", "Cette clause constitue une discrimination institutionnelle contre le français, mais elle n’interdit pas toute parole en français ni tous les usages sociaux, religieux, judiciaires ou privés de cette langue. Il faut donc éviter à la fois de minimiser la mesure et de la décrire comme une interdiction totale du français dans la colonie.", ids("act", "lafontaine")),
          fact("mono-laws-1", "L’Acte maintient les lois et ordonnances en vigueur dans chaque ancienne province jusqu’à ce que la nouvelle législature les modifie. Il conserve aussi les tribunaux, les commissions et les fonctions judiciaires ou administratives, sous réserve de changements ultérieurs.", ids("act", "guide")),
          interpretation("mono-laws-2", "Cette continuité explique pourquoi l’union législative ne produit pas une uniformité juridique complète. Le droit civil d’origine française demeure dans la section orientale, tandis que la common law demeure dans la section occidentale. Une seule législature doit ainsi gouverner un espace qui conserve deux traditions juridiques importantes.", ids("act", "guide")),
          fact("mono-territory-1", "Sur le plan territorial, la Province du Canada réunit les espaces des anciennes colonies du Haut-Canada et du Bas-Canada autour des Grands Lacs et de la vallée du Saint-Laurent. La carte historique de 1840 montre une seule nouvelle entité politique, non deux provinces fédérées.", ids("boundaries", "act")),
          nuance("mono-territory-2", "Les appellations Canada-Est et Canada-Ouest deviennent courantes pour faciliter l’administration et la description des deux sections. Elles correspondent respectivement à l’ancien Bas-Canada et à l’ancien Haut-Canada, mais l’Acte lui-même continue de parler des parties qui formaient ces anciennes provinces.", ids("names", "act", "guide")),
          interpretation("mono-territory-3", "L’Union change donc l’échelle politique sans supprimer la dualité territoriale. Les deux sections siègent ensemble et partagent des finances, mais leurs lois, leurs administrations et plusieurs intérêts locaux demeurent distincts. Cette combinaison oblige fréquemment les gouvernants à rechercher des appuis dans les deux parties de la province.", ids("guide", "act", "names")),
        ],
      },
      {
        id: "mono-reactions",
        title: "6. 1840-1841 — Réactions et mise en place du nouveau régime",
        purpose: "Présenter les positions des principaux acteurs sans développer la notion suivante.",
        paragraphs: [
          fact("mono-reaction-1", "Louis-Hippolyte LaFontaine condamne l’Union dans son adresse aux électeurs de Terrebonne en 1840. Il lui reproche d’être imposée sans consentement populaire au Bas-Canada, de réduire sa représentation, d’écarter le français des actes officiels, de mettre les finances en commun et de protéger une liste civile soustraite au vote annuel.", ids("lafontaine", "actTopic", "civilList")),
          nuance("mono-reaction-2", "La réaction canadienne-française n’est pas absolument uniforme. Certains rejettent l’Union, d’autres cherchent à en limiter les effets, et des réformistes comme LaFontaine choisissent finalement d’utiliser les institutions représentatives du nouveau régime. Cette adaptation ne signifie pas qu’ils jugent la loi juste; elle constitue une stratégie politique face à un fait accompli.", ids("lafontaine", "sydenham")),
          fact("mono-sydenham-1", "Sydenham organise les départements de la nouvelle administration, prépare les élections et choisit Kingston comme premier siège du gouvernement. Il cherche à construire une majorité capable d’appuyer les mesures de l’exécutif, ce qui montre que même un gouverneur puissant ne peut gouverner efficacement sans soutien suffisant à l’Assemblée.", ids("sydenham", "guide")),
          interpretation("mono-coalitions-1", "Avec 42 députés par section, aucun groupe régional ne peut présumer gouverner seul de façon durable. La législature commune favorise donc des alliances entre élus de l’Est et de l’Ouest. Cet effet n’équivaut pas encore au gouvernement responsable, mais il crée une condition politique importante : l’exécutif doit composer avec des majorités transsectionnelles.", ids("act", "guide", "lafontaine", "responsible")),
          nuance("mono-responsibility-1", "La responsabilité ministérielle signifie que les ministres doivent conserver la confiance de l’Assemblée élue et que le gouverneur suit normalement leurs conseils dans les affaires intérieures. L’Acte ne garantit pas cette règle. Son fonctionnement fait toutefois apparaître la contradiction entre un exécutif nommé par le gouverneur et une Assemblée dont l’appui est nécessaire pour gouverner.", ids("act", "responsible", "durham")),
        ],
      },
      {
        id: "mono-consequences",
        title: "11. Après 1841 — Changements, continuités et conséquences de l’Acte d’Union",
        purpose: "Distinguer les effets immédiats, les effets à moyen terme et les interprétations historiques.",
        paragraphs: [
          interpretation("mono-consequence-political", "La conséquence politique immédiate est une centralisation : deux législatures sont remplacées par une seule, et les pouvoirs exécutifs sont réunis sous un gouverneur. Cependant, la persistance des deux sections et la représentation égale créent une politique de coalition. L’Union concentre donc les institutions tout en rendant la coopération interrégionale nécessaire.", ids("act", "guide", "electoralMap")),
          interpretation("mono-consequence-democratic", "Sur le plan démocratique, l’ancien Bas-Canada perd du poids relatif au départ et n’a pas consenti à l’Union par une Assemblée élue. En même temps, le retour d’une Chambre élue en 1841 redonne un espace de débat et d’organisation politique après le Conseil spécial. Le changement combine ainsi exclusion et reprise de la vie parlementaire.", ids("specialCouncil", "act", "electoralMap")),
          interpretation("mono-consequence-economic", "Sur le plan économique, le fonds commun et le service commun des dettes facilitent une politique intégrée de crédit et de travaux publics. Ils font aussi porter à l’ensemble de la province les charges associées aux investissements haut-canadiens. Selon le point de vue adopté, la mesure apparaît comme une intégration économique ou comme un partage financier imposé et inégal.", ids("act", "sydenham", "actTopic")),
          interpretation("mono-consequence-linguistic", "Sur le plan linguistique, l’article XLI retire au français le statut d’original officiel dans la législature et participe au projet d’anglicisation. La persistance de la population, des institutions et de l’action politique canadiennes-françaises empêche toutefois l’assimilation rapide envisagée. La clause linguistique sera abrogée en 1848, conséquence ultérieure qui montre l’échec de cette exclusion à s’imposer durablement.", ids("act", "durham", "languageRepeal", "lafontaine")),
          interpretation("mono-consequence-legal", "Sur les plans juridique et territorial, la création d’une seule province ne fait pas disparaître les différences internes. Le maintien de lois, de tribunaux et d’administrations distincts donne au régime une dualité pratique. L’Assemblée nationale décrit ainsi une union législative et financière qui fonctionne, sur plusieurs sujets, comme si deux ensembles devaient être administrés côte à côte.", ids("act", "guide", "names")),
          interpretation("mono-historiography-1", "Une première lecture historique insiste sur l’Union comme instrument impérial d’assimilation et de domination du Bas-Canada. Une deuxième met l’accent sur la centralisation administrative, le crédit et les travaux publics. Une troisième souligne les effets non prévus du régime : coalitions entre sections, survie institutionnelle canadienne-française et pression croissante pour rendre l’exécutif responsable. Ces lectures sont complémentaires lorsqu’elles portent sur des dimensions différentes de la même loi.", ids("durham", "actTopic", "sydenham", "guide", "lafontaine")),
          nuance("mono-transition-1", "La prochaine notion expliquera comment LaFontaine et Baldwin, puis les gouverneurs Bagot, Metcalfe et Elgin, participent aux conflits et aux changements qui mènent au gouvernement responsable. Ici, l’apprentissage attendu s’arrête à comprendre la causalité : l’Acte crée une Assemblée commune influente, mais ne rend pas encore les ministres responsables devant elle.", ids("act", "responsible", "lafontaine")),
        ],
      },
    ].sort((left, right) => CHRONOLOGICAL_MONOGRAPH_SECTION_ORDER.indexOf(left.id as typeof CHRONOLOGICAL_MONOGRAPH_SECTION_ORDER[number]) - CHRONOLOGICAL_MONOGRAPH_SECTION_ORDER.indexOf(right.id as typeof CHRONOLOGICAL_MONOGRAPH_SECTION_ORDER[number])),
  },
  narrative: [
    fact("ninety-two-resolutions", "En 1834, les 92 Résolutions rassemblent les griefs de la majorité patriote et réclament notamment un Conseil législatif électif, une plus grande influence de la population sur l’exécutif et un contrôle réel de l’Assemblée sur les revenus publics.", ids("ninetyTwoResolutions", "ninetyTwoResolutionsPrimary", "lowerCanada")),
    fact("russell-resolutions", "En 1837, les résolutions Russell refusent de rendre le Conseil législatif électif et l’exécutif responsable devant l’Assemblée, puis permettent au gouverneur d’utiliser certains revenus sans son consentement. Ce refus accélère la mobilisation patriote.", ids("russellResolutionsPrimary", "rebellionsChronology", "lowerCanada")),
    fact("context", "Les Rébellions de 1837-1838 sont réprimées par les forces britanniques et coloniales. La répression entraîne des morts, des arrestations, des pendaisons, des déportations et des exils; Londres suspend aussi la constitution parlementaire du Bas-Canada et confie son administration à un Conseil spécial nommé.", ids("program", "canadaRebellions", "durham", "specialCouncil")),
    fact("durham", "Durham recommande en 1839 l’union législative, l’assimilation des Canadiens français et le gouvernement responsable. L’Acte adopte l’Union, mais non la responsabilité ministérielle.", ids("durham", "act", "responsible")),
    fact("consent", "Le Conseil spécial nommé du Bas-Canada accepte l’Union en novembre 1839; aucune Assemblée élue bas-canadienne n’est alors en fonction.", ids("specialCouncil", "chronologyUnion")),
    fact("enactment", "L’Acte est sanctionné le 23 juillet 1840 et entre en vigueur le 10 février 1841. Il crée une seule colonie et une seule législature.", ids("act", "guide", "chronologyUnion")),
    fact("representation", "L’Assemblée compte 84 députés, soit 42 pour chaque ancienne province. Cette égalité sous-représente initialement l’ancien Bas-Canada, plus peuplé.", ids("act", "electoralMap", "population")),
    nuance("population-comparison", "Les chiffres officiels disponibles sont de 455 688 habitants au Haut-Canada en 1841 et de 697 084 au Bas-Canada en 1844; ils confirment l’écart sans constituer une comparaison simultanée.", ids("population")),
    fact("executive", "Le gouverneur, le Conseil exécutif et un Conseil législatif nommé conservent des pouvoirs importants; l’Acte ne soumet pas juridiquement les ministres à la confiance de l’Assemblée.", ids("act", "responsible")),
    fact("finances", "Les revenus deviennent communs, l’intérêt des dettes est payé par le fonds consolidé et une liste civile de 75 000 livres protège certaines dépenses.", ids("act", "civilList")),
    fact("language", "L’article XLI impose l’anglais aux originaux officiels de la législature tout en permettant des traductions sans la même valeur juridique.", ids("act")),
    nuance("legal-continuities", "L’Union ne crée pas une fédération et n’uniformise pas immédiatement les lois : les tribunaux, administrations et règles existants continuent jusqu’à leur modification.", ids("act", "guide")),
    interpretation("political-consequence", "La représentation égale des sections favorise les coalitions transsectionnelles et rend l’appui de l’Assemblée important, sans instaurer encore le gouvernement responsable.", ids("act", "guide", "responsible")),
    interpretation("significance", "L’Union centralise le gouvernement et poursuit un objectif d’anglicisation, mais la dualité juridique, territoriale et politique subsiste et transforme le fonctionnement prévu du régime.", ids("durham", "act", "guide", "lafontaine")),
  ],
  chronologicalMarkers: [
    { ...statement("c-ninety-two-resolutions", "La Chambre d’assemblée du Bas-Canada adopte les 92 Résolutions pour exposer ses griefs et réclamer des réformes politiques.", ids("ninetyTwoResolutions", "ninetyTwoResolutionsPrimary")), dateLabel: "21 février 1834", sortYear: 1834 },
    { ...statement("c-russell-resolutions", "Les résolutions Russell refusent les principales réformes institutionnelles réclamées par l’Assemblée et autorisent l’utilisation de certains revenus sans son consentement.", ids("russellResolutionsPrimary", "rebellionsChronology")), dateLabel: "6 mars 1837", sortYear: 1837 },
    { ...statement("c-rebellions", "Rébellions dans le Bas-Canada et le Haut-Canada.", ids("program", "durham", "upperCanada")), dateLabel: "1837-1838", sortYear: 1837 },
    { ...statement("c-suspension", "Suspension de la constitution parlementaire du Bas-Canada.", ids("specialCouncil")), dateLabel: "10 février 1838", sortYear: 1838 },
    { ...statement("c-durham", "Dépôt du rapport Durham à la Chambre des communes britannique.", ids("durham", "chronologyUnion")), dateLabel: "11 février 1839", sortYear: 1839 },
    { ...statement("c-special-council", "Le Conseil spécial du Bas-Canada adopte des résolutions favorables à l’Union.", ids("specialCouncil", "chronologyUnion")), dateLabel: "13 novembre 1839", sortYear: 1839 },
    { ...statement("c-upper-acceptance", "Le Parlement du Haut-Canada accepte les propositions d’Union de Thomson.", ids("upperCanada", "sydenham", "civilList")), dateLabel: "19 décembre 1839", sortYear: 1839 },
    { ...statement("c-bill", "Lord John Russell présente le projet d’Union aux Communes britanniques.", ids("chronologyUnion")), dateLabel: "23 mars 1840", sortYear: 1840 },
    { ...statement("c-commons", "Adoption du projet par la Chambre des communes britannique.", ids("chronologyUnion")), dateLabel: "18 juin 1840", sortYear: 1840 },
    { ...statement("c-sanction", "Sanction royale de l’Acte d’Union.", ids("act", "chronologyUnion")), dateLabel: "23 juillet 1840", sortYear: 1840 },
    { ...statement("c-force", "Proclamation de l’Union et entrée en vigueur de la Province du Canada.", ids("act", "guide", "sydenham")), dateLabel: "10 février 1841", sortYear: 1841 },
    { ...statement("c-language-repeal", "Abrogation ultérieure de la clause imposant l’anglais aux documents législatifs; repère de conséquence, non développement de la notion suivante.", ids("languageRepeal")), dateLabel: "14 août 1848", sortYear: 1848 },
  ],
  actors: [
    { ...statement("a-durham", "Enquête sur les troubles et recommande union, assimilation et gouvernement responsable.", ids("durham")), actorType: "person", name: "John George Lambton, lord Durham" },
    { ...statement("a-russell", "Secrétaire d’État britannique qui dirige le processus législatif et présente le projet d’Union.", ids("chronologyUnion", "civilList")), actorType: "person", name: "Lord John Russell" },
    { ...statement("a-sydenham", "Négocie, prépare et proclame l’Union; premier gouverneur de la Province du Canada.", ids("sydenham", "act")), actorType: "person", name: "Charles Edward Poulett Thomson, lord Sydenham" },
    { ...statement("a-special-council", "Institution nommée qui gouverne le Bas-Canada sans Assemblée élue et accepte l’Union en 1839.", ids("specialCouncil")), actorType: "institution", name: "Conseil spécial du Bas-Canada" },
    { ...statement("a-upper-parliament", "Institution élue qui débat et accepte l’Union avec ses propres conditions et intérêts.", ids("upperCanada", "sydenham")), actorType: "institution", name: "Parlement du Haut-Canada" },
    { ...statement("a-lafontaine", "Dénonce les injustices de l’Union puis choisit d’agir dans le nouveau Parlement; son action détaillée appartient à la notion suivante.", ids("lafontaine")), actorType: "person", name: "Louis-Hippolyte LaFontaine" },
    { ...statement("a-canadiens-francais", "Majorité de l’ancien Bas-Canada visée par le projet d’assimilation et sous-représentée au début du régime.", ids("durham", "population", "electoralMap")), actorType: "group", name: "Canadiens français" },
  ],
  territories: [
    statement("t-province", "La Province du Canada est une colonie unique créée en 1841 par la réunion des anciennes colonies du Haut-Canada et du Bas-Canada.", ids("act", "guide", "boundaries")),
    statement("t-east", "Le Canada-Est est le nom usuel, non constitutionnel en 1841, de la section correspondant à l’ancien Bas-Canada.", ids("names", "act")),
    statement("t-west", "Le Canada-Ouest est le nom usuel, non constitutionnel en 1841, de la section correspondant à l’ancien Haut-Canada.", ids("names", "act")),
    statement("t-axis", "Le territoire réuni s’organise autour de la vallée du Saint-Laurent et des Grands Lacs, axe majeur des échanges et des travaux de canalisation.", ids("boundaries", "sydenham")),
  ],
  relationships: [
    { ...statement("r-cause", "L’impasse institutionnelle, les Rébellions et leur répression conduisent Londres à revoir le régime; le rapport Durham fournit une justification à l’Union.", ids("durham", "specialCouncil", "program")), relationshipType: "cause", relatedKnowledgeHeadingIds: ["acte-union"] },
    { ...statement("r-financial-cause", "La dette et les travaux publics du Haut-Canada, ainsi que les conflits sur les revenus, favorisent la création de finances communes.", ids("act", "sydenham", "upperCanada")), relationshipType: "cause", relatedKnowledgeHeadingIds: ["acte-union"] },
    { ...statement("r-political-consequence", "La législature unique centralise le pouvoir politique, tandis que la représentation égale oblige fréquemment à former des alliances entre les deux sections.", ids("act", "guide")), relationshipType: "consequence", relatedKnowledgeHeadingIds: ["acte-union"] },
    { ...statement("r-economic-consequence", "Le fonds consolidé permet une politique financière commune et fait supporter à la Province du Canada l’intérêt des dettes contractées par les anciennes colonies.", ids("act", "civilList")), relationshipType: "consequence", relatedKnowledgeHeadingIds: ["acte-union"] },
    { ...statement("r-linguistic-consequence", "L’anglais devient la langue des originaux officiels de la législature, mais l’assimilation rapide envisagée par Durham ne se réalise pas.", ids("act", "durham", "languageRepeal")), relationshipType: "consequence", relatedKnowledgeHeadingIds: ["acte-union"] },
    { ...statement("r-continuity", "La colonie demeure sous la Couronne, le gouverneur conserve de grands pouvoirs et le Conseil législatif reste nommé.", ids("act")), relationshipType: "continuity", relatedKnowledgeHeadingIds: ["gouvernement-responsable"] },
    { ...statement("r-next-notion", "L’écart entre un exécutif nommé et une Assemblée nécessaire au gouvernement prépare les conflits menant à la responsabilité ministérielle, étudiée dans la notion suivante.", ids("act", "responsible", "lafontaine")), relationshipType: "connection", relatedKnowledgeHeadingIds: ["gouvernement-responsable"] },
  ],
  vocabulary: [
    { ...statement("v-union", "Réunion de plusieurs territoires sous une seule législature, sans partage constitutionnel des compétences entre des provinces autonomes.", ids("act", "guide")), term: "Union législative" },
    { ...statement("v-responsibility", "Principe selon lequel les ministres doivent conserver la confiance de la chambre élue; l’Acte d’Union ne l’instaure pas encore.", ids("responsible", "act")), term: "Responsabilité ministérielle" },
    { ...statement("v-assembly", "Chambre composée de députés élus qui débat des projets de loi et vote des fonds.", ids("act")), term: "Assemblée législative" },
    { ...statement("v-legislative-council", "Chambre haute dont les membres sont nommés plutôt qu’élus sous le régime de 1841.", ids("act", "guide")), term: "Conseil législatif" },
    { ...statement("v-executive-council", "Groupe de conseillers participant à l’administration auprès du gouverneur.", ids("act", "responsible")), term: "Conseil exécutif" },
    { ...statement("v-equal", "Attribution du même nombre de députés aux deux sections, sans proportion directe avec leur population.", ids("act", "electoralMap")), term: "Représentation égale" },
    { ...statement("v-consolidated", "Compte public commun regroupant les revenus et servant à payer les charges de la Province du Canada.", ids("act")), term: "Fonds consolidé" },
    { ...statement("v-civil-list", "Sommes protégées destinées à certaines dépenses du gouverneur, de la justice et de l’administration.", ids("act", "civilList")), term: "Liste civile" },
    { ...statement("v-assimilation", "Processus par lequel un groupe est amené à perdre des caractères collectifs au profit d’un autre; objectif explicite du projet de Durham.", ids("durham")), term: "Assimilation" },
    { ...statement("v-royal", "Approbation formelle donnée au nom de la Couronne et nécessaire pour qu’un projet de loi entre dans l’ordre juridique.", ids("act")), term: "Sanction royale" },
  ],
  misconceptions: [
    { ...statement("m-date", "La loi est sanctionnée en 1840 et le régime entre en vigueur en 1841.", ids("act", "chronologyUnion")), misconception: "Il faut choisir entre 1840 et 1841 comme seule date correcte." },
    { ...statement("m-federation", "Le Canada-Est et le Canada-Ouest sont deux sections d’une même province, non deux provinces fédérées.", ids("act", "names")), misconception: "L’Union crée une fédération." },
    { ...statement("m-responsible", "Durham recommande la responsabilité, mais l’Acte ne la garantit pas; son obtention appartient à la notion suivante.", ids("act", "durham", "responsible")), misconception: "L’Acte d’Union crée le gouvernement responsable." },
    { ...statement("m-french", "La clause vise les originaux officiels de la législature; elle n’interdit pas tous les usages du français.", ids("act", "lafontaine")), misconception: "Le français devient totalement illégal dans la Province du Canada." },
    { ...statement("m-consent", "Le Bas-Canada est administré par un Conseil spécial nommé lorsque celui-ci accepte l’Union.", ids("specialCouncil")), misconception: "Les deux populations approuvent l’Union par leurs assemblées élues." },
    { ...statement("m-debt", "Les revenus et le paiement de l’intérêt deviennent communs; il ne s’agit pas d’une facture simplement remise au Bas-Canada.", ids("act")), misconception: "Toute la dette du Haut-Canada est directement transférée au Bas-Canada." },
    { ...statement("m-uniformity", "Les lois, tribunaux et administrations continuent jusqu’à leur modification; les deux traditions juridiques ne disparaissent pas en 1841.", ids("act", "guide")), misconception: "L’Union rend immédiatement toutes les lois identiques." },
  ],
  expectedLearning: [
    objective("e-definition", "Expliquer ce qu’est l’Acte d’Union : une loi britannique sanctionnée en 1840 et mise en vigueur en 1841 qui réunit le Haut-Canada et le Bas-Canada dans une seule Province du Canada dotée d’une législature unique.", ids("program", "act", "guide"), "Rubrique officielle « Acte d’Union » et opération « Établir des faits ».", ["Loi britannique", "1840 et 1841", "Province du Canada", "Législature unique"], ["establish_facts", "time_and_space"]),
    objective("e-chain", "Relier l’impasse politique, les 92 Résolutions, le refus exprimé par les résolutions Russell, les Rébellions, la suspension du régime bas-canadien, le rapport Durham et l’Acte d’Union dans une chaîne causale.", ids("program", "ninetyTwoResolutionsPrimary", "russellResolutionsPrimary", "durham", "specialCouncil"), "Rubrique officielle « Acte d’Union » et opération « Établir des liens de causalité ».", ["92 Résolutions", "Résolutions Russell", "Rébellions", "Conseil spécial", "Rapport Durham", "Acte d’Union"], ["causal_connections"]),
    objective("e-demands-response", "Comparer les principales demandes des 92 Résolutions à la réponse formulée dans les résolutions Russell : Conseil législatif électif, responsabilité de l’exécutif et contrôle des revenus publics.", ids("ninetyTwoResolutionsPrimary", "russellResolutionsPrimary", "rebellionsChronology"), "Dérivation éditoriale de Socrato fondée sur les opérations ministérielles « Dégager des différences et des similitudes » et « Mettre en relation des faits ».", ["Conseil législatif électif", "Responsabilité de l’exécutif", "Contrôle des revenus", "Demandes et refus"], ["differences_and_similarities", "relationships_between_facts"]),
    objective("e-structure", "Représenter la structure politique de 1841 en distinguant la Couronne, le gouverneur, les conseils nommés et l’Assemblée élue.", ids("program", "act", "guide"), "Précision officielle « Structure politique » et compétence « Caractériser une période de l’histoire du Québec et du Canada ».", ["Couronne", "Gouverneur", "Conseil exécutif", "Conseil législatif", "Assemblée législative"], ["establish_facts", "relationships_between_facts"]),
    objective("e-provisions", "Expliquer les principaux changements : union législative, 42 sièges par section, revenus et dettes communs, liste civile et anglais dans les originaux officiels.", ids("program", "act", "civilList"), "Précisions officielles « Structure politique » et « Dispositions administratives ».", ["Union législative", "Représentation", "Fonds consolidé", "Liste civile", "Article XLI"], ["establish_facts", "changes_and_continuities"]),
    objective("e-effects", "Distinguer les conséquences politiques, économiques, linguistiques, territoriales et démographiques de l’Acte, ainsi que les continuités du pouvoir colonial et des régimes juridiques.", ids("program", "act", "guide", "population"), "Rubrique officielle « Acte d’Union » et opérations portant sur les conséquences, les changements et les continuités.", ["Centralisation", "Sous-représentation", "Finances communes", "Anglicisation", "Dualité juridique"], ["causes_and_consequences", "changes_and_continuities"]),
    objective("e-population", "Utiliser les données de population en nommant leur année et expliquer pourquoi elles établissent un écart sans constituer une comparaison parfaitement simultanée.", ids("population", "act", "electoralMap"), "Précision « Contexte sociopolitique et économique » et lecture critique de données historiques.", ["432 159 en 1840", "455 688 en 1841", "697 084 en 1844", "42 sièges par section"], ["time_and_space", "relationships_between_facts"]),
    objective("e-responsibility", "Définir la responsabilité ministérielle et expliquer que l’Acte d’Union ne l’instaure pas, mais crée une tension entre l’exécutif nommé et l’Assemblée élue qui mène à la notion suivante.", ids("program", "act", "durham", "responsible"), "Lien explicite entre la rubrique « Acte d’Union » et la rubrique suivante « Gouvernement responsable », sans anticiper son étude détaillée.", ["Confiance parlementaire", "Exécutif nommé", "Assemblée élue", "Transition causale"], ["relationships_between_facts", "causal_connections"]),
    objective("e-territory", "Situer la Province du Canada et distinguer ses sections orientale et occidentale sans les présenter comme deux provinces fédérées.", ids("program", "act", "names", "boundaries"), "Précision officielle « Territoire de la Province du Canada » et opération « Situer dans le temps et dans l’espace ».", ["Province du Canada", "Ancien Bas-Canada", "Ancien Haut-Canada", "Saint-Laurent", "Grands Lacs"], ["time_and_space"]),
    objective("e-interpretations", "Comparer trois interprétations compatibles de l’Union : instrument d’assimilation, réorganisation administrative et économique, puis régime produisant des coalitions et des effets non prévus.", ids("durham", "actTopic", "sydenham", "guide"), "Approfondissement éditorial de Socrato appuyé sur la mise en relation de faits et la distinction entre faits et interprétations.", ["Assimilation", "Centralisation", "Travaux publics", "Coalitions", "Effets non prévus"], ["differences_and_similarities", "relationships_between_facts"]),
  ],
  sourceCatalog: [
    ...Object.values(SOURCES),
    ...ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter((documentSource) => !Object.values(SOURCES).some((source) => source.url && source.url === documentSource.url)),
  ],
  editorialNotes: "Monographie de travail rédigée le 30 juillet 2026 comme synthèse originale à partir des sources indiquées. Aucun passage n’est approuvé pour un usage élève. Une révision historienne, pédagogique, linguistique et juridique indépendante demeure obligatoire avant approbation ou soumission externe.",
  version: null,
  approvedAt: null,
};
