import Link from "next/link";
import "../../pedagogical-reference.css";
import "./period-overview.css";

const timeline = [
  ["1840", "Acte d’Union", "/historical-documents/timeline-kingston-1841.jpg", "Vue de Kingston au début des années 1840", "W. H. Bartlett, vers 1841", "https://commons.wikimedia.org/wiki/File:Citadel_of_Kingston.jpg", "Politique"],
  ["1844", "Fondation de l’Institut canadien|Dépôt du rapport de la commission Bagot", "/historical-documents/period-1840-1896/institut-canadien.png", "Édifice de l’Institut canadien de Montréal, rue Notre-Dame", "Édifice de l’Institut canadien · BAnQ, no 2731703", "https://commons.wikimedia.org/wiki/File:%C3%89difice_de_l%27Institut_canadien_de_Montr%C3%A9al_sur_la_rue_Notre-Dame_entre_1870_et_1920_-_Building_of_the_Institut_canadien_de_Montreal_on_Notre-Dame_Street_between_1870_and_1920.png", "Culture et politique"],
  ["1845-1848", "Publication de Histoire du Canada depuis sa découverte jusqu’à nos jours", "/historical-documents/period-1840-1896/garneau.jpg", "Portrait de François-Xavier Garneau", "François-Xavier Garneau, XIXe siècle", "https://commons.wikimedia.org/wiki/File:Francois-Xavier_Garneau.jpg", "Culture"],
  ["1845-1847", "Immigration irlandaise massive", "/historical-documents/period-1840-1896/irish-famine-1847.jpg", "Illustration de la famine à Skibbereen en 1847", "James Mahony, Illustrated London News, 1847", "https://commons.wikimedia.org/wiki/File:Skibbereen_by_James_Mahony,_1847.JPG", "Population"],
  ["1849", "Incendie du parlement de Montréal|Retrait du droit de vote aux femmes", "/historical-documents/gr-parliament-fire.jpg", "Lithographie montrant le Parlement de Montréal en flammes", "E. Hides et Matthews’ Lith., 1849 · BAC", "https://commons.wikimedia.org/wiki/File:Destruction_of_the_Parliament_House_-_Montreal_-_April_25th_1849.jpg", "Politique et société"],
  ["1852", "Fondation de la Compagnie du Grand Tronc|Fondation de la première université francophone d’Amérique", "/historical-documents/period-1840-1896/grand-trunk.jpg", "Pont ferroviaire du Grand Tronc au XIXe siècle", "Pont du Grand Tronc, photographie du XIXe siècle", "https://commons.wikimedia.org/wiki/File:Railroad_Bridge_over_the_Grand_River._Grand_Trunk_Railway.jpg", "Économie et culture"],
  ["1854", "Abolition du régime seigneurial", "/historical-documents/period-1840-1896/cour-seigneuriale-1855.jpg", "Lithographie de la Cour spéciale réunie en vertu de l’Acte seigneurial de 1854", "William Lockwood, 1856 · Musée McCord, M5524", "https://commons.wikimedia.org/wiki/File:Cour_speciale_assemblee_en_vertu_de_l_acte_seigneurial_du_parlement_provincial_de_1854.jpg", "Société"],
  ["1854-1866", "Traité de réciprocité", "/historical-documents/period-1840-1896/reciprocity-treaty-1854.jpg", "Page de titre d’un ouvrage historique consacré au traité de réciprocité de 1854", "The Canadian Reciprocity Treaty of 1854 · exemplaire numérisé", "https://commons.wikimedia.org/wiki/File:The_Canadian_reciprocity_treaty_of_1854_(IA_canadianreciproc00tansiala).pdf", "Économie"],
  ["1866", "Entrée en vigueur du Code civil du Bas-Canada", "/historical-documents/period-1840-1896/code-civil.jpg", "Page couverture du Code civil du Bas-Canada", "Code civil du Bas-Canada, édition de 1866", "https://commons.wikimedia.org/wiki/File:Cover_page_Civil_Code_of_Lower-Canada.jpg", "Droit"],
  ["1867", "Adoption de l’Acte de l’Amérique du Nord britannique", "/historical-documents/period-1840-1896/bna-act-1867.jpg", "Première page de l’Acte de l’Amérique du Nord britannique", "British North America Act, 1867", "https://commons.wikimedia.org/wiki/File:British_North_America_Act,_1867.jpg", "Politique"],
  ["1869", "Premier soulèvement des Métis", "/historical-documents/period-1840-1896/metis-1869.jpg", "Membres du gouvernement provisoire métis", "Gouvernement provisoire métis, 1870 · BAC", "https://commons.wikimedia.org/wiki/File:ProvisionalMetisGovernment.jpg", "Territoire et politique"],
  ["1870", "Création des Territoires du Nord-Ouest", "/historical-documents/period-1840-1896/metis-1869.jpg", "Gouvernement provisoire métis durant les transformations territoriales", "Gouvernement provisoire métis, 1870 · BAC", "https://commons.wikimedia.org/wiki/File:ProvisionalMetisGovernment.jpg", "Territoire"],
  ["1872", "Légalisation des syndicats", "/historical-documents/period-1840-1896/printers-strike-1872.jpg", "Plaque historique illustrant la grève des typographes de Toronto de 1872", "Grève des typographes de Toronto · mouvement des neuf heures", "https://commons.wikimedia.org/wiki/File:The_Printers%27_Strike_of_1872.jpg", "Travail"],
  ["1875", "Abolition du ministère de l’Instruction publique", "/historical-documents/period-1840-1896/parliament-ottawa.jpg", "Édifice du Parlement canadien au XIXe siècle", "Édifices du Parlement à Ottawa, XIXe siècle", "https://commons.wikimedia.org/wiki/File:Original_Canadian_parliament.jpg", "Éducation et politique"],
  ["1876", "Adoption de la Loi sur les Indiens", "/historical-documents/period-1840-1896/parliament-ottawa.jpg", "Parlement où est adoptée la Loi sur les Indiens", "Édifices du Parlement à Ottawa, XIXe siècle", "https://commons.wikimedia.org/wiki/File:Original_Canadian_parliament.jpg", "État et Autochtones"],
  ["1885", "Pendaison de Louis Riel", "/historical-documents/period-1840-1896/riel.jpg", "Portrait de Louis Riel", "Louis Riel, photographie du XIXe siècle · BAC", "https://commons.wikimedia.org/wiki/File:Louis_Riel.jpg", "Politique"],
  ["1893", "Fondation du Montreal Local Council of Women", "/historical-documents/period-1840-1896/lady-aberdeen.jpg", "Portrait de lady Aberdeen", "Lady Aberdeen, figure du Conseil national des femmes", "https://commons.wikimedia.org/wiki/File:Lady_Ishbel_Aberdeen_1899_IIAV_15541.TIF", "Femmes et société"],
  ["1895", "Fondation de l’École littéraire de Montréal", "/historical-documents/period-1840-1896/ecole-litteraire-1900.jpg", "Une du Monde illustré présentant les membres de l’École littéraire de Montréal", "Le Monde illustré, 21 avril 1900 · MEM", "https://ville.montreal.qc.ca/memoiresdesmontrealais/files/ecole-litteraire-de-montreal-1899-1900", "Culture"],
] as const;

export default function Period18401896Page() {
  return <main className="reference-admin period-overview">
    <header className="reference-admin__header"><div><p>Administration · Référentiel pédagogique</p><h1>1840-1896</h1><span>La formation du régime fédéral canadien · espace transversal de la période</span></div><div className="reference-admin__header-actions"><Link href="/admin/pedagogical-reference">Toutes les périodes</Link><Link href="/admin/pedagogical-reference/questions?scope=transversal">Questions transversales</Link></div></header>
    <nav className="period-overview__tabs" aria-label="Sections de la période"><a href="#chronologie">Ligne du temps</a><a href="#questions">Questions transversales</a><a href="#futures">Autres chronologies</a></nav>
    <section className="period-overview__intro"><p>Document de référence ministériel</p><h2>Une vue d’ensemble de la période</h2><span>Cette première chronologie reprend les repères de la ligne du temps transmise. Chaque carte visuelle relie une date, un événement et une dimension de la réalité sociale.</span></section>
    <section id="chronologie" className="period-timeline" aria-labelledby="period-timeline-title"><header><div><p>1840 → 1896</p><h2 id="period-timeline-title">Ligne du temps transversale</h2></div><strong>{timeline.length} repères illustrés</strong></header><div className="period-timeline__rail">{timeline.map(([date, joinedEvents, image, alt, credit, source, theme], index) => { const events = joinedEvents.split("|"); return <article className="period-event" key={`${date}-${index}`}><div className="period-event__marker"><time>{date}</time><span aria-hidden="true" /></div><div className="period-event__card"><a href={source} target="_blank" rel="noreferrer"><img src={image} alt={alt} /></a><div><small>{theme}</small><h3>{events.join(" · ")}</h3>{events.length > 1 ? <ul>{events.map((event) => <li key={event}>{event}</li>)}</ul> : null}<p>{credit}</p><a href={source} target="_blank" rel="noreferrer">Voir la source visuelle ↗</a></div></div></article>; })}</div></section>
    <section id="questions" className="period-hub"><div><p>Banque de questions</p><h2>Questions transversales</h2><span>Les questions qui mobilisent plusieurs notions de 1840 à 1896 seront regroupées ici.</span></div><Link href="/admin/pedagogical-reference/questions?scope=transversal">Ouvrir les questions transversales →</Link></section>
    <section id="futures" className="period-hub period-hub--future"><div><p>À développer</p><h2>Chronologies qui traversent plusieurs notions</h2><span>Cet espace pourra accueillir des parcours ciblés : territoire et fédération, industrialisation et travail, droits politiques, migrations ou relations avec les peuples autochtones.</span></div></section>
  </main>;
}
