import type { HistoricalDocumentRecord } from "./historical-document.ts";

export const BRITISH_NORTH_AMERICA_MACDONALD_CONFEDERATION_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-001",
  title: "Macdonald défend un gouvernement central fort",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["differences_and_similarities", "relationships_between_facts", "establish_facts"],
  historicalDate: "6 février 1865",
  creator: "John A. Macdonald, procureur général du Canada-Ouest",
  holdingInstitution: "Débats parlementaires de la Province du Canada · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/confederation-debates-legislative-assembly-february-6-1865/",
  sourceLocator: "Débats sur la Confédération, Assemblée législative de la Province du Canada, 6 février 1865, p. 35-42.",
  assetUrl: "https://primarydocuments.ca/confederation-debates-legislative-assembly-february-6-1865/",
  rightsStatement: "Débat parlementaire de 1865 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato.",
  transcription: "Toutes les grandes questions qui touchent les intérêts généraux de la Confédération seront confiées au Parlement fédéral, tandis que les intérêts et les lois locales de chaque province seront préservés et placés sous la responsabilité des législatures provinciales. […] Le Parlement fédéral s’occupera notamment de la dette publique, du commerce, des douanes, des chemins de fer et des canaux qui relient plusieurs provinces. La défense du pays relèvera également du gouvernement général. Au lieu de posséder plusieurs systèmes militaires séparés, nous aurons une organisation commune permettant aux provinces de se porter assistance. […] Nous renforcerons ainsi le Parlement central et ferons de la Confédération un seul peuple et un seul gouvernement, plutôt que plusieurs peuples et plusieurs gouvernements unis par une autorité trop faible.",
  accessibleDescription: "Montage d’extraits dans lesquels Macdonald attribue les grandes questions communes au Parlement fédéral et défend un gouvernement central puissant.",
  historicalContext: "Macdonald présente le projet issu de la Conférence de Québec devant l’Assemblée législative. Il souhaite éviter la faiblesse qu’il attribue au système américain en confiant au gouvernement central les pouvoirs généraux et résiduels.",
  observationGuide: ["Repérer les responsabilités attribuées au Parlement fédéral.", "Identifier les responsabilités laissées aux provinces.", "Expliquer pourquoi Macdonald souhaite renforcer le pouvoir central."],
  interpretationCautions: ["L’extrait réunit plusieurs passages du même discours; les […] signalent les coupures.", "Macdonald défend le projet gouvernemental et cherche à convaincre l’Assemblée.", "L’expression un seul peuple et un seul gouvernement n’abolit pas les provinces, mais révèle sa préférence pour un centre politique puissant."],
  pedagogicalUses: ["Déterminer le point de vue de Macdonald sur le partage des pouvoirs.", "Comparer sa conception du pouvoir central à celles de Cartier et de Dorion."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_CARTIER_CONFEDERATION_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-002",
  title: "Cartier présente la fédération comme une union protectrice des particularités locales",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["differences_and_similarities", "causes_and_consequences", "establish_facts"],
  historicalDate: "7 et 21 février 1865",
  creator: "George-Étienne Cartier, procureur général du Canada-Est",
  holdingInstitution: "Débats parlementaires de la Province du Canada · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/confederation-debates-legislative-assembly-february-7-1865/",
  sourceLocator: "Débats sur la Confédération, Assemblée législative de la Province du Canada, 7 février 1865, p. 55-62, et 21 février 1865, p. 367-368.",
  assetUrl: "https://primarydocuments.ca/confederation-debates-legislative-assembly-february-21-1865/",
  rightsStatement: "Débats parlementaires de 1865 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato.",
  transcription: "La Confédération est devenue nécessaire. Les provinces britanniques, si elles demeurent séparées, ne peuvent assurer efficacement leur défense. Une fois unies, elles pourront se protéger mutuellement et bénéficier de la force de l’Empire britannique. L’union favorisera également le commerce en donnant au Canada un meilleur accès aux ports maritimes. […] Il serait toutefois impossible qu’un seul gouvernement administre tous les intérêts particuliers et locaux des différentes provinces. C’est précisément en raison de la diversité des populations, des religions et des intérêts locaux que le système fédéral doit être adopté. […] Le Parlement central s’occupera du commerce, des communications et des questions générales. Les gouvernements provinciaux conserveront la responsabilité des affaires locales. Les Canadiens français pourront donc administrer leurs institutions, leur religion et leur nationalité sans les remettre entre les mains de la majorité du Canada-Ouest.",
  accessibleDescription: "Montage d’extraits dans lesquels Cartier associe la Confédération à la défense et au commerce, tout en présentant l’autonomie provinciale comme une protection des particularités locales.",
  historicalContext: "Cartier doit convaincre les députés du Canada-Est que la représentation selon la population au Parlement fédéral ne fera pas disparaître leurs institutions. Il présente la fédération comme un compromis entre l’union des colonies et la maîtrise provinciale des affaires locales.",
  observationGuide: ["Repérer les avantages communs associés à l’union.", "Identifier pourquoi Cartier rejette un gouvernement unique pour toutes les affaires.", "Nommer les particularités que les gouvernements provinciaux doivent protéger."],
  interpretationCautions: ["L’extrait réunit des passages de deux interventions; les […] signalent les coupures.", "Cartier défend le projet gouvernemental et minimise les risques dénoncés par ses adversaires.", "La protection annoncée des institutions ne signifie pas que toutes les minorités ou tous les peuples participent également au projet."],
  pedagogicalUses: ["Déterminer les arguments de Cartier en faveur du fédéralisme.", "Distinguer son insistance sur l’autonomie provinciale de la préférence de Macdonald pour un centre fort."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_DORION_CONFEDERATION_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-003",
  title: "Dorion craint la centralisation et la domination de la majorité",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["differences_and_similarities", "establish_facts"],
  historicalDate: "16 février 1865",
  creator: "Antoine-Aimé Dorion, député d’Hochelaga et chef de l’opposition",
  holdingInstitution: "Débats parlementaires de la Province du Canada · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/confederation-debates-legislative-assembly-february-16-1865/",
  sourceLocator: "Débats sur la Confédération, Assemblée législative de la Province du Canada, 16 février 1865, intervention d’Antoine-Aimé Dorion.",
  assetUrl: "https://primarydocuments.ca/confederation-debates-legislative-assembly-february-16-1865/",
  rightsStatement: "Débat parlementaire de 1865 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato.",
  transcription: "Dans le gouvernement fédéral, le Bas-Canada ne comptera qu’une minorité de représentants. […] Quelles garanties aurons-nous que la majorité ne modifiera pas nos institutions? Le pouvoir central pourra intervenir dans les affaires provinciales et imposer ses décisions. […] Une transformation aussi importante de la constitution ne devrait pas être imposée sans consulter directement la population.",
  accessibleDescription: "Montage d’extraits présentant les craintes de Dorion envers la majorité fédérale, les pouvoirs du gouvernement central et l’absence de consultation populaire directe.",
  historicalContext: "Dorion accepte l’idée générale d’une fédération dans certaines conditions, mais s’oppose au projet de 1864-1865. Il estime que le gouvernement central dispose de pouvoirs trop étendus et que les garanties offertes au Canada-Est sont insuffisantes.",
  observationGuide: ["Repérer le groupe que Dorion croit placé en minorité.", "Identifier le risque qu’il associe au pouvoir central.", "Relever sa critique du processus d’adoption."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée; les […] signalent les coupures.", "Dorion ne rejette pas nécessairement tout modèle fédéral : il s’oppose au projet précis qui lui est soumis.", "Son point de vue est celui d’un chef politique du Canada-Est et ne représente pas automatiquement toute sa population."],
  pedagogicalUses: ["Déterminer des objections au projet de Confédération.", "Comparer une critique du pouvoir central aux arguments favorables de Macdonald et de Cartier."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_ANNAND_RAILWAY_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-004",
  title: "La Nouvelle-Écosse exige que le chemin de fer précède l’union",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["establish_facts", "differences_and_similarities"],
  historicalDate: "5 avril 1866",
  creator: "William Annand, député de la Nouvelle-Écosse opposé au projet de Confédération",
  holdingInstitution: "Débats de la Chambre d’assemblée de la Nouvelle-Écosse · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/nova-scotia-house-of-assembly-debates-and-proceedings-union-of-the-colonies-5-april-1866/",
  sourceLocator: "Débats de la Chambre d’assemblée de la Nouvelle-Écosse, 5 avril 1866, intervention de William Annand.",
  assetUrl: "https://primarydocuments.ca/nova-scotia-house-of-assembly-debates-and-proceedings-union-of-the-colonies-5-april-1866/",
  rightsStatement: "Débat parlementaire de 1866 appartenant au domaine public; traduction française de l’extrait préparée pour Socrato.",
  transcription: "En supposant que l’union soit souhaitable […], je crois et je soutiens que le chemin de fer doit précéder l’union. […] Nous devrions actuellement traverser les régions sauvages du Nouveau-Brunswick; je maintiens donc que le chemin de fer doit précéder l’union.",
  accessibleDescription: "William Annand soutient que le chemin de fer reliant les colonies doit être construit avant que la Nouvelle-Écosse accepte l’union.",
  historicalContext: "Annand s’oppose au projet présenté par le gouvernement de la Nouvelle-Écosse. Il considère qu’une liaison ferroviaire concrète entre les colonies doit précéder leur union politique.",
  observationGuide: ["Repérer ce qui doit être construit avant l’union selon Annand.", "Identifier l’ordre qu’il établit entre le chemin de fer et l’union.", "Distinguer sa position de celle d’un partisan d’une construction après l’adhésion."],
  interpretationCautions: ["Annand exprime le point de vue d’un député d’opposition et non celui de toute la population de la Nouvelle-Écosse.", "L’extrait comporte des coupures signalées par […].", "Son argument ne signifie pas qu’il rejette nécessairement toute union possible, mais qu’il refuse l’ordre des étapes proposé."],
  pedagogicalUses: ["Établir une condition associée à l’adhésion de la Nouvelle-Écosse.", "Comparer l’importance accordée au chemin de fer en Nouvelle-Écosse et au Nouveau-Brunswick."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_FISHER_RAILWAY_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-005",
  title: "Le Nouveau-Brunswick demande la construction immédiate du chemin de fer Intercolonial",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["establish_facts", "differences_and_similarities"],
  historicalDate: "30 juin 1866",
  creator: "Charles Fisher, procureur général du Nouveau-Brunswick",
  holdingInstitution: "Débats de la Chambre d’assemblée du Nouveau-Brunswick · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/new-brunswick-house-of-assembly-debates-of-the-house-of-assembly-mr-fishers-resolution-regarding-the-appointment-of-delegates-30-june-1866/",
  sourceLocator: "Débats de la Chambre d’assemblée du Nouveau-Brunswick, 30 juin 1866, résolution proposée par Charles Fisher.",
  assetUrl: "https://primarydocuments.ca/new-brunswick-house-of-assembly-debates-of-the-house-of-assembly-mr-fishers-resolution-regarding-the-appointment-of-delegates-30-june-1866/",
  rightsStatement: "Débat parlementaire de 1866 appartenant au domaine public; traduction française de l’extrait préparée pour Socrato.",
  transcription: "[Que des délégués soient nommés] pour organiser avec le gouvernement impérial l’Union de l’Amérique du Nord britannique, selon des conditions qui garantiront les droits et les intérêts du Nouveau-Brunswick, accompagnées d’une disposition prévoyant la construction immédiate du chemin de fer Intercolonial.",
  accessibleDescription: "La résolution de Charles Fisher lie l’union des colonies à la protection des intérêts du Nouveau-Brunswick et à la construction immédiate du chemin de fer Intercolonial.",
  historicalContext: "En 1866, le gouvernement favorable à la Confédération cherche à faire approuver l’envoi de délégués auprès du gouvernement britannique. La résolution présente le chemin de fer Intercolonial comme une garantie concrète accompagnant l’union.",
  observationGuide: ["Repérer l’infrastructure réclamée dans la résolution.", "Identifier le moment prévu pour sa construction.", "Relier cette disposition aux intérêts du Nouveau-Brunswick."],
  interpretationCautions: ["Il s’agit d’une résolution gouvernementale favorable au projet de Confédération.", "Les crochets indiquent un ajout nécessaire pour rendre la citation compréhensible hors de son contexte.", "La construction immédiate demandée n’implique pas que le chemin de fer était déjà achevé au moment du débat."],
  pedagogicalUses: ["Établir une condition associée à l’adhésion du Nouveau-Brunswick.", "Comparer cette demande à la position de William Annand en Nouvelle-Écosse."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_RAILWAY_CONDITION_DOCUMENTS = [
  BRITISH_NORTH_AMERICA_ANNAND_RAILWAY_DOCUMENT,
  BRITISH_NORTH_AMERICA_FISHER_RAILWAY_DOCUMENT,
] as const;

export const BRITISH_NORTH_AMERICA_BELLEAU_INSTABILITY_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-006",
  title: "Belleau relie l’instabilité à la coalition et aux conférences",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causal_connections", "relationships_between_facts"],
  historicalDate: "14 février 1865",
  creator: "Narcisse-Fortunat Belleau, conseiller législatif",
  holdingInstitution: "Conseil législatif de la Province du Canada · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/lc-14-fev-1865/?lang=fr",
  sourceLocator: "Débats sur la Confédération, Conseil législatif, 14 février 1865, p. 183-184.",
  assetUrl: "https://primarydocuments.ca/lc-14-fev-1865/?lang=fr",
  rightsStatement: "Débat parlementaire de 1865 appartenant au domaine public; reformulation pédagogique fidèle composée à partir de passages du même discours.",
  transcription: "Depuis trois ans, les gouvernements se succèdent rapidement et le pays connaît une véritable instabilité politique. Les conflits entre les partis risquent de bloquer les affaires publiques. […] Pour sortir de cette situation, des dirigeants politiques ont décidé de se réunir dans une coalition. Cette coalition [la Grande Coalition] repose sur le principe de la Confédération. […] Ses membres participent ensuite aux conférences de Charlottetown et de Québec, qui produisent le projet maintenant présenté au Parlement.",
  accessibleDescription: "Reformulation des propos de Belleau reliant la succession des gouvernements, la formation de la Grande Coalition et les conférences constitutionnelles.",
  historicalContext: "Belleau défend le projet de Confédération devant le Conseil législatif en 1865. Il présente la coalition et les conférences comme une réponse à l’instabilité politique de la Province du Canada.",
  observationGuide: ["Repérer le problème politique initial.", "Identifier la solution immédiate adoptée par les dirigeants.", "Relier la coalition aux conférences de Charlottetown et de Québec."],
  interpretationCautions: ["Le texte est une reformulation pédagogique fidèle, et non une transcription mot à mot.", "Les […] signalent le rapprochement de passages distincts du même discours.", "Les crochets identifient un référent implicite sans ajouter un nouvel argument."],
  pedagogicalUses: ["Construire une chaîne causale de l’instabilité aux conférences.", "Distinguer la coalition politique du projet constitutionnel qu’elle fait progresser."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_BROWN_COALITION_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-007",
  title: "Brown justifie son entrée dans la Grande Coalition",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causal_connections", "relationships_between_facts"],
  historicalDate: "8 février 1865",
  creator: "George Brown, président du Conseil exécutif",
  holdingInstitution: "Assemblée législative de la Province du Canada · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/la-8-fev-1865/?lang=fr",
  sourceLocator: "Débats sur la Confédération, Assemblée législative, 8 février 1865, p. 82-116.",
  assetUrl: "https://primarydocuments.ca/la-8-fev-1865/?lang=fr",
  rightsStatement: "Débat parlementaire de 1865 appartenant au domaine public; reformulation pédagogique fidèle composée à partir de passages du même discours.",
  transcription: "Pendant plusieurs années, nous avons connu des luttes politiques, des élections répétées et de nombreuses crises ministérielles. […] Malgré nos anciennes rivalités, des dirigeants des deux côtés de la Chambre ont accepté de mettre leurs différends de côté pour le bien du pays. J’ai accepté de joindre le gouvernement [de la Grande Coalition] afin que nous puissions trouver une solution constitutionnelle. […] Depuis la formation de notre coalition, nous avons élaboré un projet d’union fédérale. Ce projet doit permettre de mettre fin aux difficultés politiques qui divisent la Province du Canada.",
  accessibleDescription: "Reformulation à la première personne des propos de George Brown sur les crises politiques, la collaboration entre adversaires et le projet d’union fédérale.",
  historicalContext: "Brown avait longtemps combattu Macdonald et Cartier. En juin 1864, il accepte néanmoins de collaborer avec eux afin de rechercher une solution constitutionnelle à l’impasse politique.",
  observationGuide: ["Repérer pourquoi Brown accepte de collaborer avec ses adversaires.", "Identifier le rôle de la coalition.", "Nommer le projet produit par cette collaboration."],
  interpretationCautions: ["Le texte est une reformulation pédagogique fidèle à la première personne.", "Les […] rapprochent des passages distincts du même discours.", "L’entrée de Brown dans la coalition ne signifie pas la disparition de toutes les rivalités politiques."],
  pedagogicalUses: ["Relier la Grande Coalition au projet d’union fédérale.", "Interpréter le point de vue d’un acteur de la coalition."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_MONCK_NEGOTIATIONS_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-008",
  title: "Monck présente les négociations et les Résolutions de Québec",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causal_connections", "relationships_between_facts"],
  historicalDate: "19 janvier 1865",
  creator: "Charles Stanley Monck, gouverneur général de la Province du Canada",
  holdingInstitution: "Conseil législatif de la Province du Canada · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/province-of-canada-legislative-council-parliamentary-debates-speech-from-the-throne-19-january-1865/",
  sourceLocator: "Discours du Trône, Conseil législatif de la Province du Canada, 19 janvier 1865.",
  assetUrl: "https://primarydocuments.ca/province-of-canada-legislative-council-parliamentary-debates-speech-from-the-throne-19-january-1865/",
  rightsStatement: "Discours officiel de 1865 appartenant au domaine public; reformulation pédagogique fidèle composée à partir de passages du même discours.",
  transcription: "Sur l’avis de mon gouvernement [le gouvernement de la Grande Coalition], j’ai entrepris des discussions avec les gouvernements des autres colonies britanniques d’Amérique du Nord. […] Ces démarches ont mené à une rencontre de leurs délégués à Québec. Les participants devaient examiner la possibilité d’unir les colonies. […] Ils ont adopté un ensemble de résolutions [les Résolutions de Québec] établissant les principes d’un gouvernement fédéral. Ces résolutions servent de base au projet d’union des provinces britanniques d’Amérique du Nord.",
  accessibleDescription: "Reformulation du discours du Trône reliant l’action du gouvernement de coalition, la Conférence de Québec et le projet d’union fédérale.",
  historicalContext: "Le discours du Trône rend compte des négociations entreprises en 1864 avec les autres colonies et du projet constitutionnel issu de la Conférence de Québec.",
  observationGuide: ["Identifier qui conseille l’ouverture des discussions.", "Repérer le résultat de la rencontre de Québec.", "Relier les résolutions au projet d’union."],
  interpretationCautions: ["Le texte est une reformulation pédagogique fidèle du discours officiel.", "Les […] rapprochent des passages distincts du même discours.", "Le discours est prononcé au nom du gouverneur, mais expose la politique de son gouvernement."],
  pedagogicalUses: ["Relier les négociations intercoloniales à la préparation du Dominion.", "Compléter une chaîne causale allant de l’instabilité à l’union fédérale."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_COALITION_CAUSAL_DOCUMENTS = [
  BRITISH_NORTH_AMERICA_BELLEAU_INSTABILITY_DOCUMENT,
  BRITISH_NORTH_AMERICA_BROWN_COALITION_DOCUMENT,
  BRITISH_NORTH_AMERICA_MONCK_NEGOTIATIONS_DOCUMENT,
] as const;

export const BRITISH_NORTH_AMERICA_INTERCOLONIAL_MAP_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-M-005",
  title: "Le tracé du chemin de fer Intercolonial en 1877",
  kind: "map",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causes_and_consequences", "time_and_space", "establish_facts"],
  historicalDate: "1877",
  creator: "Auteur non identifié",
  holdingInstitution: "Wikimedia Commons",
  sourceUrl: "https://commons.wikimedia.org/wiki/File:Intercolonial-1877.jpg",
  sourceLocator: "Carte de l’Intercolonial vers 1876-1877, fichier Intercolonial-1877.jpg, 855 × 757 pixels; notice Wikimedia Commons.",
  assetUrl: "/historical-documents/aanb-intercolonial-1877.png",
  rightsStatement: "La notice Wikimedia Commons marque le fichier comme domaine public aux États-Unis, mais ne fournit ni auteur ni provenance originale complète. Reproduction recadrée et légende française ajoutée dans l’image transmise à Socrato.",
  transcription: "Dominion du Canada, 1877; chemin de fer Intercolonial; Québec; Nouveau-Brunswick; Nouvelle-Écosse; Rivière-du-Loup; Moncton; Halifax.",
  accessibleDescription: "Carte historique en noir et blanc montrant le tracé du chemin de fer Intercolonial entre le Québec, le Nouveau-Brunswick et la Nouvelle-Écosse en 1877.",
  historicalContext: "La liaison ferroviaire continue entre le centre du Canada et Halifax est achevée en 1876. La carte de 1877 permet d’observer les provinces et les villes reliées par l’Intercolonial.",
  observationGuide: ["Repérer les provinces traversées par la ligne.", "Suivre le tracé entre Rivière-du-Loup, Moncton et Halifax.", "Relier cette nouvelle communication aux objectifs économiques de la Confédération."],
  interpretationCautions: ["La notice Wikimedia ne permet pas d’identifier l’auteur ou l’éditeur original de la carte.", "La carte montre un réseau et non le volume réel des échanges commerciaux.", "Le tracé ne prouve pas à lui seul que toutes les marchandises transportées franchissent une frontière provinciale."],
  pedagogicalUses: ["Situer l’Intercolonial dans l’espace.", "Établir une conséquence de la création d’une liaison ferroviaire entre les provinces.", "Mettre le tracé en relation avec des données sur les marchandises transportées."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_INTERCOLONIAL_FREIGHT_TABLE_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-S-001",
  title: "Marchandises transportées par le chemin de fer Intercolonial",
  kind: "statistics",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causes_and_consequences", "changes_and_continuities", "establish_facts"],
  historicalDate: "1875-1878",
  creator: "Gouvernement du Canada",
  holdingInstitution: "Publications du gouvernement du Canada · Statistique Canada",
  sourceUrl: "https://publications.gc.ca/collections/collection_2017/statcan/CS13-D-54A-1934-eng.pdf",
  sourceLocator: "Historical Statistics of Canada, tableau 9, « Number of Passengers and Tons of Freight Carried by the Intercolonial and Prince Edward Island Railways »; données annuelles de 1875-1876 à 1877-1878.",
  assetUrl: "https://publications.gc.ca/collections/collection_2017/statcan/CS13-D-54A-1934-eng.pdf",
  rightsStatement: "Données historiques publiées par le gouvernement du Canada; tableau pédagogique en français préparé par Socrato à partir des valeurs officielles.",
  transcription: "1875-1876 — liaison continue non achevée : 342 196 tonnes de marchandises; 1876-1877 — première année suivant l’achèvement : 421 327 tonnes; 1877-1878 — deuxième année suivant l’achèvement : 522 710 tonnes.",
  accessibleDescription: "Tableau montrant une hausse des marchandises transportées par l’Intercolonial, de 342 196 tonnes en 1875-1876 à 522 710 tonnes en 1877-1878.",
  historicalContext: "La ligne continue de l’Intercolonial est achevée en 1876. Les données permettent de comparer la dernière année précédant cet achèvement aux deux premières années qui le suivent.",
  observationGuide: ["Comparer la valeur de 1875-1876 à celle de 1877-1878.", "Calculer ou décrire la tendance générale.", "Mettre la hausse en relation avec l’achèvement de la liaison montré sur la carte."],
  interpretationCautions: ["Les chiffres comptent toutes les marchandises transportées sur le réseau et non seulement celles qui franchissent une frontière provinciale.", "Plusieurs tronçons ferroviaires existaient avant 1876; la comparaison porte sur l’achèvement de la liaison continue.", "La hausse observée peut aussi être influencée par la conjoncture économique et par d’autres politiques commerciales."],
  pedagogicalUses: ["Déterminer une conséquence économique de l’achèvement de l’Intercolonial.", "Appuyer une réponse sur des données chiffrées.", "Distinguer une association historique d’une causalité exclusive."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_INTERCOLONIAL_CAUSE_CONSEQUENCE_DOCUMENTS = [
  BRITISH_NORTH_AMERICA_INTERCOLONIAL_MAP_DOCUMENT,
  BRITISH_NORTH_AMERICA_INTERCOLONIAL_FREIGHT_TABLE_DOCUMENT,
] as const;

export const BRITISH_NORTH_AMERICA_LINCOLN_THREAT_CARTOON_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-I-001",
  title: "Ce bon Mr Lincoln!",
  kind: "image",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causes_and_consequences", "differences_and_similarities", "establish_facts"],
  historicalDate: "1865",
  creator: "Charles-Henri Moreau",
  holdingInstitution: "Bibliothèque et Archives Canada",
  sourceUrl: "/historical-documents/aanb-ce-bon-mr-lincoln-1865.png",
  sourceLocator: "Charles-Henri Moreau, « Ce bon Mr. Lincoln », Le Perroquet, Montréal, 15 avril 1865, no 59, BAC C-112901.",
  assetUrl: "/historical-documents/aanb-ce-bon-mr-lincoln-1865.png",
  rightsStatement: "Caricature publiée en 1865 et conservée par Bibliothèque et Archives Canada sous la cote C-112901; reproduction numérique fournie par l’utilisateur.",
  transcription: "Ce bon Mr Lincoln!",
  accessibleDescription: "Caricature en noir et blanc montrant Abraham Lincoln, armé et assis sur le Capitole américain, face à un personnage canadien-français placé au-dessus de fortifications et de soldats.",
  historicalContext: "La caricature est publiée à Montréal pendant la guerre de Sécession. Elle représente de façon satirique la puissance militaire des États-Unis et l’inquiétude qu’elle suscite dans les colonies britanniques voisines.",
  observationGuide: ["Identifier Lincoln et les armes qui l’entourent.", "Repérer les soldats et les fortifications du côté des colonies britanniques.", "Comparer la taille et la position des personnages afin d’interpréter le rapport de force."],
  interpretationCautions: ["La caricature exprime une perception satirique de la menace américaine; elle ne prouve pas qu’une invasion était officiellement annoncée.", "Le personnage canadien-français est une représentation stéréotypée propre à la caricature du 19e siècle."],
  pedagogicalUses: ["Interpréter la crainte de la puissance militaire américaine.", "Relier un contexte international à un argument en faveur de l’union.", "Comparer une représentation visuelle à des discours politiques contemporains."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_CARTIER_DEFENCE_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-009",
  title: "Cartier présente l’union comme une protection commune",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causes_and_consequences", "differences_and_similarities", "establish_facts"],
  historicalDate: "7 février 1865",
  creator: "George-Étienne Cartier, député de Montréal-Est et procureur général du Canada-Est",
  holdingInstitution: "Assemblée législative de la Province du Canada · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/province-du-canada-assemblee-legislative-le-journal-de-quebec-7-fevrier-1865/?lang=fr",
  sourceLocator: "Débats sur la Confédération, Assemblée législative de la Province du Canada, 7 février 1865, intervention de George-Étienne Cartier.",
  assetUrl: "https://primarydocuments.ca/province-du-canada-assemblee-legislative-le-journal-de-quebec-7-fevrier-1865/?lang=fr",
  rightsStatement: "Débat parlementaire de 1865 appartenant au domaine public; reformulation pédagogique fidèle composée à partir de passages consécutifs du même discours.",
  transcription: "Certains croient que la Confédération n’est pas nécessaire pour empêcher [les colonies britanniques] d’être absorbées par les États-Unis, mais ils se trompent. […] Les provinces britanniques, séparées comme elles le sont actuellement, ne pourraient pas se défendre seules. […] Pour obtenir un appui efficace de la Grande-Bretagne, elles doivent elles-mêmes contribuer à leur défense; elles ne peuvent y parvenir sans une confédération. […] Une fois unies pour leur protection mutuelle, toute attaque contre une province devrait affronter les forces combinées [des colonies et] de l’Empire britannique. La Grande-Bretagne pourrait alors leur envoyer des soldats et des ressources pour leur défense.",
  accessibleDescription: "Reformulation des propos de Cartier reliant le risque d’absorption ou de guerre avec les États-Unis à la nécessité d’une défense commune des colonies.",
  historicalContext: "Cartier défend la Confédération devant l’Assemblée législative alors que la guerre de Sécession vient de renforcer la puissance militaire des États-Unis et les inquiétudes dans les colonies britanniques.",
  observationGuide: ["Repérer la menace nommée par Cartier.", "Identifier la faiblesse qu’il attribue aux colonies séparées.", "Expliquer comment l’union modifierait leur capacité de défense."],
  interpretationCautions: ["Le texte est une reformulation pédagogique fidèle, non une transcription mot à mot.", "Les […] signalent le rapprochement de passages du même développement; les autres crochets explicitent des référents implicites.", "Cartier défend le projet gouvernemental et cherche à convaincre les députés."],
  pedagogicalUses: ["Déterminer une cause militaire de la Confédération.", "Interpréter le point de vue d’un partisan de l’union.", "Relier la crainte des États-Unis à l’organisation d’une défense commune."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_CAUCHON_INTERCOLONIAL_DEFENCE_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-010",
  title: "Cauchon présente l’Intercolonial comme un moyen de déplacer les troupes",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["causes_and_consequences", "relationships_between_facts", "establish_facts"],
  historicalDate: "2 mars 1865",
  creator: "Joseph Cauchon, député de Montmorency",
  holdingInstitution: "Assemblée législative de la Province du Canada · Université de Victoria",
  sourceUrl: "https://confederation.uvic.ca/fr/lgPCLA_fr_1865-03-02.html",
  sourceLocator: "Débats sur la Confédération, Assemblée législative de la Province du Canada, 2 mars 1865, p. 578-579, intervention de Joseph Cauchon.",
  assetUrl: "https://confederation.uvic.ca/fr/lgPCLA_fr_1865-03-02.html",
  rightsStatement: "Débat parlementaire de 1865 appartenant au domaine public; extrait abrégé, avec les coupures et précisions éditoriales signalées par des crochets.",
  transcription: "Une possible guerre entre les États-Unis et l’Angleterre nous exposerait aux attaques de l’ennemi sur tous les points vulnérables des diverses provinces. […] L’union [la fédération des colonies] impose le chemin de fer intercolonial […]. [Celui-ci] permettra […] à l’Angleterre et aux provinces de transporter rapidement leurs troupes […] vers les points menacés du territoire national.",
  accessibleDescription: "Extrait dans lequel Cauchon relie le risque d’attaques américaines, l’union des colonies, la construction de l’Intercolonial et le déplacement rapide des troupes.",
  historicalContext: "Cauchon répond aux adversaires qui doutent que l’union augmente la force défensive. Il affirme que la Confédération rendra possible l’Intercolonial, infrastructure utile pour concentrer rapidement les troupes aux endroits menacés.",
  observationGuide: ["Identifier le danger militaire évoqué.", "Repérer l’infrastructure découlant de l’union.", "Expliquer le rôle militaire attribué au chemin de fer."],
  interpretationCautions: ["Les crochets au début et dans l’extrait rendent les référents explicites; les […] signalent les coupures.", "Cauchon expose un avantage attendu du projet, non le compte rendu d’une invasion réellement survenue.", "L’expression territoire national reflète le vocabulaire politique de l’orateur avant la création officielle du Dominion."],
  pedagogicalUses: ["Relier la Confédération à la construction de l’Intercolonial.", "Établir une conséquence militaire attendue de l’union.", "Compléter l’argument général de défense formulé par Cartier."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_INSULAR_COLONIES_NON_ADHESION_DOCUMENT = {
  schemaVersion: 1,
  id: "AANB-T-011",
  title: "Participer aux conférences sans adhérer au Dominion",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-de-l-amerique-du-nord-britannique"],
  operationIds: ["relationships_between_facts", "establish_facts"],
  historicalDate: "octobre 1866",
  creator: "Antoine-Aimé Dorion et d’autres députés de la Province du Canada opposés au projet de Confédération",
  holdingInstitution: "Parlement britannique · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/correspondence-respecting-the-proposed-union-of-the-british-north-american-provinces-1867/",
  sourceLocator: "Mémoire daté de Montréal, octobre 1866, reproduit dans Correspondence respecting the Proposed Union of the British North American Provinces (1867), passage sur la Conférence de Québec et les colonies insulaires.",
  assetUrl: "https://primarydocuments.ca/correspondence-respecting-the-proposed-union-of-the-british-north-american-provinces-1867/",
  rightsStatement: "Document parlementaire de 1867 appartenant au domaine public; traduction-adaptation française et montage de passages préparés par Socrato.",
  transcription: "Des délégués de toutes les provinces se réunissent à Québec en octobre 1864. Leurs délibérations aboutissent à un projet composé de 72 résolutions. […] L’Île-du-Prince-Édouard rejette expressément le projet de Québec. À Terre-Neuve, les résolutions de la conférence ne sont pas approuvées par la législature. Pour le moment, le projet d’union ne concerne donc que la Province du Canada, le Nouveau-Brunswick et la Nouvelle-Écosse.",
  accessibleDescription: "Extrait reliant la participation des colonies à la Conférence de Québec au rejet ou à la non-approbation subséquente du projet par l’Île-du-Prince-Édouard et Terre-Neuve.",
  historicalContext: "Dorion et plusieurs autres députés opposés à la Confédération rédigent ce mémoire pendant que des délégués se préparent à négocier le projet à Londres. Ils rappellent que la participation d’une colonie aux conférences ne l’oblige pas à adhérer et soutiennent qu’à ce moment seules la Province du Canada, le Nouveau-Brunswick et la Nouvelle-Écosse poursuivent le projet d’union.",
  observationGuide: ["Repérer la participation de toutes les provinces à la Conférence de Québec.", "Distinguer le rejet de l’Île-du-Prince-Édouard de la non-approbation législative à Terre-Neuve.", "Identifier les trois colonies qui poursuivent alors le projet d’union."],
  interpretationCautions: ["Le mémoire est rédigé par des opposants à la Confédération et présente leur argumentation politique.", "Le texte est une traduction-adaptation; les […] signalent une coupure entre les passages retenus.", "La participation aux conférences ne liait pas juridiquement les législatures coloniales."],
  pedagogicalUses: ["Distinguer la participation aux négociations de l’adhésion au Dominion.", "Expliquer pourquoi l’Île-du-Prince-Édouard et Terre-Neuve ne sont pas des provinces fondatrices en 1867."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const BRITISH_NORTH_AMERICA_AMERICAN_THREAT_DOCUMENTS = [
  BRITISH_NORTH_AMERICA_LINCOLN_THREAT_CARTOON_DOCUMENT,
  BRITISH_NORTH_AMERICA_CARTIER_DEFENCE_DOCUMENT,
  BRITISH_NORTH_AMERICA_CAUCHON_INTERCOLONIAL_DEFENCE_DOCUMENT,
] as const;

export const BRITISH_NORTH_AMERICA_CONFEDERATION_DOCUMENTS = [
  BRITISH_NORTH_AMERICA_MACDONALD_CONFEDERATION_DOCUMENT,
  BRITISH_NORTH_AMERICA_CARTIER_CONFEDERATION_DOCUMENT,
  BRITISH_NORTH_AMERICA_DORION_CONFEDERATION_DOCUMENT,
  ...BRITISH_NORTH_AMERICA_RAILWAY_CONDITION_DOCUMENTS,
  ...BRITISH_NORTH_AMERICA_COALITION_CAUSAL_DOCUMENTS,
  ...BRITISH_NORTH_AMERICA_INTERCOLONIAL_CAUSE_CONSEQUENCE_DOCUMENTS,
  ...BRITISH_NORTH_AMERICA_AMERICAN_THREAT_DOCUMENTS,
  BRITISH_NORTH_AMERICA_INSULAR_COLONIES_NON_ADHESION_DOCUMENT,
] as const;
