import type { HistoricalDocumentRecord } from "./historical-document.ts";

export const COLONIAL_ECONOMY_CANADA_CORN_LAW_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-T-001",
  title: "Le Parlement britannique décrit la préférence accordée au blé canadien",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["changes_and_continuities", "establish_facts"],
  historicalDate: "26 mai 1843",
  creator: "Chambre des communes du Royaume-Uni",
  holdingInstitution: "Parlement du Royaume-Uni · Historic Hansard",
  sourceUrl: "https://api.parliament.uk/historic-hansard/commons/1843/may/26/canada-corn-law",
  sourceLocator: "HC Deb, 26 mai 1843, vol. 69, col. 939-940; résolution de lord Stanley sur la Canada Corn Law.",
  assetUrl: "https://api.parliament.uk/historic-hansard/commons/1843/may/26/canada-corn-law",
  rightsStatement: "Débat parlementaire de 1843 dans le domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Le 12 octobre 1842, le Conseil législatif et l’Assemblée législative de la Province du Canada ont adopté une loi imposant un droit de trois shillings sur le blé étranger importé au Canada. […] Cette loi a été adoptée dans l’espoir que la Couronne recommande au Parlement britannique de réduire les droits sur le blé et la farine provenant du Canada. […] En échange du droit imposé par la législature canadienne, il est jugé opportun de réduire les droits sur le blé et la farine produits au Canada et importés au Royaume-Uni. […] Le droit exigé pour le blé canadien sera fixé à un shilling par quarter.",
  accessibleDescription: "Extrait d’une résolution parlementaire britannique expliquant le tarif préférentiel accordé au blé et à la farine de la Province du Canada en 1843.",
  historicalContext: "Avant le virage libre-échangiste britannique de 1846, la Province du Canada bénéficie d’un accès tarifaire avantageux au marché du Royaume-Uni pour certains produits agricoles, particulièrement le blé et la farine.",
  observationGuide: ["Repérer le marché auquel les produits canadiens sont destinés.", "Identifier les produits bénéficiant du tarif réduit.", "Comparer le traitement du blé canadien à celui du blé étranger."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée d’une résolution citée dans le débat, et non une transcription française officielle.", "Le mot anglais quarter désigne une unité de mesure des céréales, et non une période de trois mois.", "Cette préférence vise certains produits; elle ne signifie pas que toutes les marchandises coloniales entrent librement au Royaume-Uni."],
  pedagogicalUses: ["Caractériser le régime des préférences impériales avant 1846.", "Comparer les règles commerciales de 1843 avec celles du traité de réciprocité de 1854."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_RECIPROCITY_TREATY_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-T-002",
  title: "Le traité de réciprocité ouvre le marché américain aux produits naturels",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["changes_and_continuities", "establish_facts", "differences_and_similarities"],
  historicalDate: "5 juin 1854",
  creator: "Royaume-Uni et États-Unis; signé par lord Elgin et William L. Marcy",
  holdingInstitution: "United States Government Publishing Office · GovInfo",
  sourceUrl: "https://www.govinfo.gov/link/statute/10/1089",
  sourceLocator: "10 Stat. 1089-1092, article III et annexe, puis article IV; p. 1090-1091 de l’édition officielle.",
  assetUrl: "https://www.govinfo.gov/link/statute/10/1089",
  rightsStatement: "Traité officiel de 1854 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Les produits énumérés dans l’annexe, lorsqu’ils proviennent des colonies britanniques ou des États-Unis, seront admis dans l’autre pays sans droits de douane. […] Ces produits comprennent les grains, la farine, les animaux, les viandes, le poisson et les produits agricoles. […] Ils comprennent également les minerais, le charbon ainsi que le bois rond, équarri ou scié, non transformé en totalité ou en partie. […] Les habitants des États-Unis pourront aussi naviguer sur le Saint-Laurent et sur les canaux canadiens reliant les Grands Lacs à l’océan Atlantique, aux mêmes conditions que les sujets britanniques.",
  accessibleDescription: "Extrait du traité de 1854 présentant l’entrée réciproque sans droits de plusieurs produits naturels et l’accès américain aux voies navigables canadiennes.",
  historicalContext: "Après le recul des préférences britanniques, la Province du Canada recherche un marché de remplacement. Le traité de 1854 accorde un accès réciproque au marché américain et colonial pour une liste de produits naturels, sans instaurer un libre-échange complet.",
  observationGuide: ["Repérer la nouvelle destination possible des produits canadiens.", "Classer les produits énumérés comme ressources naturelles ou produits agricoles.", "Identifier la disposition concernant le Saint-Laurent et les canaux."],
  interpretationCautions: ["L’extrait réunit des passages de l’article III, de son annexe et de l’article IV; les […] signalent les coupures.", "Le traité ne vise pas l’ensemble des produits manufacturés.", "La Province du Canada demeure une colonie : le traité est conclu officiellement entre le Royaume-Uni et les États-Unis."],
  pedagogicalUses: ["Déterminer les produits et les droits couverts par le traité.", "Comparer le marché américain de 1854 au marché britannique préférentiel d’avant 1846.", "Dégager la continuité de l’exportation de produits agricoles et de ressources naturelles."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_RECIPROCITY_TRADE_MAP_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-M-001",
  title: "Le commerce avec les États-Unis pendant le traité de réciprocité",
  kind: "map",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["changes_and_continuities", "establish_facts", "time_and_space"],
  historicalDate: "1862 (planche publiée en 1974; version pédagogique modifiée)",
  creator: "Ressources naturelles Canada; modifications pédagogiques fournies par l’utilisateur",
  holdingInstitution: "Ressources naturelles Canada · Atlas national du Canada",
  sourceUrl: "https://open.canada.ca/data/fr/dataset/ae607339-800b-50d7-8d1e-4309d17d10c3",
  sourceLocator: "Atlas national du Canada, 4e édition (1974), Évolution territoriale du Canada, 1667 à 1873, planches 83-84, vignette de 1862. La version affichée a été recadrée et modifiée par l’ajout du titre, des flèches, des pictogrammes et des étiquettes sur les produits, les tarifs et les droits de pêche.",
  assetUrl: "/historical-documents/economie-coloniale-traite-reciprocite-1854.jpg",
  rightsStatement: "Source cartographique publiée par Ressources naturelles Canada sous la Licence du gouvernement ouvert – Canada. Version recadrée et modifiée à des fins pédagogiques; les ajouts ne proviennent pas de la planche originale.",
  transcription: "Commerce entre la Province du Canada et les États-Unis lors du traité de réciprocité (1854-1866). Blé, bois et charbon : sans tarifs. Droits de pêche.",
  accessibleDescription: "Carte pédagogique de la Province du Canada et du nord-est des États-Unis montrant le blé, le bois et le charbon échangés sans tarifs douaniers ainsi que les droits de pêche sur la côte atlantique.",
  historicalContext: "Le traité de réciprocité entre en vigueur en 1854. Il permet l’échange sans droits de douane de plusieurs produits naturels entre les États-Unis et les colonies britanniques d’Amérique du Nord et accorde aussi des droits de pêche réciproques dans certaines zones.",
  observationGuide: ["Repérer la mention sans tarifs.", "Identifier les produits représentés sur la carte.", "Observer les flèches commerciales et la mention des droits de pêche."],
  interpretationCautions: ["La carte est une représentation pédagogique contemporaine et non une carte produite en 1854.", "Le traité ne supprime pas les droits de douane sur tous les produits, notamment sur l’ensemble des produits manufacturés.", "La carte indique les échanges permis par le traité, mais ne mesure pas leur volume."],
  pedagogicalUses: ["Déterminer un changement commercial provoqué par l’entrée en vigueur du traité.", "Identifier des produits naturels échangés sans droits de douane.", "Situer les échanges entre la Province du Canada et les États-Unis."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_CORN_LAWS_REPEAL_CONSEQUENCE_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-T-003",
  title: "Lord Grey décrit les pertes causées par l’abolition des Corn Laws",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["causes_and_consequences", "causal_connections", "establish_facts"],
  historicalDate: "14 mars 1851",
  creator: "Henry Grey, secrétaire d’État britannique aux Colonies",
  holdingInstitution: "Collection Elgin-Grey · transcription de DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/la-collection-elgin-grey-1846-1852-vol-4/?lang=fr",
  sourceLocator: "Appendice XXVIII, dépêche no 568 de Grey à Elgin, Downing Street, 14 mars 1851, paragraphes 7-8.",
  assetUrl: "https://primarydocuments.ca/la-collection-elgin-grey-1846-1852-vol-4/?lang=fr",
  rightsStatement: "Dépêche officielle de 1851 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Le commerce et l’industrie traversaient de graves difficultés, qui provoquaient l’agitation politique et le mécontentement. […] Une grande partie de la détresse était attribuable aux changements apportés à la législation britannique. […] L’Acte de 1843 avait encouragé l’investissement de capitaux pour approvisionner le Royaume-Uni en farine du Canada. […] L’abolition générale des Corn Laws, c’est-à-dire des restrictions sur l’importation du blé et de la farine au Royaume-Uni, a ensuite causé de très lourdes pertes au Canada.",
  accessibleDescription: "Extrait d’une dépêche officielle de lord Grey à lord Elgin reliant l’abolition des restrictions britanniques sur le blé et la farine à de lourdes pertes économiques au Canada.",
  historicalContext: "La préférence tarifaire accordée en 1843 avait encouragé des investissements canadiens dans la production et l’exportation de farine vers le Royaume-Uni. Le virage libre-échangiste britannique de 1846 retire cet avantage et expose les producteurs canadiens à une concurrence accrue.",
  observationGuide: ["Repérer les investissements réalisés avant l’abolition.", "Identifier la conséquence économique explicitement nommée par Grey.", "Relier le changement de politique britannique aux difficultés du commerce canadien."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée de la dépêche anglaise; les […] signalent les coupures.", "Grey décrit rétrospectivement la conjoncture canadienne depuis la position du gouvernement britannique.", "Le document établit des pertes et une dépression commerciale; il ne permet pas à lui seul d’attribuer à l’abolition toutes les difficultés économiques de la période."],
  pedagogicalUses: ["Déterminer une conséquence économique de l’abolition des Corn Laws.", "Établir un lien de causalité entre le retrait de la préférence britannique et les pertes subies au Canada."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_UNITED_STATES_MARKET_NEGOTIATION_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-T-004",
  title: "Le gouvernement cherche un accès réciproque au marché américain",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["causes_and_consequences", "causal_connections", "establish_facts"],
  historicalDate: "1er novembre 1849",
  creator: "Henry John Temple, vicomte Palmerston, secrétaire britannique aux Affaires étrangères",
  holdingInstitution: "Collection Elgin-Grey · transcription de DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/la-collection-elgin-grey-1846-1852-vol-4/?lang=fr",
  sourceLocator: "Appendice XVI, instructions de Palmerston à sir Henry Bulwer, Foreign Office, 1er novembre 1849, passages sur les négociations commerciales, p. 1481-1482 de l’édition Doughty.",
  assetUrl: "https://primarydocuments.ca/la-collection-elgin-grey-1846-1852-vol-4/?lang=fr",
  rightsStatement: "Instructions diplomatiques officielles de 1849 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Des communications ont déjà eu lieu avec le gouvernement des États-Unis au sujet de l’admission réciproque sans droits de certains produits. […] M. Crampton, aidé d’un membre du gouvernement canadien, a ouvert des discussions avec le gouvernement américain. […] Une proposition a été faite de notre côté pour établir une juste réciprocité du commerce des produits agricoles entre le Canada et les États-Unis. […] Le gouvernement de Sa Majesté considère comme très important d’obtenir l’accès sans droits au marché américain pour les produits agricoles et les matières premières de l’Amérique britannique.",
  accessibleDescription: "Extrait d’instructions diplomatiques britanniques de 1849 montrant que le gouvernement canadien participe à des démarches visant un commerce réciproque avec les États-Unis.",
  historicalContext: "Après la fin de la préférence britannique, le gouvernement de la Province du Canada participe à des démarches diplomatiques visant l’ouverture du marché américain. Ces négociations précèdent le traité de réciprocité conclu en 1854.",
  observationGuide: ["Repérer les deux partenaires des négociations.", "Identifier le rôle joué par un membre du gouvernement canadien.", "Nommer les catégories de produits pour lesquelles un accès au marché américain est recherché."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée d’instructions diplomatiques anglaises; les […] signalent les coupures.", "La Province du Canada ne peut pas conclure seule un traité international : les négociations officielles sont menées par le gouvernement britannique avec la participation canadienne.", "Le document présente une démarche entreprise en 1849, et non encore le traité de réciprocité signé en 1854."],
  pedagogicalUses: ["Démontrer que la Province du Canada cherche à développer ses échanges avec les États-Unis.", "Relier la fin de la préférence britannique aux négociations qui précèdent le traité de réciprocité."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_SEWARD_RECIPROCITY_TENSIONS_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-T-005",
  title: "Seward relie les tensions de la guerre de Sécession au traité de réciprocité",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["causes_and_consequences", "causal_connections", "establish_facts"],
  historicalDate: "10 mars 1865",
  creator: "William H. Seward, secrétaire d’État des États-Unis",
  holdingInstitution: "Office of the Historian · Département d’État des États-Unis",
  sourceUrl: "https://history.state.gov/historicaldocuments/frus1865p1/d114",
  sourceLocator: "Foreign Relations of the United States, 1865, partie I, document 114, Seward à Adams, Washington, 10 mars 1865, p. 201-202.",
  assetUrl: "https://history.state.gov/historicaldocuments/frus1865p1/d114",
  rightsStatement: "Dépêche diplomatique officielle de 1865 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Même sans la détérioration des relations avec le Canada ou la Grande-Bretagne, le traité de réciprocité n’aurait pas pu être maintenu sans une révision importante. […] Il serait inutile de tenter de négocier un nouveau traité pendant que la guerre civile se poursuit et que la Grande-Bretagne reconnaît officiellement les insurgés confédérés comme une partie au conflit. […] Cette situation a nui au commerce américain et à l’amitié entre les peuples des États-Unis et de la Grande-Bretagne. […] Lorsque la Grande-Bretagne reconnaîtra de nouveau toute l’autorité nationale des États-Unis, le gouvernement américain sera disposé à négocier une réciprocité commerciale juste avec le Canada.",
  accessibleDescription: "Extrait d’une dépêche de Seward expliquant que la reconnaissance officielle des Confédérés comme partie au conflit détériore les relations et empêche alors la négociation d’un nouveau traité commercial avec le Canada.",
  historicalContext: "Pendant la guerre de Sécession, la Grande-Bretagne proclame sa neutralité, mais reconnaît officiellement les États confédérés comme une partie au conflit. Des responsables américains considèrent aussi que des navires construits ou équipés en territoire britannique et certaines activités confédérées en Amérique du Nord britannique favorisent le Sud. Dans ce climat, le Congrès américain vote la dénonciation du traité de réciprocité, qui prend fin en 1866.",
  observationGuide: ["Identifier le geste britannique contesté par Seward.", "Repérer son effet sur les relations entre les États-Unis et la Grande-Bretagne.", "Expliquer pourquoi ce climat nuit au maintien ou à la renégociation du traité avec le Canada."],
  interpretationCautions: ["La Grande-Bretagne est officiellement neutre : il est plus exact de parler d’une aide ou d’une sympathie perçue par les États-Unis que d’une alliance officielle avec la Confédération.", "Seward affirme que le traité aurait dû être révisé même sans la crise diplomatique; les tensions de guerre contribuent donc à sa fin sans en être la cause unique.", "L’extrait est une traduction-adaptation abrégée de la dépêche anglaise; les […] signalent les coupures."],
  pedagogicalUses: ["Établir un lien de causalité entre les tensions diplomatiques de la guerre de Sécession et la fin du traité de réciprocité.", "Distinguer une cause contributive d’une cause unique."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_COBDEN_CORN_LAWS_REPEAL_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-T-006",
  title: "Richard Cobden appuie l’abolition immédiate des Corn Laws",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["differences_and_similarities", "establish_facts"],
  historicalDate: "6 février 1846",
  creator: "Richard Cobden, député britannique et industriel",
  holdingInstitution: "The National Archives (Royaume-Uni)",
  sourceUrl: "https://www.nationalarchives.gov.uk/education/resources/the-corn-laws/the-corn-laws-source-4/",
  sourceLocator: "PRO 30/22/5A, lettre de Richard Cobden à lord John Russell, 6 février 1846.",
  assetUrl: "https://www.nationalarchives.gov.uk/education/resources/the-corn-laws/the-corn-laws-source-4/",
  rightsStatement: "Lettre de 1846 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "J’ai constaté que l’opinion du pays est de plus en plus favorable à la mesure de sir Robert Peel visant l’abolition des Corn Laws. Nous ne devrions rien faire pour l’entraver ou la mettre en danger. […] J’espère encore voir tous les partis s’entendre pour rendre cette abolition immédiate.",
  accessibleDescription: "Extrait d’une lettre privée dans laquelle Richard Cobden soutient la mesure de Robert Peel et souhaite l’abolition immédiate des Corn Laws.",
  historicalContext: "Cobden est l’un des principaux dirigeants de l’Anti-Corn Law League. En février 1846, le gouvernement de Robert Peel propose d’abandonner progressivement les droits protecteurs britanniques sur les céréales.",
  observationGuide: ["Repérer l’attitude de Cobden envers la mesure de Peel.", "Identifier le rythme d’abolition qu’il souhaite.", "Relever les mots qui montrent son appui."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée d’une lettre privée rédigée en anglais; les […] signalent la coupure.", "Cobden exprime le point de vue d’un partisan britannique du libre-échange, non celui de l’ensemble de la population britannique.", "La lettre est adressée à lord John Russell, même si Cobden y évoque également l’opinion de John Bright."],
  pedagogicalUses: ["Déterminer le point de vue favorable d’un partisan du libre-échange.", "Comparer ce point de vue britannique à celui d’acteurs commerciaux de la Province du Canada."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_QUEBEC_BOARD_OF_TRADE_CORN_LAWS_DOCUMENT = {
  schemaVersion: 1,
  id: "EC-T-007",
  title: "Le Bureau de commerce de Québec craint l’abolition des Corn Laws",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["economie-coloniale"],
  operationIds: ["differences_and_similarities", "causes_and_consequences", "establish_facts"],
  historicalDate: "1846",
  creator: "Bureau de commerce de Québec",
  holdingInstitution: "Canadiana · Bibliothèque et Archives Canada",
  sourceUrl: "https://www.canadiana.ca/view/oocihm.22043/9",
  sourceLocator: "To the Right Honorable W. E. Gladstone…: the petition of the Quebec Board of Trade, Québec, 1846, passages sur le retrait de la protection impériale.",
  assetUrl: "https://www.canadiana.ca/view/oocihm.22043/9",
  rightsStatement: "Pétition de 1846 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "L’annonce de mesures qui priveront immédiatement la Province du Canada d’une grande partie de la protection dont ses produits bénéficient sur les marchés du Royaume-Uni est accueillie avec inquiétude et alarme. […] Ces mesures pourraient détourner graduellement les habitants de leur attachement envers la mère patrie et les rapprocher d’un pays étranger avec lequel le transport de leurs marchandises serait favorisé.",
  accessibleDescription: "Extrait d’une pétition dans laquelle le Bureau de commerce de Québec s’inquiète de la perte de la protection britannique et d’un rapprochement commercial avec les États-Unis.",
  historicalContext: "Les marchands de Québec profitent de la préférence accordée aux produits coloniaux sur le marché britannique. L’abolition des Corn Laws menace cet avantage et peut réorienter les échanges canadiens vers les États-Unis.",
  observationGuide: ["Repérer le sentiment exprimé à l’annonce de l’abolition.", "Identifier l’avantage que la Province du Canada risque de perdre.", "Nommer le pays étranger vers lequel le commerce pourrait se réorienter."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée de la pétition anglaise; les […] signalent la coupure.", "Le Bureau de commerce représente des intérêts marchands de Québec et non l’opinion de toute la population de la Province du Canada.", "L’expression mère patrie appartient au vocabulaire colonial du document."],
  pedagogicalUses: ["Déterminer le point de vue inquiet d’acteurs commerciaux coloniaux.", "Comparer les effets attendus de l’abolition en Grande-Bretagne et dans la Province du Canada."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const COLONIAL_ECONOMY_PRIMARY_DOCUMENTS = [
  COLONIAL_ECONOMY_CANADA_CORN_LAW_DOCUMENT,
  COLONIAL_ECONOMY_RECIPROCITY_TREATY_DOCUMENT,
  COLONIAL_ECONOMY_RECIPROCITY_TRADE_MAP_DOCUMENT,
  COLONIAL_ECONOMY_CORN_LAWS_REPEAL_CONSEQUENCE_DOCUMENT,
  COLONIAL_ECONOMY_UNITED_STATES_MARKET_NEGOTIATION_DOCUMENT,
  COLONIAL_ECONOMY_SEWARD_RECIPROCITY_TENSIONS_DOCUMENT,
  COLONIAL_ECONOMY_COBDEN_CORN_LAWS_REPEAL_DOCUMENT,
  COLONIAL_ECONOMY_QUEBEC_BOARD_OF_TRADE_CORN_LAWS_DOCUMENT,
] as const;
