import type { HistoricalDocumentRecord } from "./historical-document.ts";
import { PROVINCIAL_DISALLOWANCE_ACT_DOCUMENT } from "./provincial-disallowance.ts";
import { RIEL_RESISTANCE_DOCUMENTS } from "./riel-resistance-documents.ts";
import { CONFERENCE_1887_DOCUMENTS } from "./conference-1887.ts";

export const FEDERAL_PROVINCIAL_RELATIONS_RED_RIVER_DECLARATION_DOCUMENT = {
  schemaVersion: 1,
  id: "RFP-T-001",
  title: "Le gouvernement provisoire justifie la résistance de la rivière Rouge",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["relations-federales-provinciales"],
  operationIds: ["differences_and_similarities", "causes_and_consequences", "relationships_between_facts"],
  historicalDate: "8 décembre 1869",
  creator: "John Bruce et Louis Riel, gouvernement provisoire de la Terre de Rupert et du Nord-Ouest",
  holdingInstitution: "Bibliothèque et Archives Canada · transcription diffusée par la Manitoba Historical Society",
  sourceUrl: "https://www.mhs.mb.ca/docs/pageant/09/rupertslanddeclaration.shtml",
  sourceLocator: "Declaration of the People of Rupert’s Land and the North-West, Fort Garry, 8 décembre 1869; BAC, R176-28-0-E, RG6-C-1, vol. 316, dossier 995, partie 5, item 5379864.",
  assetUrl: "https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?IdNumber=5379864&app=fonandcol",
  rightsStatement: "Déclaration de 1869 appartenant au domaine public; traduction-adaptation française de quatre passages préparée par Socrato. Les coupures sont signalées par […].",
  transcription: "Le gouvernement de la Compagnie de la Baie d’Hudson a transféré au Canada les droits qu’il prétendait posséder sur ce territoire sans que le peuple soit jugé digne d’en être informé. […] Nous refusons de reconnaître l’autorité du Canada, qui prétend nous imposer un gouvernement sans notre consentement. […] Nous avons donc établi un gouvernement provisoire, que nous tenons pour la seule autorité légitime existant dans la Terre de Rupert et le Nord-Ouest. […] Nous demeurons toutefois prêts à négocier avec le gouvernement canadien les conditions favorables au bon gouvernement et à la prospérité de ce peuple.",
  accessibleDescription: "Quatre phrases adaptées de la déclaration de 1869 : elles dénoncent un transfert territorial sans consultation, refusent l’autorité canadienne imposée, proclament un gouvernement provisoire et proposent une négociation.",
  historicalContext: "En 1869, le Canada se prépare à prendre possession de la Terre de Rupert sans avoir négocié les conditions du transfert avec la population de la rivière Rouge. Les Métis dirigés par Riel bloquent les représentants et les arpenteurs canadiens, occupent Upper Fort Garry et forment un gouvernement provisoire. Celui-ci négocie avec Ottawa; la Loi sur le Manitoba de 1870 crée ensuite une province et prévoit certaines garanties politiques, linguistiques, scolaires et territoriales.",
  observationGuide: ["Repérer la cause invoquée pour refuser l’autorité canadienne.", "Identifier les deux moyens politiques employés par les résistants.", "Distinguer le refus d’une annexion imposée du refus de toute entrée dans le Canada."],
  interpretationCautions: ["L’extrait est une traduction-adaptation de quatre passages éloignés dans la déclaration anglaise; les […] signalent les coupures.", "La déclaration défend le point de vue du gouvernement provisoire et ne représente pas automatiquement celui de chaque habitant de la rivière Rouge.", "Le document est antérieur à la Loi sur le Manitoba; l’issue de la résistance doit être établie à l’aide du contexte historique."],
  pedagogicalUses: ["Déterminer une cause et deux moyens de la résistance de 1869-1870.", "Comparer le recours au gouvernement provisoire et à la négociation avec les moyens employés en 1885.", "Relier les revendications de la rivière Rouge à la création du Manitoba."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_PROVINCIAL_RELATIONS_RIEL_TRIAL_SPEECH_DOCUMENT = {
  schemaVersion: 1,
  id: "RFP-T-002",
  title: "Louis Riel explique la résistance de 1885 devant le jury",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["relations-federales-provinciales"],
  operationIds: ["differences_and_similarities", "causes_and_consequences", "relationships_between_facts"],
  historicalDate: "31 juillet 1885",
  creator: "Louis Riel, déclaration au jury lors de son procès pour haute trahison",
  holdingInstitution: "Rapport du procès de Louis Riel · transcription diffusée par Famous Trials, UMKC School of Law",
  sourceUrl: "https://www.famous-trials.com/louisriel/859-statement",
  sourceLocator: "The Queen vs. Louis Riel, rapport du procès, déclaration finale de Riel au jury, Regina, 31 juillet 1885; passages sur les libertés, les pétitions, l’agitation et le verdict.",
  assetUrl: "https://www.famous-trials.com/louisriel/859-statement",
  rightsStatement: "Déclaration judiciaire de 1885 appartenant au domaine public; traduction-adaptation française de quatre passages préparée par Socrato. Les coupures sont signalées par […].",
  transcription: "Je vis que les Métis étaient privés du gouvernement responsable et de leurs libertés publiques. […] Nous avons adressé des pétitions au gouvernement canadien pour lui demander d’améliorer la situation de ce pays. […] L’agitation dans les Territoires du Nord-Ouest serait demeurée constitutionnelle si, à mon avis, nous n’avions pas été attaqués. […] Ma réputation, ma liberté et ma vie sont à votre discrétion.",
  accessibleDescription: "Quatre phrases adaptées du discours de Riel à son procès : elles évoquent les griefs politiques, les pétitions, le passage de l’agitation constitutionnelle à l’affrontement et le sort judiciaire de Riel.",
  historicalContext: "Les Métis de la Saskatchewan réclament depuis plusieurs années la reconnaissance de leurs terres et une représentation politique plus forte. Après des pétitions et la formation d’un gouvernement provisoire, la résistance devient armée en mars 1885. Les troupes fédérales remportent la bataille de Batoche en mai; Riel se rend, est jugé coupable de haute trahison et est pendu le 16 novembre 1885.",
  observationGuide: ["Repérer les griefs que Riel présente comme causes de la résistance.", "Identifier le moyen employé avant les combats.", "Expliquer ce que le lieu et la date du discours révèlent de l’issue de la résistance."],
  interpretationCautions: ["L’extrait est une traduction-adaptation de quatre passages du discours anglais transcrit au procès; les […] signalent les coupures.", "Riel parle pour sa défense devant le jury : il cherche à justifier ses décisions et son interprétation des événements doit être confrontée au contexte.", "Le document ne représente pas l’ensemble des positions métisses et autochtones en 1885; les participants et leurs objectifs ne sont pas uniformes."],
  pedagogicalUses: ["Déterminer des causes, des moyens et une conséquence de la résistance de 1885.", "Comparer les pétitions et le gouvernement provisoire de 1885 avec la stratégie de 1869-1870.", "Relier la défaite de Batoche au procès et à l’exécution de Riel."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_PROVINCIAL_RELATIONS_CONSTITUTION_COMPETENCIES_DOCUMENT = {
  schemaVersion: 1,
  id: "RFP-T-003",
  title: "La Constitution répartit les compétences fédérales et provinciales",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["relations-federales-provinciales"],
  operationIds: ["establish_facts", "differences_and_similarities", "relationships_between_facts"],
  historicalDate: "1er juillet 1867",
  creator: "Parlement du Royaume-Uni",
  holdingInstitution: "Ministère de la Justice du Canada",
  sourceUrl: "https://laws-lois.justice.gc.ca/fra/Const/TexteComplet.html",
  sourceLocator: "Loi constitutionnelle de 1867, articles 90 à 93 : désaveu des lois provinciales, compétences du Parlement, compétences exclusives des provinces et éducation.",
  assetUrl: "https://laws-lois.justice.gc.ca/fra/Const/TexteComplet.html",
  rightsStatement: "Texte constitutionnel officiel de 1867 appartenant au domaine public; sélection et reformulation pédagogique préparées par Socrato à partir des articles 90 à 93.",
  transcription: "L’article 91 confie notamment au Parlement fédéral le commerce, la défense, le service postal, la monnaie, les banques, le droit criminel ainsi que les affaires indiennes et les terres réservées aux Indiens. […] L’article 92 confie notamment aux provinces la taxation directe, les municipalités, les hôpitaux, la propriété et les droits civils, l’administration de la justice ainsi que les matières locales. […] L’article 93 attribue l’éducation aux provinces, sous réserve de garanties concernant certaines écoles confessionnelles. […] L’article 90 applique aux lois provinciales le mécanisme de désaveu prévu par la Constitution, ce qui peut créer une tension avec l’autonomie provinciale.",
  accessibleDescription: "Résumé en quatre phrases des articles constitutionnels qui répartissent les compétences entre les ordres fédéral et provincial et qui encadrent l’éducation et le désaveu.",
  historicalContext: "La Loi constitutionnelle de 1867 établit deux ordres de gouvernement dotés de compétences législatives. Les articles 91 et 92 fournissent les principales listes, alors que l’article 93 traite séparément de l’éducation. Le mécanisme de désaveu permet au gouvernement fédéral de faire cesser l’effet d’une loi provinciale selon la procédure constitutionnelle, alimentant les débats sur l’autonomie des provinces.",
  observationGuide: ["Associer chaque titre de compétence à l’article 91 ou à l’article 92.", "Repérer que l’éducation est provinciale tout en étant encadrée par des garanties particulières.", "Distinguer le désaveu politique d’une décision judiciaire sur la constitutionnalité d’une loi."],
  interpretationCautions: ["L’extrait reformule et regroupe des éléments des articles 90 à 93; il ne remplace pas le texte constitutionnel intégral.", "Les listes de l’activité sont sélectives et adaptées à la quatrième secondaire.", "Le désaveu ne transforme pas une compétence provinciale en compétence fédérale; il constitue un pouvoir distinct d’intervention sur une loi provinciale."],
  pedagogicalUses: ["Classer des compétences essentielles selon l’ordre de gouvernement.", "Établir des faits à partir des articles 91, 92 et 93.", "Expliquer une zone de tension entre l’éducation provinciale, les garanties confessionnelles et le pouvoir fédéral de désaveu."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_PROVINCIAL_RELATIONS_METIS_PRIMARY_DOCUMENTS = [
  FEDERAL_PROVINCIAL_RELATIONS_RED_RIVER_DECLARATION_DOCUMENT,
  FEDERAL_PROVINCIAL_RELATIONS_RIEL_TRIAL_SPEECH_DOCUMENT,
] as const satisfies readonly HistoricalDocumentRecord[];

export const RIEL_EXECUTION_DOCUMENTS = [
  {
    schemaVersion: 1, id: "RFP-I-001", title: "Louis Riel dans une brochure commémorative", kind: "image", status: "ready-for-review",
    periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["causal_connections"],
    historicalDate: "1885", creator: "Illustrateur non identifié; Imprimerie Carmel, Montréal",
    holdingInstitution: "Reproduction numérique diffusée sur Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_la_memoire_de_Louis_Riel_-_la_Marseillaise_canadienne_(1885)_p4.png",
    sourceLocator: "À la mémoire de Louis Riel : la Marseillaise canadienne, Montréal, Imprimerie Carmel, 1885, p. 4.",
    assetUrl: "/historical-documents/riel-memoire-1885.png",
    rightsStatement: "Illustration publiée en 1885; reproduction signalée comme appartenant au domaine public sur Wikimedia Commons. Image intégrale, non retouchée.",
    transcription: "Louis Riel.",
    accessibleDescription: "Portrait imprimé de Louis Riel en buste, entouré d’un encadrement décoratif, avec son nom sous le portrait. Page d’une brochure intitulée À la mémoire de Louis Riel, publiée en 1885.",
    historicalContext: "Après l’exécution de Riel, des publications entretiennent sa mémoire. Le titre commémoratif de cette brochure est un indice d’hommage, mais le portrait seul ne permet pas de connaître les opinions de toute la population.",
    observationGuide: ["Observer la place du portrait et du nom.", "Utiliser le titre et la date de la brochure pour interpréter la fonction de cette image.", "Relier cet hommage aux propos de Mercier sans prétendre que l’image prouve une réaction unanime."],
    interpretationCautions: ["Il s’agit d’une illustration imprimée d’époque, et non d’une photographie de l’exécution.", "Le portrait et sa provenance documentent un hommage; ils ne mesurent pas l’adhésion de la population et ne montrent pas une manifestation."],
    pedagogicalUses: ["Interpréter une publication commémorative en la confrontant à un discours politique de 1885."], version: "1.0", approvedAt: null,
  },
  {
    schemaVersion: 1, id: "RFP-T-004", title: "Discours d’Honoré Mercier au Champ-de-Mars", kind: "other", status: "ready-for-review",
    periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["causal_connections", "differences_and_similarities"],
    historicalDate: "22 novembre 1885 (édition de 1890)", creator: "Honoré Mercier; discours recueilli par Joseph-Octave Pelland",
    holdingInstitution: "Wikisource, transcription du recueil de Joseph-Octave Pelland",
    sourceUrl: "https://fr.wikisource.org/wiki/Biographie,_discours,_conférences,_etc._de_l’Hon._Honoré_Mercier/Discours_prononcé_sur_le_Champ_de_Mars,_le_22_novembre_1885",
    sourceLocator: "Joseph-Octave Pelland, Biographie, discours, conférences, etc. de l’Hon. Honoré Mercier, Montréal, 1890, p. 328-333 : discours prononcé le 22 novembre 1885.",
    assetUrl: "https://fr.wikisource.org/wiki/Biographie,_discours,_conférences,_etc._de_l’Hon._Honoré_Mercier/Discours_prononcé_sur_le_Champ_de_Mars,_le_22_novembre_1885",
    rightsStatement: "Discours de 1885 publié en 1890, domaine public. Extrait français de trois phrases; […] indique les coupures, sans reformulation des propos.",
    transcription: "Riel, notre frère, est mort, victime de son dévouement à la cause des Métis dont il était le chef, victime du fanatisme et de la trahison ; du fanatisme de Sir John et de quelques-uns de ses amis ; de la trahison de trois des nôtres qui, pour garder leur portefeuille, ont vendu leur frère. […] En tuant Riel, Sir John n’a pas seulement frappé notre race au cœur, mais il a surtout frappé la cause de la justice et de l’humanité qui, représentée dans toutes les langues et sanctifiée par toutes les croyances religieuses, demandait grâce pour le prisonnier de Régina, notre pauvre frère du Nord-Ouest. […] Nous avons trois choses à faire : nous unir pour punir les coupables ; briser l’alliance que nos députés ont faite avec l’orangisme et chercher dans une alliance plus naturelle et moins dangereuse, la protection de nos intérêts nationaux.",
    accessibleDescription: "Trois phrases du discours de Mercier : solidarité avec Riel, accusation contre Macdonald et des ministres canadiens-français, appel à une nouvelle alliance politique.",
    historicalContext: "Riel est exécuté le 16 novembre 1885. Six jours plus tard, Honoré Mercier, chef libéral de l’opposition au Québec, prononce ce discours à Montréal. Sir John désigne le premier ministre fédéral John A. Macdonald. Les trois ministres visés sont Langevin, Chapleau et Caron.",
    observationGuide: ["Interpréter l’expression notre frère.", "Identifier les dirigeants auxquels Mercier attribue une responsabilité.", "Relier l’indignation à l’appel à une action politique."],
    interpretationCautions: ["Extrait de trois phrases non consécutives : les coupures sont signalées par […].", "Mercier est un adversaire politique du gouvernement : ses accusations sont un point de vue, non un constat neutre ni l’opinion de tous les Canadiens français.", "Race est un terme d’époque désignant ici une communauté d’origine et de culture; portefeuille désigne une fonction ministérielle. L’orangisme est un mouvement protestant associé à la loyauté britannique."],
    pedagogicalUses: ["Expliquer comment la solidarité avec Riel et la responsabilité attribuée au gouvernement alimentent une opposition politique."], version: "1.0", approvedAt: null,
  },
] as const satisfies readonly HistoricalDocumentRecord[];

export const MANITOBA_1870_DOCUMENT = {
  schemaVersion: 1, id: "RFP-T-005", title: "Extraits d’une loi canadienne de 1870", kind: "law-or-official-text", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["causes_and_consequences", "establish_facts", "differences_and_similarities"],
  historicalDate: "12 mai 1870 (sanction)", creator: "Parlement du Canada",
  holdingInstitution: "Recueil des textes constitutionnels · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/wp-content/uploads/2017/12/ManAct81870May12.pdf",
  sourceLocator: "Loi de 1870 sur le Manitoba, 33 Victoria, chapitre 3, articles 1, 4 et 9; recueil bilingue, no 8, p. 2-3.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2017/12/ManAct81870May12.pdf#page=2",
  rightsStatement: "Texte législatif de 1870, domaine public. Trois passages du texte français reproduits sans reformulation; les coupures sont indiquées par […]. Majuscule initiale et ponctuation de fin de passage ajustées.",
  transcription: "[…] Il sera constitué dans ces territoires une province qui sera l’une des provinces de la Puissance du Canada, et qui sera dénommée la province de Manitoba […]. Cette province sera, en premier lieu, représentée dans la Chambre des Communes du Canada par quatre membres […]. Il y aura, pour la province, une législature composée du lieutenant-gouverneur et de deux Chambres appelées le Conseil Législatif de Manitoba et l’Assemblée Législative de Manitoba.",
  accessibleDescription: "Trois passages de la loi : constitution d’une province, représentation au Parlement canadien et institutions provinciales.",
  historicalContext: "La résistance de la rivière Rouge en 1869-1870 et les négociations des délégués du gouvernement provisoire avec Ottawa conduisent à la Loi sur le Manitoba. Sanctionnée le 12 mai 1870, elle prévoit une nouvelle province qui entre dans la fédération le 15 juillet 1870 : le Manitoba devient la cinquième province du Canada.",
  observationGuide: ["Repérer le changement apporté à la composition du Canada.", "Identifier les institutions et la représentation politique prévues.", "Relier la date du texte à la résistance de 1869-1870."],
  interpretationCautions: ["Les articles 1 et 4 sont abrégés; l’article 9 est reproduit intégralement. Les passages proviennent de trois articles distincts.", "La loi établit le résultat politique, mais n’explique pas à elle seule le rôle de la résistance et des négociations.", "Ne pas confondre la sanction du 12 mai avec l’entrée dans la fédération du 15 juillet 1870, ni avec la résistance de 1885.", "La création de la province ne signifie pas que toutes les revendications et garanties métisses ont été respectées par la suite."],
  pedagogicalUses: ["Déterminer une conséquence politique de la résistance de 1869-1870.", "Choisir un document pertinent pour établir l’entrée du Manitoba dans la fédération."],
  version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const MANITOBA_SCHOOLS_DOCUMENT = {
  schemaVersion: 1, id: "RFP-T-006", title: "L’éducation dans la Loi sur le Manitoba", kind: "law-or-official-text", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["causal_connections"],
  historicalDate: "12 mai 1870", creator: "Parlement du Canada",
  holdingInstitution: "Recueil des textes constitutionnels · DocumentsPrimaires.ca",
  sourceUrl: "https://primarydocuments.ca/wp-content/uploads/2017/12/ManAct81870May12.pdf",
  sourceLocator: "Loi de 1870 sur le Manitoba, 33 Victoria, chapitre 3, article 22, dispositions introductives et paragraphes 1 à 3; recueil bilingue, no 8, p. 6.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2017/12/ManAct81870May12.pdf#page=6",
  rightsStatement: "Texte législatif de 1870, domaine public. Extrait français vérifié sur la page numérisée; […] signale les coupures. Numérotation retirée, ponctuation ajustée et majuscule initiale ajoutée au dernier passage.",
  transcription: "Dans la province, la législature pourra exclusivement décréter des lois relatives à l’éducation, sujettes et conformes aux dispositions suivantes : […] Rien dans ces lois ne devra préjudicier à aucun droit ou privilège conféré, lors de l’Union, par la loi ou par la coutume à aucune classe particulière de personnes dans la province, relativement aux écoles séparées (denominational schools). Il pourra être interjeté appel au gouverneur-général en conseil de tout acte ou décision de la législature de la province ou de toute autorité provinciale affectant quelqu’un des droits ou privilèges de la minorité protestante ou catholique romaine des sujets de Sa Majesté relativement à l’éducation. […] Dans le cas où quelque décision du gouverneur-général en conseil, sur appel interjeté en vertu de cet article, ne serait pas dûment mise à exécution par l’autorité provinciale compétente, […] le parlement du Canada pourra décréter des lois propres à y remédier […].",
  accessibleDescription: "Passages de l’article 22 établissant la compétence provinciale en éducation, des garanties confessionnelles, un recours au gouverneur général en conseil et un pouvoir fédéral de réparation.",
  historicalContext: "En 1890, le Manitoba remplace le système scolaire confessionnel financé publiquement par un système public non confessionnel, privant les écoles catholiques de financement public. La minorité catholique réclame une intervention fédérale. L’article 22 fournit le cadre du recours : autonomie provinciale et protection des droits scolaires minoritaires entrent en tension. En 1895, le Comité judiciaire du Conseil privé reconnaît la possibilité du recours fédéral, malgré la validité de la loi provinciale reconnue auparavant.",
  observationGuide: ["Repérer l’ordre de gouvernement responsable de l’éducation.", "Identifier les droits et les minorités mentionnés.", "Expliquer comment l’appel puis une loi réparatrice peuvent mettre en jeu les autorités fédérales."],
  interpretationCautions: ["Le texte date de 1870 : il établit le cadre du conflit de 1890, sans raconter celui-ci.", "Les écoles séparées sont ici confessionnelles. Les droits religieux et les droits linguistiques ne sont pas identiques.", "Le gouverneur général en conseil désigne ici l’exécutif fédéral, non le Comité judiciaire du Conseil privé de Londres.", "Le paragraphe 3 est abrégé : le passage conserve le cas d’une décision sur appel non exécutée; le pouvoir réparateur est conditionnel et limité aux circonstances. Ce n’est ni un transfert général de l’éducation au fédéral ni le désaveu d’une loi.", "Ne pas présenter la loi scolaire de 1890 comme automatiquement inconstitutionnelle : le recours réparateur et le contrôle de validité sont distincts."],
  pedagogicalUses: ["Expliquer pourquoi une politique scolaire provinciale peut susciter une intervention fédérale et un conflit entre les deux ordres de gouvernement."],
  version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const NEW_BRUNSWICK_SCHOOLS_DOCUMENT = {
  schemaVersion: 1, id: "RFP-T-007", title: "Discours sur les écoles du Nouveau-Brunswick", kind: "other", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["establish_facts", "causes_and_consequences"],
  historicalDate: "14 mai 1873 (édition de 1890)", creator: "Honoré Mercier, député de Rouville; discours recueilli par Joseph-Octave Pelland",
  holdingInstitution: "Wikisource, transcription du recueil de Joseph-Octave Pelland",
  sourceUrl: "https://fr.wikisource.org/wiki/Biographie,_discours,_conférences,_etc._de_l’Hon._Honoré_Mercier/Question_des_Écoles_du_Nouveau-Brunswick",
  sourceLocator: "Joseph-Octave Pelland, Biographie, discours, conférences, etc. de l’Hon. Honoré Mercier, Montréal, 1890, p. 43-44 : discours à la Chambre des communes du 14 mai 1873.",
  assetUrl: "https://fr.wikisource.org/wiki/Biographie,_discours,_conférences,_etc._de_l’Hon._Honoré_Mercier/Question_des_Écoles_du_Nouveau-Brunswick#43",
  rightsStatement: "Discours de 1873 publié en 1890, domaine public. Trois phrases françaises non consécutives, sans reformulation; […] signale les coupures.",
  transcription: "Cette loi rappelle l’acte de 1858 et décrète qu’à l’avenir les écoles, dans le Nouveau-Brunswick, seront non-sectaires, c’est-à-dire non confessionnelles. […] Cette conséquence terrible pour les catholiques est rendue inévitable par la section 58 § 12 qui déclare qu’aucun argent ne sera donné en faveur de toute école qui ne sera pas conduite suivant les dispositions ci-dessus, c’est-à-dire à une école qui sera catholique. […] Voilà quelques-unes des dispositions de cette loi de 1871 ; elles sécularisent l’enseignement et chassent la religion de l’école.",
  accessibleDescription: "Mercier décrit le caractère non confessionnel imposé aux écoles financées publiquement et dénonce ses conséquences pour l’enseignement catholique.",
  historicalContext: "La Common Schools Act de 1871 instaure au Nouveau-Brunswick un réseau public non confessionnel financé par une taxe scolaire. Les écoles confessionnelles ne sont plus admissibles au financement public prévu par ce régime. Des catholiques s’opposent à cette réforme parce qu’ils souhaitent conserver un enseignement conforme à leur religion et doivent contribuer au réseau public même s’ils financent leurs propres écoles. Mercier intervient aux Communes pour soutenir leurs revendications.",
  observationGuide: ["Repérer le changement dans le caractère religieux des écoles.", "Relever la condition imposée pour obtenir des fonds publics.", "Distinguer la description de la réforme des expressions qui montrent l’opposition de Mercier."],
  interpretationCautions: ["Le mot rappelle signifie ici abroge; deniers publics signifie fonds publics.", "Mercier défend les catholiques opposés à la réforme : conséquence terrible et chassent la religion expriment son jugement, non une description neutre.", "La loi impose la non-confessionnalité aux écoles relevant du régime public; elle n’interdit pas toute école catholique privée ni toute pratique religieuse. Non confessionnel ne signifie pas entièrement dépourvu de références chrétiennes.", "Ne pas assimiler cette réforme à une interdiction générale du français ni à la crise manitobaine de 1890."],
  pedagogicalUses: ["Identifier le changement scolaire de 1871 qui provoque l’opposition catholique.", "Appuyer une réponse sur un témoignage parlementaire d’époque en tenant compte de son point de vue."],
  version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const LAURIER_GREENWAY_AGREEMENT_DOCUMENT = {
  schemaVersion: 1, id: "RFP-T-008", title: "Accord scolaire du 16 novembre 1896", kind: "law-or-official-text", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["changes_and_continuities"],
  historicalDate: "16 novembre 1896", creator: "Gouvernements du Canada et du Manitoba",
  holdingInstitution: "Documents de la session du Canada · transcription diffusée par Canada History",
  sourceUrl: "https://www.canadahistory.com/sections/documents/frontier/manitobaschoolagreement.html",
  sourceLocator: "Terms of Agreement between the Government of Canada and the Government of Manitoba for the Settlement of the School Question, 16 novembre 1896, article 2, paragraphes 2, 3, 8 et 10; Canada, Sessional Papers, 1897, no 35, p. 1-2.",
  assetUrl: "https://www.canadahistory.com/sections/documents/frontier/manitobaschoolagreement.html",
  rightsStatement: "Accord de 1896, domaine public. Traduction française par Socrato de quatre passages du texte anglais transcrit; […] marque les coupures et les crochets explicitent le raccord grammatical. Ne pas confondre cette transcription primaire avec l’analyse moderne qui la précède sur le site.",
  transcription: "[L’enseignement religieux sera dispensé si] une pétition est présentée au conseil des commissaires scolaires pour le demander, signée par les parents ou tuteurs d’au moins dix enfants fréquentant l’école dans un district rural, ou d’au moins vingt-cinq enfants fréquentant l’école dans une ville ou un village. […] Cet enseignement religieux aura lieu entre quinze heures trente et seize heures […]. Aucune séparation des élèves selon leur confession religieuse n’aura lieu pendant l’enseignement des matières non religieuses. […] Lorsque dix élèves d’une école ont le français (ou une langue autre que l’anglais) comme langue maternelle, l’enseignement de ces élèves sera dispensé en français (ou dans cette autre langue) et en anglais, selon le système bilingue.",
  accessibleDescription: "Quatre passages de l’accord : demande d’enseignement religieux, plage horaire limitée, absence de séparation confessionnelle pour les matières non religieuses et enseignement bilingue conditionnel.",
  historicalContext: "Avant 1890, le Manitoba possède un système scolaire public confessionnel comprenant des écoles catholiques et protestantes. La réforme de 1890 retire le financement public aux écoles confessionnelles. L’accord négocié en 1896 par les gouvernements Laurier et Greenway, mis en œuvre par la législation manitobaine de 1897, prévoit des concessions au sein du réseau public sans rétablir le réseau séparé catholique financé publiquement.",
  observationGuide: ["Identifier les conditions et l’horaire de l’enseignement religieux.", "Repérer la règle applicable pendant l’enseignement des matières non religieuses.", "Identifier le seuil et les deux langues prévus pour l’enseignement bilingue.", "Distinguer des concessions dans le réseau public du rétablissement d’un réseau confessionnel séparé."],
  interpretationCautions: ["Il s’agit d’une traduction de passages de l’accord, non d’une citation française originale. La première phrase rétablit le sujet de la clause introductive entre crochets.", "L’extrait ne reproduit pas toutes les dispositions : le paragraphe 1 permet aussi une autorisation par résolution des commissaires; la pétition n’est donc pas l’unique voie. Le consentement des parents à la participation de leurs enfants est requis par le paragraphe 11.", "Le seuil de dix élèves pour l’enseignement bilingue diffère des seuils de la pétition religieuse et de ceux prévus pour engager un enseignant d’une confession donnée.", "La Loi de 1870 établit des garanties, mais ne décrit pas à elle seule toute l’organisation du réseau scolaire de 1871 à 1889.", "Les concessions de 1896 ne rétablissent ni un réseau séparé catholique financé publiquement ni l’ensemble de la situation antérieure à 1890."],
  pedagogicalUses: ["Justifier le caractère partiel du compromis de 1896 en confrontant les concessions de l’accord au cadre antérieur à 1890."],
  version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_REVENUE_TABLE = {
  caption: "Quelques recettes du gouvernement fédéral — avril 1868 (dollars courants)",
  headers: ["Source de revenus", "Recettes du mois ($)"] as [string, string],
  rows: [{ label: "Droits de douane", value: "757 409,97" }, { label: "Droits d’accise", value: "357 791,00" }, { label: "Service postal", value: "62 840,52" }],
};

export const GOVERNMENT_REVENUE_DOCUMENTS = [
  {
    schemaVersion: 1, id: "RFP-S-001", title: "Recettes fédérales en avril 1868", kind: "statistics", status: "ready-for-review",
    periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["differences_and_similarities", "establish_facts"],
    historicalDate: "Avril 1868; publication du 5 juin 1868", creator: "John Langton, vérificateur, Bureau de la vérification, Ottawa",
    holdingInstitution: "Gazette du Canada · transcription sur Wikisource",
    sourceUrl: "https://en.wikisource.org/wiki/Canada_Gazette/Volume_I/No._50/Statement_of_Revenue,_June_5,_1868",
    sourceLocator: "Canada Gazette, vol. I, no 50, Statement of Revenue, 5 juin 1868 : état du mois terminé le 30 avril 1868, rubriques Customs, Excise et Post Office.",
    assetUrl: "https://en.wikisource.org/wiki/Canada_Gazette/Volume_I/No._50/Statement_of_Revenue,_June_5,_1868",
    rightsStatement: "État financier officiel de 1868, domaine public. Sélection de trois lignes, libellés traduits en français et notation des nombres francisée; montants conservés.",
    transcription: "Droits de douane : 757 409,97 $; droits d’accise : 357 791,00 $; service postal : 62 840,52 $. Recettes du gouvernement fédéral pour avril 1868; sélection non exhaustive.",
    accessibleDescription: "Tableau de trois recettes mensuelles fédérales : douanes, accise et poste, avec leurs montants en dollars de 1868.",
    historicalContext: "Au début de la fédération, les douanes et l’accise constituent des sources importantes de recettes fédérales. Ce relevé mensuel fournit un exemple de recettes effectivement perçues, à distinguer des pouvoirs fiscaux établis par la Constitution.",
    observationGuide: ["Identifier l’ordre de gouvernement concerné et le mois couvert.", "Distinguer droits de douane, droits d’accise et recettes postales.", "Comparer ces recettes aux ressources provinciales décrites dans le document constitutionnel."],
    interpretationCautions: ["Le tableau est une sélection de trois rubriques : il ne représente pas la totalité des revenus fédéraux et ne comporte pas de total.", "Les valeurs concernent un mois seulement, pas une année; ne pas en déduire des parts annuelles.", "Les douanes portent notamment sur les importations; l’accise est un prélèvement sur certaines productions ou marchandises intérieures. Les recettes postales ne sont pas des impôts.", "Le pouvoir fédéral de taxation ne se limite pas constitutionnellement aux taxes indirectes."],
    pedagogicalUses: ["Distinguer des revenus fédéraux observés des sources de revenus provinciales prévues en 1867."], version: "1.0", approvedAt: null,
  },
  {
    schemaVersion: 1, id: "RFP-T-009", title: "Dispositions financières de l’AANB de 1867", kind: "law-or-official-text", status: "ready-for-review",
    periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["differences_and_similarities", "establish_facts", "causal_connections"],
    historicalDate: "1867", creator: "Parlement du Royaume-Uni",
    holdingInstitution: "Ministère de la Justice du Canada",
    sourceUrl: "https://laws-lois.justice.gc.ca/fra/Const/TexteComplet.html",
    sourceLocator: "Loi constitutionnelle de 1867, articles 91(3), 92(2), 92(5), 92(9) et article 118 original, reproduit dans la note de fin de page 59.",
    assetUrl: "https://laws-lois.justice.gc.ca/fra/Const/TexteComplet.html",
    rightsStatement: "Texte constitutionnel de 1867, domaine public. Sélection de passages français, avec étiquettes explicatives entre crochets, coupures […] et ponctuation de raccord. L’article 118 est cité dans sa version originale, et non comme disposition actuellement en vigueur.",
    transcription: "[Parlement du Canada, art. 91(3)] Le prélèvement de deniers par tous modes ou systèmes de taxation. […] [Législatures provinciales, art. 92] La taxation directe dans les limites de la province, dans le but de prélever un revenu pour des objets provinciaux; […] L’administration et la vente des terres publiques appartenant à la province, et des bois et forêts qui s’y trouvent; […] Les licences de boutiques, de cabarets, d’auberges, d’encanteurs et autres licences, dans le but de prélever un revenu pour des objets provinciaux, locaux, ou municipaux. […] [Art. 118 original] Les sommes suivantes seront annuellement payées par le Canada aux diverses provinces pour le maintien de leurs gouvernements et législatures : […] Et chaque province aura droit à une subvention annuelle de quatre-vingts centins par chaque tête de la population, constatée par le recensement de mil huit cent soixante-et-un […].",
    accessibleDescription: "Passages sur le pouvoir de taxation fédéral, la taxation directe provinciale, les terres et forêts provinciales, les licences et les subventions fédérales aux provinces.",
    historicalContext: "Le partage financier de 1867 accorde au fédéral un large pouvoir de taxation. Les provinces disposent notamment de taxation directe, de licences, de revenus de leurs terres et forêts et de subventions fédérales. Les pouvoirs prévus ne mesurent pas les recettes effectivement perçues par chaque province.",
    observationGuide: ["Repérer les ressources propres des provinces.", "Identifier le sens du transfert financier prévu à l’article 118.", "Comparer les pouvoirs de taxation sans réserver toute taxation directe aux provinces."],
    interpretationCautions: ["Extraits de plusieurs articles, non texte continu; la liste détaillée des subventions fixes et les conditions démographiques particulières ont été retranchées.", "L’article 118 original a été remplacé dans l’évolution du financement provincial : l’activité porte sur les dispositions de 1867.", "Les recettes foncières visées proviennent des terres et forêts appartenant aux provinces, non de toutes les terres du Canada.", "Ne pas confondre une source autorisée et une recette effectivement encaissée, ni une subvention reçue par une province et un revenu fédéral.", "La taxation directe n’est pas exclusivement provinciale : l’article 91(3) confère aussi au fédéral un pouvoir général de taxation."],
    pedagogicalUses: ["Classer les sources de revenus et distinguer ressources propres provinciales et transferts fédéraux."], version: "1.0", approvedAt: null,
  },
] as const satisfies readonly HistoricalDocumentRecord[];

export const MANITOBA_CARTOON_TRANSLATION = "Sur la tombe : « Ici repose pour de bon la question des écoles du Manitoba, réglée pacifiquement. Qu’elle repose en paix. » Titre : « Le début de la fin ». Légende : Laurier — « Maintenant, Greenway, mon garçon, il ne reste plus qu’à préparer les “restes”. » Sur les pelles : « Conciliation » (Greenway, à gauche) et « Compromis » (Laurier, à droite). Traduction française par Socrato; inscriptions originales conservées dans l’image.";

export const MANITOBA_NEGOTIATION_CARTOON = {
  schemaVersion: 1, id: "RFP-I-002", title: "The Beginning of the End — Le début de la fin", kind: "image", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["relations-federales-provinciales"], operationIds: ["relationships_between_facts"],
  historicalDate: "24 octobre 1896", creator: "J. W. Bengough",
  holdingInstitution: "Victoria Daily Times · exemplaire numérisé diffusé sur Wikimedia Commons / Internet Archive",
  sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Victoria_Daily_Times_%281896-10-24%29_%28IA_victoriadailytimes18961024%29.pdf#page=3",
  sourceLocator: "J. W. Bengough, « The Beginning of the End », Victoria Daily Times, 24 octobre 1896, p. 3.",
  assetUrl: "/historical-documents/manitoba-beginning-end-1896.png",
  rightsStatement: "Caricature publiée en 1896, domaine public. Zone de la caricature extraite de la page numérisée, titre, signature et légende conservés; dessin non retouché. Traduction française présentée séparément.",
  transcription: "Tombe : HERE REPOSES FOR GOOD, THE MANITOBA SCHOOL QUESTION PEACEFULLY SETTLED. R.I.P. Titre : THE BEGINNING OF THE END. Légende : LAURIER—Now Greenway, my boy, there is nothing more to be done but to get the ‘remains’ ready. Pelles : CONCILIATION; COMPROMISE.",
  accessibleDescription: "Greenway, à gauche, et Laurier, à droite, munis de pelles, se tiennent devant une fosse ouverte et vide. Une pierre tombale annonce que la question des écoles du Manitoba est réglée pacifiquement. La signature, le titre et la légende sont conservés sous le dessin.",
  historicalContext: "Laurier dirige le gouvernement fédéral et Greenway celui du Manitoba. La caricature est publiée le 24 octobre 1896, avant l’accord du 16 novembre. Elle met en scène la recherche d’un règlement négocié du conflit scolaire, tout en jouant sur le contraste entre une épitaphe déjà prête et une tombe encore vide.",
  observationGuide: ["Identifier les deux ordres de gouvernement représentés.", "Mettre en relation les mots sur les pelles et l’annonce sur la tombe.", "Confronter la fosse vide à la légende attribuée à Laurier."],
  interpretationCautions: ["Recadrage documentaire de la page 3, sans modification du dessin; traduction séparée pour conserver la source originale.", "La caricature précède l’accord du 16 novembre 1896 : elle ne démontre ni son application ni la satisfaction de la minorité catholique.", "La tombe symbolise la fin espérée d’un conflit, pas la mort de personnes.", "Accepter une lecture de confiance dans la négociation ou d’ironie sur un règlement encore inachevé si elle s’appuie sur des indices visuels et la légende."],
  pedagogicalUses: ["Interpréter le message d’un caricaturiste sur la négociation fédérale-provinciale en justifiant par deux indices."], version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_PROVINCIAL_RELATIONS_PRIMARY_DOCUMENTS = [
  PROVINCIAL_DISALLOWANCE_ACT_DOCUMENT,
  ...RIEL_RESISTANCE_DOCUMENTS,
  ...CONFERENCE_1887_DOCUMENTS,
  ...FEDERAL_PROVINCIAL_RELATIONS_METIS_PRIMARY_DOCUMENTS,
  FEDERAL_PROVINCIAL_RELATIONS_CONSTITUTION_COMPETENCIES_DOCUMENT,
  ...RIEL_EXECUTION_DOCUMENTS,
  MANITOBA_1870_DOCUMENT,
  MANITOBA_SCHOOLS_DOCUMENT,
  NEW_BRUNSWICK_SCHOOLS_DOCUMENT,
  LAURIER_GREENWAY_AGREEMENT_DOCUMENT,
  ...GOVERNMENT_REVENUE_DOCUMENTS,
  MANITOBA_NEGOTIATION_CARTOON,
] as const satisfies readonly HistoricalDocumentRecord[];
