import type { HistoricalDocumentRecord } from "./historical-document.ts";

export const FEDERAL_PROVINCIAL_RELATIONS_RED_RIVER_DECLARATION_DOCUMENT = {
  schemaVersion: 1,
  id: "RFP-T-001",
  title: "Le gouvernement provisoire justifie la résistance de la rivière Rouge",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["relations-federales-provinciales"],
  operationIds: ["differences_and_similarities", "causes_and_consequences", "relationships_between_facts"],
  historicalDate: "8 décembre 1869",
  creator: "John Bruce et Louis Riel, gouvernement provisoire de la Terre de Rupert et du Nord-Ouest",
  holdingInstitution: "Bibliothèque et Archives Canada · transcription diffusée par la Manitoba Historical Society",
  sourceUrl: "https://www.mhs.mb.ca/docs/pageant/09/rupertslanddeclaration.shtml",
  sourceLocator: "Declaration of the People of Rupert’s Land and the North-West, Fort Garry, 8 décembre 1869; BAC, R176-28-0-E, RG6-C-1, vol. 316, dossier 995, partie 5, item 5379864.",
  assetUrl: "https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?IdNumber=5379864&app=fonandcol",
  rightsStatement: "Déclaration de 1869 appartenant au domaine public; traduction-adaptation française de quatre passages préparée par Socrato. Les coupures sont signalées par […].",
  transcription: "Le gouvernement de la Compagnie de la Baie d’Hudson a transféré au Canada les droits qu’il prétendait posséder sur ce territoire sans que le peuple soit jugé digne d’en être informé. […] Nous refusons de reconnaître l’autorité du Canada, qui prétend nous imposer un gouvernement sans notre consentement. […] Nous avons donc établi un gouvernement provisoire, que nous tenons pour la seule autorité légitime existant dans la Terre de Rupert et le Nord-Ouest. […] Nous demeurons toutefois prêts à négocier avec le gouvernement canadien les conditions favorables au bon gouvernement et à la prospérité de ce peuple.",
  accessibleDescription: "Quatre phrases adaptées de la déclaration de 1869 : elles dénoncent un transfert territorial sans consultation, refusent l’autorité canadienne imposée, proclament un gouvernement provisoire et proposent une négociation.",
  historicalContext: "En 1869, le Canada se prépare à prendre possession de la Terre de Rupert sans avoir négocié les conditions du transfert avec la population de la rivière Rouge. Les Métis dirigés par Riel bloquent les représentants et les arpenteurs canadiens, occupent Upper Fort Garry et forment un gouvernement provisoire. Celui-ci négocie avec Ottawa; la Loi sur le Manitoba de 1870 crée ensuite une province et prévoit certaines garanties politiques, linguistiques, scolaires et territoriales.",
  observationGuide: ["Repérer la cause invoquée pour refuser l’autorité canadienne.", "Identifier les deux moyens politiques employés par les résistants.", "Distinguer le refus d’une annexion imposée du refus de toute entrée dans le Canada."],
  interpretationCautions: ["L’extrait est une traduction-adaptation de quatre passages éloignés dans la déclaration anglaise; les […] signalent les coupures.", "La déclaration défend le point de vue du gouvernement provisoire et ne représente pas automatiquement celui de chaque habitant de la rivière Rouge.", "Le document est antérieur à la Loi sur le Manitoba; l’issue de la résistance doit être établie à l’aide du contexte historique."],
  pedagogicalUses: ["Déterminer une cause et deux moyens de la résistance de 1869-1870.", "Comparer le recours au gouvernement provisoire et à la négociation avec les moyens employés en 1885.", "Relier les revendications de la rivière Rouge à la création du Manitoba."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_PROVINCIAL_RELATIONS_RIEL_TRIAL_SPEECH_DOCUMENT = {
  schemaVersion: 1,
  id: "RFP-T-002",
  title: "Louis Riel explique la résistance de 1885 devant le jury",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["relations-federales-provinciales"],
  operationIds: ["differences_and_similarities", "causes_and_consequences", "relationships_between_facts"],
  historicalDate: "31 juillet 1885",
  creator: "Louis Riel, déclaration au jury lors de son procès pour haute trahison",
  holdingInstitution: "Rapport du procès de Louis Riel · transcription diffusée par Famous Trials, UMKC School of Law",
  sourceUrl: "https://www.famous-trials.com/louisriel/859-statement",
  sourceLocator: "The Queen vs. Louis Riel, rapport du procès, déclaration finale de Riel au jury, Regina, 31 juillet 1885; passages sur les libertés, les pétitions, l’agitation et le verdict.",
  assetUrl: "https://www.famous-trials.com/louisriel/859-statement",
  rightsStatement: "Déclaration judiciaire de 1885 appartenant au domaine public; traduction-adaptation française de quatre passages préparée par Socrato. Les coupures sont signalées par […].",
  transcription: "Je vis que les Métis étaient privés du gouvernement responsable et de leurs libertés publiques. […] Nous avons adressé des pétitions au gouvernement canadien pour lui demander d’améliorer la situation de ce pays. […] L’agitation dans les Territoires du Nord-Ouest serait demeurée constitutionnelle si, à mon avis, nous n’avions pas été attaqués. […] Ma réputation, ma liberté et ma vie sont à votre discrétion.",
  accessibleDescription: "Quatre phrases adaptées du discours de Riel à son procès : elles évoquent les griefs politiques, les pétitions, le passage de l’agitation constitutionnelle à l’affrontement et le sort judiciaire de Riel.",
  historicalContext: "Les Métis de la Saskatchewan réclament depuis plusieurs années la reconnaissance de leurs terres et une représentation politique plus forte. Après des pétitions et la formation d’un gouvernement provisoire, la résistance devient armée en mars 1885. Les troupes fédérales remportent la bataille de Batoche en mai; Riel se rend, est jugé coupable de haute trahison et est pendu le 16 novembre 1885.",
  observationGuide: ["Repérer les griefs que Riel présente comme causes de la résistance.", "Identifier le moyen employé avant les combats.", "Expliquer ce que le lieu et la date du discours révèlent de l’issue de la résistance."],
  interpretationCautions: ["L’extrait est une traduction-adaptation de quatre passages du discours anglais transcrit au procès; les […] signalent les coupures.", "Riel parle pour sa défense devant le jury : il cherche à justifier ses décisions et son interprétation des événements doit être confrontée au contexte.", "Le document ne représente pas l’ensemble des positions métisses et autochtones en 1885; les participants et leurs objectifs ne sont pas uniformes."],
  pedagogicalUses: ["Déterminer des causes, des moyens et une conséquence de la résistance de 1885.", "Comparer les pétitions et le gouvernement provisoire de 1885 avec la stratégie de 1869-1870.", "Relier la défaite de Batoche au procès et à l’exécution de Riel."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_PROVINCIAL_RELATIONS_CONSTITUTION_COMPETENCIES_DOCUMENT = {
  schemaVersion: 1,
  id: "RFP-T-003",
  title: "La Constitution répartit les compétences fédérales et provinciales",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["relations-federales-provinciales"],
  operationIds: ["establish_facts", "differences_and_similarities", "relationships_between_facts"],
  historicalDate: "1er juillet 1867",
  creator: "Parlement du Royaume-Uni",
  holdingInstitution: "Ministère de la Justice du Canada",
  sourceUrl: "https://laws-lois.justice.gc.ca/fra/Const/TexteComplet.html",
  sourceLocator: "Loi constitutionnelle de 1867, articles 90 à 93 : désaveu des lois provinciales, compétences du Parlement, compétences exclusives des provinces et éducation.",
  assetUrl: "https://laws-lois.justice.gc.ca/fra/Const/TexteComplet.html",
  rightsStatement: "Texte constitutionnel officiel de 1867 appartenant au domaine public; sélection et reformulation pédagogique préparées par Socrato à partir des articles 90 à 93.",
  transcription: "L’article 91 confie notamment au Parlement fédéral le commerce, la défense, le service postal, la monnaie, les banques, le droit criminel ainsi que les affaires indiennes et les terres réservées aux Indiens. […] L’article 92 confie notamment aux provinces la taxation directe, les municipalités, les hôpitaux, la propriété et les droits civils, l’administration de la justice ainsi que les matières locales. […] L’article 93 attribue l’éducation aux provinces, sous réserve de garanties concernant certaines écoles confessionnelles. […] L’article 90 applique aux lois provinciales le mécanisme de désaveu prévu par la Constitution, ce qui peut créer une tension avec l’autonomie provinciale.",
  accessibleDescription: "Résumé en quatre phrases des articles constitutionnels qui répartissent les compétences entre les ordres fédéral et provincial et qui encadrent l’éducation et le désaveu.",
  historicalContext: "La Loi constitutionnelle de 1867 établit deux ordres de gouvernement dotés de compétences législatives. Les articles 91 et 92 fournissent les principales listes, alors que l’article 93 traite séparément de l’éducation. Le mécanisme de désaveu permet au gouvernement fédéral de faire cesser l’effet d’une loi provinciale selon la procédure constitutionnelle, alimentant les débats sur l’autonomie des provinces.",
  observationGuide: ["Associer chaque titre de compétence à l’article 91 ou à l’article 92.", "Repérer que l’éducation est provinciale tout en étant encadrée par des garanties particulières.", "Distinguer le désaveu politique d’une décision judiciaire sur la constitutionnalité d’une loi."],
  interpretationCautions: ["L’extrait reformule et regroupe des éléments des articles 90 à 93; il ne remplace pas le texte constitutionnel intégral.", "Les listes de l’activité sont sélectives et adaptées à la quatrième secondaire.", "Le désaveu ne transforme pas une compétence provinciale en compétence fédérale; il constitue un pouvoir distinct d’intervention sur une loi provinciale."],
  pedagogicalUses: ["Classer des compétences essentielles selon l’ordre de gouvernement.", "Établir des faits à partir des articles 91, 92 et 93.", "Expliquer une zone de tension entre l’éducation provinciale, les garanties confessionnelles et le pouvoir fédéral de désaveu."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const FEDERAL_PROVINCIAL_RELATIONS_METIS_PRIMARY_DOCUMENTS = [
  FEDERAL_PROVINCIAL_RELATIONS_RED_RIVER_DECLARATION_DOCUMENT,
  FEDERAL_PROVINCIAL_RELATIONS_RIEL_TRIAL_SPEECH_DOCUMENT,
] as const satisfies readonly HistoricalDocumentRecord[];

export const FEDERAL_PROVINCIAL_RELATIONS_PRIMARY_DOCUMENTS = [
  ...FEDERAL_PROVINCIAL_RELATIONS_METIS_PRIMARY_DOCUMENTS,
  FEDERAL_PROVINCIAL_RELATIONS_CONSTITUTION_COMPETENCIES_DOCUMENT,
] as const satisfies readonly HistoricalDocumentRecord[];
