import { createHistoricalDocumentResearchNeed } from "./historical-document.ts";
import type { HistoricalDocumentRecord } from "./historical-document.ts";

export const ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-001",
  title: "Extrait de l’Acte d’Union (1840)",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "time_and_space", "relationships_between_facts", "causes_and_consequences"],
  historicalDate: "23 juillet 1840; entrée en vigueur le 10 février 1841",
  creator: "Parlement du Royaume-Uni",
  holdingInstitution: "PrimaryDocuments.ca — version numérique du texte officiel reproduit dans les Lois révisées du Canada (1985)",
  sourceUrl: "https://primarydocuments.ca/acte-dunion-1840-r-u/?lang=fr",
  sourceLocator: "Acte d’Union (R.-U.), 3-4 Victoria, ch. 35, art. I; reproduit dans L.R.C. 1985, annexe II, no 4.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2018/03/Act-of-Union-1840.pdf",
  rightsStatement: "Texte législatif officiel de 1840 reproduit dans les Lois révisées du Canada; conserver la référence à la version numérique de PrimaryDocuments.ca.",
  transcription: "[…] il est expédient que les dites Provinces soient réunies et ne forment qu’une seule Province pour les fins de Gouvernement Exécutif et de Législation […] les dites Provinces ne formeront et ne constitueront qu’une seule et même Province, sous le nom de Province du Canada […]",
  accessibleDescription: "Extrait de l’article premier de l’Acte d’Union annonçant la réunion du Haut-Canada et du Bas-Canada en une seule colonie appelée Province du Canada, pour les fins du gouvernement exécutif et de la législation.",
  historicalContext: "Adopté par le Parlement britannique en 1840 et appliqué en 1841, l’Acte d’Union fusionne le Haut-Canada et le Bas-Canada afin de créer une seule colonie : la Province du Canada. Cet extrait présente la principale disposition de la loi, soit l’union politique des deux colonies sous un même gouvernement.",
  observationGuide: [
    "Identifier la réunion du Haut-Canada et du Bas-Canada comme principale mesure annoncée.",
    "Nommer la Province du Canada comme nouveau territoire créé par la loi.",
    "Repérer que le gouvernement exécutif et la législation deviennent communs.",
    "Situer l’adoption en 1840 et l’entrée en vigueur en 1841 dans la période 1840–1896.",
  ],
  interpretationCautions: [
    "Distinguer l’adoption de la loi en 1840 de son entrée en vigueur en 1841.",
    "Signaler que les coupures sont indiquées par […] et conserver le sens de l’article premier.",
    "Ne pas attribuer à ce seul extrait toutes les causes ou conséquences de l’Union sans mobiliser d’autres sources approuvées.",
  ],
  pedagogicalUses: [
    "Établir des faits : identifier la principale mesure annoncée et nommer le nouveau territoire créé.",
    "Situer dans le temps et dans l’espace : replacer le document dans la période 1840–1896 et situer les deux colonies réunies.",
    "Mettre en relation des faits : relier la disposition législative aux recommandations du rapport Durham.",
    "Déterminer des causes et des conséquences : expliquer une conséquence politique de la création d’un gouvernement commun.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-010",
  title: "L’anglais dans les documents officiels de la législature",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "differences_and_similarities", "changes_and_continuities"],
  historicalDate: "23 juillet 1840; entrée en vigueur le 10 février 1841",
  creator: "Parlement du Royaume-Uni",
  holdingInstitution: "PrimaryDocuments.ca — reproduction du texte officiel dans les Lois révisées du Canada (1985)",
  sourceUrl: "https://primarydocuments.ca/acte-dunion-1840-r-u/?lang=fr",
  sourceLocator: "Acte d’Union (R.-U.), 3-4 Victoria, ch. 35, art. XLI; reproduit dans L.R.C. 1985, annexe II, no 4.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2018/03/Act-of-Union-1840.pdf",
  rightsStatement: "Texte législatif officiel de 1840 dans le domaine public; le texte élève est une adaptation pédagogique assemblée par Socrato à partir de l’article 41.",
  transcription: "Après l’Union du Haut-Canada et du Bas-Canada, les proclamations, les documents électoraux, les journaux parlementaires, les rapports de comités et les autres travaux écrits du Conseil législatif et de l’Assemblée législative doivent être produits officiellement en anglais.\n\nLa loi permet cependant de préparer des traductions de ces documents. Ces traductions peuvent être consultées, mais elles ne sont pas conservées comme documents parlementaires originaux et ne possèdent pas la même valeur officielle.",
  accessibleDescription: "Adaptation pédagogique de l’article 41 distinguant l’anglais exigé pour les documents officiels de la législature des traductions autorisées sans valeur de document original.",
  historicalContext: "L’article 41 vise la langue des documents et travaux officiels du Conseil législatif et de l’Assemblée législative. Il n’interdit pas l’usage général du français dans la Province du Canada. Cette restriction parlementaire est abrogée en 1848.",
  observationGuide: ["Repérer les catégories de documents visées.", "Constater que les traductions demeurent permises.", "Distinguer l’exclusivité de l’anglais dans les originaux officiels d’une interdiction générale du français."],
  interpretationCautions: ["Le texte est une adaptation pédagogique assemblée, non une transcription intégrale.", "Ne pas conclure que le français devient illégal dans toutes les sphères de la société.", "Distinguer la mesure de 1840 de son abrogation en 1848."],
  pedagogicalUses: ["Établir la portée de la disposition linguistique.", "Comparer document officiel et traduction.", "Corriger l’idée d’une interdiction générale du français."],
  version: "1.0",
  approvedAt: "2026-08-02T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-012",
  title: "La réunion des revenus publics et le paiement des dettes",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "relationships_between_facts", "causes_and_consequences"],
  historicalDate: "23 juillet 1840; entrée en vigueur le 10 février 1841",
  creator: "Parlement du Royaume-Uni",
  holdingInstitution: "PrimaryDocuments.ca — reproduction du texte officiel dans les Lois révisées du Canada (1985)",
  sourceUrl: "https://primarydocuments.ca/acte-dunion-1840-r-u/?lang=fr",
  sourceLocator: "Acte d’Union (R.-U.), 3-4 Victoria, ch. 35, art. L et LVI; reproduit dans L.R.C. 1985, annexe II, no 4.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2018/03/Act-of-Union-1840.pdf",
  rightsStatement: "Texte législatif officiel de 1840 dans le domaine public; transcription modernisée d’extraits des articles 50 et 56, avec les coupures signalées par […].",
  transcription: "Lors de la réunion des provinces du Haut-Canada et du Bas-Canada, tous les droits et revenus que les législatures respectives desdites provinces […] ont le pouvoir d’affecter formeront un fonds de revenus réunis. Ce fonds sera affecté aux besoins publics de la Province du Canada […].\n\nLes frais de perception, de gestion et de recouvrement du fonds des revenus réunis constitueront la première charge sur ce fonds. L’intérêt annuel de la dette publique des provinces du Haut-Canada et du Bas-Canada, ou de l’une ou l’autre d’entre elles, au moment de leur réunion, constituera la deuxième charge sur ce fonds […].",
  accessibleDescription: "Deux extraits de l’Acte d’Union indiquant que les revenus publics du Haut-Canada et du Bas-Canada sont réunis dans un même fonds destiné aux besoins de la Province du Canada, notamment au paiement de l’intérêt sur les dettes publiques des deux anciennes colonies.",
  historicalContext: "Les articles 50 et 56 de l’Acte d’Union établissent un fonds commun alimenté par les revenus publics auparavant administrés par les deux colonies. La loi détermine ensuite l’ordre des dépenses qui doivent être payées à même ce fonds, dont les coûts de perception et l’intérêt sur les dettes publiques.",
  observationGuide: ["Repérer l’origine des revenus versés au fonds commun.", "Identifier l’usage public du fonds.", "Nommer les deux premières charges imposées au fonds par la loi."],
  interpretationCautions: ["L’extrait est composé uniquement de passages du texte législatif primaire; l’orthographe, la ponctuation et certaines tournures grammaticales ont été modernisées, et les coupures sont indiquées par […].", "Le texte emploie l’expression historique « fonds de revenus réunis »; l’appellation pédagogique « fonds consolidé » désigne ici ce mécanisme financier commun.", "Distinguer la réunion des revenus et le paiement de l’intérêt des dettes d’une annulation de ces dettes."],
  pedagogicalUses: ["Définir le fonds commun à partir du texte de loi.", "Identifier les revenus qui l’alimentent et les dépenses qu’il assume.", "Relier le fonds commun à la mise en commun des charges financières des deux colonies."],
  version: "1.0",
  approvedAt: "2026-08-03T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-006",
  title: "Les Rébellions entraînent la suspension du régime représentatif",
  kind: "other",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences", "causal_connections", "changes_and_continuities"],
  historicalDate: "30 juin 1840",
  creator: "Chambre des lords du Royaume-Uni",
  holdingInstitution: "Parlement du Royaume-Uni — Historic Hansard; transcription complémentaire par PrimaryDocuments.ca",
  sourceUrl: "https://api.parliament.uk/historic-hansard/lords/1840/jun/30/government-of-canada",
  sourceLocator: "Chambre des lords du Royaume-Uni, débat « Government of Canada », 30 juin 1840, vol. 55, col. 229.",
  assetUrl: "https://primarydocuments.ca/uk-house-of-lords-government-of-canada-vol-55-cols-227-272-30-june-1840/",
  rightsStatement: "Débat parlementaire britannique de 1840 dans le domaine public; traduction-adaptation française rédigée par Socrato à partir de la transcription anglaise.",
  transcription: "Les conflits entre les gouverneurs et les assemblées se terminèrent par l’insurrection. Le Parlement suspendit alors l’Acte constitutionnel de 1791 et établit au Bas-Canada un gouvernement dirigé par le gouverneur et un Conseil spécial.",
  accessibleDescription: "Adaptation française d’un débat parlementaire britannique qui relie les Rébellions à la suspension des institutions représentatives du Bas-Canada et à leur remplacement temporaire par un gouverneur assisté d’un Conseil spécial.",
  historicalContext: "Après les Rébellions de 1837-1838, le Parlement britannique suspend la constitution parlementaire du Bas-Canada. L’Assemblée élue ne siège plus et la colonie est administrée temporairement par le gouverneur et un Conseil spécial nommé. En 1840, ce régime sert de contexte immédiat au débat britannique sur l’union des deux Canadas.",
  observationGuide: [
    "Repérer l’insurrection comme événement qui précède la décision britannique.",
    "Identifier la suspension de l’Acte constitutionnel de 1791 comme conséquence politique.",
    "Nommer le gouverneur et le Conseil spécial comme autorités qui remplacent temporairement l’Assemblée élue.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève est une traduction-adaptation française d’un débat tenu en anglais.",
    "Le passage présente le récit rétrospectif d’un parlementaire britannique en 1840; il ne constitue pas une description neutre de toutes les causes des Rébellions.",
    "Distinguer la suspension temporaire du régime représentatif en 1838 de l’Acte d’Union adopté en 1840 et appliqué en 1841.",
  ],
  pedagogicalUses: [
    "Déterminer une conséquence politique des Rébellions de 1837-1838.",
    "Établir la chaîne causale entre les Rébellions, la suspension de l’Assemblée élue, le Conseil spécial et le projet d’Union.",
    "Comparer le régime représentatif antérieur au gouvernement temporaire du Bas-Canada.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-009",
  title: "BAnQ repère 512 Patriotes emprisonnés",
  kind: "other",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences"],
  historicalDate: "Base mise à jour le 4 décembre 2024; registres couvrant 1819-1838",
  creator: "Bibliothèque et Archives nationales du Québec (BAnQ)",
  holdingInstitution: "Archives nationales à Montréal — fonds Ministère de la Justice, registres d’écrou de la prison de Montréal",
  sourceUrl: "https://www2.banq.qc.ca/archives/genealogie_histoire_familiale/ressources/bd/recherche.html?id=PRISON_MTL_1836_38",
  sourceLocator: "Présentation de la base « Les registres d’écrou de la prison de Montréal, 1826-1838 », paragraphe sur les Événements de 1837-1838.",
  assetUrl: "https://www2.banq.qc.ca/archives/genealogie_histoire_familiale/ressources/bd/recherche.html?id=PRISON_MTL_1836_38",
  rightsStatement: "Court extrait d’un texte institutionnel de BAnQ reproduit avec attribution et lien vers la page source.",
  transcription: "La période couverte est particulièrement mouvementée. L’emprisonnement de 512 patriotes lors des Événements de 1837-1838 en témoigne.",
  accessibleDescription: "Court texte de BAnQ indiquant que sa base des registres d’écrou de Montréal permet de repérer 512 Patriotes emprisonnés pendant les événements de 1837-1838.",
  historicalContext: "BAnQ a compilé 7 124 entrées provenant des trois premiers registres d’écrou de la prison de Montréal et a ajouté un champ permettant de repérer les Patriotes. Le nombre de 512 concerne les Patriotes identifiés dans cette base montréalaise, et non nécessairement toutes les personnes emprisonnées dans l’ensemble du Bas-Canada.",
  observationGuide: ["Relever le nombre de Patriotes emprisonnés repérés par BAnQ.", "Identifier l’emprisonnement comme une conséquence humaine et judiciaire des Rébellions."],
  interpretationCautions: ["Il s’agit d’un texte institutionnel contemporain fondé sur des archives, et non d’un témoignage rédigé en 1837-1838.", "Le total de 512 correspond à la base montréalaise de BAnQ et ne doit pas être présenté comme le nombre de tous les prisonniers du Bas-Canada.", "Une inscription au registre ne signifie pas nécessairement qu’une personne a été reconnue coupable."],
  pedagogicalUses: ["Établir un fait quantitatif sur les emprisonnements.", "Déterminer l’emprisonnement comme conséquence des Rébellions.", "Distinguer une base archivistique contemporaine des registres historiques qu’elle décrit."],
  version: "1.0",
  approvedAt: "2026-08-02T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const PATRIOTES_MERCURY_MILITARY_MOVEMENTS_DOCUMENT = {
  schemaVersion: 1,
  id: "PAT-T-001",
  title: "Les rebelles face à l’expédition militaire",
  kind: "newspaper",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences", "relationships_between_facts", "causal_connections"],
  historicalDate: "15 décembre 1837; article repris du Montreal Courier du 13 décembre 1837",
  creator: "Mercury Office, d’après le Montreal Courier",
  holdingInstitution: "Bibliothèque McLennan, Université McGill; reproduction numérique diffusée par Canadiana",
  sourceUrl: "https://www.canadiana.ca/view/oocihm.60931",
  sourceLocator: "Extraordinary, « Military Movements », Mercury Office, 15 décembre 1837, colonne de gauche; reprise du Montreal Courier, 13 décembre 1837. Canadiana, identifiant 60931.",
  assetUrl: "https://www.canadiana.ca/view/oocihm.60931/5",
  rightsStatement: "Article de journal publié en 1837 et appartenant au domaine public au Canada. La reproduction numérique est diffusée par Canadiana à des fins notamment de recherche et d’enseignement; conserver la référence au document original, à la Bibliothèque McLennan de l’Université McGill et à Canadiana. Vérifier les conditions de la plateforme avant toute rediffusion externe du fac-similé.",
  transcription: "Ce matin, les forces destinées à l’expédition ont quitté la ville. Elles comprennent plusieurs régiments, une importante unité d’artillerie munie de six canons ainsi que des volontaires à cheval et à pied. […] Les forces rebelles à Grand-Brûlé sont complètement encerclées. Des troupes régulières et des volontaires se trouvent derrière elles, tandis qu’une autre force les attaque de front. Les hommes armés placés à l’arrière leur laissent peu d’espoir de s’échapper.",
  accessibleDescription: "Traduction-adaptation de deux passages d’un supplément de journal loyaliste décrivant le déploiement de régiments, d’artillerie et de volontaires contre des rebelles présentés comme encerclés à Grand-Brûlé en décembre 1837.",
  historicalContext: "En décembre 1837, les forces britanniques et les volontaires loyalistes mènent des opérations contre les Patriotes. Ce supplément publié par le Mercury reprend un article du Montreal Courier et présente l’expédition du point de vue de journaux favorables aux autorités coloniales.",
  observationGuide: [
    "Identifier les forces mobilisées contre les rebelles : régiments, artillerie et volontaires.",
    "Repérer la position attribuée aux forces placées devant et derrière les rebelles.",
    "Relever les mots qui présentent l’issue de l’affrontement comme presque certaine.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève est une traduction-adaptation française de passages sélectionnés; les coupures sont signalées par […].",
    "Le mot « rebelles » et la description de leur encerclement reflètent un point de vue loyaliste et militaire.",
    "Le supplément du Mercury reprend un article du Montreal Courier; distinguer la date de l’article, le 13 décembre, de celle de sa republication, le 15 décembre 1837.",
    "Ne pas présenter le récit journalistique comme un bilan neutre ou complet des opérations militaires.",
  ],
  pedagogicalUses: [
    "Décrire le rapport de force militaire auquel font face les Patriotes.",
    "Déterminer la répression armée comme conséquence de l’insurrection.",
    "Établir le point de vue loyaliste d’un article de journal.",
    "Relier la mobilisation militaire, l’encerclement et la défaite des Patriotes.",
  ],
  version: "1.0",
  approvedAt: "2026-08-01T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT = {
  schemaVersion: 1,
  id: "PAT-T-002",
  title: "Un gouvernement hors de l’influence de la population",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences", "relationships_between_facts", "causal_connections"],
  historicalDate: "21 février 1834",
  creator: "92 Résolutions, résolutions 14 et 28 — majorité patriote de la Chambre d’assemblée du Bas-Canada; adaptation pédagogique assemblée et modernisée",
  holdingInstitution: "Journaux de la Chambre d’assemblée du Bas-Canada; reproduction numérique diffusée par PrimaryDocuments.ca",
  sourceUrl: "https://primarydocuments.ca/lower-canada-house-of-assembly-92-resolutions-14th-parl-4th-sess-21-february-1834/",
  sourceLocator: "92 Résolutions, résolutions 14 et 28, Journaux de la Chambre d’assemblée du Bas-Canada, 14e Parlement, 4e session, 1834, p. 310-338; fac-similé bilingue, pages PDF 2 et 6.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2021/05/92ResolutionsLA.pdf",
  rightsStatement: "Résolutions parlementaires officielles de 1834 appartenant au domaine public. Conserver la référence aux Journaux de la Chambre d’assemblée du Bas-Canada, les numéros des résolutions et le lien vers le fac-similé bilingue diffusé par PrimaryDocuments.ca.",
  transcription: "Le système électif devrait être étendu au Conseil législatif. […] Le bonheur ou le malheur du pays dépend d’un pouvoir exécutif sur lequel la population n’exerce aucune influence. L’extension du principe électif constitue donc le seul moyen d’assurer une protection égale à tous les habitants de la province.",
  accessibleDescription: "Adaptation en français modernisé de deux passages des 92 Résolutions réclamant l’élection du Conseil législatif et dénonçant un pouvoir exécutif soustrait à l’influence de la population.",
  historicalContext: "En 1834, la Chambre d’assemblée du Bas-Canada adopte 92 résolutions qui rassemblent ses principaux griefs contre l’administration coloniale. Les résolutions 14 et 28 portent sur la composition du Conseil législatif et sur l’absence d’influence de la population sur le pouvoir exécutif.",
  observationGuide: [
    "Identifier l’institution que les députés souhaitent rendre élective.",
    "Repérer le problème soulevé au sujet du pouvoir exécutif.",
    "Nommer la réforme présentée comme une solution par la Chambre d’assemblée.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève assemble les résolutions 14 et 28; la coupure entre les passages est indiquée par […].",
    "Il s’agit d’une adaptation en français modernisé, et non d’une transcription diplomatique du document de 1834.",
    "Les 92 Résolutions présentent le point de vue majoritaire de la Chambre d’assemblée et ne résument pas à elles seules toutes les causes des Rébellions.",
    "La date de 1834 doit être distinguée des affrontements armés de 1837-1838.",
  ],
  pedagogicalUses: [
    "Établir l’absence de contrôle de la population sur le Conseil législatif et l’exécutif.",
    "Déterminer une cause politique profonde des Rébellions de 1837-1838.",
    "Relier une revendication de 1834 au rejet britannique exprimé dans les résolutions Russell de 1837.",
    "Comparer les institutions élues et non élues du régime colonial.",
  ],
  version: "1.0",
  approvedAt: "2026-08-01T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT = {
  schemaVersion: 1,
  id: "PAT-T-003",
  title: "Londres rejette les principales demandes de l’Assemblée",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences", "relationships_between_facts", "causal_connections"],
  historicalDate: "6 mars 1837",
  creator: "Lord John Russell; Chambre des communes du Royaume-Uni",
  holdingInstitution: "Parlement du Royaume-Uni — Historic Hansard; fac-similé diffusé par PrimaryDocuments.ca",
  sourceUrl: "https://primarydocuments.ca/uk-hc-affairs-of-canada-vol-36-6-march-1837/",
  sourceLocator: "Résolutions Russell, résolutions 4, 5 et 8, débat « Affairs of Canada », Chambre des communes du Royaume-Uni, 6 mars 1837, vol. 36, col. 1284-1362.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2021/05/RussellResolutions1837.pdf",
  rightsStatement: "Résolutions et débat parlementaire officiels de 1837 appartenant au domaine public. Conserver la référence à Lord John Russell, à la Chambre des communes, aux numéros des résolutions et aux versions numériques de Historic Hansard et de PrimaryDocuments.ca.",
  transcription: "Dans l’état actuel du Bas-Canada, il n’est pas souhaitable de rendre le Conseil législatif électif. […] Il n’est pas souhaitable de soumettre le Conseil exécutif à la responsabilité demandée par la Chambre d’assemblée. […] Le gouverneur pourra prélever sur les revenus de la province les sommes nécessaires au paiement des dépenses du gouvernement civil.",
  accessibleDescription: "Traduction-adaptation de trois résolutions britanniques qui refusent l’élection du Conseil législatif, refusent la responsabilité de l’exécutif devant l’Assemblée et autorisent le gouverneur à utiliser les revenus provinciaux pour payer les dépenses civiles.",
  historicalContext: "En 1837, le Parlement britannique répond à la crise politique du Bas-Canada. Les résolutions présentées par Lord John Russell rejettent deux réformes institutionnelles réclamées par la Chambre d’assemblée et permettent au gouverneur de payer les dépenses du gouvernement à même les revenus coloniaux malgré le refus de subsides de l’Assemblée.",
  observationGuide: [
    "Identifier les deux réformes institutionnelles refusées par Londres.",
    "Repérer le pouvoir financier accordé au gouverneur.",
    "Comparer chaque refus aux demandes formulées dans les 92 Résolutions.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève assemble les résolutions 4, 5 et 8; chaque coupure est indiquée par […].",
    "Il s’agit d’une traduction-adaptation française simplifiée, et non d’une transcription intégrale du texte anglais.",
    "Les résolutions présentent la décision du Parlement britannique; elles ne décrivent pas à elles seules toutes les réactions au Bas-Canada.",
    "Distinguer le dépôt des résolutions le 6 mars 1837 de leur adoption ultérieure par le Parlement.",
  ],
  pedagogicalUses: [
    "Déterminer le rejet des réformes politiques comme cause immédiate de la radicalisation en 1837.",
    "Relier les 92 Résolutions aux résolutions Russell dans une chaîne causale.",
    "Comparer le pouvoir financier de l’Assemblée à celui que Londres accorde au gouverneur.",
    "Expliquer pourquoi la réponse britannique accroît la méfiance envers le régime colonial.",
  ],
  version: "1.0",
  approvedAt: "2026-08-01T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const PATRIOTES_MINERVE_POLITICAL_REPRESSION_DOCUMENT = {
  schemaVersion: 1,
  id: "PAT-T-004",
  title: "Punir la participation politique",
  kind: "newspaper",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences", "relationships_between_facts", "causal_connections"],
  historicalDate: "2 novembre 1837",
  creator: "La Minerve",
  holdingInstitution: "Bibliothèque et Archives nationales du Québec (BAnQ)",
  sourceUrl: "https://numerique.banq.qc.ca/patrimoine/details/52327/4128839",
  sourceLocator: "La Minerve, Montréal, jeudi 2 novembre 1837, no 78; passages relatifs aux explications exigées d’officiers de milice présents à des assemblées et au « système d’oppression ».",
  assetUrl: "https://numerique.banq.qc.ca/patrimoine/details/52327/4128839",
  rightsStatement: "Numéro de journal de 1837 signalé par BAnQ comme appartenant au domaine public au Canada. Conserver la référence au numéro original et indiquer clairement le caractère adapté du montage textuel.",
  transcription: "Le gouverneur demande à des officiers de milice de s’expliquer sur leur présence à des assemblées politiques; leur commission est alors remise en question. […] En soutenant de telles mesures, le gouvernement maintient un système d’oppression. Il est temps d’ouvrir les yeux sur le véritable état du Bas-Canada.",
  accessibleDescription: "Adaptation pédagogique assemblée montrant que la participation d’officiers de milice à des assemblées politiques pouvait entraîner des pressions sur leur commission, puis reliant ces mesures à la dénonciation d’un système d’oppression.",
  historicalContext: "À l’automne 1837, les assemblées patriotes se multiplient et l’administration coloniale cherche à neutraliser l’opposition. Dans ce numéro, La Minerve associe les explications exigées de certains officiers de milice et la remise en question de leur commission à un système politique qu’elle présente comme oppressif.",
  observationGuide: [
    "Identifier l’activité politique reprochée aux officiers de milice.",
    "Repérer la fonction que le pouvoir colonial peut leur retirer.",
    "Expliquer pourquoi La Minerve parle d’un système d’oppression.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève est une adaptation pédagogique assemblée à partir de plusieurs passages du même numéro; la coupure est indiquée par […].",
    "La formulation a été simplifiée et explicitée : il ne s’agit ni d’une citation littérale ni d’une transcription diplomatique mot à mot.",
    "La Minerve est alors un journal associé au mouvement patriote; son vocabulaire exprime un point de vue engagé.",
    "Le document est textuel : aucun fac-similé iconographique n’a été modifié.",
  ],
  pedagogicalUses: [
    "Déterminer la répression de la participation politique comme une cause du mécontentement.",
    "Relier la présence à une assemblée politique au risque de perdre une fonction officielle.",
    "Interpréter le point de vue patriote exprimé dans un journal de 1837.",
  ],
  version: "1.0",
  approvedAt: "2026-08-01T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const PATRIOTES_MINERVE_RESIGNATION_DOCUMENT = {
  schemaVersion: 1,
  id: "PAT-T-005",
  title: "Choisir entre sa fonction et sa patrie",
  kind: "newspaper",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences", "relationships_between_facts"],
  historicalDate: "2 novembre 1837",
  creator: "Lettre reproduite dans La Minerve",
  holdingInstitution: "Bibliothèque et Archives nationales du Québec (BAnQ)",
  sourceUrl: "https://numerique.banq.qc.ca/patrimoine/details/52327/4128839",
  sourceLocator: "La Minerve, Montréal, jeudi 2 novembre 1837, no 78; lettre annonçant la remise d’une commission de juge de paix.",
  assetUrl: "https://numerique.banq.qc.ca/patrimoine/details/52327/4128839",
  rightsStatement: "Numéro de journal de 1837 signalé par BAnQ comme appartenant au domaine public au Canada. Conserver la référence au numéro original et indiquer clairement le caractère adapté du montage textuel.",
  transcription: "Mon dévouement envers ma patrie m’oblige aujourd’hui à remettre ma commission comme juge de paix. […] Je ne peux continuer à exercer cette fonction sous une administration qui s’oppose aux convictions politiques de la population.",
  accessibleDescription: "Adaptation pédagogique assemblée d’une lettre présentant la démission d’un juge de paix comme un choix entre sa fonction officielle et son attachement politique à la patrie.",
  historicalContext: "À l’automne 1837, le conflit entre l’administration coloniale et le mouvement patriote place certains titulaires de charges publiques devant un choix de loyauté. La lettre reproduite par La Minerve présente la remise d’une commission de juge de paix comme un geste politique.",
  observationGuide: [
    "Identifier la fonction officielle abandonnée par l’auteur.",
    "Repérer la valeur invoquée pour justifier cette décision.",
    "Expliquer ce que la démission révèle du rapport entre certains fonctionnaires et l’administration coloniale.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève est une adaptation pédagogique assemblée; la coupure est indiquée par […].",
    "La seconde phrase explicite le sens politique de la lettre : l’ensemble n’est ni une citation littérale ni une transcription diplomatique mot à mot.",
    "Cette démission individuelle témoigne d’un mécontentement, mais ne représente pas nécessairement l’ensemble des juges de paix.",
    "Le document est textuel : aucun fac-similé iconographique n’a été modifié.",
  ],
  pedagogicalUses: [
    "Établir qu’une fonction publique pouvait entrer en conflit avec les convictions patriotes.",
    "Interpréter une démission comme une manifestation du mécontentement politique.",
    "Relier un choix individuel à la crise de confiance envers l’administration coloniale.",
  ],
  version: "1.0",
  approvedAt: "2026-08-01T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT = {
  schemaVersion: 1,
  id: "PAT-T-006",
  title: "Envisager l’indépendance",
  kind: "newspaper",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "causes_and_consequences", "relationships_between_facts", "causal_connections"],
  historicalDate: "2 novembre 1837",
  creator: "La Minerve",
  holdingInstitution: "Bibliothèque et Archives nationales du Québec (BAnQ)",
  sourceUrl: "https://numerique.banq.qc.ca/patrimoine/details/52327/4128839",
  sourceLocator: "La Minerve, Montréal, jeudi 2 novembre 1837, no 78; passages évoquant la rupture avec l’Angleterre et l’état jugé désespérant des affaires du Bas-Canada.",
  assetUrl: "https://numerique.banq.qc.ca/patrimoine/details/52327/4128839",
  rightsStatement: "Numéro de journal de 1837 signalé par BAnQ comme appartenant au domaine public au Canada. Conserver la référence au numéro original et identifier le texte comme une adaptation pédagogique assemblée.",
  transcription: "Le mécontentement est devenu si profond que certains souhaitent profiter de la première occasion favorable pour secouer le joug de l’Angleterre et déclarer le Canada indépendant, à l’exemple des États-Unis. […] La situation des affaires dans le Bas-Canada est jugée désespérante.",
  accessibleDescription: "Adaptation pédagogique assemblée présentant l’indépendance à l’égard de l’Angleterre comme une solution envisagée devant une situation politique jugée désespérante.",
  historicalContext: "À l’automne 1837, la crise politique du Bas-Canada s’aggrave. Dans ce numéro engagé en faveur du mouvement patriote, l’idée de rompre avec l’Angleterre et de suivre l’exemple des États-Unis témoigne d’un mécontentement qui dépasse désormais les seules demandes de réforme.",
  observationGuide: [
    "Identifier le lien politique que certains souhaitent rompre.",
    "Repérer le pays présenté comme un exemple.",
    "Expliquer ce que l’idée d’indépendance révèle de l’intensité du mécontentement.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève est une adaptation pédagogique assemblée à partir de passages du même numéro; la coupure est indiquée par […].",
    "La formulation a été simplifiée et explicitée : il ne s’agit ni d’une citation littérale ni d’une transcription diplomatique mot à mot.",
    "Le passage rapporte une possibilité de rupture politique; il ne prouve pas que toute la population du Bas-Canada souhaitait l’indépendance.",
    "La Minerve exprime alors un point de vue engagé associé au mouvement patriote.",
  ],
  pedagogicalUses: [
    "Montrer que le mécontentement pouvait conduire au-delà des demandes de réforme.",
    "Relier la crise de confiance envers le régime colonial à l’idée d’indépendance.",
    "Comparer la solution réformiste à la possibilité d’une rupture avec l’Angleterre.",
  ],
  version: "1.0",
  approvedAt: "2026-08-01T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_BERMUDA_EXILE_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-007",
  title: "Des chefs patriotes exilés aux Bermudes",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "time_and_space", "causes_and_consequences", "causal_connections"],
  historicalDate: "28 juin 1838",
  creator: "Gouverneur général et Conseil spécial du Bas-Canada",
  holdingInstitution: "Ordonnances du Conseil spécial du Bas-Canada; reproduction dans William Houston, Documents Illustrative of the Canadian Constitution (1891), numérisée par PrimaryDocuments.ca",
  sourceUrl: "https://primarydocuments.ca/documents-illustrative-of-the-canadian-constitution/",
  sourceLocator: "« An Ordinance to provide for the Security of the Province of Lower Canada », 28 juin 1838; voir aussi l’Indemnity Act, 1-2 Victoria, ch. 112, 16 août 1838.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2018/01/DocsIllusCanConst1891Mar31.pdf",
  rightsStatement: "Ordonnance officielle de 1838 dans le domaine public; traduction-adaptation française rédigée par Socrato à partir du texte anglais reproduit dans une compilation historique numérisée.",
  transcription: "Plusieurs personnes détenues et accusées de haute trahison, dont Wolfred Nelson, devront être transportées aux Bermudes. Elles y demeureront sous les restrictions nécessaires pour empêcher leur retour au Bas-Canada.",
  accessibleDescription: "Adaptation française d’une ordonnance de 1838 qui prévoit le transport aux Bermudes de prisonniers politiques du Bas-Canada, dont Wolfred Nelson, et des mesures pour empêcher leur retour dans la colonie.",
  historicalContext: "Après la Rébellion de 1837, lord Durham cherche une solution au sort des prisonniers politiques du Bas-Canada. Avec le Conseil spécial, il fait adopter une ordonnance qui envoie Wolfred Nelson et sept autres détenus aux Bermudes. Le Parlement britannique reconnaît ensuite que la partie de l’ordonnance exécutée hors du Bas-Canada excédait les pouvoirs des autorités coloniales.",
  observationGuide: [
    "Identifier Wolfred Nelson comme l’une des personnes visées.",
    "Situer les Bermudes comme lieu d’exil imposé hors du Bas-Canada.",
    "Repérer l’interdiction de retour comme conséquence politique et judiciaire de la Rébellion.",
  ],
  interpretationCautions: [
    "Le texte montré à l’élève est une traduction-adaptation française; il ne reproduit pas toute l’ordonnance ni la liste complète des personnes visées.",
    "Les personnes nommées n’avaient pas toutes été jugées et condamnées selon la procédure judiciaire ordinaire.",
    "L’autorité du gouverneur et du Conseil spécial ne s’étendait pas légalement aux Bermudes; le Parlement britannique a ensuite reconnu le problème et adopté une loi d’indemnisation.",
  ],
  pedagogicalUses: [
    "Déterminer une conséquence judiciaire et politique de la Rébellion de 1837.",
    "Situer le déplacement forcé de prisonniers entre le Bas-Canada et les Bermudes.",
    "Relier la répression, l’exil de chefs patriotes et les limites juridiques du régime du Conseil spécial.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-008",
  title: "Cinquante-huit Patriotes déportés en Australie",
  kind: "other",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "time_and_space", "causes_and_consequences", "causal_connections"],
  historicalDate: "27 septembre 1839; arrivée le 25 février 1840",
  creator: "Autorités coloniales britanniques; transport à bord du HMS Buffalo",
  holdingInstitution: "Dictionnaire biographique du Canada; archives pénitentiaires de la Nouvelle-Galles du Sud",
  sourceUrl: "https://www.biographi.ca/fr/bio/morin_achille_12E.html?print=1",
  sourceLocator: "Notice « Achille-Gabriel Morin », paragraphes sur la commutation des peines et le départ du HMS Buffalo; registres associés aux prisonniers canadiens dans les NSW State Archives.",
  assetUrl: "https://sara-backup.mhnsw.au/www.records.nsw.gov.au/archives/collections-and-research/guides-and-indexes/stories/french-migration-stories.html",
  rightsStatement: "Les faits sont reconstruits à partir de notices institutionnelles canadiennes et australiennes; le texte élève est une adaptation originale de Socrato et non la transcription d’un registre.",
  transcription: "En septembre 1839, 58 prisonniers reconnus coupables après la Rébellion du Bas-Canada voient leur peine de mort commuée en déportation pénale. Le HMS Buffalo les transporte jusqu’en Nouvelle-Galles du Sud, en Australie.",
  accessibleDescription: "Texte adapté expliquant que 58 prisonniers patriotes ont échappé à la pendaison lorsque leur peine a été commuée en déportation pénale vers l’Australie à bord du HMS Buffalo.",
  historicalContext: "Après les procès militaires suivant l’insurrection de 1838, 58 prisonniers du Bas-Canada condamnés à mort reçoivent un pardon conditionnel qui transforme leur peine en déportation pénale. Le HMS Buffalo quitte Québec en septembre 1839; les prisonniers arrivent à Sydney en février 1840 et sont conduits au camp de Longbottom.",
  observationGuide: [
    "Relever le nombre de prisonniers concernés.",
    "Distinguer la condamnation à mort de la peine finalement appliquée.",
    "Situer le déplacement entre le Bas-Canada et la Nouvelle-Galles du Sud.",
  ],
  interpretationCautions: [
    "Le texte élève résume plusieurs notices institutionnelles et ne constitue pas la transcription d’un seul document de 1839.",
    "Employer le terme déportation pénale et expliquer que la peine de mort a été commuée; ne pas présenter le voyage comme une migration volontaire.",
    "Distinguer ces 58 déportés des huit prisonniers envoyés aux Bermudes en 1838.",
  ],
  pedagogicalUses: [
    "Déterminer une conséquence judiciaire et humaine des Rébellions.",
    "Situer le trajet du HMS Buffalo entre Québec et Sydney.",
    "Comparer l’exil aux Bermudes et la déportation pénale en Australie.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_RUSSELL_POINT_OF_VIEW_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-002",
  title: "Lord John Russell défend l’union des deux Canadas",
  kind: "other",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "relationships_between_facts", "causal_connections"],
  historicalDate: "3 juin 1839",
  creator: "Lord John Russell, ministre de l’Intérieur du Royaume-Uni",
  holdingInstitution: "Parlement du Royaume-Uni — Historic Hansard; transcription complémentaire par PrimaryDocuments.ca",
  sourceUrl: "https://api.parliament.uk/historic-hansard/commons/1839/jun/03/canada",
  sourceLocator: "Chambre des communes du Royaume-Uni, débat « Canada », 3 juin 1839, vol. 47, colonnes 1274-1275.",
  assetUrl: "https://primarydocuments.ca/uk-hc-canada-vol-47-1839-cols-1254-90-3-june-1839/",
  rightsStatement: "Débat parlementaire britannique de 1839 dans le domaine public; traduction-adaptation française rédigée par Socrato à partir de la transcription anglaise.",
  transcription: "Selon moi, l’union législative du Haut-Canada et du Bas-Canada permettra de leur donner des institutions représentatives communes et de favoriser la prospérité de la nouvelle province.",
  accessibleDescription: "Adaptation française d’un passage dans lequel Lord John Russell défend devant la Chambre des communes une union législative fondée sur un gouvernement représentatif commun.",
  historicalContext: "Après les Rébellions de 1837-1838 et le rapport Durham, le gouvernement britannique cherche une nouvelle organisation politique pour les Canadas. Le 3 juin 1839, Lord John Russell présente à la Chambre des communes une résolution favorable à leur union législative.",
  observationGuide: [
    "Identifier l’union législative comme la solution proposée par Russell.",
    "Relever les institutions représentatives communes et la prospérité comme avantages annoncés.",
    "Distinguer le point de vue du gouvernement britannique de celui des opposants à l’Union.",
  ],
  interpretationCautions: [
    "Présenter ce passage comme le point de vue d’un ministre britannique favorable à l’Union, et non comme une opinion partagée par toute la population.",
    "Indiquer clairement que le texte montré à l’élève est une traduction-adaptation française du débat anglais.",
    "Ne pas confondre cette proposition de 1839 avec le texte définitif de l’Acte d’Union adopté en 1840.",
  ],
  pedagogicalUses: [
    "Établir le point de vue favorable à l’Union défendu par le gouvernement britannique.",
    "Comparer les arguments de Russell aux critiques formulées par Louis-Hippolyte La Fontaine.",
    "Établir un lien entre les débats britanniques de 1839 et l’adoption de l’Acte d’Union en 1840.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_SPECIAL_COUNCIL_RESOLUTIONS_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-003",
  title: "Le Conseil spécial présente l’Union comme une nécessité urgente",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "relationships_between_facts", "causal_connections"],
  historicalDate: "13 novembre 1839",
  creator: "Conseil spécial du Bas-Canada",
  holdingInstitution: "Bibliothèque et Archives Canada; exemplaire numérisé par Canadiana",
  sourceUrl: "https://www.canadiana.ca/view/oocihm.9_00944",
  sourceLocator: "Journals of the Special Council of the Province of Lower Canada, vol. 5, partie 1, séance du 13 novembre 1839, résolutions sur la réunion des provinces.",
  assetUrl: "https://www.canadiana.ca/view/oocihm.9_00944",
  rightsStatement: "Procès-verbal officiel de 1839 dans le domaine public; traduction-adaptation française rédigée par Socrato à partir du texte bilingue numérisé.",
  transcription: "Dans les circonstances actuelles, afin d’assurer la paix, la tranquillité et un gouvernement constitutionnel efficace, la réunion du Haut-Canada et du Bas-Canada sous une seule législature est devenue, selon ce Conseil, une nécessité indispensable et urgente.",
  accessibleDescription: "Adaptation française d’une résolution dans laquelle le Conseil spécial du Bas-Canada affirme que l’union des deux provinces sous une seule législature est urgente et nécessaire.",
  historicalContext: "Après la suspension de la constitution du Bas-Canada, le Conseil spécial remplace temporairement l’Assemblée élue. En novembre 1839, le gouverneur Charles Poulett Thomson lui soumet le projet d’union avec le Haut-Canada; le Conseil adopte des résolutions favorables à cette mesure.",
  observationGuide: [
    "Relever les problèmes auxquels l’Union est censée répondre.",
    "Identifier la réunion sous une seule législature comme la solution proposée.",
    "Identifier l’institution qui adopte la résolution et s’interroger sur sa représentativité.",
  ],
  interpretationCautions: [
    "Le Conseil spécial n’est pas une assemblée élue et ne représente pas à lui seul l’opinion de la population du Bas-Canada.",
    "Le texte montré à l’élève est une traduction-adaptation d’une résolution officielle.",
    "La résolution appuie le principe de l’Union avant l’adoption définitive de la loi britannique de 1840.",
  ],
  pedagogicalUses: [
    "Établir le point de vue favorable du Conseil spécial sur l’Union.",
    "Comparer cet appui institutionnel à l’opposition exprimée par La Fontaine.",
    "Établir un lien entre la suspension de l’Assemblée élue et le processus menant à l’Acte d’Union.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_UPPER_CANADA_ASSEMBLY_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-005",
  title: "L’Assemblée du Haut-Canada juge l’Union indispensable",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "relationships_between_facts", "causal_connections"],
  historicalDate: "1839",
  creator: "Assemblée législative du Haut-Canada; documents transmis par Charles Poulett Thomson (futur lord Sydenham)",
  holdingInstitution: "Bibliothèque des Archives publiques du Canada; exemplaire numérisé par Canadiana",
  sourceUrl: "https://www.canadiana.ca/view/oocihm.21720",
  sourceLocator: "Messages from His Excellency the Governor General on the subject of the re-union of the provinces of Upper & Lower Canada, Toronto, Patriot, 1839, 17 p., identifiant Canadiana oocihm.21720; voir aussi le débat britannique du 3 juin 1839, col. 1272.",
  assetUrl: "https://primarydocuments.ca/uk-hc-canada-vol-47-1839-cols-1254-90-3-june-1839/",
  rightsStatement: "Documents parlementaires officiels de 1839 dans le domaine public; traduction-adaptation française rédigée par Socrato à partir des transcriptions anglaises.",
  transcription: "Selon l’Assemblée du Haut-Canada, une législature unie pour les deux Canadas est indispensable; tout nouveau retard risque de nuire gravement aux intérêts des deux colonies.",
  accessibleDescription: "Adaptation française d’une résolution dans laquelle l’Assemblée législative du Haut-Canada présente l’union des deux Canadas comme indispensable et demande qu’elle ne soit plus retardée.",
  historicalContext: "En 1839, des élus du Haut-Canada appuient le principe d’une union législative avec le Bas-Canada. Charles Poulett Thomson, futur lord Sydenham, rassemble ensuite les messages, résolutions, amendements et votes liés au projet. L’appui est notamment associé aux intérêts politiques et financiers du Haut-Canada, mais les conditions proposées et les votes consignés montrent que le débat ne se résume pas à une opinion unanime.",
  observationGuide: [
    "Identifier l’union législative comme la mesure jugée indispensable.",
    "Relever l’urgence exprimée par la mise en garde contre tout nouveau retard.",
    "Distinguer le point de vue de l’Assemblée du Haut-Canada des messages transmis par le gouverneur.",
  ],
  interpretationCautions: [
    "Le point de vue de l’Assemblée ne représente pas automatiquement celui de toute la population du Haut-Canada.",
    "Le texte montré à l’élève est une traduction-adaptation française d’une résolution rédigée en anglais.",
    "Ne pas attribuer directement la résolution à Sydenham : son recueil réunit ses messages et les décisions de l’Assemblée.",
  ],
  pedagogicalUses: [
    "Établir le point de vue favorable à l’Union exprimé par l’Assemblée du Haut-Canada.",
    "Comparer cet appui aux résolutions du Conseil spécial et à l’opposition de La Fontaine.",
    "Mettre en relation les intérêts du Haut-Canada et le processus politique menant à l’Acte d’Union.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_LANGUAGE_REPEAL_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-004",
  title: "L’abolition de l’exclusivité de l’anglais au Parlement",
  kind: "law-or-official-text",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "changes_and_continuities", "relationships_between_facts", "causal_connections"],
  historicalDate: "14 août 1848",
  creator: "Parlement du Royaume-Uni",
  holdingInstitution: "Statutes of the United Kingdom; exemplaire numérisé et transcrit par PrimaryDocuments.ca",
  sourceUrl: "https://primarydocuments.ca/the-union-act-amendment-act-1848-uk/",
  sourceLocator: "11 & 12 Victoria, chapitre 56, sanctionné le 14 août 1848; Statutes of the United Kingdom, vol. 19, p. 231-232.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2018/03/7-UnionActAmendmentAct1848.pdf",
  rightsStatement: "Texte législatif officiel de 1848 dans le domaine public; traduction-adaptation française rédigée par Socrato à partir du texte anglais.",
  transcription: "La disposition de l’Acte d’Union exigeant que les documents et les travaux du Conseil législatif et de l’Assemblée législative soient uniquement en anglais est abrogée.",
  accessibleDescription: "Adaptation française d’une loi britannique de 1848 qui abroge la disposition de l’Acte d’Union imposant l’anglais dans les documents officiels du Parlement de la Province du Canada.",
  historicalContext: "L’article 41 de l’Acte d’Union imposait l’anglais dans les documents officiels de la législature, même si des traductions sans valeur officielle pouvaient être produites. La loi britannique de 1848 abroge cette restriction et permet aux institutions de la Province du Canada d’établir leurs propres règles linguistiques.",
  observationGuide: [
    "Identifier la disposition linguistique qui est abrogée.",
    "Comparer la situation créée en 1840 à celle rendue possible en 1848.",
    "Distinguer l’abolition de l’exclusivité de l’anglais d’une déclaration moderne de bilinguisme officiel.",
  ],
  interpretationCautions: [
    "La loi retire la restriction de 1840, mais son court texte ne proclame pas à lui seul un régime moderne de langues officielles.",
    "Le texte montré à l’élève est une traduction-adaptation française du document anglais.",
    "Relier cette modification au contexte politique du gouvernement responsable sans présenter une seule cause comme suffisante.",
  ],
  pedagogicalUses: [
    "Déterminer un changement apporté au régime de l’Acte d’Union.",
    "Comparer une disposition de la loi de 1840 à son abrogation en 1848.",
    "Mettre en relation les revendications linguistiques et l’évolution politique de la Province du Canada.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT = {
  schemaVersion: 1,
  id: "historical-document:acte-union:lafontaine-terrebonne-1840",
  title: "Louis-Hippolyte La Fontaine dénonce l’Acte d’Union",
  kind: "other",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union"],
  operationIds: ["establish_facts", "relationships_between_facts", "causes_and_consequences", "causal_connections"],
  historicalDate: "25 août 1840; publication le 28 août 1840",
  creator: "Louis-Hippolyte La Fontaine",
  holdingInstitution: "Bibliothèque et Archives nationales du Québec — collection numérique de L’Aurore des Canadas",
  sourceUrl: "https://www.banq.qc.ca/liste-des-journaux-du-quebec-disponibles-en-ligne/",
  sourceLocator: "Louis-Hippolyte La Fontaine, « Adresse aux électeurs du comté de Terrebonne », 25 août 1840, publiée à la une de L’Aurore des Canadas, Montréal, 28 août 1840.",
  assetUrl: "https://books.openedition.org/pum/13006",
  rightsStatement: "Texte de 1840 dans le domaine public; exemplaire du journal conservé et numérisé par BAnQ. L’extrait modernisé doit conserver la référence au numéro du 28 août 1840.",
  transcription: "L’Union est enfin décrétée! Le Canada […] ne doit, à l’avenir, former qu’une seule Province. […] L’histoire dira que la force l’a imposée aux deux peuples du Bas et du Haut-Canada.\n\n[…] Elle est un acte d’injustice et de despotisme, en ce qu’elle nous est imposée sans notre consentement, en ce qu’elle prive le Bas-Canada du nombre légitime de ses représentants, en ce qu’elle nous prive de l’usage de notre langue dans les travaux de la Législature, […] en ce qu’elle nous fait payer, sans notre consentement, une dette que nous n’avons pas contractée.",
  accessibleDescription: "Extrait d’une adresse politique dans laquelle Louis-Hippolyte La Fontaine dénonce l’Union du Haut-Canada et du Bas-Canada ainsi que ses effets politiques, linguistiques et financiers pour le Bas-Canada.",
  historicalContext: "En 1840, le Parlement britannique adopte l’Acte d’Union, qui réunit le Haut-Canada et le Bas-Canada dans une seule colonie appelée la Province du Canada. La Fontaine présente cette union comme imposée sans le consentement de la population du Bas-Canada et critique la représentation politique, la restriction de l’usage du français dans les institutions parlementaires et le partage de la dette du Haut-Canada.",
  observationGuide: [
    "Relever que La Fontaine présente l’Union comme imposée sans consentement.",
    "Repérer la critique du nombre de représentants accordé au Bas-Canada.",
    "Repérer la restriction de l’usage du français dans les travaux de la Législature.",
    "Repérer la critique du partage de la dette du Haut-Canada.",
  ],
  interpretationCautions: [
    "Présenter le texte comme le point de vue d’un opposant réformiste à l’Union, et non comme une description neutre de la loi.",
    "Signaler que l’extrait est composé de passages du document original et que les coupures sont indiquées par […].",
    "Signaler que l’orthographe et la ponctuation ont été légèrement modernisées pour faciliter la lecture au secondaire.",
  ],
  pedagogicalUses: [
    "Établir des faits en relevant deux injustices dénoncées par La Fontaine.",
    "Mettre en relation les dispositions de l’Acte d’Union et les critiques formulées dans l’adresse.",
    "Déterminer des causes et des conséquences politiques et linguistiques de l’Union pour le Bas-Canada.",
    "Établir des liens de causalité entre les dispositions de l’Union et l’opposition de La Fontaine.",
  ],
  version: "1.0",
  approvedAt: "2026-07-31T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT = {
  schemaVersion: 1,
  id: "AU-T-011",
  title: "Francis Hincks propose une alliance à La Fontaine",
  kind: "other",
  status: "approved",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["acte-union", "gouvernement-responsable"],
  operationIds: ["relationships_between_facts", "causes_and_consequences", "causal_connections"],
  historicalDate: "17 juin 1840",
  creator: "Francis Hincks",
  holdingInstitution: "Dictionnaire biographique du Canada — biographie de Louis-Hippolyte La Fontaine",
  sourceUrl: "https://www.biographi.ca/en/bio/4541?revision_id=33966",
  sourceLocator: "Lettre de Francis Hincks à Louis-Hippolyte La Fontaine, 17 juin 1840; passage cité dans la biographie de La Fontaine.",
  assetUrl: "https://www.biographi.ca/en/bio/4541?revision_id=33966",
  rightsStatement: "Lettre de 1840 dans le domaine public; traduction-adaptation pédagogique française réalisée par Socrato à partir du passage anglais cité par le Dictionnaire biographique du Canada.",
  transcription: "[Contexte pédagogique : en juin 1840, alors que l’union du Haut-Canada et du Bas-Canada est en préparation, les réformistes envisagent une seule législature commune. Pour défendre leurs réformes et former une majorité, ils devront obtenir l’appui de députés des deux sections.] Francis Hincks expose cette stratégie à Louis-Hippolyte La Fontaine : Vos compatriotes n’obtiendraient jamais leurs droits dans une législature du Bas-Canada. Vous avez besoin de notre aide autant que nous avons besoin de la vôtre. […] Nos libertés ne peuvent être garanties que par l’Union.",
  accessibleDescription: "Extrait d’une lettre dans laquelle le réformiste du Haut-Canada Francis Hincks explique à Louis-Hippolyte La Fontaine que les réformistes des deux sections ont besoin de collaborer pour défendre leurs droits politiques dans la nouvelle législature unie.",
  historicalContext: "À la veille de l’entrée en vigueur de l’Acte d’Union, des réformistes du Haut-Canada et du Bas-Canada cherchent à unir leurs forces dans la future Assemblée législative. Hincks présente cette collaboration comme une nécessité réciproque. Cette stratégie prépare le rapprochement politique entre les réformistes de Robert Baldwin et ceux de Louis-Hippolyte La Fontaine.",
  observationGuide: [
    "Relever l’idée d’une aide réciproque entre les réformistes des deux sections.",
    "Relier cette collaboration à leur recherche d’une majorité dans la législature commune.",
    "Distinguer la proposition formulée par Hincks en 1840 de l’alliance politique ensuite associée à La Fontaine et Baldwin.",
  ],
  interpretationCautions: [
    "Le texte présenté est une adaptation pédagogique assemblée : le passage entre crochets donne le contexte historique, puis le reste traduit un extrait de la lettre originale anglaise.",
    "La lettre exprime le point de vue stratégique de Francis Hincks; elle ne prouve pas que tous les députés appuient l’alliance.",
    "Ne pas présenter l’Acte d’Union comme ayant instauré immédiatement le gouvernement responsable.",
  ],
  pedagogicalUses: [
    "Expliquer pourquoi les réformistes du Canada-Est et du Canada-Ouest cherchent à collaborer.",
    "Mettre en relation la structure de l’Assemblée unie et la formation d’une alliance politique transsectionnelle.",
    "Établir un lien entre l’Union de 1840 et la lutte ultérieure pour le gouvernement responsable.",
  ],
  version: "1.0",
  approvedAt: "2026-08-03T00:00:00.000-04:00",
} as const satisfies HistoricalDocumentRecord;

export const ACTE_UNION_HISTORICAL_DOCUMENT_NEEDS = [
  createHistoricalDocumentResearchNeed({
    id: "document-need:acte-union:territory-map",
    title: "Carte du territoire de la Province du Canada",
    kind: "map",
    periodIds: ["1840-1896"],
    knowledgeHeadingIds: ["acte-union"],
    operationIds: ["time_and_space"],
    pedagogicalUses: ["Situer le Canada-Est et le Canada-Ouest et comprendre la nouvelle organisation territoriale."],
  }),
  createHistoricalDocumentResearchNeed({
    id: "document-need:acte-union:official-excerpt",
    title: "Extrait authentique de l’Acte d’Union",
    kind: "law-or-official-text",
    periodIds: ["1840-1896"],
    knowledgeHeadingIds: ["acte-union"],
    operationIds: ["establish_facts", "relationships_between_facts"],
    pedagogicalUses: ["Repérer directement dans la loi certaines dispositions politiques et administratives."],
  }),
  createHistoricalDocumentResearchNeed({
    id: "document-need:acte-union:population-table",
    title: "Tableau démographique du Canada-Est et du Canada-Ouest",
    kind: "statistics",
    periodIds: ["1840-1896"],
    knowledgeHeadingIds: ["acte-union"],
    operationIds: ["establish_facts", "differences_and_similarities", "causal_connections"],
    pedagogicalUses: ["Comparer les populations et expliquer la portée politique de la représentation égale."],
  }),
  createHistoricalDocumentResearchNeed({
    id: "document-need:acte-union:political-structure",
    title: "Schéma de la structure politique sous l’Acte d’Union",
    kind: "political-diagram",
    periodIds: ["1840-1896"],
    knowledgeHeadingIds: ["acte-union"],
    operationIds: ["relationships_between_facts", "causal_connections"],
    pedagogicalUses: ["Visualiser les rapports entre le gouverneur, les conseils et l’Assemblée législative."],
  }),
  createHistoricalDocumentResearchNeed({
    id: "document-need:acte-union:language-politics",
    title: "Document sur les dimensions linguistiques ou politiques de l’Union",
    kind: "image",
    periodIds: ["1840-1896"],
    knowledgeHeadingIds: ["acte-union"],
    operationIds: ["establish_facts", "causes_and_consequences"],
    pedagogicalUses: ["Interpréter une trace de la politique d’assimilation ou de ses conséquences."],
  }),
] as const;

export const ACTE_UNION_MAP_CANDIDATES = [
  {
    id: "document-candidate:acte-union:map-east-west-1855",
    needId: "document-need:acte-union:territory-map",
    title: "Map of Canada East and West",
    historicalDate: "1855",
    creator: "Ensign, Bridgman & Fanning",
    holdingInstitution: "Bibliothèque et Archives Canada",
    sourceUrl: "https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?IdNumber=3694915&app=FonAndCol",
    sourceLocator: "R11981-27-4-E · MIKAN 3694915 · collection Alexander E. MacDonald no 529",
    rightsAssessment: "La notice de BAC indique « Copyright expired » et demande de créditer Bibliothèque et Archives Canada.",
    strengths: ["Nomme directement le Canada-Est et le Canada-Ouest.", "Présente les comtés et des données du recensement de 1842.", "La provenance, la cote et les conditions d’utilisation sont explicites."],
    limitations: ["La carte date de 1855, quatorze ans après l’entrée en vigueur de l’Union.", "La densité d’information et l’anglais exigent un accompagnement pédagogique."],
    recommendation: "preferred",
  },
  {
    id: "document-candidate:acte-union:wyld-1842",
    needId: "document-need:acte-union:territory-map",
    title: "Map of the Province of Canada",
    historicalDate: "vers 1842",
    creator: "James Wyld (1812-1887), éditeur",
    holdingInstitution: "The Huntington Library; reproduction repérée sur Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Province_of_Canada.JamesWyld.ca1842.jpg",
    sourceLocator: "Fichier 5 766 × 3 814 px; source déclarée : Huntington Digital Library",
    rightsAssessment: "Commons signale l’œuvre de 1842 dans le domaine public aux États-Unis. La politique de la Huntington laisse toutefois la vérification finale des droits à l’utilisateur.",
    strengths: ["Contemporaine des débuts de la Province du Canada.", "Vue générale du territoire dans un fichier de très haute résolution.", "Excellent potentiel pour situer les espaces et les voies d’eau."],
    limitations: ["La notice de droits est moins directe que celle de BAC.", "Il faut consigner la notice originale précise de la Huntington avant toute approbation."],
    recommendation: "alternative",
  },
  {
    id: "document-candidate:acte-union:bouchette-1846",
    needId: "document-need:acte-union:territory-map",
    title: "Map of the Provinces of Canada…",
    historicalDate: "1846",
    creator: "Joseph Bouchette fils (1800-1881)",
    holdingInstitution: "Bibliothèque et Archives Canada",
    sourceUrl: "https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?app=fonandcol&idnumber=3721270",
    sourceLocator: "R11981-98-5-E · MIKAN 3721270 · collection Alexander E. MacDonald no 408",
    rightsAssessment: "La notice de BAC indique « Copyright expired » et demande de créditer Bibliothèque et Archives Canada.",
    strengths: ["Carte très détaillée, proche chronologiquement de l’Union.", "Auteur identifié et nombreuses autorités cartographiques consignées.", "Montre routes, canaux, chemins de fer, relief et plusieurs cartes en médaillon."],
    limitations: ["Format original immense et contenu trop dense pour une première lecture d’élève.", "Convient davantage comme approfondissement ou comme base d’un extrait autorisé."],
    recommendation: "context-only",
  },
] as const;

export const ACTE_UNION_MAP_ADAPTATION_DRAFT = {
  id: "document-draft:acte-union:wyld-1842-socrato",
  title: "Province du Canada vers 1842 — carte de Wyld modifiée",
  status: "approved",
  previewUrl: "/pedagogical-reference/documents/acte-union/province-canada-wyld-1842-modifiee-officielle.png",
  editableAssetUrl: "/pedagogical-reference/documents/acte-union/province-canada-wyld-1842-socrato.svg",
  originalAssetUrl: "/pedagogical-reference/documents/acte-union/province-canada-wyld-1842-original.jpg",
  sourceUrl: "https://commons.wikimedia.org/wiki/File:Province_of_Canada.JamesWyld.ca1842.jpg",
  cartographicReferenceUrl: "https://www.canada.ca/fr/patrimoine-canadien/services/frontieres-historiques-canada.html",
  cartographicReferenceStatement: "L’étendue générale des quatre zones a été recoupée avec la carte de 1840 publiée par Patrimoine canadien. Les aplats de Socrato demeurent des repères pédagogiques schématiques et ne remplacent pas une frontière de levé.",
  attribution: "James Wyld, Map of the Province of Canada, vers 1842, carte modifiée à des fins pédagogiques; The Huntington Library; reproduction repérée sur Wikimedia Commons.",
  rightsAssessment: "L’œuvre cartographique de 1842 est dans le domaine public au Canada. La notice exacte de la reproduction numérique de la Huntington doit néanmoins être confirmée avant l’approbation et toute diffusion externe.",
  modifications: [
    "Ajout d’aplats colorés semi-transparents pour distinguer le Canada-Ouest, le Canada-Est, la Terre de Rupert, le Nouveau-Brunswick et les États-Unis.",
    "Ajout de grandes étiquettes françaises pour identifier les cinq zones représentées.",
    "Ajout de tracés colorés pour faciliter la lecture des limites territoriales approximatives.",
    "Ajout dans l’interface d’une légende qui associe chaque couleur à sa zone et précise que les frontières sont approximatives.",
  ],
  validationNotes: [
    "Vérifier les limites colorées avec une référence cartographique historique avant l’approbation.",
    "Présenter explicitement les frontières comme approximatives et les aplats comme des repères pédagogiques.",
    "Employer Nouveau-Brunswick dans la légende même si l’étiquette intégrée à l’image indique seulement Brunswick.",
    "Confirmer la notice de la reproduction numérique de la Huntington avant de faire passer le document à Prêt à valider.",
    "Conserver le fichier original sans modification et distinguer clairement l’adaptation de la source historique.",
    "Utiliser l’image autonome pour l’aperçu du module et conserver le fichier vectoriel uniquement comme version de travail modifiable.",
  ],
  version: "1.0",
  approvedAt: "2026-08-01T00:00:00.000-04:00",
} as const;
