export {
  getSecondaryFourKnowledgeHeading,
  getSecondaryFourPeriod,
  SECONDARY_FOUR_KNOWLEDGE_HEADINGS,
  SECONDARY_FOUR_PERIODS,
  SECONDARY_FOUR_PROGRAM_SOURCE,
} from "./secondary-four.ts";
export {
  createEmptyNotionReferenceCard,
  EMPTY_REFERENCE_VALIDATION_CHECKLIST,
  isNotionReferenceCardReady,
  validateNotionReferenceCard,
} from "./reference-card.ts";
export { createEmptyHistoricalRecord, validateHistoricalRecord } from "./historical-record.ts";
export { getIntellectualOperation, INTELLECTUAL_OPERATIONS, INTELLECTUAL_OPERATION_IDS, INTELLECTUAL_OPERATION_SOURCES } from "./intellectual-operations.ts";
export { createEmptyApprovedQuestion, validateApprovedQuestion } from "./approved-question.ts";
export { ACTE_UNION_CAUSAL_PILOT_QUESTION, ACTE_UNION_TIMELINE_PROTOTYPE_QUESTION, ACTE_UNION_TIMELINE_CAUSAL_DEVELOPMENT_QUESTION, ACTE_UNION_DEFINITION_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_DURHAM_DEFINITION_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_EQUAL_REPRESENTATION_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_LANGUAGE_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_PROVINCE_SECTIONS_SHORT_ANSWER_QUESTION, ACTE_UNION_RESPONSIBLE_GOVERNMENT_SHORT_ANSWER_QUESTION, ACTE_UNION_SHARED_DEBT_SHORT_ANSWER_QUESTION, ACTE_UNION_LAFONTAINE_OPPOSITION_SHORT_ANSWER_QUESTION, ACTE_UNION_1840_1841_SHORT_ANSWER_QUESTION, ACTE_UNION_POLITICAL_TRANSFORMATION_DOCUMENT_QUESTION, ACTE_UNION_RUSSELL_LAFONTAINE_COMPARISON_QUESTION, ACTE_UNION_DURHAM_ACT_COMPARISON_QUESTION, ACTE_UNION_DEBT_STRUCTURE_RELATIONSHIP_QUESTION, ACTE_UNION_DEBT_OPPOSITION_CAUSAL_QUESTION, ACTE_UNION_SOLUTION_INJUSTICE_DOCUMENT_QUESTION, ACTE_UNION_DURHAM_RECOMMENDATIONS_DOCUMENT_QUESTION, ACTE_UNION_DURHAM_ASSIMILATION_CAUSAL_QUESTION, ACTE_UNION_WYLD_TERRITORIAL_TRANSFORMATION_QUESTION, ACTE_UNION_WYLD_TERRITORIES_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_REBELLION_CONSEQUENCES_DOCUMENT_QUESTION, ACTE_UNION_CAUSES_CONSEQUENCES_DEVELOPMENT_QUESTION, ACTE_UNION_DURHAM_ACT_DEVELOPMENT_QUESTION, ACTE_UNION_DEBT_REPRESENTATION_DEVELOPMENT_QUESTION, ACTE_UNION_DURHAM_OPPOSITION_CAUSAL_DEVELOPMENT_QUESTION, ACTE_UNION_REPRESSION_DOCUMENT_MULTIPLE_CHOICE_QUESTION, RESPONSIBLE_GOVERNMENT_COALITION_SHORT_ANSWER_QUESTION, RESPONSIBLE_GOVERNMENT_TIMELINE_CAUSAL_DEVELOPMENT_QUESTION, ACTE_UNION_SYDENHAM_ROLE_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_POLITICAL_INSTITUTIONS_ASSOCIATION_QUESTION, COLONIAL_ECONOMY_MARKETS_CHANGE_CONTINUITY_QUESTION, COLONIAL_ECONOMY_CORN_LAWS_MULTIPLE_CHOICE_QUESTION, COLONIAL_ECONOMY_RECIPROCITY_MULTIPLE_CHOICE_QUESTION, getQuestionsForKnowledgeHeading, getTransversalQuestions, PEDAGOGICAL_QUESTION_CATALOG } from "./question-catalog.ts";
export { PEDAGOGICAL_REFERENCE_PILOTS } from "./pilots.ts";
export { COLONIAL_ECONOMY_CORN_LAWS_REPEAL_CONSEQUENCE_QUESTION } from "./question-catalog.ts";
export { COLONIAL_ECONOMY_CIVIL_WAR_RECIPROCITY_CAUSAL_QUESTION } from "./question-catalog.ts";
export { COLONIAL_ECONOMY_RECIPROCITY_EXPORTS_CHART_QUESTION } from "./question-catalog.ts";
export { COLONIAL_ECONOMY_CORN_LAWS_VIEWPOINT_COMPARISON_QUESTION } from "./question-catalog.ts";
export { COLONIAL_ECONOMY_RECIPROCITY_TRADE_MAP_QUESTION } from "./question-catalog.ts";
export { INDIAN_AFFAIRS_1876_STATE_RELATIONS_VIEWPOINT_COMPARISON_QUESTION } from "./question-catalog.ts";
export { COLONIAL_ECONOMY_CONCEPTS_ASSOCIATION_QUESTION } from "./question-catalog.ts";
export { INDIAN_AFFAIRS_BAGOT_CONSEQUENCES_QUESTION } from "./question-catalog.ts";
export { INDIAN_AFFAIRS_THOMAS_MOORE_ASSIMILATION_QUESTION } from "./question-catalog.ts";
export { INDIAN_AFFAIRS_QUAPPELLE_FAMILY_SEPARATION_QUESTION } from "./question-catalog.ts";
export { INDIAN_AFFAIRS_CHRISTIANIZATION_CONSEQUENCE_QUESTION } from "./question-catalog.ts";
export { INDIAN_AFFAIRS_INDIAN_ACT_CONTROL_QUESTION } from "./question-catalog.ts";
export { INDIAN_AFFAIRS_RESERVE_MANAGEMENT_QUESTION } from "./question-catalog.ts";
export { FEDERAL_PROVINCIAL_RELATIONS_METIS_COMPARISON_QUESTION } from "./question-catalog.ts";
export { FEDERAL_PROVINCIAL_RELATIONS_COMPETENCIES_ASSOCIATION_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_TERRITORIAL_EVOLUTION_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_TERRITORIAL_DATES_ASSOCIATION_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_PROVINCES_EXPANSION_ASSOCIATION_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_MAP_ADHESION_DATES_QUESTION } from "./question-catalog.ts";
export { ACTE_UNION_HISTORICAL_RECORD } from "./records/acte-union.ts";
export { RESPONSIBLE_GOVERNMENT_HISTORICAL_RECORD } from "./records/responsible-government.ts";
export { COLONIAL_ECONOMY_HISTORICAL_RECORD } from "./records/economie-coloniale.ts";
export { INDIAN_AFFAIRS_HISTORICAL_RECORD } from "./records/affaires-indiennes.ts";
export { BRITISH_NORTH_AMERICA_ACT_HISTORICAL_RECORD } from "./records/acte-amerique-nord-britannique.ts";
export { BRITISH_NORTH_AMERICA_CONFEDERATION_DOCUMENTS, BRITISH_NORTH_AMERICA_RAILWAY_CONDITION_DOCUMENTS, BRITISH_NORTH_AMERICA_COALITION_CAUSAL_DOCUMENTS, BRITISH_NORTH_AMERICA_INTERCOLONIAL_CAUSE_CONSEQUENCE_DOCUMENTS, BRITISH_NORTH_AMERICA_AMERICAN_THREAT_DOCUMENTS, BRITISH_NORTH_AMERICA_INTERCOLONIAL_MAP_DOCUMENT, BRITISH_NORTH_AMERICA_INTERCOLONIAL_FREIGHT_TABLE_DOCUMENT, BRITISH_NORTH_AMERICA_LINCOLN_THREAT_CARTOON_DOCUMENT, BRITISH_NORTH_AMERICA_CARTIER_DEFENCE_DOCUMENT, BRITISH_NORTH_AMERICA_CAUCHON_INTERCOLONIAL_DEFENCE_DOCUMENT, BRITISH_NORTH_AMERICA_INSULAR_COLONIES_NON_ADHESION_DOCUMENT, BRITISH_NORTH_AMERICA_MACDONALD_CONFEDERATION_DOCUMENT, BRITISH_NORTH_AMERICA_CARTIER_CONFEDERATION_DOCUMENT, BRITISH_NORTH_AMERICA_DORION_CONFEDERATION_DOCUMENT, BRITISH_NORTH_AMERICA_ANNAND_RAILWAY_DOCUMENT, BRITISH_NORTH_AMERICA_FISHER_RAILWAY_DOCUMENT, BRITISH_NORTH_AMERICA_BELLEAU_INSTABILITY_DOCUMENT, BRITISH_NORTH_AMERICA_BROWN_COALITION_DOCUMENT, BRITISH_NORTH_AMERICA_MONCK_NEGOTIATIONS_DOCUMENT } from "./british-north-america-confederation-documents.ts";
export { BRITISH_NORTH_AMERICA_ACT_CONFEDERATION_VIEWPOINTS_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_CONFERENCES_ASSOCIATION_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_COMPETENCIES_ASSOCIATION_QUESTION, BRITISH_NORTH_AMERICA_ACT_CONFERENCE_PARTICIPATION_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_RAILWAY_CONDITION_QUESTION } from "./question-catalog.ts";
export { BRITISH_NORTH_AMERICA_ACT_COALITION_CAUSAL_QUESTION, BRITISH_NORTH_AMERICA_ACT_INTERCOLONIAL_CAUSE_CONSEQUENCE_QUESTION, BRITISH_NORTH_AMERICA_ACT_AMERICAN_THREAT_QUESTION, BRITISH_NORTH_AMERICA_ACT_TERRITORIAL_FEAR_QUESTION } from "./question-catalog.ts";
export { FEDERAL_PROVINCIAL_RELATIONS_HISTORICAL_RECORD } from "./records/relations-federales-provinciales.ts";
export { ACTE_UNION_DOCUMENT_SOURCE_CATALOG } from "./acte-union-document-source-catalog.ts";
export { acceptHistoricalRecordReviewItems, canApproveHistoricalRecord, countHistoricalRecordReview, createHistoricalRecordReviewDraft, getHistoricalRecordReviewItems } from "./review.ts";
export { createHistoricalDocumentResearchNeed, validateHistoricalDocument, validateHistoricalDocumentPresentation } from "./historical-document.ts";
export { ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT, ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT, ACTE_UNION_BERMUDA_EXILE_DOCUMENT, ACTE_UNION_EXECUTIVE_COUNCIL_DOCUMENT, ACTE_UNION_HISTORICAL_DOCUMENT_NEEDS, ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT, ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT, ACTE_UNION_LANGUAGE_REPEAL_DOCUMENT, ACTE_UNION_MAP_ADAPTATION_DRAFT, ACTE_UNION_MAP_CANDIDATES, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT, ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT, ACTE_UNION_RUSSELL_POINT_OF_VIEW_DOCUMENT, ACTE_UNION_SPECIAL_COUNCIL_RESOLUTIONS_DOCUMENT, ACTE_UNION_UPPER_CANADA_ASSEMBLY_DOCUMENT, PATRIOTES_MERCURY_MILITARY_MOVEMENTS_DOCUMENT, PATRIOTES_MINERVE_BRITISH_REFUSAL_RESISTANCE_DOCUMENT, PATRIOTES_MINERVE_INDEPENDENCE_DOCUMENT, PATRIOTES_MINERVE_POLITICAL_REPRESSION_DOCUMENT, PATRIOTES_MINERVE_RESIGNATION_DOCUMENT, PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT, PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT } from "./historical-document-needs.ts";
export { ACTE_UNION_DURHAM_ADVANCEMENT_ANGLICIZATION_PRESENTATION, ACTE_UNION_DURHAM_ANGLICIZATION_PRESENTATION, ACTE_UNION_DURHAM_DOCUMENT, ACTE_UNION_DURHAM_PRESENTATIONS, ACTE_UNION_DURHAM_RESPONSIBLE_GOVERNMENT_PRESENTATION, ACTE_UNION_DURHAM_UNION_PRESENTATION } from "./historical-document-presentations.ts";
export { ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM, ACTE_UNION_STUDENT_TIMELINE, PATRIOTES_ICONOGRAPHIC_DOCUMENTS, RESPONSIBLE_GOVERNMENT_ICONOGRAPHIC_DOCUMENTS, RESPONSIBLE_GOVERNMENT_STUDENT_TIMELINE, type IconographicDocumentRecord } from "./responsible-government-iconography.ts";
export { INDUSTRIALIZATION_ICONOGRAPHIC_DOCUMENTS, type IndustrializationIconographicDocumentRecord } from "./industrialization-iconography.ts";
export { BRITISH_NORTH_AMERICA_ACT_PROVINCE_CANADA_1849_MAP, BRITISH_NORTH_AMERICA_ACT_DOMINION_1867_MAP, BRITISH_NORTH_AMERICA_ACT_DOMINION_1873_MAP, BRITISH_NORTH_AMERICA_ACT_DOMINION_1949_MAP, BRITISH_NORTH_AMERICA_ACT_TERRITORIAL_MAPS, type BritishNorthAmericaActMapRecord } from "./british-north-america-act-maps.ts";
export { RESPONSIBLE_GOVERNMENT_ELECTORAL_LAW_DOCUMENT, RESPONSIBLE_GOVERNMENT_ELECTORAL_LAW_PRESENTATION } from "./responsible-government-electoral-law.ts";
export { RESPONSIBLE_GOVERNMENT_CANADIEN_PARLIAMENT_FIRE_DOCUMENT, RESPONSIBLE_GOVERNMENT_ELGIN_NON_INTERVENTION_DOCUMENT, RESPONSIBLE_GOVERNMENT_METCALFE_ELGIN_DOCUMENTS, RESPONSIBLE_GOVERNMENT_METCALFE_RESIGNATION_DOCUMENT } from "./responsible-government-primary-documents.ts";
export { COLONIAL_ECONOMY_CANADA_CORN_LAW_DOCUMENT, COLONIAL_ECONOMY_PRIMARY_DOCUMENTS, COLONIAL_ECONOMY_RECIPROCITY_TRADE_MAP_DOCUMENT, COLONIAL_ECONOMY_RECIPROCITY_TREATY_DOCUMENT } from "./colonial-economy-primary-documents.ts";
export { COLONIAL_ECONOMY_CORN_LAWS_REPEAL_CONSEQUENCE_DOCUMENT } from "./colonial-economy-primary-documents.ts";
export { COLONIAL_ECONOMY_COBDEN_CORN_LAWS_REPEAL_DOCUMENT, COLONIAL_ECONOMY_QUEBEC_BOARD_OF_TRADE_CORN_LAWS_DOCUMENT } from "./colonial-economy-primary-documents.ts";
export { INDIAN_AFFAIRS_FEDERAL_TUTELAGE_CITIZENSHIP_DOCUMENT, INDIAN_AFFAIRS_ONONDAGA_CHIEFS_ALLIANCE_PETITION_DOCUMENT } from "./indian-affairs-primary-documents.ts";
export { COLONIAL_ECONOMY_UNITED_STATES_MARKET_NEGOTIATION_DOCUMENT } from "./colonial-economy-primary-documents.ts";
export { COLONIAL_ECONOMY_SEWARD_RECIPROCITY_TENSIONS_DOCUMENT } from "./colonial-economy-primary-documents.ts";
export { INDIAN_AFFAIRS_BAGOT_EDUCATION_DOCUMENT, INDIAN_AFFAIRS_CONSTITUTION_DOCUMENT, INDIAN_AFFAIRS_INDIAN_ACT_DOCUMENT, INDIAN_AFFAIRS_INDIAN_ACT_STATUS_DOCUMENT, INDIAN_AFFAIRS_PRIMARY_DOCUMENTS, INDIAN_AFFAIRS_PROTECTION_ACT_DOCUMENT, INDIAN_AFFAIRS_RESERVES_ACT_DOCUMENT, INDIAN_AFFAIRS_RESERVES_LAWS_COMBINED_DOCUMENT, INDIAN_AFFAIRS_RYERSON_INDUSTRIAL_SCHOOLS_DOCUMENT, INDIAN_AFFAIRS_SCHOOL_ENROLMENT_TABLE_DOCUMENT } from "./indian-affairs-primary-documents.ts";
export { INDIAN_AFFAIRS_CARCROSS_NIGHTLY_PRAYERS_DOCUMENT, INDIAN_AFFAIRS_ICONOGRAPHIC_DOCUMENTS, INDIAN_AFFAIRS_MANIWAKI_RESERVE_PLAN_DOCUMENT, INDIAN_AFFAIRS_QUAPPELLE_FAMILIES_DOCUMENT, INDIAN_AFFAIRS_QUEBEC_RESERVES_STATUS_MAP_DOCUMENT, INDIAN_AFFAIRS_RED_DEER_RELIGIOUS_INSTRUCTION_DOCUMENT, INDIAN_AFFAIRS_THOMAS_MOORE_AFTER_DOCUMENT, INDIAN_AFFAIRS_THOMAS_MOORE_BEFORE_DOCUMENT, INDIAN_AFFAIRS_THOMAS_MOORE_DOCUMENTS, type IndianAffairsIconographicDocumentRecord } from "./indian-affairs-iconography.ts";
export { FEDERAL_PROVINCIAL_RELATIONS_CONSTITUTION_COMPETENCIES_DOCUMENT, FEDERAL_PROVINCIAL_RELATIONS_METIS_PRIMARY_DOCUMENTS, FEDERAL_PROVINCIAL_RELATIONS_PRIMARY_DOCUMENTS, FEDERAL_PROVINCIAL_RELATIONS_RED_RIVER_DECLARATION_DOCUMENT, FEDERAL_PROVINCIAL_RELATIONS_RIEL_TRIAL_SPEECH_DOCUMENT } from "./federal-provincial-relations-primary-documents.ts";
export { ACTE_UNION_DEBT_COMPARISON_CHART, ACTE_UNION_POPULATION_COMPARISON_CHART, COLONIAL_ECONOMY_RECIPROCITY_EXPORTS_CHART } from "./historical-comparison-charts.ts";
export type { HistoricalComparisonChart, HistoricalComparisonChartItem } from "./historical-comparison-charts.ts";
export type {
  ApprovedQuestion,
  ApprovedQuestionFormat,
  ApprovedQuestionScope,
  ChronologicalMarker,
  EditorialStatus,
  ExpectedLearningObjective,
  HistoricalRecord,
  HistoricalClaim,
  HistoricalManualSection,
  HistoricalManualTable,
  HistoricalManualTableRow,
  HistoricalReferenceManual,
  HistoricalActor,
  HistoricalRelationship,
  IntellectualOperationId,
  NotionReferenceCard,
  KnowledgePrecisionCoverageStatus,
  OfficialKnowledgePrecisionCoverage,
  OfficialProgramSource,
  ReferenceCardStatus,
  ReferenceSource,
  ReferenceSourceKind,
  ReferenceValidationChecklist,
  SecondaryFourKnowledgeHeading,
  SecondaryFourPeriod,
  SecondaryFourPeriodId,
  SourcedStatement,
  SourcedMisconception,
  SourcedVocabularyEntry,
} from "./types.ts";
export type { PedagogicalReferencePilot } from "./pilots.ts";
export type { ReferenceCardValidationErrors } from "./reference-card.ts";
export type { HistoricalRecordValidationErrors } from "./historical-record.ts";
export type { IntellectualOperationDefinition, IntellectualOperationSource, IntellectualOperationSourceId } from "./intellectual-operations.ts";
export type { ApprovedQuestionValidationErrors } from "./approved-question.ts";
export type { ClaimReviewDecision, HistoricalRecordCorrectionRequest, HistoricalRecordReviewCategory, HistoricalRecordReviewDraft, HistoricalRecordReviewItem } from "./review.ts";
export type { HistoricalDocumentAdaptationDraft, HistoricalDocumentCandidate, HistoricalDocumentKind, HistoricalDocumentPresentationKind, HistoricalDocumentPresentationStatus, HistoricalDocumentPresentationValidationErrors, HistoricalDocumentRecord, HistoricalDocumentStatus, HistoricalDocumentStudentPresentation, HistoricalDocumentValidationErrors } from "./historical-document.ts";
