import type { HistoricalDocumentRecord } from "./historical-document.ts";

export type IndianAffairsIconographicDocumentRecord = HistoricalDocumentRecord & {
  imageCredit: string;
  studentVisibleCaption?: string;
  studentVisibleCaptionNote?: string;
};

const common = {
  schemaVersion: 1 as const,
  status: "ready-for-review" as const,
  kind: "image" as const,
  periodIds: ["1840-1896"] as const,
  knowledgeHeadingIds: ["affaires-indiennes"] as const,
  operationIds: ["changes_and_continuities", "relationships_between_facts", "establish_facts"] as const,
  historicalDate: "photographies publiées en 1897",
  creator: "Ministère des Affaires indiennes du Canada; photographe non identifié",
  holdingInstitution: "Bibliothèque et Archives Canada",
  sourceUrl: "https://recherche-collection-search.bac-lac.gc.ca/fra/accueil/notice?idnumber=31&app=indaffannrep&ecopy=1896r05a",
  rightsStatement: "Publication officielle canadienne de 1897 appartenant au domaine public. Le fichier local est un recadrage de la reproduction numérique diffusée par Bibliothèque et Archives Canada. Conserver le nom de Thomas Moore, le titre du rapport et la référence archivistique.",
  studentVisibleCaption: undefined,
  studentVisibleCaptionNote: undefined,
  version: "1.0",
  approvedAt: null,
};

export const INDIAN_AFFAIRS_THOMAS_MOORE_BEFORE_DOCUMENT = {
  ...common,
  id: "AI-I-001",
  title: "Thomas Moore à son admission à l’école industrielle de Regina",
  sourceLocator: "Dominion of Canada, Annual Report of the Department of Indian Affairs for the Year Ended 30th June 1896, planche préliminaire, p. PDF 5; Bibliothèque et Archives Canada, C-022474.",
  assetUrl: "/historical-documents/affaires-indiennes-thomas-moore-avant.jpg",
  imageCredit: "Thomas Moore à son admission · Rapport annuel des Affaires indiennes, publié en 1897 · BAC, C-022474",
  transcription: "THOMAS MOORE, AS HE APPEARED WHEN ADMITTED TO THE REGINA INDIAN INDUSTRIAL SCHOOL.",
  accessibleDescription: "Portrait en pied mis en scène de Thomas Moore avant sa scolarisation à l’école industrielle de Regina. Il porte les cheveux longs en tresses et des vêtements ornés; il est placé devant une fourrure et tient un petit pistolet.",
  historicalContext: "Le ministère des Affaires indiennes publie ce portrait avec un second portrait de Thomas Moore après sa scolarisation. Ce montage avant-après sert à promouvoir l’école industrielle de Regina comme un instrument de transformation des enfants autochtones selon les normes eurocanadiennes. Il s’inscrit dans la politique d’assimilation culturelle administrée par le gouvernement fédéral.",
  observationGuide: ["Décrire les cheveux, les vêtements, la posture et les accessoires sans les hiérarchiser.", "Repérer les éléments de décor qui donnent à la photographie un caractère mis en scène.", "Comparer la légende officielle et la composition avec celles du portrait pris après la scolarisation."],
  interpretationCautions: ["La photographie est mise en scène et publiée par le gouvernement dans un but promotionnel; elle n’est pas un portrait neutre de Thomas Moore.", "Les éléments visibles ne permettent pas de connaître le consentement, les sentiments ni l’expérience vécue de Thomas Moore.", "Éviter de reprendre les oppositions coloniales entre apparence « sauvage » et apparence « civilisée » que le montage cherchait à suggérer."],
  pedagogicalUses: ["Comparer les changements visibles entre les deux portraits.", "Déterminer le point de vue et l’intention du gouvernement qui publie les images.", "Relier les écoles industrielles à l’objectif d’assimilation culturelle des politiques fédérales."],
} as const satisfies IndianAffairsIconographicDocumentRecord;

export const INDIAN_AFFAIRS_THOMAS_MOORE_AFTER_DOCUMENT = {
  ...common,
  id: "AI-I-002",
  title: "Thomas Moore après sa scolarisation à l’école industrielle de Regina",
  sourceLocator: "Dominion of Canada, Annual Report of the Department of Indian Affairs for the Year Ended 30th June 1896, planche préliminaire, p. PDF 6; Bibliothèque et Archives Canada, NL-022474.",
  assetUrl: "/historical-documents/affaires-indiennes-thomas-moore-apres.jpg",
  imageCredit: "Thomas Moore après sa scolarisation · Rapport annuel des Affaires indiennes, publié en 1897 · BAC, NL-022474",
  transcription: "THOMAS MOORE, AFTER TUITION AT THE REGINA INDIAN INDUSTRIAL SCHOOL.",
  accessibleDescription: "Portrait en pied mis en scène de Thomas Moore après sa scolarisation à l’école industrielle de Regina. Ses cheveux sont courts; il porte un costume, des bottes et un chapeau, dans un décor de studio comprenant une plante et une balustrade.",
  historicalContext: "Publié immédiatement après le portrait d’admission, ce second portrait présente comme un résultat souhaitable l’adoption d’une apparence eurocanadienne. L’ensemble documente surtout le message que le ministère des Affaires indiennes voulait communiquer au public : l’école devait remplacer des marqueurs culturels autochtones par les normes vestimentaires et sociales de la société dominante.",
  observationGuide: ["Décrire les cheveux, les vêtements, la posture et le décor.", "Relever les éléments choisis pour produire une image de respectabilité selon les normes eurocanadiennes de l’époque.", "Comparer les deux légendes et expliquer le récit de transformation qu’elles construisent."],
  interpretationCautions: ["Le portrait est une construction visuelle gouvernementale destinée à démontrer l’efficacité de l’école.", "Un changement d’apparence imposé ou préparé pour la photographie ne prouve ni une adhésion volontaire ni l’abandon de l’identité culturelle.", "Les deux images ne documentent pas à elles seules les conditions de vie, les violences ni les conséquences durables du système des écoles industrielles et des pensionnats."],
  pedagogicalUses: ["Interpréter le montage avant-après comme une source sur l’objectif d’assimilation.", "Distinguer une observation visuelle d’une inférence sur l’expérience personnelle de Thomas Moore.", "Exercer la critique d’une source photographique produite par une institution gouvernementale."],
} as const satisfies IndianAffairsIconographicDocumentRecord;

export const INDIAN_AFFAIRS_THOMAS_MOORE_DOCUMENTS = [
  INDIAN_AFFAIRS_THOMAS_MOORE_BEFORE_DOCUMENT,
  INDIAN_AFFAIRS_THOMAS_MOORE_AFTER_DOCUMENT,
] as const satisfies readonly IndianAffairsIconographicDocumentRecord[];

export const INDIAN_AFFAIRS_QUAPPELLE_FAMILIES_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-I-003",
  title: "Des familles autochtones campent près de l’école industrielle de Qu’Appelle",
  kind: "image",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["causes_and_consequences", "establish_facts", "relationships_between_facts"],
  historicalDate: "vers mai 1885",
  creator: "Oliver B. Buell",
  holdingInstitution: "Bibliothèque et Archives Canada",
  sourceUrl: "https://recherche-collection-search.bac-lac.gc.ca/fra/Accueil/Notice?app=FonAndCol&idnumber=3624992",
  sourceLocator: "Bibliothèque et Archives Canada, R11996-5-X-F, boîte 55063.1, p. 8 (bas), négatif de copie PA-182246; annotation au crayon : « Annual Report p. 131 - 1895 ».",
  assetUrl: "/historical-documents/affaires-indiennes-quappelle-ecole-familles.jpg",
  imageCredit: "Oliver B. Buell, vers mai 1885 · Bibliothèque et Archives Canada, PA-182246",
  rightsStatement: "UTILISATION AUTORISÉE : Bibliothèque et Archives Canada indique que le droit d’auteur est expiré et qu’aucune restriction d’utilisation ne s’applique. Mention exigée : O.B. Buell / Bibliothèque et Archives Canada / PA-182246.",
  transcription: "L’école industrielle indienne de Fort Qu’Appelle avec des tentes, des charrettes de la rivière Rouge et des tipis à l’extérieur de la clôture, Lebret, Saskatchewan, vers mai 1885.",
  studentVisibleCaption: "Pensionnat indien de Qu’Appelle, en Saskatchewan, vers 1885. Des parents autochtones campent à l’extérieur des barrières de l’école pour rendre visite à leurs enfants.",
  studentVisibleCaptionNote: undefined,
  accessibleDescription: "Vue éloignée de l’école industrielle de Fort Qu’Appelle, à Lebret, avec plusieurs bâtiments derrière une clôture. Au premier plan, des tentes, des tipis et des charrettes forment un campement à l’extérieur de l’enceinte.",
  historicalContext: "Ouverte en 1884 et financée par le gouvernement fédéral, l’école industrielle de Qu’Appelle sépare les enfants de leur milieu familial pendant leur scolarisation. La photographie montre un campement autochtone hors de l’enceinte. La notice de Bibliothèque et Archives Canada indique que les tipis appartiennent probablement à des familles des Premières Nations et que les tentes et charrettes peuvent appartenir à des familles métisses. Une annotation relie la photographie à la page 131 du rapport annuel de 1895 des Affaires indiennes.",
  observationGuide: ["Repérer l’école, la clôture, le chemin et le campement.", "Comparer la position des bâtiments scolaires à celle des tentes, des tipis et des charrettes.", "Distinguer ce que la photographie montre directement des renseignements ajoutés par la légende."],
  interpretationCautions: ["La photographie montre un campement hors de la clôture, mais elle ne permet pas, à elle seule, d’identifier toutes les personnes ni leurs intentions.", "La notice archivistique précise seulement que les tentes et les charrettes peuvent appartenir à des familles métisses et que les tipis appartiennent probablement à des familles des Premières Nations.", "Employer la photographie pour analyser la séparation physique et institutionnelle sans prétendre qu’elle résume l’expérience de toutes les familles ou de tous les pensionnats."],
  pedagogicalUses: ["Expliquer une conséquence du système des pensionnats sur les liens familiaux.", "Mettre en relation la séparation spatiale, le contrôle institutionnel et l’objectif d’assimilation.", "Distinguer une observation, une information de légende et une inférence historique."],
  version: "1.0",
  approvedAt: null,
} as const satisfies IndianAffairsIconographicDocumentRecord;

export const INDIAN_AFFAIRS_RED_DEER_RELIGIOUS_INSTRUCTION_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-I-004",
  title: "Un cours d’écriture sous l’inscription « Looking Unto Jesus »",
  kind: "image",
  status: "ready-for-review",
  periodIds: ["1896-1945"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["causes_and_consequences", "relationships_between_facts", "changes_and_continuities"],
  historicalDate: "entre 1914 et 1919",
  creator: "Photographe non identifié",
  holdingInstitution: "Archives de l’Église Unie du Canada, Université Victoria",
  sourceUrl: "https://catalogue.unitedchurcharchives.ca/a-class-in-penmanship-red-deer-industrial-institute",
  sourceLocator: "The United Church of Canada Archives, From Mission to Partnership Photograph collection, 1993.049P/850; [A class in penmanship, Red Deer Industrial Institute], entre 1914 et 1919.",
  assetUrl: "/historical-documents/affaires-indiennes-red-deer-looking-unto-jesus.jpg",
  imageCredit: "Cours d’écriture, Red Deer Industrial Institute, 1914-1919 · Archives de l’Église Unie du Canada, 1993.049P/850",
  rightsStatement: "Reproduction de consultation tirée d’une source diffusée par la Fondation autochtone de l’espoir et conservée aux Archives de l’Église Unie du Canada. The Children Remembered réserve ses images à la recherche et à l’étude privée; confirmer l’autorisation auprès des Archives avant toute diffusion publique hors de l’environnement pédagogique local.",
  transcription: "LOOKING UNTO JESUS — HEB. 12:2",
  studentVisibleCaption: "« Looking Unto Jesus » (« Les yeux fixés sur Jésus »). Cours d’écriture à l’école industrielle indienne de Red Deer, en Alberta, entre 1914 et 1919. Archives de l’Église Unie du Canada, 1993.049P/850.",
  studentVisibleCaptionNote: undefined,
  accessibleDescription: "Photographie en noir et blanc montrant des filles et des garçons autochtones, vus de dos, qui tracent des caractères au tableau. Une grande inscription religieuse en anglais, « Looking Unto Jesus », domine la classe.",
  historicalContext: "L’école industrielle de Red Deer est construite par le ministère des Affaires indiennes et administrée par la société missionnaire de l’Église méthodiste de 1893 à 1919. La photographie associe visuellement un exercice scolaire ordinaire à un message chrétien placé au-dessus du tableau.",
  observationGuide: ["Repérer l’inscription religieuse au-dessus du tableau.", "Observer l’activité d’écriture et la disposition séparée des filles et des garçons.", "Mettre en relation l’apprentissage scolaire et l’enseignement chrétien dans un même espace."],
  interpretationCautions: ["La photographie documente l’organisation de la classe, mais ne révèle pas ce que les élèves pensent ou ressentent.", "La date exacte demeure incertaine à l’intérieur de l’intervalle 1914-1919.", "La copie de bonne qualité provient d’une reproduction publique; les droits de l’image archivistique doivent être confirmés avant une diffusion externe."],
  pedagogicalUses: ["Expliquer comment la christianisation est intégrée à l’enseignement scolaire.", "Relier l’éducation religieuse à l’objectif d’assimilation culturelle.", "Distinguer les pratiques institutionnelles visibles des réactions individuelles non documentées."],
  version: "1.0",
  approvedAt: null,
} as const satisfies IndianAffairsIconographicDocumentRecord;

export const INDIAN_AFFAIRS_CARCROSS_NIGHTLY_PRAYERS_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-I-005",
  title: "Des garçons récitent leurs prières du soir dans le dortoir",
  kind: "image",
  status: "ready-for-review",
  periodIds: ["1945-1980"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["causes_and_consequences", "relationships_between_facts", "changes_and_continuities"],
  historicalDate: "décembre 1964",
  creator: "Photographe non identifié",
  holdingInstitution: "Archives du Yukon",
  sourceUrl: "https://archives-ftp.gov.yk.ca/findingaids/caption_lists/caption_list_86_61.pdf",
  sourceLocator: "Archives du Yukon, fonds de l’Église anglicane, diocèse du Yukon, 86/61, no 678, T-127; Carcross Indian Residential School, décembre 1964.",
  assetUrl: "/historical-documents/affaires-indiennes-carcross-prieres-dortoir.jpg",
  imageCredit: "Garçons récitant leurs prières au dortoir, décembre 1964 · Archives du Yukon, 86/61, no 678, T-127",
  rightsStatement: "Reproduction de consultation diffusée par la Fondation autochtone de l’espoir; l’original est conservé aux Archives du Yukon. Les conditions de réutilisation de la photographie ne sont pas précisées dans la liste descriptive. Confirmer l’autorisation auprès des Archives du Yukon avant toute diffusion publique hors de l’environnement pédagogique local.",
  transcription: "Boys saying their prayers, kneeling on their beds in the dormitory. Carcross Indian Residential School, Carcross, Yukon. « Dec 64 » developed into border of original photograph.",
  studentVisibleCaption: "Garçons autochtones récitant leurs prières du soir dans le dortoir du pensionnat indien de Carcross, au Yukon, en décembre 1964. Archives du Yukon, fonds du diocèse anglican du Yukon, 86/61, no 678, T-127.",
  studentVisibleCaptionNote: undefined,
  accessibleDescription: "Photographie en noir et blanc d’un dortoir où plusieurs garçons autochtones sont agenouillés sur ou près de leur lit, tournés vers le mur. Une femme adulte se tient debout à droite, les mains jointes.",
  historicalContext: "La liste descriptive des Archives du Yukon identifie la scène au pensionnat indien de Carcross en décembre 1964. La prière chrétienne fait partie de la routine du dortoir, en dehors des heures de classe, ce qui montre que l’encadrement religieux s’étend à la vie quotidienne des enfants.",
  observationGuide: ["Repérer la posture des garçons et celle de l’adulte.", "Identifier le dortoir comme un espace de vie autant que de pratique religieuse.", "Comparer cette routine du soir à l’inscription chrétienne visible dans la classe de Red Deer."],
  interpretationCautions: ["La photographie montre une pratique encadrée, mais ne permet pas de connaître les convictions ou les réactions personnelles des garçons.", "La publication de l’exposition indiquait autrefois une date inconnue; la liste descriptive officielle précise maintenant décembre 1964.", "Les élèves ne doivent pas conclure que les traditions spirituelles autochtones ont disparu : la source documente la volonté institutionnelle de christianisation."],
  pedagogicalUses: ["Établir la présence de la religion chrétienne dans la routine quotidienne des pensionnats.", "Comparer une pratique religieuse au dortoir et un message religieux en classe.", "Expliquer une conséquence culturelle durable des politiques d’assimilation."],
  version: "1.0",
  approvedAt: null,
} as const satisfies IndianAffairsIconographicDocumentRecord;

export const INDIAN_AFFAIRS_MANIWAKI_RESERVE_PLAN_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-I-006",
  title: "Plan de lotissement de la réserve de Maniwaki, aujourd’hui Kitigan Zibi",
  kind: "map",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["relationships_between_facts", "time_and_space", "establish_facts"],
  historicalDate: "1891",
  creator: "Ministère des Affaires indiennes du Canada; cartographe non identifié",
  holdingInstitution: "Bibliothèque et Archives Canada",
  sourceUrl: "https://recherche-collection-search.bac-lac.gc.ca/fra/accueil/notice?app=fonandcol&ecopy=e011205348&idnumber=2148194",
  sourceLocator: "Plan of Maniwaki Indian Reserve showing the subdivision, 1891, RG10M 76703/9, boîte 2000001837, pièce 34, NMC12897, copie numérique e011205348.",
  assetUrl: "/historical-documents/affaires-indiennes-maniwaki-plan-1891.jpg",
  imageCredit: "Ministère des Affaires indiennes, 1891 · Bibliothèque et Archives Canada, NMC12897, e011205348",
  rightsStatement: "Reproduction de consultation d’une carte gouvernementale de 1891 conservée par Bibliothèque et Archives Canada. Crédit demandé : Bibliothèque et Archives Canada / fonds du ministère des Affaires indiennes et du Nord canadien / e011205348. Confirmer les modalités de réutilisation avant toute diffusion externe.",
  transcription: "COPY OF PLAN OF MANIWAKI INDIAN RESERVE — Shewing the Subdivision. […] The area of each regular Lot is 60.00 acres.",
  studentVisibleCaption: "Plan de lotissement de la réserve de Maniwaki, aujourd’hui Kitigan Zibi, en 1891. Les limites, les rangs, les lots et leur superficie y sont tracés par l’administration fédérale.",
  studentVisibleCaptionNote: undefined,
  accessibleDescription: "Plan cadastral ancien sur papier beige. La réserve longe les rivières Gatineau et Désert. Elle est divisée en rangs et en nombreux lots rectangulaires, dont plusieurs portent une superficie en acres.",
  historicalContext: "La réserve de la rivière Désert est attribuée dans le contexte de la répartition de 1853 découlant de la loi de 1851. Réalisé en 1891 par l’administration des Affaires indiennes, ce plan ultérieur montre concrètement la délimitation, l’arpentage et la subdivision du territoire de Maniwaki, aujourd’hui Kitigan Zibi.",
  observationGuide: ["Repérer les rivières qui bordent le territoire représenté.", "Observer les limites, les rangs, les numéros de lots et les superficies inscrites.", "Mettre ces éléments en relation avec les verbes décrire, arpenter, mettre à part et gérer dans les extraits législatifs."],
  interpretationCautions: ["Le plan date de 1891 : il illustre un résultat durable du processus foncier, mais ne montre pas la réserve exactement au moment de la loi de 1851.", "Un plan cadastral représente des limites administratives; il ne montre pas l’ensemble du territoire ancestral ni tous les usages du territoire par les Anishinabeg.", "Le nom Maniwaki employé dans la source est historique; la communauté porte aujourd’hui le nom de Kitigan Zibi Anishinabeg."],
  pedagogicalUses: ["Visualiser l’arpentage et la subdivision d’une réserve.", "Mettre en relation un plan cadastral et les lois de 1850-1851.", "Distinguer une réserve administrative d’un territoire ancestral."],
  version: "1.0",
  approvedAt: null,
} as const satisfies IndianAffairsIconographicDocumentRecord;

export const INDIAN_AFFAIRS_QUEBEC_RESERVES_STATUS_MAP_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-I-007",
  title: "Réserves et établissements autochtones au Québec selon leur statut foncier",
  kind: "map",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["changes_and_continuities", "time_and_space", "relationships_between_facts"],
  historicalDate: "synthèse publiée en 1984 à partir de données historiques",
  creator: "Commission d’étude sur l’intégrité du territoire du Québec; reproduction par Affaires indiennes et du Nord Canada",
  holdingInstitution: "Publications du gouvernement du Canada",
  sourceUrl: "https://publications.gc.ca/site/eng/9.839194/publication.html",
  sourceLocator: "Larry Villeneuve et Daniel Francis, The Historical Background of Indian Reserves and Settlements in the Province of Quebec, 1984, carte 2, « Réserves et établissements indiens (répartition et statut) », p. 20.",
  assetUrl: "/historical-documents/affaires-indiennes-quebec-reserves-statut-1851.png",
  imageCredit: "Commission d’étude sur l’intégrité du territoire du Québec · reproduction gouvernementale, 1984 · légende agrandie ajoutée pour la lecture pédagogique",
  rightsStatement: "Carte reproduite dans une publication officielle du gouvernement du Canada. Utilisation pédagogique locale avec référence complète; vérifier les modalités avant toute diffusion externe.",
  transcription: "RÉSERVES ET ÉTABLISSEMENTS INDIENS (RÉPARTITION ET STATUT). La légende distingue notamment les réserves existant avant 1851 et celles créées en vertu de la loi de 1851.",
  studentVisibleCaption: undefined,
  studentVisibleCaptionNote: undefined,
  accessibleDescription: "Carte en noir et blanc du Québec localisant des réserves et des établissements autochtones. Des symboles distincts identifient plusieurs statuts fonciers. Une légende agrandie au bas de l’image met en évidence le symbole des réserves créées en vertu de la loi de 1851.",
  historicalContext: "La loi de 1851 autorise la mise à part de terres au Bas-Canada pour différentes Premières Nations. Cette carte rétrospective permet de distinguer plusieurs établissements plus anciens des réserves créées ou encadrées par les mesures gouvernementales du XIXe siècle.",
  observationGuide: ["Repérer dans la légende les deux symboles demandés.", "Comparer leur répartition dans le sud et le centre du Québec.", "Ne pas interpréter les espaces sans symbole comme des territoires sans présence autochtone."],
  interpretationCautions: ["La carte est une synthèse publiée en 1984, et non une carte dessinée en 1851.", "Elle rassemble aussi des statuts postérieurs; la question demande seulement d’utiliser les deux catégories indiquées.", "Les réserves administratives ne correspondent pas à l’ensemble des territoires ancestraux ou fréquentés par les Nations."],
  pedagogicalUses: ["Distinguer les réserves antérieures à la loi de 1851 de celles qui découlent de cette loi.", "Observer le développement d’un système foncier administré par l’État colonial.", "Préparer une comparaison avec une carte canadienne de 1891."],
  version: "1.0",
  approvedAt: null,
} as const satisfies IndianAffairsIconographicDocumentRecord;

export const INDIAN_AFFAIRS_ICONOGRAPHIC_DOCUMENTS = [
  ...INDIAN_AFFAIRS_THOMAS_MOORE_DOCUMENTS,
  INDIAN_AFFAIRS_QUAPPELLE_FAMILIES_DOCUMENT,
  INDIAN_AFFAIRS_RED_DEER_RELIGIOUS_INSTRUCTION_DOCUMENT,
  INDIAN_AFFAIRS_CARCROSS_NIGHTLY_PRAYERS_DOCUMENT,
  INDIAN_AFFAIRS_MANIWAKI_RESERVE_PLAN_DOCUMENT,
  INDIAN_AFFAIRS_QUEBEC_RESERVES_STATUS_MAP_DOCUMENT,
] as const satisfies readonly IndianAffairsIconographicDocumentRecord[];
