import type { HistoricalDocumentRecord } from "./historical-document.ts";

export const INDIAN_AFFAIRS_PROTECTION_ACT_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-001",
  title: "La loi de 1850 confie les terres à un commissaire pour les protéger",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["establish_facts", "relationships_between_facts", "changes_and_continuities"],
  historicalDate: "10 août 1850",
  creator: "Parlement de la Province du Canada",
  holdingInstitution: "Publications du gouvernement du Canada",
  sourceUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-1-1978-eng.pdf",
  sourceLocator: "S.C. 1850, 13 & 14 Vict., c. 42, préambule et article 1; reproduction dans Consolidation of Indian Legislation, vol. I.",
  assetUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-1-1978-eng.pdf",
  rightsStatement: "Texte législatif de 1850 dans le domaine public; traduction-adaptation française préparée par Socrato à partir de la reproduction officielle. Les coupures sont signalées par […].",
  transcription: "Il est nécessaire de mieux prévenir les empiètements et les dommages causés aux terres mises à part pour l’usage des tribus et groupes indiens du Bas-Canada, et de défendre leurs droits et privilèges. […] Le gouverneur peut nommer un commissaire des terres indiennes pour le Bas-Canada. […] Les terres ou propriétés mises à part pour l’usage d’une tribu ou d’un groupe lui sont confiées en fiducie. […] Le commissaire peut exercer et défendre les droits associés à ces terres et propriétés.",
  accessibleDescription: "Extrait adapté de la loi de 1850 qui annonce la protection des terres des Premières Nations du Bas-Canada et en confie la gestion à un commissaire.",
  historicalContext: "Les empiètements liés à la colonisation poussent la Province du Canada à mieux encadrer certaines terres déjà occupées ou mises à part. La mesure protège contre des intrusions, mais place aussi la gestion juridique entre les mains d’un représentant colonial.",
  observationGuide: ["Identifier le problème nommé dans le préambule.", "Repérer la personne chargée de la gestion des terres.", "Distinguer l’usage des terres par les communautés de leur gestion juridique par le commissaire."],
  interpretationCautions: ["Il s’agit d’une traduction-adaptation d’un texte anglais; les […] signalent les coupures.", "Le langage de protection ne signifie pas que les Premières Nations contrôlent elles-mêmes l’administration prévue par la loi.", "La terminologie historique de la loi est reproduite uniquement pour analyser le document."],
  pedagogicalUses: ["Établir le double rôle de protection et de contrôle de la loi de 1850.", "Comparer cette mesure à la loi de mise à part des terres de 1851."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_RESERVES_ACT_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-002",
  title: "La loi de 1851 autorise la mise à part de 230 000 acres",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["establish_facts", "time_and_space", "causes_and_consequences"],
  historicalDate: "30 août 1851",
  creator: "Parlement de la Province du Canada",
  holdingInstitution: "Publications du gouvernement du Canada",
  sourceUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-1-1978-eng.pdf",
  sourceLocator: "S.C. 1851, 14 & 15 Vict., c. 106, article 1, p. 96; reproduction dans Consolidation of Indian Legislation, vol. I.",
  assetUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-1-1978-eng.pdf",
  rightsStatement: "Texte législatif de 1851 dans le domaine public; traduction-adaptation française préparée par Socrato à partir de la reproduction officielle. Les coupures sont signalées par […].",
  transcription: "Des étendues de terre dans le Bas-Canada, ne dépassant pas au total deux cent trente mille acres, peuvent être décrites, arpentées et mises à part par le commissaire des terres de la Couronne. […] Elles sont réservées à l’usage des différentes tribus indiennes du Bas-Canada désignées par décret. […] Aucun prix ni paiement ne leur est demandé. […] Les terres sont confiées à la gestion du commissaire des terres indiennes pour le Bas-Canada.",
  accessibleDescription: "Extrait adapté de la loi de 1851 indiquant la superficie maximale, le territoire visé, les opérations d’arpentage et le mode de gestion des terres.",
  historicalContext: "Après la loi de protection de 1850, la législature autorise la création de nouvelles réserves au Bas-Canada. La répartition entre différentes Premières Nations est précisée par une liste proposée en juin 1853 et approuvée en août.",
  observationGuide: ["Relever la superficie maximale autorisée.", "Identifier le territoire colonial visé.", "Repérer les verbes qui décrivent le processus foncier."],
  interpretationCautions: ["L’extrait est une traduction-adaptation; les […] signalent les coupures.", "Les 230 000 acres représentent un maximum total, non une superficie accordée à chaque communauté.", "Cette loi ne crée pas toutes les réserves du Québec et ne décrit pas tout le territoire ancestral des Nations."],
  pedagogicalUses: ["Établir les faits essentiels de la création des réserves au Bas-Canada.", "Situer la mesure entre la loi de protection de 1850 et la répartition de 1853."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_CONSTITUTION_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-003",
  title: "La Constitution attribue les affaires indiennes au Parlement fédéral",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes", "acte-de-l-amerique-du-nord-britannique", "relations-federales-provinciales"],
  operationIds: ["establish_facts", "changes_and_continuities", "relationships_between_facts"],
  historicalDate: "1er juillet 1867",
  creator: "Parlement du Royaume-Uni",
  holdingInstitution: "Ministère de la Justice du Canada",
  sourceUrl: "https://laws-lois.justice.gc.ca/fra/const/section-91.html",
  sourceLocator: "Loi constitutionnelle de 1867, article 91, paragraphe 24.",
  assetUrl: "https://laws-lois.justice.gc.ca/fra/const/section-91.html",
  rightsStatement: "Texte constitutionnel officiel diffusé par le ministère de la Justice du Canada; court extrait reproduit à des fins pédagogiques avec sa référence complète.",
  transcription: "L’autorité législative exclusive du Parlement du Canada s’étend aux matières suivantes : […] 24. Les Indiens et les terres réservées pour les Indiens.",
  accessibleDescription: "Court extrait de l’article 91 de la Loi constitutionnelle de 1867 attribuant une compétence exclusive au Parlement du Canada.",
  historicalContext: "La Confédération partage les compétences entre le Parlement fédéral et les législatures provinciales. Le paragraphe 91(24) fait des affaires indiennes et des terres réservées une responsabilité fédérale.",
  observationGuide: ["Identifier l’ordre de gouvernement nommé.", "Relever le caractère exclusif de la compétence.", "Nommer les deux objets réunis au paragraphe 24."],
  interpretationCautions: ["Le document emploie la terminologie constitutionnelle historique, qui doit être contextualisée.", "Le transfert de compétence n’efface ni les droits autochtones ni les relations territoriales des Nations.", "L’article attribue une compétence législative; il ne décrit pas à lui seul toutes les politiques appliquées."],
  pedagogicalUses: ["Relier la Confédération à la fédéralisation des affaires indiennes.", "Préparer l’étude de la Loi sur les Indiens de 1876."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_INDIAN_ACT_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-004",
  title: "La Loi sur les Indiens place les terres et les biens sous administration fédérale",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["establish_facts", "relationships_between_facts", "changes_and_continuities"],
  historicalDate: "12 avril 1876",
  creator: "Parlement du Canada",
  holdingInstitution: "Publications du gouvernement du Canada",
  sourceUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-2-1978-eng.pdf",
  sourceLocator: "S.C. 1876, 39 Vict., c. 18, articles 1 et 2, p. 43-44; reproduction dans Consolidation of Indian Legislation, vol. II.",
  assetUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-2-1978-eng.pdf",
  rightsStatement: "Texte législatif de 1876 dans le domaine public; traduction-adaptation française préparée par Socrato à partir de la reproduction officielle. Les coupures sont signalées par […].",
  transcription: "La présente loi sera connue sous le nom de Loi sur les Indiens de 1876. […] Le ministre de l’Intérieur sera surintendant général des Affaires indiennes. Dans la surveillance de ces affaires ainsi que dans le contrôle et la gestion des réserves, des terres, des sommes et des biens des Indiens au Canada, il sera régi par les dispositions de la présente loi.",
  accessibleDescription: "Traduction-adaptation des articles 1 et 2 de la Loi sur les Indiens de 1876, qui désignent le responsable fédéral et les biens placés sous son administration.",
  historicalContext: "Neuf ans après la Confédération, le Parlement fédéral rassemble et modifie plusieurs lois antérieures. La loi définit les catégories juridiques et accroît l’intervention administrative dans les communautés des Premières Nations.",
  observationGuide: ["Repérer le responsable politique de l’administration.", "Énumérer les objets placés sous son contrôle.", "Distinguer les terres et réserves des sommes et des autres biens."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée; les […] signalent les coupures.", "Le langage de gestion et de tutelle exprime le point de vue de l’État, non celui des Premières Nations.", "La loi consolide des mesures antérieures; elle ne constitue pas le début des politiques coloniales."],
  pedagogicalUses: ["Caractériser les domaines d’intervention de la Loi sur les Indiens.", "Comparer la centralisation de 1876 aux lois foncières de 1850 et 1851."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_INDIAN_ACT_STATUS_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-007",
  title: "La Loi sur les Indiens définit juridiquement le statut et l’appartenance",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["establish_facts", "causes_and_consequences", "relationships_between_facts"],
  historicalDate: "12 avril 1876",
  creator: "Parlement du Canada",
  holdingInstitution: "Bibliothèque et Archives Canada",
  sourceUrl: "https://epe.lac-bac.gc.ca/100/205/301/ic/cdc/aboriginaldocs/stat/html/1876ap12.htm?nodisclaimer=1",
  sourceLocator: "S.C. 1876, 39 Vict., c. 18, article 3, paragraphe 3 et alinéa c; version numérisée par Bibliothèque et Archives Canada.",
  assetUrl: "https://epe.lac-bac.gc.ca/100/205/301/ic/cdc/aboriginaldocs/stat/html/1876ap12.htm?nodisclaimer=1",
  rightsStatement: "Texte législatif de 1876 dans le domaine public; traduction-adaptation française préparée par Socrato à partir de la version anglaise numérisée par Bibliothèque et Archives Canada. Les coupures sont signalées par […].",
  transcription: "Le terme « Indien » signifie : premièrement, toute personne de sexe masculin et de sang indien réputée appartenir à une bande; deuxièmement, tout enfant d’une telle personne; troisièmement, toute femme qui est ou a été légalement mariée à une telle personne. […] Toute femme indienne qui épouse une personne autre qu’un Indien ou qu’un Indien non visé par un traité cesse d’être considérée comme Indienne au sens de la présente loi, sous réserve de certaines dispositions financières.",
  accessibleDescription: "Traduction-adaptation d’un extrait de l’article 3 de la Loi sur les Indiens de 1876, qui définit le statut juridique selon la filiation et le mariage.",
  historicalContext: "La loi fédérale ne se limite pas à administrer des terres et des biens : elle impose aussi des catégories juridiques déterminant qui est reconnu comme membre des Premières Nations au sens de la loi. Les règles de 1876 sont discriminatoires envers les femmes, dont le statut dépend notamment de celui de leur mari.",
  observationGuide: ["Repérer les trois catégories de personnes incluses dans la définition.", "Identifier le rôle attribué au père ou au mari.", "Relever l’effet juridique du mariage mentionné dans l’extrait."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée; les […] signalent les coupures.", "La terminologie historique et les catégories raciales de la loi sont reproduites uniquement pour analyser le contrôle exercé par l’État.", "Le statut défini par la loi fédérale ne détermine ni l’identité personnelle ni l’appartenance reconnue par les Nations elles-mêmes."],
  pedagogicalUses: ["Établir que le gouvernement fédéral intervient dans la définition du statut juridique et de l’appartenance.", "Mettre en évidence la discrimination fondée sur le sexe dans la loi de 1876.", "Comparer le contrôle des terres et des biens au contrôle exercé sur le statut."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_RESERVES_LAWS_COMBINED_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-008",
  title: "Les lois de 1850 et de 1851 encadrent les terres des Premières Nations",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["relationships_between_facts", "changes_and_continuities", "establish_facts"],
  historicalDate: "10 août 1850 et 30 août 1851",
  creator: "Parlement de la Province du Canada",
  holdingInstitution: "Publications du gouvernement du Canada",
  sourceUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-1-1978-eng.pdf",
  sourceLocator: "S.C. 1850, 13 & 14 Vict., c. 42, préambule et article 1; S.C. 1851, 14 & 15 Vict., c. 106, article 1; reproductions dans Consolidation of Indian Legislation, vol. I.",
  assetUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-158-1-1978-eng.pdf",
  rightsStatement: "Textes législatifs de 1850 et de 1851 dans le domaine public; traduction-adaptation française préparée par Socrato à partir de la reproduction officielle. Les coupures sont signalées par […].",
  transcription: "LOI DE 1850 — Les terres ou propriétés mises à part pour l’usage d’une tribu ou d’un groupe sont confiées au commissaire des terres indiennes pour le Bas-Canada. Le commissaire peut exercer et défendre les droits associés à ces terres et propriétés. […] LOI DE 1851 — Des étendues de terre dans le Bas-Canada, ne dépassant pas au total 230 000 acres, peuvent être décrites, arpentées et mises à part par le commissaire des terres de la Couronne. Elles sont réservées à l’usage des différentes tribus désignées par décret et sont confiées à la gestion du commissaire des terres indiennes.",
  accessibleDescription: "Deux courts extraits adaptés des lois de 1850 et de 1851 présentant la gestion, l’arpentage et la mise à part de terres au Bas-Canada.",
  historicalContext: "La colonisation accroît les empiètements sur les terres des Premières Nations. La loi de 1850 met en place une protection juridique administrée par un commissaire colonial. Celle de 1851 autorise ensuite l’arpentage et la mise à part d’un maximum total de 230 000 acres au Bas-Canada.",
  observationGuide: ["Dans l’extrait de 1850, repérer le responsable de la gestion des terres.", "Dans l’extrait de 1851, relever les trois opérations appliquées aux terres.", "Distinguer l’usage des terres par les communautés de leur administration par des représentants de l’État."],
  interpretationCautions: ["Les extraits sont des traductions-adaptations abrégées; les […] signalent les coupures.", "La protection contre les empiètements s’accompagne d’un contrôle administratif accru par l’État colonial.", "Les 230 000 acres constituent un maximum total et la loi de 1851 n’est pas à l’origine de toutes les réserves du Québec."],
  pedagogicalUses: ["Comparer les fonctions des lois de 1850 et de 1851.", "Expliquer le passage de la protection juridique à l’arpentage et à la mise à part des terres.", "Mettre en relation un texte législatif et un plan cadastral ultérieur."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_BAGOT_EDUCATION_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-005",
  title: "La commission Bagot recommande des écoles industrielles et l’appui des organisations religieuses",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["causes_and_consequences", "causal_connections", "relationships_between_facts"],
  historicalDate: "22 janvier 1844",
  creator: "Rawson W. Rawson, John Davidson et William Hepburn, commissaires nommés par Charles Bagot",
  holdingInstitution: "Centre national pour la vérité et la réconciliation",
  sourceUrl: "https://nctr.ca/wp-content/uploads/2021/01/Bagot-report.pdf",
  sourceLocator: "Report on the Affairs of the Indians in Canada, rapport daté du 22 janvier 1844 et déposé devant l’Assemblée législative le 20 mars 1845, Appendix EEE, recommandations générales sur l’éducation.",
  assetUrl: "https://nctr.ca/wp-content/uploads/2021/01/Bagot-report.pdf",
  rightsStatement: "Rapport gouvernemental de 1844 dans le domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Les efforts du gouvernement devraient être dirigés vers l’éducation des jeunes et vers le détachement des adultes de leurs habitudes de dépendance. […] Des écoles devraient être établies, et des missionnaires et des enseignants soutenus dans chaque établissement; leur efficacité devrait être surveillée avec soin. […] En plus des écoles communes, autant d’écoles de travail manuel ou d’écoles industrielles que les fonds le permettent devraient être créées. […] La coopération des différentes organisations religieuses devrait être sollicitée pour mettre en œuvre les mesures du gouvernement.",
  accessibleDescription: "Extrait adapté des recommandations générales de la commission Bagot sur l’éducation, les écoles industrielles et la participation d’organisations religieuses.",
  historicalContext: "La commission créée par le gouverneur général Charles Bagot enquête sur l’administration coloniale des affaires indiennes. Son rapport recommande d’utiliser l’éducation et la formation au travail comme instruments de transformation culturelle, tout en confiant une partie de la mise en œuvre à des organisations religieuses.",
  observationGuide: ["Identifier le groupe principalement visé par l’éducation.", "Nommer le type d’école recommandé en plus des écoles communes.", "Repérer les partenaires que le gouvernement veut faire participer."],
  interpretationCautions: ["L’extrait est une traduction-adaptation de recommandations rédigées en anglais; les […] signalent les coupures.", "Le vocabulaire du rapport exprime une vision coloniale et paternaliste, non le point de vue des Premières Nations.", "La recommandation de 1844 ne crée pas immédiatement un réseau national et obligatoire de pensionnats; elle contribue toutefois au développement ultérieur d’une politique scolaire assimilationniste."],
  pedagogicalUses: ["Identifier une recommandation éducative de la commission Bagot.", "Relier la commission aux missions chrétiennes et au développement des écoles industrielles.", "Préparer une chaîne causale avec le rapport de Ryerson de 1847."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_RYERSON_INDUSTRIAL_SCHOOLS_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-006",
  title: "Ryerson précise le modèle des écoles industrielles demandé par les Affaires indiennes",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["causes_and_consequences", "causal_connections", "changes_and_continuities"],
  historicalDate: "26 mai 1847",
  creator: "Egerton Ryerson, surintendant en chef de l’Éducation du Canada-Ouest",
  holdingInstitution: "Bibliothèque et Archives Canada · reproduction du ministère des Affaires indiennes",
  sourceUrl: "https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?app=FonAndCol&idnumber=2069786",
  sourceLocator: "Report of Dr. Ryerson on Industrial Schools, 26 mai 1847, reproduit dans Statistics Respecting Indian Schools, Ottawa, Government Printing Bureau, 1898, p. 73-77.",
  assetUrl: "https://commons.wikimedia.org/wiki/File:Egerton_Ryerson_on_Residential_Schools.pdf",
  rightsStatement: "Lettre officielle de 1847 et reproduction gouvernementale de 1898 dans le domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Ces établissements devraient être appelés écoles industrielles : ce sont des écoles d’apprentissage et de religion, où le travail constitue un élément essentiel. […] L’enseignement devrait offrir une éducation anglaise élémentaire adaptée aux futurs agriculteurs et ouvriers, ainsi qu’une formation en agriculture, en jardinage et dans certains travaux mécaniques. […] Il est donc nécessaire que les élèves résident ensemble, ce qui permet aussi d’organiser leur éducation domestique et leur instruction religieuse. […] L’organisation religieuse responsable de la majorité des Autochtones d’un établissement pourrait diriger localement l’école, tandis que le gouvernement fixerait les principes, inspecterait et accorderait l’aide financière.",
  accessibleDescription: "Extrait adapté du rapport demandé à Egerton Ryerson par le ministère des Affaires indiennes en 1847, précisant l’enseignement, la résidence des élèves et la gestion religieuse des écoles industrielles.",
  historicalContext: "Trois ans après les recommandations de la commission Bagot, le ministère des Affaires indiennes demande à Ryerson de proposer une méthode d’organisation des écoles industrielles. Sa réponse détaille un modèle résidentiel, anglophone, agricole et chrétien administré avec des organisations religieuses.",
  observationGuide: ["Repérer la langue et les types d’apprentissage privilégiés.", "Identifier la disposition concernant le lieu de vie des élèves.", "Distinguer les rôles envisagés pour le gouvernement et les organisations religieuses."],
  interpretationCautions: ["L’extrait est une traduction-adaptation abrégée; les […] signalent les coupures.", "Le texte présente le projet de Ryerson et non l’expérience vécue par les enfants ou les familles des Premières Nations.", "Ce modèle de 1847 ne doit pas être confondu avec le réseau fédéral plus tardif ni avec les mesures de fréquentation obligatoire adoptées ultérieurement."],
  pedagogicalUses: ["Déterminer une conséquence institutionnelle des recommandations de la commission Bagot.", "Comparer une recommandation générale à un projet de mise en œuvre plus précis.", "Expliquer le développement d’une politique éducative assimilationniste avant la Confédération."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_SCHOOL_ENROLMENT_TABLE_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-S-001",
  title: "Élèves inscrits dans les écoles relevant des Affaires indiennes",
  kind: "statistics",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["changes_and_continuities", "establish_facts"],
  historicalDate: "1890 à 1897",
  creator: "Ministère des Affaires indiennes du Canada",
  holdingInstitution: "Publications du gouvernement du Canada",
  sourceUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R1-90-1890-eng.pdf",
  sourceLocator: "Rapports annuels de 1890, 1891 et 1897, sections Education : inscriptions aux écoles de jour, industrielles et pensionnats.",
  assetUrl: "https://publications.gc.ca/site/eng/9.846380/publication.html",
  rightsStatement: "Données historiques officielles du domaine public; tableau comparatif préparé par Socrato.",
  transcription: "1890 : 6 671 élèves inscrits. 1891 : 7 554 élèves inscrits. 1897 : 9 628 élèves inscrits.",
  accessibleDescription: "Tableau à deux colonnes montrant une hausse du nombre total d’élèves autochtones inscrits dans les écoles déclarées par les Affaires indiennes : 6 671 en 1890, 7 554 en 1891 et 9 628 en 1897.",
  historicalContext: "Les écoles de mission existaient avant la Loi sur les Indiens de 1876. Dans les années 1880 et 1890, le gouvernement fédéral finance et encadre un réseau croissant d’écoles de jour, de pensionnats et d’écoles industrielles destiné aux enfants des Premières Nations.",
  observationGuide: ["Comparer les valeurs de 1890 et de 1897.", "Calculer ou décrire l’ampleur de la hausse.", "Appuyer le constat sur au moins deux données."],
  interpretationCautions: ["Les chiffres sont les totaux déclarés par l’administration fédérale et peuvent omettre certaines écoles non aidées ou non rapportées.", "Le tableau mesure les inscriptions, non les ouvertures d’écoles ni la fréquentation quotidienne.", "La hausse des inscriptions ne renseigne pas à elle seule sur le consentement des familles ni sur les conditions vécues par les élèves."],
  pedagogicalUses: ["Déterminer un changement dans les inscriptions scolaires entre 1890 et 1897.", "Relier l’expansion du réseau scolaire à l’intervention fédérale dans les affaires indiennes."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_FEDERAL_TUTELAGE_CITIZENSHIP_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-009",
  title: "Le gouvernement fédéral présente la tutelle et l’accès à la citoyenneté",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["differences_and_similarities", "establish_facts"],
  historicalDate: "1876 (publié en 1877)",
  creator: "Ministère de l’Intérieur du Canada, citant David Laird",
  holdingInstitution: "Publications du gouvernement du Canada",
  sourceUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R1-88-1876-eng.pdf",
  sourceLocator: "Annual Report of the Department of the Interior for the Year Ended 30th June, 1876, section « The Indian Act, 1876 », p. 5-6 de la partie consacrée aux Affaires indiennes.",
  assetUrl: "https://publications.gc.ca/collections/collection_2017/aanc-inac/R1-88-1876-eng.pdf",
  rightsStatement: "Rapport gouvernemental du domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. La coupure est signalée par […].",
  transcription: "Notre législation concernant les Autochtones repose généralement sur le principe qu’ils doivent être maintenus dans une condition de tutelle et traités comme des pupilles ou des enfants de l’État. […] Il est de notre devoir, par l’éducation et par tous les autres moyens, de les préparer à une civilisation plus élevée, en les encourageant à assumer les privilèges et les responsabilités de la pleine citoyenneté.",
  accessibleDescription: "Extrait d’un rapport fédéral décrivant la tutelle imposée aux Premières Nations et un projet d’éducation menant à l’émancipation et à la citoyenneté selon les normes de l’État.",
  historicalContext: "Le rapport présente la Loi sur les Indiens de 1876 et reprend les propos de David Laird sur les clauses d’émancipation. Le gouvernement affirme vouloir faire sortir les Premières Nations de la tutelle, mais par une politique d’éducation et d’intégration à la citoyenneté canadienne définie par l’État.",
  observationGuide: ["Repérer la relation de tutelle décrite par le gouvernement.", "Identifier les moyens proposés pour transformer cette relation.", "Préciser la forme de citoyenneté recherchée par l’État."],
  interpretationCautions: ["Le vocabulaire du rapport est colonial et paternaliste; il ne représente pas le point de vue des Premières Nations.", "Le passage critique le maintien permanent de la tutelle, mais propose d’en sortir par l’éducation et l’émancipation selon les normes gouvernementales.", "L’émancipation prévue par la loi pouvait faire perdre le statut juridique et certains droits collectifs; la pleine citoyenneté évoquée n’équivaut donc pas simplement à l’égalité sans condition."],
  pedagogicalUses: ["Déterminer le point de vue fédéral sur la tutelle, l’éducation et l’émancipation.", "Comparer une politique gouvernementale de 1876 à une critique autochtone ultérieure de la Loi sur les Indiens."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_ONONDAGA_CHIEFS_ALLIANCE_PETITION_DOCUMENT = {
  schemaVersion: 1,
  id: "AI-T-010",
  title: "Des chefs onondagas revendiquent une relation d’alliance avec la Couronne",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["affaires-indiennes"],
  operationIds: ["differences_and_similarities", "changes_and_continuities", "establish_facts"],
  historicalDate: "17 août 1876",
  creator: "33 chefs onondagas des Six Nations de la rivière Grand",
  holdingInstitution: "Bibliothèque et Archives Canada · reproduit par la Commission royale sur les peuples autochtones",
  sourceUrl: "https://publications.gc.ca/collections/collection_2014/bcp-pco/Z1-1991-1-1-fra.pdf",
  sourceLocator: "BAC, RG10, série Rouge, vol. 1995, dossier 6897, microfilm C-11130, pétition au surintendant général David Laird, 17 août 1876; reproduite dans le Rapport de la Commission royale sur les peuples autochtones, vol. 1.",
  assetUrl: "https://publications.gc.ca/collections/collection_2014/bcp-pco/Z1-1991-1-1-fra.pdf",
  rightsStatement: "Pétition de 1876 appartenant au domaine public; traduction-adaptation française et montage d’extraits préparés par Socrato. Les coupures sont signalées par […].",
  transcription: "Certains disent que nous sommes des sujets du gouvernement britannique et que nous devons être contrôlés par les lois adoptées au Parlement du Dominion. Nous disons plutôt que nous ne sommes pas des sujets, mais des alliés du gouvernement britannique. […] Nous demeurerons des alliés comme l’étaient nos ancêtres. […] Ceux qui veulent être contrôlés par vos lois peuvent devenir comme votre propre peuple; quant à nous, nous suivrons nos anciennes lois et nos anciennes règles, et nous ne nous en écarterons pas.",
  accessibleDescription: "Extrait d’une pétition dans laquelle des chefs onondagas refusent d’être considérés comme des sujets sous contrôle fédéral et revendiquent une relation d’alliance ainsi que leurs propres lois.",
  historicalContext: "La pétition est adressée à David Laird quelques mois après l’adoption de la Loi sur les Indiens de 1876. Elle témoigne d’un débat au sein des Six Nations et d’une position onondaga qui fonde la relation politique sur l’alliance avec la Couronne plutôt que sur la tutelle et l’assujettissement aux lois fédérales.",
  observationGuide: ["Distinguer les mots sujets et alliés.", "Repérer la position des chefs sur les lois fédérales.", "Identifier la forme de relation politique qu’ils souhaitent préserver."],
  interpretationCautions: ["La pétition exprime la position des 33 signataires onondagas dans un débat interne; elle ne représente pas automatiquement toutes les Premières Nations ni tous les membres des Six Nations.", "Le document emploie le gouvernement britannique et le Dominion dans le cadre d’une relation historique avec la Couronne.", "L’extrait est une traduction-adaptation abrégée; les […] signalent les coupures."],
  pedagogicalUses: ["Déterminer un point de vue autochtone contemporain de la Loi sur les Indiens.", "Comparer une conception d’alliance et d’autonomie politique à la tutelle administrative revendiquée par l’État."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const INDIAN_AFFAIRS_PRIMARY_DOCUMENTS = [
  INDIAN_AFFAIRS_PROTECTION_ACT_DOCUMENT,
  INDIAN_AFFAIRS_RESERVES_ACT_DOCUMENT,
  INDIAN_AFFAIRS_CONSTITUTION_DOCUMENT,
  INDIAN_AFFAIRS_INDIAN_ACT_DOCUMENT,
  INDIAN_AFFAIRS_BAGOT_EDUCATION_DOCUMENT,
  INDIAN_AFFAIRS_RYERSON_INDUSTRIAL_SCHOOLS_DOCUMENT,
  INDIAN_AFFAIRS_INDIAN_ACT_STATUS_DOCUMENT,
  INDIAN_AFFAIRS_RESERVES_LAWS_COMBINED_DOCUMENT,
  INDIAN_AFFAIRS_SCHOOL_ENROLMENT_TABLE_DOCUMENT,
  INDIAN_AFFAIRS_FEDERAL_TUTELAGE_CITIZENSHIP_DOCUMENT,
  INDIAN_AFFAIRS_ONONDAGA_CHIEFS_ALLIANCE_PETITION_DOCUMENT,
] as const;
