import type { HistoricalDocumentRecord } from "./historical-document.ts";

export type IndustrializationIconographicDocumentRecord = HistoricalDocumentRecord & {
  imageCredit: string;
};

const common = {
  schemaVersion: 1 as const,
  status: "ready-for-review" as const,
  periodIds: ["1840-1896"] as const,
  knowledgeHeadingIds: ["premiere-phase-d-industrialisation"] as const,
  version: "1.0",
  approvedAt: null,
};

export const INDUSTRIALIZATION_ICONOGRAPHIC_DOCUMENTS = [
  {
    ...common,
    id: "IND-I-001",
    title: "Le canal Lachine",
    kind: "image",
    operationIds: ["establish_facts", "time_and_space", "relationships_between_facts"] as const,
    historicalDate: "vers 1850",
    creator: "James Duncan",
    holdingInstitution: "Musée McCord Stewart",
    sourceUrl: "https://collections.musee-mccord-stewart.ca/fr/objects/60332/le-canal-lachine",
    sourceLocator: "Musée McCord Stewart, M984.273; aquarelle et mine de plomb sur papier, 19,4 × 29,3 cm. Fichier numérique diffusé sur Wikimedia Commons.",
    assetUrl: "/historical-documents/industrialisation-canal-lachine.jpg",
    imageCredit: "James Duncan, vers 1850 · Musée McCord Stewart, M984.273",
    rightsStatement: "UTILISATION AUTORISÉE : l’œuvre et sa reproduction fidèle sont indiquées comme appartenant au domaine public dans la notice Wikimedia Commons. Conserver l’auteur, la date, l’institution et le numéro d’acquisition.",
    transcription: "Le canal Lachine",
    accessibleDescription: "Aquarelle montrant le canal Lachine bordé de bâtiments, de chemins et de végétation, avec des embarcations circulant sur la voie d’eau.",
    historicalContext: "Élargi dans les années 1840, le canal Lachine facilite le transport des matières premières et des produits vers Montréal. La force hydraulique et l’accès au transport favorisent aussi l’établissement d’industries le long du canal.",
    observationGuide: ["Repérer la voie d’eau, les embarcations et les bâtiments.", "Identifier les aménagements qui facilitent la circulation des marchandises.", "Relier le canal à la concentration des activités industrielles autour de Montréal."],
    interpretationCautions: ["L’aquarelle offre un point de vue composé par l’artiste et ne constitue pas un relevé technique.", "Elle montre un lieu précis; elle ne représente pas à elle seule l’ensemble du réseau de canaux."],
    pedagogicalUses: ["Établir le rôle des canaux dans l’industrialisation.", "Mettre en relation transport, énergie hydraulique et localisation des manufactures.", "Comparer une voie navigable à une infrastructure ferroviaire."],
  },
  {
    ...common,
    id: "IND-M-001",
    title: "Les rapides de Lachine et les chenaux vers Montréal",
    kind: "map",
    operationIds: ["establish_facts", "time_and_space", "relationships_between_facts"] as const,
    historicalDate: "décembre 1850",
    creator: "Thomas C. Keefer (nom associé à la notice)",
    holdingInstitution: "Bibliothèque et Archives Canada",
    sourceUrl: "https://recherche-collection-search.bac-lac.gc.ca/fra/Accueil/Notice?IdNumber=4130243&app=fonandcol&ecopy=n0010957",
    sourceLocator: "Bibliothèque et Archives Canada, pièce 4130243, indice H1/312/1850, copie numérique n0010957; carte manuscrite coloriée.",
    assetUrl: "/historical-documents/industrialisation-carte-rapides-lachine.jpg",
    imageCredit: "Carte manuscrite, 1850 · Bibliothèque et Archives Canada, pièce 4130243",
    rightsStatement: "UTILISATION AUTORISÉE : la notice de Bibliothèque et Archives Canada indique que le droit d’auteur est expiré. Le fichier local est une copie redimensionnée de l’objet numérique officiel.",
    transcription: "A sketch of Lachine Rapids and channels to Montreal, Dec. 1850",
    accessibleDescription: "Reproduction en tons de gris d’une carte manuscrite représentant les rapides de Lachine, les îles et les chenaux navigables menant vers Montréal en 1850.",
    historicalContext: "Les rapides de Lachine constituent un obstacle à la navigation sur le Saint-Laurent. Les cartes des chenaux et l’aménagement du canal témoignent des efforts pour assurer une circulation plus régulière des marchandises entre l’intérieur du continent et Montréal.",
    observationGuide: ["Localiser les rapides, les îles et les chenaux.", "Repérer les contraintes naturelles imposées à la navigation.", "Expliquer pourquoi un canal améliore le transport commercial."],
    interpretationCautions: ["La carte est rédigée en anglais et emploie les conventions cartographiques de 1850; l’objet original est décrit comme colorié, mais sa reproduction numérique est en tons de gris.", "Le nom de Thomas C. Keefer est associé à la notice, sans qu’une attribution complète de la carte soit assurée."],
    pedagogicalUses: ["Situer un obstacle naturel au commerce.", "Relier l’aménagement du territoire au développement économique.", "Comparer une carte technique à une représentation artistique du canal."],
  },
  {
    ...common,
    id: "IND-I-002",
    title: "Le pont Victoria en construction",
    kind: "image",
    operationIds: ["establish_facts", "time_and_space", "causal_connections"] as const,
    historicalDate: "vers 1858-1860",
    creator: "William Notman",
    holdingInstitution: "Bibliothèque et Archives Canada, collection Thomas Seaton Scott",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Victoria_Bridge_under_construction.jpg",
    sourceLocator: "Bibliothèque et Archives Canada, PA-181435; reproduction numérique diffusée sur Wikimedia Commons.",
    assetUrl: "/historical-documents/industrialisation-pont-victoria-construction.jpg",
    imageCredit: "William Notman, vers 1858-1860 · Bibliothèque et Archives Canada, PA-181435",
    rightsStatement: "UTILISATION AUTORISÉE : la photographie de William Notman est identifiée comme appartenant au domaine public et libre de restrictions connues dans la notice Wikimedia Commons.",
    transcription: "Le pont Victoria en construction",
    accessibleDescription: "Photographie montrant le pont Victoria en construction au-dessus du fleuve Saint-Laurent, avec ses piliers massifs et des installations de chantier.",
    historicalContext: "Construit pour le chemin de fer du Grand Tronc et achevé en 1859, le pont Victoria relie Montréal à la rive sud et aux réseaux ferroviaires donnant accès aux marchés nord-américains.",
    observationGuide: ["Repérer les piliers, le chantier et le fleuve.", "Identifier l’ampleur des travaux et les matériaux mobilisés.", "Relier le pont au développement du réseau ferroviaire."],
    interpretationCautions: ["La photographie montre une étape du chantier, non l’ouvrage achevé.", "L’image renseigne sur l’infrastructure, mais pas directement sur les conditions de travail de tous les ouvriers."],
    pedagogicalUses: ["Établir un fait sur l’expansion ferroviaire.", "Expliquer comment une infrastructure réduit un obstacle au transport.", "Relier les investissements ferroviaires à l’accès aux marchés."],
  },
  {
    ...common,
    id: "IND-I-003",
    title: "Le Grand Tronc et le pont Victoria projeté",
    kind: "image",
    operationIds: ["establish_facts", "relationships_between_facts", "causal_connections"] as const,
    historicalDate: "octobre 1854",
    creator: "S. Russell; lithographie de Day & Son",
    holdingInstitution: "Musée McCord Stewart",
    sourceUrl: "https://collections.musee-mccord-stewart.ca/en/objects/3669/compagnie-de-chemin-de-fer-du-grand-tronc-du-canada-pont-vi",
    sourceLocator: "Musée McCord Stewart, M930.40.1.49; lithographie rehaussée à l’aquarelle, publiée à Londres en octobre 1854. Fichier diffusé sur Wikimedia Commons.",
    assetUrl: "/historical-documents/industrialisation-grand-tronc-pont-victoria.jpg",
    imageCredit: "S. Russell et Day & Son, 1854 · Musée McCord Stewart, M930.40.1.49",
    rightsStatement: "UTILISATION AUTORISÉE : l’œuvre et sa reproduction fidèle sont indiquées comme appartenant au domaine public dans la notice Wikimedia Commons. Conserver le titre, l’artiste, la date et l’institution.",
    transcription: "Grand Trunk Railway of Canada — Victoria Bridge — connecting by railway Canada with the United States of America",
    accessibleDescription: "Lithographie panoramique montrant le projet du pont Victoria franchissant le Saint-Laurent, avec un train, des navires, Montréal et des armoiries symbolisant les liens entre le Canada et les États-Unis.",
    historicalContext: "Publiée au début des travaux, cette image présente le pont Victoria comme une grande réalisation du Grand Tronc capable de relier par rail le Canada aux États-Unis. Elle témoigne à la fois d’un projet d’infrastructure et de sa promotion auprès du public et des investisseurs.",
    observationGuide: ["Repérer le train, les navires, le pont et la ville.", "Lire l’inscription reliant le Canada aux États-Unis.", "Distinguer la représentation promotionnelle du chantier réel."],
    interpretationCautions: ["L’image représente un projet et adopte un point de vue promotionnel.", "Elle exagère la clarté et l’harmonie du paysage pour valoriser l’investissement ferroviaire."],
    pedagogicalUses: ["Mettre en relation chemin de fer, pont et marchés continentaux.", "Comparer un projet promotionnel à une photographie du chantier.", "Expliquer le rôle du capital et des grands travaux dans l’industrialisation."],
  },
] as const satisfies readonly IndustrializationIconographicDocumentRecord[];
