import type { ApprovedQuestion } from "./types.ts";
import { ACTE_UNION_HISTORICAL_RECORD } from "./records/acte-union.ts";
import { ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM, ACTE_UNION_STUDENT_TIMELINE } from "./responsible-government-iconography.ts";
import { ACTE_UNION_DEBT_COMPARISON_CHART, ACTE_UNION_POPULATION_COMPARISON_CHART } from "./historical-comparison-charts.ts";
import { ACTE_UNION_DOCUMENT_SOURCE_CATALOG } from "./acte-union-document-source-catalog.ts";
import { ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT, ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT, ACTE_UNION_BERMUDA_EXILE_DOCUMENT, ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT, ACTE_UNION_EXECUTIVE_COUNCIL_DOCUMENT, ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT, ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT, ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT, ACTE_UNION_MAP_ADAPTATION_DRAFT, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT, ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT, ACTE_UNION_RUSSELL_POINT_OF_VIEW_DOCUMENT, ACTE_UNION_SPECIAL_COUNCIL_RESOLUTIONS_DOCUMENT, PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT, PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT } from "./historical-document-needs.ts";
import { ACTE_UNION_DURHAM_ANGLICIZATION_PRESENTATION, ACTE_UNION_DURHAM_CONTINUITIES_PRESENTATION, ACTE_UNION_DURHAM_DOCUMENT, ACTE_UNION_DURHAM_FINANCES_PRESENTATION, ACTE_UNION_DURHAM_RESPONSIBLE_GOVERNMENT_PRESENTATION, ACTE_UNION_DURHAM_UNION_PRESENTATION } from "./historical-document-presentations.ts";

const PILOT_SOURCE_IDS = ["lower-canada-92-resolutions-1834-primary", "uk-russell-resolutions-1837-primary"] as const;
const pilotSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => PILOT_SOURCE_IDS.includes(id as typeof PILOT_SOURCE_IDS[number]));
const officialActSource = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "union-act-1840-official");
const durhamSource = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "durham-report-1839");
const sydenhamSource = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "dbc-sydenham");
const representationSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "union-act-1840-official" || id === "anq-carte-electorale-union");
const provinceNamesSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "union-act-1840-official" || id === "anq-canada-est-ouest");
const responsibleGovernmentSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "union-act-1840-official" || id === "anq-gouvernement-responsable");
const unionDebtSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "union-act-1840-official" || id === "anq-liste-civile");
const lafontaineOppositionSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "dbc-lafontaine" || id === "union-act-1840-official" || id === "anq-carte-electorale-union");
const unionChronologySources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "union-act-1840-official" || id === "anq-chronology-1839-1841");
const russellLafontaineSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "anq-chronology-1839-1841" || id === "dbc-lafontaine");
const durhamActSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "durham-report-1839" || id === "union-act-1840-official");
const durhamActOppositionSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "durham-report-1839" || id === "union-act-1840-official" || id === "dbc-lafontaine");
const unionSolutionInjusticeSources = ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "durham-report-1839" || id === "anq-special-council-1838-1841" || id === "dbc-lafontaine");
const debtStructureSourceIds = [`document-source:${ACTE_UNION_DEBT_COMPARISON_CHART.id}`, `document-source:${ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id}`];
const debtStructureSources = ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => debtStructureSourceIds.includes(id));
const mapActSources = [...officialActSource, ...ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => id === `document-source:${ACTE_UNION_MAP_ADAPTATION_DRAFT.id}`)];
const wyldMapSources = ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => id === `document-source:${ACTE_UNION_MAP_ADAPTATION_DRAFT.id}`);
const rebellionConsequenceDocumentIds = [ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT.id, ACTE_UNION_BERMUDA_EXILE_DOCUMENT.id, ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT.id];
const rebellionConsequenceSources = ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => rebellionConsequenceDocumentIds.some((documentId) => id === `document-source:${documentId}`));
const imprisonmentDeportationDocumentIds = [ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT.id, ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT.id];
const imprisonmentDeportationSources = ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => imprisonmentDeportationDocumentIds.some((documentId) => id === `document-source:${documentId}`));
const causesConsequencesDevelopmentDocumentIds = [PATRIOTES_NINETY_TWO_RESOLUTIONS_DOCUMENT.id, PATRIOTES_RUSSELL_RESOLUTIONS_DOCUMENT.id, ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT.id, ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT.id];
const causesConsequencesDevelopmentSources = ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => causesConsequencesDevelopmentDocumentIds.some((documentId) => id === `document-source:${documentId}`));
const coalitionShortAnswerDocumentIds = [ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id, ACTE_UNION_HINCKS_LAFONTAINE_ALLIANCE_DOCUMENT.id];
const coalitionShortAnswerSources = ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => coalitionShortAnswerDocumentIds.some((documentId) => id === `document-source:${documentId}`));
const languageArticleSources = [...officialActSource, ...ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => id === `document-source:${ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.id}`)];
const consolidatedRevenueFundSources = ACTE_UNION_DOCUMENT_SOURCE_CATALOG.filter(({ id }) => id === `document-source:${ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.id}`);
const timelineSources = ACTE_UNION_STUDENT_TIMELINE.entries.map((entry, index) => ({
  id: `acte-union-timeline-source-${index + 1}`,
  kind: index === 0 ? "museum-or-archive" as const : index === 2 ? "government" as const : "other" as const,
  title: entry.title,
  publisher: index === 0 ? "Bibliothèque et Archives Canada" : index === 2 ? "PrimaryDocuments.ca" : "Wikimedia Commons",
  url: entry.sourceUrl,
  locator: entry.credit,
  rightsNote: "Document ancien du domaine public ou texte officiel; conserver le crédit et le lien de la notice.",
  verificationStatus: "verified" as const,
}));

export const ACTE_UNION_CAUSAL_PILOT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:001",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide des documents sur les 92 Résolutions et les résolutions Russell, explique pourquoi la réponse britannique contribue au déclenchement des Rébellions de 1837-1838.",
  instruction: "Appuie ta réponse sur une revendication des 92 Résolutions, sur la réponse formulée dans les résolutions Russell et sur l’indice de radicalisation présenté dans La Minerve.",
  expectedAnswer: "Les Patriotes réclament notamment un Conseil législatif électif, un exécutif responsable et un contrôle réel des revenus publics par l’Assemblée. Les résolutions Russell refusent les principales réformes institutionnelles et permettent au gouverneur d’utiliser certains revenus sans le consentement de l’Assemblée. Cette réponse ferme la voie aux réformes parlementaires réclamées et accentue le mécontentement. L’extrait de La Minerve montre que, devant une situation jugée désespérante, certains envisagent désormais une rupture avec l’Angleterre et l’indépendance. La réponse britannique contribue donc à la radicalisation qui mène vers la rébellion, sans constituer à elle seule l’unique cause des Rébellions.",
  historicalDocumentIds: ["PAT-T-002", "PAT-T-003", "PAT-T-006"],
  commonErrors: ["Présenter les résolutions Russell comme l’unique cause des Rébellions.", "Confondre les 92 Résolutions avec les résolutions Russell.", "Affirmer que les revendications patriotes ont été accordées."],
  distractors: [],
  operationId: "causal_connections",
  sourceIds: [...PILOT_SOURCE_IDS],
  sourceCatalog: pilotSources,
  rationale: "La question vérifie si l’élève peut relier des revendications politiques, une réponse britannique documentée et la radicalisation de 1837 dans une chaîne causale nuancée.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_TIMELINE_PROTOTYPE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:timeline-001",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "interactive-timeline",
  prompt: "Replace les cinq événements dans l’ordre chronologique en associant chaque image et sa description à la bonne date.",
  instruction: "Sélectionne une carte, puis choisis sa date. Sur ordinateur, tu peux aussi la faire glisser. Vérifie tes réponses lorsque les cinq cartes sont placées.",
  expectedAnswer: "1837-1838 — Rébellions dans les deux Canadas; 1839 — Publication du rapport Durham; 1840 — Adoption de l’Acte d’Union; 1841 — Naissance de la Province du Canada; 1848 — Avènement du gouvernement responsable.",
  historicalDocumentIds: [ACTE_UNION_STUDENT_TIMELINE.id],
  commonErrors: ["Confondre l’adoption de l’Acte d’Union en 1840 avec son entrée en vigueur en 1841.", "Placer le rapport Durham après l’Acte d’Union.", "Placer le gouvernement responsable au moment de la création de la Province du Canada."],
  distractors: [],
  operationId: "time_and_space",
  sourceIds: timelineSources.map(({ id }) => id),
  sourceCatalog: timelineSources,
  rationale: "La manipulation oblige l’élève à distinguer cinq repères rapprochés et à relier chaque représentation iconographique à l’événement correspondant.",
  timelineInteraction: {
    documentId: ACTE_UNION_STUDENT_TIMELINE.id,
    dates: ACTE_UNION_STUDENT_TIMELINE.entries.map(({ date }) => date),
    entries: ACTE_UNION_STUDENT_TIMELINE.entries.map((entry, index) => ({ id: `timeline-entry-${index + 1}`, date: entry.date, title: entry.title, description: entry.description, imageUrl: entry.imageUrl, imageAlt: entry.imageAlt, credit: entry.credit })),
  },
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_TIMELINE_CAUSAL_DEVELOPMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:development-001",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "development-150",
  prompt: "À l’aide de la ligne du temps, explique comment les Rébellions de 1837-1838 entraînent une succession de transformations politiques qui mène à l’obtention du gouvernement responsable en 1848.",
  instruction: "Rédige une réponse d’environ 150 mots. Établis un lien entre chacune des cinq étapes : les Rébellions, le rapport Durham, l’adoption de l’Acte d’Union, la création de la Province du Canada et l’avènement du gouvernement responsable.",
  expectedAnswer: "Les Rébellions de 1837-1838 révèlent l’ampleur de la crise politique dans les colonies et poussent le gouvernement britannique à enquêter sur ses causes. Dans son rapport publié en 1839, lord Durham recommande notamment l’union du Haut et du Bas-Canada ainsi que l’instauration d’un gouvernement responsable pour les affaires coloniales. Le Parlement britannique adopte ensuite l’Acte d’Union en 1840. Son entrée en vigueur, en 1841, crée la Province du Canada, mais ne rend pas immédiatement l’exécutif responsable devant l’Assemblée. Sous ce nouveau régime, les réformistes de La Fontaine et de Baldwin développent une alliance capable d’obtenir l’appui d’une majorité de députés. En 1848, le gouverneur Elgin accepte de choisir ses ministres parmi cette majorité élue. Le gouvernement responsable résulte donc d’une succession de réactions, de réformes institutionnelles et de luttes politiques; chaque étape contribue à rendre possible la suivante sans en être l’unique cause.",
  historicalDocumentIds: [ACTE_UNION_STUDENT_TIMELINE.id],
  commonErrors: ["Énumérer les événements sans expliquer les liens qui les unissent.", "Affirmer que l’Acte d’Union accorde immédiatement le gouvernement responsable.", "Présenter chaque événement comme la cause unique et directe du suivant."],
  distractors: [],
  operationId: "causal_connections",
  sourceIds: timelineSources.map(({ id }) => id),
  sourceCatalog: timelineSources,
  rationale: "La réponse développée permet de vérifier une chaîne causale nuancée reliant les cinq repères de la ligne du temps, plutôt qu’une simple récitation chronologique.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DEFINITION_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-001",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Quelle affirmation définit le mieux l’Acte d’Union de 1840?",
  instruction: "Choisis la réponse qui définit correctement la nature et l’effet principal de l’Acte d’Union.",
  expectedAnswer: "B. Une loi britannique qui réunit le Haut-Canada et le Bas-Canada pour former la Province du Canada.",
  historicalDocumentIds: [ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id],
  commonErrors: ["Confondre l’Acte d’Union avec l’obtention du gouvernement responsable.", "Confondre l’Union de 1840 avec la Confédération de 1867.", "Présenter l’Acte d’Union comme une déclaration d’indépendance patriote."],
  distractors: ["Une loi qui accorde immédiatement le gouvernement responsable aux colonies britanniques.", "Une entente qui crée la fédération canadienne et partage les pouvoirs entre les provinces.", "Une déclaration adoptée par les Patriotes pour rendre le Bas-Canada indépendant."],
  answerOptions: [
    { label: "A", text: "Une loi qui accorde immédiatement le gouvernement responsable aux colonies britanniques.", correct: false },
    { label: "B", text: "Une loi britannique qui réunit le Haut-Canada et le Bas-Canada pour former la Province du Canada.", correct: true },
    { label: "C", text: "Une entente qui crée la fédération canadienne et partage les pouvoirs entre les provinces.", correct: false },
    { label: "D", text: "Une déclaration adoptée par les Patriotes pour rendre le Bas-Canada indépendant.", correct: false },
  ],
  operationId: "establish_facts",
  sourceIds: officialActSource.map(({ id }) => id),
  sourceCatalog: officialActSource,
  rationale: "La question vérifie la définition fondamentale de l’Acte d’Union tout en distinguant trois confusions fréquentes : gouvernement responsable, Confédération et indépendance patriote.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_DEFINITION_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-002",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Quelle affirmation définit le mieux le rapport Durham?",
  instruction: "Choisis la réponse qui décrit correctement la nature, le contexte et les principales recommandations du rapport Durham.",
  expectedAnswer: "C. Un rapport d’enquête rédigé après les Rébellions qui recommande notamment l’union des deux Canadas, l’assimilation des Canadiens français et le gouvernement responsable.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_DOCUMENT.id],
  commonErrors: ["Confondre le rapport Durham avec une loi adoptée par le Parlement britannique.", "Confondre le rapport Durham avec les revendications formulées dans les 92 Résolutions.", "Présenter le rapport comme une déclaration patriote d’indépendance."],
  distractors: ["Une série de résolutions britanniques qui refuse les principales revendications de l’Assemblée du Bas-Canada et autorise le gouverneur à utiliser certains revenus publics.", "Une loi adoptée par le Parlement britannique qui réunit le Haut-Canada et le Bas-Canada dans une seule colonie dotée d’une législature commune.", "Un ensemble de revendications politiques qui réclame notamment un Conseil législatif électif et un meilleur contrôle des dépenses publiques."],
  answerOptions: [
    { label: "A", text: "Une série de résolutions britanniques qui refuse les principales revendications de l’Assemblée du Bas-Canada et autorise le gouverneur à utiliser certains revenus publics.", correct: false },
    { label: "B", text: "Une loi adoptée par le Parlement britannique qui réunit le Haut-Canada et le Bas-Canada dans une seule colonie dotée d’une législature commune.", correct: false },
    { label: "C", text: "Un rapport d’enquête rédigé après les Rébellions qui recommande notamment l’union des deux Canadas, l’assimilation des Canadiens français et le gouvernement responsable.", correct: true },
    { label: "D", text: "Un ensemble de revendications politiques qui réclame notamment un Conseil législatif électif et un meilleur contrôle des dépenses publiques.", correct: false },
  ],
  operationId: "establish_facts",
  sourceIds: durhamSource.map(({ id }) => id),
  sourceCatalog: durhamSource,
  rationale: "La question vérifie la définition du rapport Durham en distinguant un rapport d’enquête et de recommandations d’une loi, d’une revendication parlementaire ou d’une déclaration politique patriote.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_EQUAL_REPRESENTATION_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-003",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Quelle règle de représentation politique est mise en place par l’Acte d’Union dans la nouvelle Assemblée législative?",
  instruction: "Choisis la réponse qui décrit correctement la répartition initiale des députés entre les deux sections de la Province du Canada.",
  expectedAnswer: "D. Le Canada-Est et le Canada-Ouest obtiennent chacun 42 députés, malgré leur différence de population. Au moment de l’Union, la population de l’ancien Bas-Canada, devenu le Canada-Est, est estimée à environ 650 000 habitants, tandis que l’ancien Haut-Canada, devenu le Canada-Ouest, compte 455 688 habitants au recensement de 1841. Le Canada-Est, pourtant plus peuplé, ne reçoit donc pas davantage de sièges.",
  historicalDocumentIds: [],
  commonErrors: ["Croire que la représentation est proportionnelle à la population.", "Attribuer davantage de sièges au Canada-Est parce qu’il est plus peuplé.", "Confondre l’Assemblée élue avec un conseil entièrement nommé."],
  distractors: ["Le Canada-Est obtient davantage de députés parce que sa population est plus nombreuse.", "Le nombre de députés de chaque section est déterminé annuellement selon sa population.", "Le Canada-Ouest choisit tous les députés tandis que le Canada-Est conserve seulement un conseil nommé."],
  answerOptions: [
    { label: "A", text: "Le Canada-Est obtient davantage de députés parce que sa population est plus nombreuse.", correct: false },
    { label: "B", text: "Le nombre de députés de chaque section est déterminé annuellement selon sa population.", correct: false },
    { label: "C", text: "Le Canada-Ouest choisit tous les députés tandis que le Canada-Est conserve seulement un conseil nommé.", correct: false },
    { label: "D", text: "Le Canada-Est et le Canada-Ouest obtiennent le même nombre de députés, malgré leur différence de population.", correct: true },
  ],
  operationId: "establish_facts",
  sourceIds: representationSources.map(({ id }) => id),
  sourceCatalog: representationSources,
  rationale: "La question vérifie la règle des 42 sièges par section et la distingue d’une représentation proportionnelle à la population, sans imposer la consultation d’un document à l’élève.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_LANGUAGE_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-004",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Quelle mesure linguistique est imposée lors de l’entrée en vigueur de l’Acte d’Union?",
  instruction: "Choisis la réponse qui décrit correctement la règle appliquée aux documents officiels de la nouvelle législature.",
  expectedAnswer: "B. L’anglais devient la seule langue des documents officiels de la législature, même si des traductions peuvent être produites.",
  historicalDocumentIds: [],
  commonErrors: ["Croire que le français devient la seule langue de la législature.", "Attribuer immédiatement un statut officiel égal au français et à l’anglais.", "Croire que chaque section choisit séparément sa langue officielle."],
  distractors: ["Le français devient la seule langue utilisée par la nouvelle Assemblée législative.", "Le français et l’anglais obtiennent immédiatement un statut officiel parfaitement égal.", "Chaque section de la Province du Canada choisit séparément sa langue officielle."],
  answerOptions: [
    { label: "A", text: "Le français devient la seule langue utilisée par la nouvelle Assemblée législative.", correct: false },
    { label: "B", text: "L’anglais devient la seule langue des documents officiels de la législature, même si des traductions peuvent être produites.", correct: true },
    { label: "C", text: "Le français et l’anglais obtiennent immédiatement un statut officiel parfaitement égal.", correct: false },
    { label: "D", text: "Chaque section de la Province du Canada choisit séparément sa langue officielle.", correct: false },
  ],
  operationId: "establish_facts",
  sourceIds: officialActSource.map(({ id }) => id),
  sourceCatalog: officialActSource,
  rationale: "La question vérifie la disposition linguistique initiale de l’Acte d’Union et la distingue du rétablissement ultérieur de l’usage officiel du français en 1848.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_PROVINCE_SECTIONS_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:short-answer-001",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "short-answer",
  prompt: "Quel territoire politique est créé par l’entrée en vigueur de l’Acte d’Union en 1841, et quelles sont ses deux sections?",
  instruction: "Réponds en une ou deux phrases en nommant le nouveau territoire et ses deux sections.",
  expectedAnswer: "La Province du Canada est créée. Elle est composée du Canada-Est, qui correspond à l’ancien Bas-Canada, et du Canada-Ouest, qui correspond à l’ancien Haut-Canada.",
  historicalDocumentIds: [],
  commonErrors: ["Répondre Canada sans nommer la Province du Canada.", "Inverser le Canada-Est et le Canada-Ouest.", "Confondre la Province du Canada avec la fédération canadienne créée en 1867."],
  distractors: [],
  operationId: "establish_facts",
  sourceIds: provinceNamesSources.map(({ id }) => id),
  sourceCatalog: provinceNamesSources,
  rationale: "La question vérifie en une réponse brève la création de la Province du Canada et la correspondance territoriale entre les anciennes et les nouvelles appellations.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_RESPONSIBLE_GOVERNMENT_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:short-answer-002",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "short-answer",
  prompt: "L’Acte d’Union instaure-t-il immédiatement le gouvernement responsable? Justifie ta réponse en une ou deux phrases.",
  instruction: "Réponds par oui ou non, puis justifie ta réponse en précisant le rôle de l’exécutif ou la date d’obtention du gouvernement responsable.",
  expectedAnswer: "Non. L’Acte d’Union maintient un exécutif dirigé par le gouverneur et n’oblige pas les ministres à conserver la confiance de l’Assemblée élue. Le gouvernement responsable sera obtenu plus tard, en 1848.",
  historicalDocumentIds: [],
  commonErrors: ["Affirmer que l’Acte d’Union instaure immédiatement le gouvernement responsable.", "Confondre la recommandation du rapport Durham avec une disposition de l’Acte.", "Situer l’obtention du gouvernement responsable en 1841 plutôt qu’en 1848."],
  distractors: [],
  operationId: "establish_facts",
  sourceIds: responsibleGovernmentSources.map(({ id }) => id),
  sourceCatalog: responsibleGovernmentSources,
  rationale: "La question vérifie la distinction entre le régime juridique créé en 1841 et l’application du gouvernement responsable en 1848, tout en préparant la notion suivante.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_SHARED_DEBT_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:short-answer-003",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "short-answer",
  prompt: "Quelle conséquence financière l’Acte d’Union entraîne-t-il pour les dettes du Haut-Canada et du Bas-Canada?",
  instruction: "Réponds en une ou deux phrases en précisant ce que deviennent les dettes et quelle ancienne colonie est particulièrement avantagée.",
  expectedAnswer: "Les dettes des deux anciennes colonies sont réunies et deviennent à la charge de la Province du Canada. Cette mesure avantage notamment l’ancien Haut-Canada, dont la dette est alors beaucoup plus élevée.",
  historicalDocumentIds: [],
  commonErrors: ["Affirmer que les dettes demeurent entièrement séparées.", "Dire que le Bas-Canada possède la dette la plus élevée au moment de l’Union.", "Confondre la mise en commun des dettes avec leur annulation."],
  distractors: [],
  operationId: "causes_and_consequences",
  sourceIds: unionDebtSources.map(({ id }) => id),
  sourceCatalog: unionDebtSources,
  rationale: "La question vérifie une conséquence économique de l’Union et la capacité de l’élève à expliquer brièvement l’effet inégal de la mise en commun des dettes.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_LAFONTAINE_OPPOSITION_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:short-answer-004",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "short-answer",
  prompt: "Nomme deux raisons pour lesquelles Louis-Hippolyte La Fontaine s’oppose à l’Acte d’Union en 1840.",
  instruction: "Réponds en deux ou trois phrases en nommant clairement deux motifs d’opposition.",
  expectedAnswer: "Deux réponses parmi les suivantes sont acceptées : l’Union est imposée au Bas-Canada sans le consentement d’une assemblée élue; le Canada-Est est sous-représenté malgré sa population plus nombreuse; l’anglais devient la seule langue des documents officiels de la législature; les dettes des deux anciennes colonies sont mises en commun; l’Union poursuit un objectif d’assimilation des Canadiens français.",
  historicalDocumentIds: [],
  commonErrors: ["Donner une seule raison alors que la question en exige deux.", "Attribuer à La Fontaine un appui au projet d’assimilation.", "Confondre son opposition initiale à l’Union avec son action politique ultérieure à l’intérieur du nouveau régime."],
  distractors: [],
  operationId: "establish_facts",
  sourceIds: lafontaineOppositionSources.map(({ id }) => id),
  sourceCatalog: lafontaineOppositionSources,
  rationale: "La question vérifie plusieurs dimensions de l’opposition à l’Union — démocratique, représentative, linguistique, financière et nationale — tout en acceptant différentes combinaisons historiquement justes.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_1840_1841_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:short-answer-005",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "short-answer",
  prompt: "Quelle différence faut-il faire entre l’année 1840 et l’année 1841 concernant l’Acte d’Union?",
  instruction: "Réponds en une ou deux phrases en associant chaque année à l’étape correspondante.",
  expectedAnswer: "En 1840, le Parlement britannique adopte l’Acte d’Union. En 1841, la loi entre en vigueur et crée officiellement la Province du Canada.",
  historicalDocumentIds: [],
  commonErrors: ["Affirmer que la loi est adoptée et appliquée la même année.", "Inverser l’adoption de 1840 et l’entrée en vigueur de 1841.", "Associer 1841 à la création de la fédération canadienne."],
  distractors: [],
  operationId: "time_and_space",
  sourceIds: unionChronologySources.map(({ id }) => id),
  sourceCatalog: unionChronologySources,
  rationale: "La question vérifie la distinction chronologique fondamentale entre l’adoption de la loi et son entrée en vigueur.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_POLITICAL_TRANSFORMATION_DOCUMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-002",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide de l’extrait de l’Acte d’Union, explique quelle transformation politique principale cette loi apporte au Haut-Canada et au Bas-Canada.",
  instruction: "Appuie ta réponse sur la mesure annoncée dans l’extrait et nomme le nouveau territoire créé.",
  expectedAnswer: "L’Acte d’Union réunit le Haut-Canada et le Bas-Canada pour former une seule colonie, la Province du Canada. Les deux anciennes colonies partagent désormais un même gouvernement exécutif et une même législature.",
  historicalDocumentIds: [ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id],
  commonErrors: ["Répondre uniquement que le nom des colonies change.", "Confondre la Province du Canada avec la fédération créée en 1867.", "Affirmer que les deux anciennes colonies conservent des législatures entièrement séparées."],
  distractors: [],
  operationId: "establish_facts",
  sourceIds: officialActSource.map(({ id }) => id),
  sourceCatalog: officialActSource,
  rationale: "L’élève doit extraire du texte législatif la mesure centrale de l’Union et la reformuler en nommant le nouveau territoire et les institutions communes.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_RUSSELL_LAFONTAINE_COMPARISON_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-003",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide du texte de lord John Russell et de celui de Louis-Hippolyte La Fontaine, compare leur point de vue sur l’union du Haut-Canada et du Bas-Canada.",
  instruction: "Indique la position de chaque auteur et relève un argument utilisé par chacun pour justifier son point de vue.",
  expectedAnswer: "Lord John Russell est favorable à l’Union. Il affirme qu’elle permettra de donner aux deux Canadas des institutions représentatives communes et qu’elle favorisera la prospérité de la nouvelle province. Louis-Hippolyte La Fontaine s’oppose à l’Union. Il la présente comme une mesure imposée sans consentement et dénonce notamment la sous-représentation du Bas-Canada, la restriction de l’usage du français et la mise en commun des dettes.",
  historicalDocumentIds: [ACTE_UNION_RUSSELL_POINT_OF_VIEW_DOCUMENT.id, ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT.id],
  commonErrors: ["Attribuer le même point de vue aux deux auteurs.", "Nommer leur position sans relever un argument dans chaque document.", "Confondre le projet défendu par Russell avec les critiques formulées par La Fontaine."],
  distractors: [],
  operationId: "differences_and_similarities",
  sourceIds: russellLafontaineSources.map(({ id }) => id),
  sourceCatalog: russellLafontaineSources,
  rationale: "La comparaison oblige l’élève à distinguer un point de vue britannique favorable à l’Union d’un point de vue réformiste canadien-français qui en dénonce les effets politiques, linguistiques et financiers.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_ACT_COMPARISON_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-004",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide du rapport Durham et de l’extrait de l’Acte d’Union, indique une recommandation de Durham qui est appliquée par la loi et une recommandation qui ne l’est pas immédiatement.",
  instruction: "Pour chaque élément, appuie ta réponse sur une information provenant des documents.",
  expectedAnswer: "L’Acte d’Union applique la recommandation de réunir le Haut-Canada et le Bas-Canada sous une seule législature. Cependant, la loi n’instaure pas immédiatement le gouvernement responsable recommandé par Durham. Le gouverneur conserve le contrôle de l’exécutif, qui n’est pas encore obligé d’obtenir la confiance de l’Assemblée élue.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_UNION_PRESENTATION.id, ACTE_UNION_DURHAM_RESPONSIBLE_GOVERNMENT_PRESENTATION.id, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id, ACTE_UNION_EXECUTIVE_COUNCIL_DOCUMENT.id],
  commonErrors: ["Affirmer que toutes les recommandations de Durham sont intégrées immédiatement à la loi.", "Oublier de distinguer l’union législative du gouvernement responsable.", "Présenter le rapport Durham comme le texte même de l’Acte d’Union."],
  distractors: [],
  operationId: "differences_and_similarities",
  sourceIds: durhamActSources.map(({ id }) => id),
  sourceCatalog: durhamActSources,
  rationale: "L’élève doit confronter une recommandation impériale au texte législatif qui lui succède afin de distinguer ce qui est retenu de ce qui demeure absent du nouveau régime.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DEBT_STRUCTURE_RELATIONSHIP_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-005",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide du graphique de la dette et du schéma de la structure politique, explique comment l’Acte d’Union combine une représentation politique égale des deux sections avec une situation financière inégale.",
  instruction: "Relève une information précise dans chacun des deux documents, puis établis un lien entre elles.",
  expectedAnswer: "Le schéma montre que le Canada-Est et le Canada-Ouest obtiennent chacun 42 députés dans l’Assemblée législative. Les deux sections possèdent donc le même nombre de représentants. Cependant, le graphique montre que leur situation financière est très différente : la dette du Haut-Canada est d’environ 1,54 million de livres, comparativement à environ 133 000 livres pour le Bas-Canada. Comme les dettes deviennent une responsabilité commune de la Province du Canada, les deux sections participent au paiement d’obligations financières initialement très inégales.",
  historicalDocumentIds: [ACTE_UNION_DEBT_COMPARISON_CHART.id, ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id],
  commonErrors: ["Décrire un seul des deux documents.", "Confondre égalité du nombre de sièges et égalité de la dette.", "Affirmer que les dettes des deux colonies sont d’un montant comparable."],
  distractors: [],
  operationId: "relationships_between_facts",
  sourceIds: debtStructureSources.map(({ id }) => id),
  sourceCatalog: debtStructureSources,
  rationale: "L’élève doit croiser une donnée financière et une organisation institutionnelle pour distinguer l’égalité politique formelle des sections de leur inégalité financière initiale.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DEBT_OPPOSITION_CAUSAL_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-006",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide des deux documents, explique pourquoi la mise en commun des dettes peut susciter de l’opposition au Canada-Est.",
  instruction: "Utilise une donnée du graphique de la dette et un élément du schéma de la structure politique pour construire ton explication.",
  expectedAnswer: "Le graphique montre que la dette du Haut-Canada est beaucoup plus élevée que celle du Bas-Canada. La mise en commun des finances oblige donc le Canada-Est à participer au paiement d’une dette principalement contractée dans l’ancien Haut-Canada. Le schéma montre que le Canada-Est et le Canada-Ouest possèdent le même nombre de députés et que les conseils demeurent nommés. Le Canada-Est ne peut donc pas contrôler seul les décisions politiques et financières. Cette situation peut être perçue comme injuste et susciter de l’opposition.",
  historicalDocumentIds: [ACTE_UNION_DEBT_COMPARISON_CHART.id, ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id],
  commonErrors: ["Mentionner l’écart de dette sans expliquer pourquoi il provoque de l’opposition.", "Affirmer que le Canada-Est contrôle seul l’Assemblée ou les conseils.", "Présenter la mise en commun comme une annulation des dettes."],
  distractors: [],
  operationId: "causal_connections",
  sourceIds: debtStructureSources.map(({ id }) => id),
  sourceCatalog: debtStructureSources,
  rationale: "La question exige une chaîne causale reliant l’inégalité financière initiale, la représentation politique égale des sections et la perception d’injustice au Canada-Est.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_SOLUTION_INJUSTICE_DOCUMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-007",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "Explique pourquoi l’Union est présentée à la fois comme une solution politique et comme une injustice. Appuie-toi sur les documents pour justifier ta réponse.",
  instruction: "Relève dans les documents les arguments favorables à l’Union, puis une critique qui montre pourquoi elle peut être considérée comme injuste.",
  expectedAnswer: "Lord Durham présente l’union législative comme un moyen de rétablir durablement la tranquillité après les troubles du Bas-Canada. Le Conseil spécial la décrit aussi comme une nécessité urgente pour résoudre les difficultés politiques des deux colonies. À l’inverse, Louis-Hippolyte La Fontaine la dénonce comme une mesure imposée sans le consentement d’une assemblée élue du Bas-Canada et comme une injustice politique, linguistique et financière. L’Union est donc présentée comme une solution par ses promoteurs, mais comme une injustice par ceux qui contestent ses conditions et ses effets.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_UNION_PRESENTATION.id, ACTE_UNION_SPECIAL_COUNCIL_RESOLUTIONS_DOCUMENT.id, ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT.id],
  commonErrors: ["Présenter les trois documents comme s’ils défendaient le même point de vue.", "Décrire les documents sans expliquer l’opposition entre solution politique et injustice.", "Affirmer que le Conseil spécial est une assemblée élue représentant la population du Bas-Canada."],
  distractors: [],
  operationId: "differences_and_similarities",
  sourceIds: unionSolutionInjusticeSources.map(({ id }) => id),
  sourceCatalog: unionSolutionInjusticeSources,
  rationale: "La question amène l’élève à confronter deux justifications institutionnelles de l’Union à la critique de La Fontaine afin de reconnaître des points de vue opposés sur une même mesure.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_RECOMMENDATIONS_DOCUMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-008",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "Nomme deux recommandations formulées par lord Durham dans son rapport. Justifie ta réponse à l’aide des deux extraits.",
  instruction: "Nomme une recommandation différente dans chaque extrait et relève un élément du texte qui permet de la reconnaître.",
  expectedAnswer: "Lord Durham recommande d’abord de réunir le Haut-Canada et le Bas-Canada sous une seule législature. Il recommande également que les principaux responsables du gouvernement colonial soient responsables devant la législature et qu’ils possèdent sa confiance.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_UNION_PRESENTATION.id, ACTE_UNION_DURHAM_RESPONSIBLE_GOVERNMENT_PRESENTATION.id],
  commonErrors: ["Nommer deux fois la même recommandation.", "Présenter les recommandations comme si elles étaient toutes appliquées immédiatement par l’Acte d’Union.", "Donner des connaissances générales sans relever d’élément dans les deux extraits."],
  distractors: [],
  operationId: "establish_facts",
  sourceIds: durhamSource.map(({ id }) => id),
  sourceCatalog: durhamSource,
  rationale: "Les deux extraits distincts permettent à l’élève d’identifier et de justifier deux recommandations centrales du rapport Durham : l’union législative et la responsabilité ministérielle.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_ASSIMILATION_CAUSAL_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-009",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide de l’extrait sur le projet d’anglicisation, explique comment lord Durham souhaite assimiler les Canadiens français.",
  instruction: "Relève deux moyens proposés dans l’extrait, puis explique comment chacun peut favoriser l’assimilation culturelle ou politique.",
  expectedAnswer: "Durham souhaite établir au Bas-Canada une population anglaise ainsi que des lois, une langue et une législature anglaises. L’adoption de la langue et des institutions anglaises réduirait progressivement la place de la culture et des institutions canadiennes-françaises. Ces mesures participent donc à un projet d’assimilation culturelle et politique.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_ANGLICIZATION_PRESENTATION.id],
  commonErrors: ["Nommer des moyens sans expliquer leur effet sur l’assimilation.", "Présenter les jugements hiérarchisants de Durham comme des faits objectifs.", "Affirmer que l’assimilation est immédiatement et complètement réalisée en 1841."],
  distractors: [],
  operationId: "causal_connections",
  sourceIds: durhamSource.map(({ id }) => id),
  sourceCatalog: durhamSource,
  rationale: "Un seul extrait explicite permet à l’élève d’identifier deux moyens d’anglicisation et d’expliquer leur effet possible sans devoir inférer une intention absente d’un second document.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_CONTINUITY_DOCUMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-014",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide de l’extrait du rapport Durham, identifie un élément de continuité prévu après l’Union et explique pourquoi il constitue une continuité.",
  instruction: "Repère une réalité qui doit demeurer en vigueur malgré l’union politique des deux colonies.",
  expectedAnswer: "Réponse flexible : l’élève peut expliquer que les lois et les institutions des deux colonies doivent demeurer provisoirement en vigueur après l’Union, jusqu’à ce que la nouvelle législature les modifie. Il peut aussi identifier le maintien des garanties accordées à l’Église catholique au Bas-Canada. Dans les deux cas, il s’agit d’une continuité parce qu’une réalité existant avant l’Union est conservée après la création de la Province du Canada.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_CONTINUITIES_PRESENTATION.id],
  commonErrors: ["Présenter l’Union politique comme une uniformisation immédiate de toutes les lois et institutions.", "Nommer une continuité sans expliquer ce qui demeure avant et après l’Union.", "Présenter une recommandation de Durham comme une preuve suffisante de son application intégrale dans la loi."],
  distractors: [],
  operationId: "changes_and_continuities",
  sourceIds: durhamSource.map(({ id }) => id),
  sourceCatalog: durhamSource,
  rationale: "La question demande à l’élève de reconnaître qu’un changement politique majeur peut préserver certaines réalités juridiques, institutionnelles ou religieuses.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-03T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_FINANCIAL_CAUSES_CONSEQUENCES_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-015",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide de l’extrait du rapport Durham, explique une cause économique qui justifie selon lui l’Union et deux conséquences financières ou commerciales qu’il en attend.",
  instruction: "Distingue le problème économique présenté par Durham des résultats qu’il prévoit après l’Union.",
  expectedAnswer: "Selon Durham, les différends sur le partage des revenus et les difficultés financières du Haut-Canada constituent une cause économique justifiant l’Union. Parmi les conséquences attendues, l’élève peut expliquer que les revenus des deux colonies seraient mis en commun, que l’excédent du Bas-Canada contribuerait au paiement de l’intérêt de la dette du Haut-Canada, que les travaux publics comme les canaux profiteraient aux deux colonies ou que le Haut-Canada obtiendrait un accès à la mer. Deux conséquences correctement expliquées sont suffisantes.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_FINANCES_PRESENTATION.id],
  commonErrors: ["Présenter le point de vue de Durham comme une conséquence déjà réalisée au moment de la rédaction du rapport.", "Confondre la cause économique invoquée avec les conséquences prévues de l’Union.", "Affirmer que l’Union annule la dette du Haut-Canada."],
  distractors: [],
  operationId: "causes_and_consequences",
  sourceIds: durhamSource.map(({ id }) => id),
  sourceCatalog: durhamSource,
  rationale: "La question amène l’élève à organiser le raisonnement économique de Durham en distinguant le problème initial des conséquences financières et commerciales qu’il attribue à l’Union.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-03T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_WYLD_TERRITORIAL_TRANSFORMATION_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-010",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide de la carte modifiée de Wyld et de l’extrait de l’Acte d’Union, explique comment l’organisation territoriale du Haut-Canada et du Bas-Canada est transformée en 1841.",
  instruction: "Utilise les deux documents. Tu peux formuler ta réponse dans tes propres mots; nomme la nouvelle colonie et établis la correspondance entre les anciens et les nouveaux territoires.",
  expectedAnswer: "Réponse flexible : l’élève doit faire ressortir que le Haut-Canada et le Bas-Canada sont réunis dans une seule colonie, la Province du Canada, et que les deux anciens territoires deviennent respectivement le Canada-Ouest et le Canada-Est. Toute formulation équivalente et historiquement juste est acceptée. La précision selon laquelle ils demeurent deux sections territoriales sous un gouvernement commun bonifie la réponse, mais n’est pas obligatoire.",
  historicalDocumentIds: [ACTE_UNION_MAP_ADAPTATION_DRAFT.id, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id],
  commonErrors: ["Inverser le Canada-Est et le Canada-Ouest.", "Confondre la Province du Canada de 1841 avec la Confédération de 1867.", "Utiliser un seul document sans relier la carte au changement annoncé par la loi."],
  distractors: [],
  operationId: "time_and_space",
  sourceIds: mapActSources.map(({ id }) => id),
  sourceCatalog: mapActSources,
  rationale: "La question croise une représentation cartographique et un texte législatif tout en permettant plusieurs formulations exactes de la transformation territoriale.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_WYLD_TERRITORIES_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-005",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Selon la carte modifiée de Wyld, quelle affirmation décrit correctement l’organisation territoriale de la Province du Canada?",
  instruction: "Observe les territoires et leurs étiquettes sur la carte, puis choisis la bonne réponse.",
  expectedAnswer: "C. Le Canada-Est correspond à l’ancien Bas-Canada et le Canada-Ouest à l’ancien Haut-Canada.",
  historicalDocumentIds: [ACTE_UNION_MAP_ADAPTATION_DRAFT.id],
  commonErrors: ["Inverser le Canada-Est et le Canada-Ouest.", "Inclure la Terre de Rupert dans la Province du Canada.", "Inclure le Nouveau-Brunswick dans le Canada-Est."],
  distractors: ["Le Canada-Est correspond à l’ancien Haut-Canada.", "La Terre de Rupert forme une troisième section de la Province du Canada.", "Le Nouveau-Brunswick fait partie du Canada-Est."],
  answerOptions: [
    { label: "A", text: "Le Canada-Est correspond à l’ancien Haut-Canada.", correct: false },
    { label: "B", text: "La Terre de Rupert forme une troisième section de la Province du Canada.", correct: false },
    { label: "C", text: "Le Canada-Est correspond à l’ancien Bas-Canada et le Canada-Ouest à l’ancien Haut-Canada.", correct: true },
    { label: "D", text: "Le Nouveau-Brunswick fait partie du Canada-Est.", correct: false },
  ],
  operationId: "time_and_space",
  sourceIds: wyldMapSources.map(({ id }) => id),
  sourceCatalog: wyldMapSources,
  rationale: "La question vérifie la lecture spatiale de la carte et la correspondance entre les anciennes colonies et les deux sections de la Province du Canada.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_REBELLION_CONSEQUENCES_DOCUMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-011",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "En te référant aux trois documents, explique deux types de conséquences des Rébellions de 1837-1838 au Bas-Canada.",
  instruction: "Appuie chaque conséquence sur un élément précis des documents. Toute combinaison historiquement juste provenant d’au moins deux documents est acceptée.",
  expectedAnswer: "Réponse flexible : l’élève doit expliquer au moins deux catégories de conséquences. Une conséquence politique ou institutionnelle peut être la suspension du régime parlementaire, la disparition temporaire de l’Assemblée élue ou l’administration par un Conseil spécial nommé. Une conséquence humaine, judiciaire ou répressive peut être l’arrestation, l’exil aux Bermudes, la condamnation ou la déportation en Australie. Toute combinaison appuyée correctement sur au moins deux documents est acceptée.",
  historicalDocumentIds: [ACTE_UNION_REBELLION_CONSEQUENCE_DOCUMENT.id, ACTE_UNION_BERMUDA_EXILE_DOCUMENT.id, ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT.id],
  commonErrors: ["Énumérer des conséquences sans les expliquer.", "Donner deux exemples appartenant à la même catégorie sans distinguer deux types de conséquences.", "Affirmer que toutes les personnes arrêtées ont été condamnées ou déportées."],
  distractors: [],
  operationId: "causes_and_consequences",
  sourceIds: rebellionConsequenceSources.map(({ id }) => id),
  sourceCatalog: rebellionConsequenceSources,
  rationale: "Les trois documents permettent de distinguer les conséquences institutionnelles des conséquences humaines et répressives des Rébellions.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_WYLD_CHANGE_CONTINUITY_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-012",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "En te référant à la carte modifiée de Wyld et à l’extrait de l’Acte d’Union, indique un changement et une continuité dans l’organisation territoriale des Canadas après 1841.",
  instruction: "Appuie le changement et la continuité sur les deux documents. Tu peux répondre dans tes propres mots.",
  expectedAnswer: "Réponse flexible : comme changement, l’élève doit faire ressortir que le Haut-Canada et le Bas-Canada sont réunis pour former une seule colonie, la Province du Canada. Comme continuité, l’élève peut expliquer que les deux anciens territoires demeurent reconnaissables comme sections distinctes : le Bas-Canada devient le Canada-Est et le Haut-Canada devient le Canada-Ouest. Toute formulation équivalente et correctement appuyée sur les documents est acceptée.",
  historicalDocumentIds: [ACTE_UNION_MAP_ADAPTATION_DRAFT.id, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id],
  commonErrors: ["Donner deux changements sans relever une continuité.", "Affirmer que les anciennes divisions territoriales disparaissent entièrement.", "Inverser le Canada-Est et le Canada-Ouest."],
  distractors: [],
  operationId: "changes_and_continuities",
  sourceIds: mapActSources.map(({ id }) => id),
  sourceCatalog: mapActSources,
  rationale: "La confrontation du texte législatif à la carte permet de distinguer l’unification politique de la continuité des deux grandes sections territoriales.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_IMPRISONMENT_DEPORTATION_DOCUMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:document-interpretation-013",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "document-interpretation",
  prompt: "À l’aide des deux documents, nomme deux formes de répression utilisées après les Rébellions de 1837-1838 et explique ce que les données montrent sur l’ampleur de cette répression.",
  instruction: "Utilise un élément précis de chaque document. Toute formulation historiquement juste qui explique l’ampleur et la sévérité de la répression est acceptée.",
  expectedAnswer: "Réponse flexible : le texte de BAnQ montre l’ampleur de la répression puisque 512 Patriotes emprisonnés ont été repérés dans les registres montréalais. Le second document en montre la sévérité : 58 prisonniers condamnés à mort ont vu leur peine transformée en déportation pénale vers l’Australie. Toute réponse équivalente utilisant les emprisonnements nombreux et l’éloignement forcé comme preuves est acceptée.",
  historicalDocumentIds: [ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT.id, ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT.id],
  commonErrors: ["Affirmer que les 512 personnes ont toutes été condamnées.", "Confondre emprisonnement et déportation.", "Décrire les documents sans expliquer ce qu’ils révèlent sur la répression."],
  distractors: [],
  operationId: "causes_and_consequences",
  sourceIds: imprisonmentDeportationSources.map(({ id }) => id),
  sourceCatalog: imprisonmentDeportationSources,
  rationale: "La question croise un indicateur de l’ampleur des emprisonnements et un exemple de peine sévère afin de caractériser la répression après les Rébellions.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_CAUSES_CONSEQUENCES_DEVELOPMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:development-002",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "development-150",
  prompt: "À l’aide des documents, explique comment la réponse britannique aux revendications des Patriotes contribue au déclenchement des Rébellions de 1837-1838, puis analyse deux conséquences de ces Rébellions au Bas-Canada.",
  instruction: "1. Relie une revendication des 92 Résolutions à la réponse formulée dans les résolutions Russell. 2. Explique une conséquence politique et une conséquence humaine des Rébellions en t’appuyant sur les documents.",
  expectedAnswer: "Dans une réponse d’environ 150 mots, l’élève relie une revendication des 92 Résolutions — par exemple l’élection du Conseil législatif, la responsabilité de l’exécutif ou le contrôle des revenus — au refus exprimé dans les résolutions Russell, qui permettent notamment au gouverneur d’utiliser certains revenus sans le consentement de l’Assemblée. Cette fermeture politique accentue le mécontentement et contribue à la radicalisation, sans constituer l’unique cause des Rébellions. L’élève explique ensuite une conséquence politique, comme la suspension de la Constitution et de l’Assemblée élue au profit du Conseil spécial, ainsi qu’une conséquence humaine, comme l’emprisonnement : BAnQ repère 512 Patriotes dans les registres montréalais. Toute réponse historiquement juste, nuancée et appuyée sur les documents est acceptée.",
  historicalDocumentIds: causesConsequencesDevelopmentDocumentIds,
  commonErrors: ["Présenter la réponse britannique comme l’unique cause des Rébellions.", "Confondre les revendications des 92 Résolutions avec la réponse des résolutions Russell.", "Affirmer que les 512 Patriotes repérés ont tous été condamnés."],
  distractors: [],
  operationId: "causes_and_consequences",
  sourceIds: causesConsequencesDevelopmentSources.map(({ id }) => id),
  sourceCatalog: causesConsequencesDevelopmentSources,
  rationale: "La question amène l’élève à construire une chaîne causale documentée, puis à distinguer une conséquence institutionnelle d’une conséquence humaine des Rébellions.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_ACT_DEVELOPMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:development-003",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "development-150",
  prompt: "Compare les recommandations formulées dans le rapport Durham avec les mesures adoptées dans l’Acte d’Union. Explique une similitude et une différence entre les deux. Consulte les documents pour appuyer ta réponse.",
  instruction: "Commençons par la ressemblance : quelle recommandation de Durham reconnais-tu dans l’Acte d’Union?",
  expectedAnswer: "Dans une réponse d’environ 150 mots, l’élève explique comme similitude que Durham recommande l’union législative du Haut-Canada et du Bas-Canada et que l’Acte d’Union réunit effectivement les deux colonies dans la Province du Canada. Comme différence, l’élève peut montrer que Durham recommande aussi un gouvernement responsable, tandis que l’Acte d’Union de 1840 ne l’établit pas : le Conseil exécutif demeure nommé et n’est pas encore responsable devant l’Assemblée élue. Toute comparaison équivalente, historiquement juste et appuyée sur les documents est acceptée.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_UNION_PRESENTATION.id, ACTE_UNION_DURHAM_RESPONSIBLE_GOVERNMENT_PRESENTATION.id, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id, ACTE_UNION_EXECUTIVE_COUNCIL_DOCUMENT.id],
  commonErrors: ["Affirmer que toutes les recommandations de Durham sont adoptées dans l’Acte d’Union.", "Confondre l’adoption de l’Acte d’Union avec l’obtention du gouvernement responsable en 1848.", "Présenter deux ressemblances sans expliquer une différence."],
  distractors: [],
  operationId: "differences_and_similarities",
  sourceIds: durhamActSources.map(({ id }) => id),
  sourceCatalog: durhamActSources,
  rationale: "La question amène l’élève à comparer une recommandation appliquée — l’union législative — à une recommandation qui ne l’est pas immédiatement — le gouvernement responsable.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DEBT_REPRESENTATION_DEVELOPMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:development-004",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "development-150",
  prompt: "À l’aide des trois documents, explique comment la mise en commun des dettes et la représentation politique égale sont liées à l’opposition envers l’Acte d’Union au Canada-Est.",
  instruction: "Éléments à considérer : la dette des deux colonies, leur population et la représentation des députés.",
  expectedAnswer: "Dans une réponse d’environ 150 mots, l’élève établit que le Haut-Canada possède une dette nettement plus élevée que le Bas-Canada avant l’Union. La mise en commun oblige donc les habitants du Canada-Est à participer au remboursement d’une dette surtout contractée par le Haut-Canada, ce qui peut être perçu comme injuste. L’élève relie aussi l’opposition à la représentation égale : le Canada-Est et le Canada-Ouest obtiennent chacun 42 députés, même si le tableau démographique montre que le Canada-Est est alors plus peuplé. Cette combinaison — partage d’une dette inégale et nombre égal de députés malgré l’écart de population — alimente l’impression que l’Union désavantage politiquement et financièrement le Canada-Est. Toute réponse historiquement juste et appuyée sur les trois documents est acceptée.",
  historicalDocumentIds: [ACTE_UNION_DEBT_COMPARISON_CHART.id, ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id, ACTE_UNION_POPULATION_COMPARISON_CHART.id],
  commonErrors: ["Inverser la dette du Haut-Canada et celle du Bas-Canada.", "Affirmer que le Canada-Est obtient davantage de députés.", "Décrire séparément les documents sans relier les deux mesures à l’opposition."],
  distractors: [],
  operationId: "relationships_between_facts",
  sourceIds: debtStructureSources.map(({ id }) => id),
  sourceCatalog: debtStructureSources,
  rationale: "La question demande de relier deux mesures distinctes de l’Union — la dette commune et la représentation égale — à une même réaction d’opposition au Canada-Est.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_DURHAM_OPPOSITION_CAUSAL_DEVELOPMENT_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:development-005",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "development-150",
  prompt: "Explique comment les objectifs formulés par Durham influencent certaines mesures de l’Acte d’Union et contribuent à l’opposition politique au Canada-Est. Appuie ta réponse en te référant à des documents.",
  instruction: "Consulte les quatre documents pour construire et appuyer ta réponse.",
  expectedAnswer: "Dans une réponse d’environ 150 mots, l’élève explique que Durham recommande l’union du Haut-Canada et du Bas-Canada et souhaite favoriser l’assimilation de la population canadienne-française. L’Acte d’Union reprend l’unification politique en créant la Province du Canada. La représentation égale accordée au Canada-Est et au Canada-Ouest, malgré la population alors plus nombreuse du Canada-Est, ainsi que la volonté de réduire l’influence politique des Canadiens français peuvent être reliées à ces objectifs. Ces mesures contribuent à l’opposition au Canada-Est, notamment celle exprimée par LaFontaine, parce qu’elles sont perçues comme injustes et menaçantes pour la représentation politique de la population canadienne-française. Toute réponse causale, nuancée et correctement appuyée sur les documents est acceptée.",
  historicalDocumentIds: [ACTE_UNION_DURHAM_ANGLICIZATION_PRESENTATION.id, ACTE_UNION_DURHAM_UNION_PRESENTATION.id, ACTE_UNION_OFFICIAL_EXCERPT_DOCUMENT.id, ACTE_UNION_LAFONTAINE_DOCUMENT_DRAFT.id],
  commonErrors: ["Présenter l’assimilation comme une mesure explicitement formulée dans le texte de l’Acte d’Union.", "Affirmer que Durham s’oppose à l’union des deux Canadas.", "Décrire les documents sans établir de lien causal avec l’opposition au Canada-Est."],
  distractors: [],
  operationId: "causal_connections",
  sourceIds: durhamActOppositionSources.map(({ id }) => id),
  sourceCatalog: durhamActOppositionSources,
  rationale: "La question fait relier les objectifs du rapport Durham, leur traduction partielle dans l’Acte d’Union et la réaction d’opposition au Canada-Est.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_REPRESSION_DOCUMENT_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-006",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Quelle conclusion est la mieux appuyée par les deux documents concernant les conséquences des Rébellions de 1837-1838?",
  instruction: "Consulte les deux documents, puis choisis la conclusion qui respecte les informations qu’ils présentent.",
  expectedAnswer: "D. La répression a entraîné de nombreux emprisonnements et, pour certains condamnés, une déportation hors de la colonie.",
  historicalDocumentIds: [ACTE_UNION_BANQ_512_PRISONERS_DOCUMENT.id, ACTE_UNION_AUSTRALIA_DEPORTATION_DOCUMENT.id],
  commonErrors: ["Affirmer que les 512 Patriotes emprisonnés ont tous été déportés.", "Conclure que la répression a seulement touché les dirigeants.", "Confondre la commutation d’une peine avec une libération."],
  distractors: ["Les 512 Patriotes emprisonnés ont tous été déportés en Australie.", "La répression s’est limitée aux dirigeants les plus importants du mouvement patriote.", "Tous les prisonniers condamnés à mort ont finalement été libérés."],
  answerOptions: [
    { label: "A", text: "Les 512 Patriotes emprisonnés ont tous été déportés en Australie.", correct: false },
    { label: "B", text: "La répression s’est limitée aux dirigeants les plus importants du mouvement patriote.", correct: false },
    { label: "C", text: "Tous les prisonniers condamnés à mort ont finalement été libérés.", correct: false },
    { label: "D", text: "La répression a entraîné de nombreux emprisonnements et, pour certains condamnés, une déportation hors de la colonie.", correct: true },
  ],
  operationId: "causes_and_consequences",
  sourceIds: imprisonmentDeportationSources.map(({ id }) => id),
  sourceCatalog: imprisonmentDeportationSources,
  rationale: "La question vérifie si l’élève peut tirer une conclusion prudente de deux documents sans généraliser le sort de certains prisonniers à l’ensemble des personnes emprisonnées.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const RESPONSIBLE_GOVERNMENT_COALITION_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1,
  id: "question:gouvernement-responsable:short-answer-001",
  scope: "notional",
  knowledgeHeadingId: "gouvernement-responsable",
  relatedKnowledgeHeadingIds: ["gouvernement-responsable"],
  referenceCardId: "reference-card:gouvernement-responsable",
  historicalRecordId: "historical-record:gouvernement-responsable",
  status: "approved",
  format: "short-answer",
  prompt: "À l’aide des deux documents, explique comment la représentation égale du Canada-Est et du Canada-Ouest favorise une alliance politique entre les réformistes des deux sections.",
  instruction: "Appuie ta réponse sur le schéma de l’Assemblée et sur la lettre de Francis Hincks à Louis-Hippolyte La Fontaine.",
  expectedAnswer: "La représentation égale accorde 42 députés à chaque section dans une même Assemblée. Pour obtenir une majorité et défendre des réformes communes, les réformistes du Canada-Est et du Canada-Ouest ont intérêt à collaborer. La lettre de Hincks à La Fontaine montre qu’ils considèrent leur aide mutuelle comme nécessaire; cette stratégie prépare l’alliance politique associée ensuite à La Fontaine et Baldwin.",
  historicalDocumentIds: coalitionShortAnswerDocumentIds,
  commonErrors: ["Présenter LaFontaine et Baldwin comme des représentants de la même section.", "Affirmer que l’Acte d’Union instaure immédiatement le gouvernement responsable.", "Nommer l’alliance sans expliquer son lien avec la législature commune."],
  distractors: [],
  operationId: "causes_and_consequences",
  sourceIds: coalitionShortAnswerSources.map(({ id }) => id),
  sourceCatalog: coalitionShortAnswerSources,
  rationale: "La question met directement en relation la représentation égale dans l’Assemblée commune et la stratégie d’alliance transsectionnelle qui devient centrale dans la lutte pour le gouvernement responsable.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_SYDENHAM_ROLE_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-007",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Quel énoncé décrit le mieux le rôle de lord Sydenham dans la mise en place de l’Acte d’Union?",
  instruction: "Choisis l’énoncé qui correspond à son rôle historique.",
  expectedAnswer: "C. Il négocie l’acceptation de l’Union dans les colonies, prépare le nouveau régime et proclame son entrée en vigueur.",
  historicalDocumentIds: [],
  commonErrors: ["Confondre Sydenham avec les dirigeants patriotes.", "Lui attribuer la rédaction du rapport Durham.", "Le confondre avec LaFontaine ou Baldwin."],
  distractors: ["Il dirige le mouvement patriote et présente les 92 Résolutions à Londres.", "Il rédige le rapport recommandant l’assimilation des Canadiens français et le gouvernement responsable.", "Il s’oppose à l’Union et organise l’alliance politique entre LaFontaine et Baldwin."],
  answerOptions: [
    { label: "A", text: "Il dirige le mouvement patriote et présente les 92 Résolutions à Londres.", correct: false },
    { label: "B", text: "Il rédige le rapport recommandant l’assimilation des Canadiens français et le gouvernement responsable.", correct: false },
    { label: "C", text: "Il négocie l’acceptation de l’Union dans les colonies, prépare le nouveau régime et proclame son entrée en vigueur.", correct: true },
    { label: "D", text: "Il s’oppose à l’Union et organise l’alliance politique entre LaFontaine et Baldwin.", correct: false },
  ],
  operationId: "establish_facts",
  sourceIds: sydenhamSource.map(({ id }) => id),
  sourceCatalog: sydenhamSource,
  rationale: "La question distingue le rôle administratif et politique de Sydenham de ceux de Durham, des Patriotes et des réformistes LaFontaine et Baldwin.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_POLITICAL_INSTITUTIONS_ASSOCIATION_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:interactive-association-001",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "interactive-association",
  prompt: "Associe chaque institution politique à son rôle principal sous le régime de l’Acte d’Union.",
  instruction: "Consulte le schéma politique, puis déplace chaque institution vers la description correspondante.",
  expectedAnswer: "Couronne — autorité souveraine britannique et nomination officielle du gouverneur; gouverneur — représentant de la Couronne, nomination des conseils et intervention dans la sanction des lois; Conseil exécutif — conseil et administration sans responsabilité initiale devant l’Assemblée; Conseil législatif — chambre haute nommée qui étudie les projets de loi; Assemblée législative — députés élus qui débattent des projets de loi et votent les fonds publics.",
  historicalDocumentIds: [ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id],
  commonErrors: ["Confondre le Conseil exécutif et le Conseil législatif.", "Présenter les deux conseils comme des institutions élues.", "Affirmer que l’Assemblée nomme directement le gouverneur."],
  distractors: [],
  operationId: "relationships_between_facts",
  sourceIds: officialActSource.map(({ id }) => id),
  sourceCatalog: officialActSource,
  rationale: "L’association interactive vérifie la compréhension des rôles institutionnels et des liens entre les composantes nommées et élues du régime de 1841.",
  associationInteraction: {
    documentId: ACTE_UNION_POLITICAL_STRUCTURE_DIAGRAM.id,
    items: [
      { id: "crown", label: "La Couronne" },
      { id: "governor", label: "Le gouverneur" },
      { id: "executive-council", label: "Le Conseil exécutif" },
      { id: "legislative-council", label: "Le Conseil législatif" },
      { id: "legislative-assembly", label: "L’Assemblée législative" },
    ],
    targets: [
      { id: "sovereign-authority", description: "Représente l’autorité souveraine britannique et nomme officiellement le gouverneur.", correctItemId: "crown" },
      { id: "colonial-representative", description: "Représente la Couronne dans la colonie, nomme les membres des conseils et intervient dans la sanction des lois.", correctItemId: "governor" },
      { id: "administration", description: "Conseille le gouverneur et participe à l’administration sans être initialement responsable devant l’Assemblée élue.", correctItemId: "executive-council" },
      { id: "upper-house", description: "Étudie les projets de loi comme chambre haute et se compose de membres nommés.", correctItemId: "legislative-council" },
      { id: "elected-house", description: "Se compose de députés élus, débat des projets de loi et vote les fonds publics.", correctItemId: "legislative-assembly" },
    ],
  },
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_ADOPTION_SEQUENCE_MULTIPLE_CHOICE_QUESTION = {
  schemaVersion: 1,
  id: "question:acte-union:multiple-choice-008",
  scope: "notional",
  knowledgeHeadingId: "acte-union",
  relatedKnowledgeHeadingIds: ["acte-union"],
  referenceCardId: "reference-card:acte-union",
  historicalRecordId: "historical-record:acte-union",
  status: "approved",
  format: "multiple-choice",
  prompt: "Parmi les séquences suivantes, laquelle place dans le bon ordre les quatre principales étapes politiques et législatives qui conduisent à l’adoption de l’Acte d’Union de 1840?",
  instruction: "Repère d’abord les décisions prises dans les deux colonies, puis les étapes accomplies au Parlement britannique.",
  expectedAnswer: "La réponse C est appropriée. Le Conseil spécial du Bas-Canada approuve d’abord le principe de l’Union. Le Parlement du Haut-Canada accepte ensuite le projet d’union. Après ces décisions coloniales, John Russell présente le projet de loi au Parlement britannique. La sanction royale vient en dernier : elle transforme le projet adopté en loi.",
  historicalDocumentIds: [],
  commonErrors: ["Placer la présentation du projet britannique avant les décisions coloniales de 1839.", "Placer la sanction royale avant la présentation du projet.", "Inverser l’acceptation du Haut-Canada et les résolutions du Conseil spécial."],
  distractors: ["John Russell présente le projet de loi au Parlement britannique → le Conseil spécial du Bas-Canada approuve le principe de l’Union → la reine Victoria accorde la sanction royale → le Parlement du Haut-Canada accepte l’Union.", "Le Parlement du Haut-Canada accepte l’Union → le Conseil spécial du Bas-Canada approuve le principe de l’Union → John Russell présente le projet de loi au Parlement britannique → la reine Victoria accorde la sanction royale.", "Le Conseil spécial du Bas-Canada approuve le principe de l’Union → John Russell présente le projet de loi au Parlement britannique → la reine Victoria accorde la sanction royale → le Parlement du Haut-Canada accepte l’Union."],
  answerOptions: [
    { label: "A", text: "John Russell présente le projet de loi au Parlement britannique → le Conseil spécial du Bas-Canada approuve le principe de l’Union → la reine Victoria accorde la sanction royale → le Parlement du Haut-Canada accepte l’Union.", correct: false },
    { label: "B", text: "Le Parlement du Haut-Canada accepte l’Union → le Conseil spécial du Bas-Canada approuve le principe de l’Union → John Russell présente le projet de loi au Parlement britannique → la reine Victoria accorde la sanction royale.", correct: false },
    { label: "C", text: "Le Conseil spécial du Bas-Canada approuve le principe de l’Union → le Parlement du Haut-Canada accepte l’Union → John Russell présente le projet de loi au Parlement britannique → la reine Victoria accorde la sanction royale.", correct: true },
    { label: "D", text: "Le Conseil spécial du Bas-Canada approuve le principe de l’Union → John Russell présente le projet de loi au Parlement britannique → la reine Victoria accorde la sanction royale → le Parlement du Haut-Canada accepte l’Union.", correct: false },
  ],
  operationId: "time_and_space",
  sourceIds: ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "anq-special-council-1838-1841" || id === "anq-upper-canada-1791-1841" || id === "anq-chronology-1839-1841" || id === "union-act-1840-official").map(({ id }) => id),
  sourceCatalog: ACTE_UNION_HISTORICAL_RECORD.sourceCatalog.filter(({ id }) => id === "anq-special-council-1838-1841" || id === "anq-upper-canada-1791-1841" || id === "anq-chronology-1839-1841" || id === "union-act-1840-official"),
  rationale: "La question vérifie l’ordre des décisions coloniales et britanniques ayant conduit à la sanction de l’Acte d’Union, sans fournir les repères chronologiques dans la fiche élève.",
  review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_CONSOLIDATED_FUND_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1, id: "question:acte-union:short-answer-006", scope: "notional", knowledgeHeadingId: "acte-union", relatedKnowledgeHeadingIds: ["acte-union"], referenceCardId: "reference-card:acte-union", historicalRecordId: "historical-record:acte-union", status: "approved", format: "short-answer",
  prompt: "À l’aide du document, explique ce qu’est le fonds consolidé et indique à quoi il sert dans la Province du Canada.", instruction: "Formule une réponse courte qui précise l’origine des sommes et leur utilisation.", expectedAnswer: "Le fonds consolidé réunit les revenus publics du Canada-Est et du Canada-Ouest dans un compte commun. Il sert à payer les dépenses et les charges communes de la Province du Canada, notamment l’intérêt sur les dettes.",
  historicalDocumentIds: [ACTE_UNION_CONSOLIDATED_REVENUE_FUND_DOCUMENT.id], commonErrors: ["Présenter le fonds consolidé comme un impôt particulier.", "Affirmer qu’il appartient uniquement au Canada-Ouest.", "Confondre la réunion des revenus avec l’effacement des dettes."], distractors: [], operationId: "establish_facts", sourceIds: consolidatedRevenueFundSources.map(({ id }) => id), sourceCatalog: consolidatedRevenueFundSources, rationale: "La question vérifie la compréhension du mécanisme financier commun créé par l’Acte d’Union et de sa fonction dans le paiement des charges provinciales à partir des articles 50 et 56 du texte législatif primaire.", review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.0", approvedAt: "2026-08-02T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

export const ACTE_UNION_LANGUAGE_SCOPE_SHORT_ANSWER_QUESTION = {
  schemaVersion: 1, id: "question:acte-union:short-answer-007", scope: "notional", knowledgeHeadingId: "acte-union", relatedKnowledgeHeadingIds: ["acte-union"], referenceCardId: "reference-card:acte-union", historicalRecordId: "historical-record:acte-union", status: "approved", format: "short-answer",
  prompt: "À l’aide de l’extrait de l’Acte d’Union, indique comment la nouvelle législation a un impact significatif pour les Canadiens français.", instruction: "Repère la disposition linguistique et explique concrètement ce qu’elle change pour la place du français dans les institutions politiques.", expectedAnswer: "Une réponse est suffisante dès qu’elle indique que l’Acte d’Union impose l’anglais comme langue des documents officiels de la législature, ce qui réduit la reconnaissance institutionnelle du français et désavantage les Canadiens français. Une réponse peut préciser que des traductions françaises demeurent possibles, mais qu’elles n’ont pas la même valeur officielle. Il n’est pas nécessaire d’énumérer toutes les catégories de documents.",
  historicalDocumentIds: [ACTE_UNION_LANGUAGE_ARTICLE_DOCUMENT.id], commonErrors: ["Affirmer que le français devient illégal dans toute la Province du Canada.", "Affirmer que les traductions françaises possèdent la même valeur que les originaux anglais.", "Décrire seulement la règle linguistique sans expliquer son impact sur la reconnaissance du français ou sur les Canadiens français.", "Exiger l’énumération des catégories de documents après que l’élève a correctement expliqué l’impact essentiel.", "Confondre la disposition de 1840 avec son abrogation en 1848."], distractors: [], operationId: "causes_and_consequences", sourceIds: languageArticleSources.map(({ id }) => id), sourceCatalog: languageArticleSources, rationale: "La question amène l’élève à expliquer l’impact politique et institutionnel de l’exclusivité de l’anglais dans les documents officiels, tout en tenant compte des traductions françaises permises sans valeur d’original officiel.", review: { documented: true, historicallyVerified: true, pedagogicallyVerified: true, biasAndLanguageReviewed: true, approvedBy: "David Hinse", approvedVersion: "1.1", approvedAt: "2026-08-10T00:00:00.000-04:00" },
} as const satisfies ApprovedQuestion;

// Source unique de toutes les questions, quel que soit leur point d’entrée.
// Les vues par notion et la vue transversale filtrent ce même catalogue.
export const PEDAGOGICAL_QUESTION_CATALOG: readonly ApprovedQuestion[] = [ACTE_UNION_CAUSAL_PILOT_QUESTION, ACTE_UNION_TIMELINE_PROTOTYPE_QUESTION, ACTE_UNION_TIMELINE_CAUSAL_DEVELOPMENT_QUESTION, ACTE_UNION_DEFINITION_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_DURHAM_DEFINITION_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_EQUAL_REPRESENTATION_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_LANGUAGE_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_PROVINCE_SECTIONS_SHORT_ANSWER_QUESTION, ACTE_UNION_RESPONSIBLE_GOVERNMENT_SHORT_ANSWER_QUESTION, ACTE_UNION_SHARED_DEBT_SHORT_ANSWER_QUESTION, ACTE_UNION_LAFONTAINE_OPPOSITION_SHORT_ANSWER_QUESTION, ACTE_UNION_1840_1841_SHORT_ANSWER_QUESTION, ACTE_UNION_POLITICAL_TRANSFORMATION_DOCUMENT_QUESTION, ACTE_UNION_RUSSELL_LAFONTAINE_COMPARISON_QUESTION, ACTE_UNION_DURHAM_ACT_COMPARISON_QUESTION, ACTE_UNION_DEBT_STRUCTURE_RELATIONSHIP_QUESTION, ACTE_UNION_DEBT_OPPOSITION_CAUSAL_QUESTION, ACTE_UNION_SOLUTION_INJUSTICE_DOCUMENT_QUESTION, ACTE_UNION_DURHAM_RECOMMENDATIONS_DOCUMENT_QUESTION, ACTE_UNION_DURHAM_ASSIMILATION_CAUSAL_QUESTION, ACTE_UNION_DURHAM_CONTINUITY_DOCUMENT_QUESTION, ACTE_UNION_DURHAM_FINANCIAL_CAUSES_CONSEQUENCES_QUESTION, ACTE_UNION_WYLD_TERRITORIAL_TRANSFORMATION_QUESTION, ACTE_UNION_WYLD_TERRITORIES_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_REBELLION_CONSEQUENCES_DOCUMENT_QUESTION, ACTE_UNION_WYLD_CHANGE_CONTINUITY_QUESTION, ACTE_UNION_IMPRISONMENT_DEPORTATION_DOCUMENT_QUESTION, ACTE_UNION_CAUSES_CONSEQUENCES_DEVELOPMENT_QUESTION, ACTE_UNION_DURHAM_ACT_DEVELOPMENT_QUESTION, ACTE_UNION_DEBT_REPRESENTATION_DEVELOPMENT_QUESTION, ACTE_UNION_DURHAM_OPPOSITION_CAUSAL_DEVELOPMENT_QUESTION, ACTE_UNION_REPRESSION_DOCUMENT_MULTIPLE_CHOICE_QUESTION, RESPONSIBLE_GOVERNMENT_COALITION_SHORT_ANSWER_QUESTION, ACTE_UNION_SYDENHAM_ROLE_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_POLITICAL_INSTITUTIONS_ASSOCIATION_QUESTION, ACTE_UNION_ADOPTION_SEQUENCE_MULTIPLE_CHOICE_QUESTION, ACTE_UNION_CONSOLIDATED_FUND_SHORT_ANSWER_QUESTION, ACTE_UNION_LANGUAGE_SCOPE_SHORT_ANSWER_QUESTION];

export function getQuestionsForKnowledgeHeading(knowledgeHeadingId: string) {
  return PEDAGOGICAL_QUESTION_CATALOG.filter(({ relatedKnowledgeHeadingIds }) => relatedKnowledgeHeadingIds.includes(knowledgeHeadingId));
}

export function getTransversalQuestions() {
  return PEDAGOGICAL_QUESTION_CATALOG.filter(({ scope }) => scope === "transversal");
}
