import type { HistoricalDocumentRecord } from "./historical-document.ts";

export const RESPONSIBLE_GOVERNMENT_ELGIN_MINISTRY_APPOINTMENTS_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-005",
  title: "Elgin nomme le ministère La Fontaine–Baldwin",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["establish_facts", "causal_connections", "relationships_between_facts"],
  historicalDate: "11 mars 1848",
  creator: "Bureau du secrétaire de la Province du Canada, sous l’autorité de lord Elgin",
  holdingInstitution: "Bibliothèque et Archives Canada · Gazette du Canada",
  sourceUrl: "https://central.bac-lac.gc.ca/.item?app=cangaz&id=cgc_p1-1_v000_n337_t000_000_18480311_p00000&op=pdf",
  sourceLocator: "Gazette du Canada, no 337, 11 mars 1848, p. 5186 du volume numérisé (page 3 du PDF), rubrique « Nominations ».",
  assetUrl: "https://central.bac-lac.gc.ca/.item?app=cangaz&id=cgc_p1-1_v000_n337_t000_000_18480311_p00000&op=pdf",
  rightsStatement: "Publication officielle canadienne de 1848 appartenant au domaine public; reproduction numérique de Bibliothèque et Archives Canada. La transcription française est régularisée pour faciliter la lecture.",
  transcription: "Son Excellence le gouverneur général a fait les nominations suivantes : l’honorable Louis-Hippolyte La Fontaine, membre du Conseil exécutif de la Province du Canada et procureur général pour l’ancienne province du Bas-Canada; l’honorable Robert Baldwin, membre du Conseil exécutif de la Province du Canada et procureur général pour l’ancienne province du Haut-Canada.",
  accessibleDescription: "Avis officiel bilingue annonçant la nomination de Louis-Hippolyte La Fontaine et de Robert Baldwin au Conseil exécutif de la Province du Canada le 11 mars 1848.",
  historicalContext: "Après la victoire de la majorité réformiste aux élections de 1848 et la défaite du ministère conservateur à l’Assemblée, lord Elgin demande à La Fontaine et Baldwin de former un nouveau ministère. L’avis officiel confirme leur nomination au Conseil exécutif, étape concrète de la mise en pratique du gouvernement responsable.",
  observationGuide: ["Repérer l’autorité qui annonce les nominations.", "Identifier les fonctions confiées à La Fontaine et Baldwin.", "Relier la composition du Conseil exécutif à la majorité réformiste de l’Assemblée."],
  interpretationCautions: ["L’avis confirme les nominations, mais n’explique pas à lui seul le principe du gouvernement responsable.", "Ne pas présenter Elgin comme l’unique auteur de la réforme : la majorité électorale et la lutte des réformistes sont essentielles.", "La Fontaine et Baldwin représentent les deux sections de la Province du Canada."],
  pedagogicalUses: ["Établir le rôle de lord Elgin dans la formation du ministère de 1848.", "Relier la victoire électorale des réformistes à leur entrée au Conseil exécutif.", "Montrer comment le gouvernement responsable se met en place par une pratique politique concrète."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_ELGIN_GREY_MINISTRY_LETTER_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-006",
  title: "Elgin explique la formation du ministère La Fontaine–Baldwin",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["relationships_between_facts", "establish_facts"],
  historicalDate: "17 mars 1848",
  creator: "James Bruce, lord Elgin, gouverneur général de la Province du Canada",
  holdingInstitution: "Bibliothèque et Archives Canada; collection Elgin–Grey publiée par la Société Champlain",
  sourceUrl: "https://primarydocuments.ca/la-collection-elgin-grey-1846-1852-vol-1/?lang=fr",
  sourceLocator: "Elgin à Grey, lettre privée, Montréal, 17 mars 1848, The Elgin-Grey Papers, vol. 1, p. 135; passage sur la démission du ministère et la formation d’une nouvelle administration.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2018/04/ElginGreyV11937-1.pdf",
  rightsStatement: "Lettre de 1848 dans le domaine public; traduction française d’un montage d’extraits préparé à partir de l’édition de 1937. Les coupures sont signalées par […].",
  transcription: "Les anciens ministres ont remis leur démission en corps […]. J’ai alors fait venir MM. La Fontaine et Baldwin. […] Je leur ai dit […] qu’ils pouvaient former une administration méritant et possédant la confiance du Parlement […] et qu’ils pouvaient compter sur tout le soutien et toute l’assistance convenables de ma part.",
  accessibleDescription: "Extrait adapté d’une lettre dans laquelle lord Elgin raconte à lord Grey comment il a invité La Fontaine et Baldwin à former une administration soutenue par le Parlement.",
  historicalContext: "Le ministère conservateur est défait à l’Assemblée après les élections de 1848 et remet sa démission. Elgin rencontre ensuite La Fontaine et Baldwin, chefs de la majorité réformiste, afin qu’ils forment une administration possédant la confiance parlementaire.",
  observationGuide: ["Identifier les personnes qu’Elgin fait venir après la démission du ministère.", "Repérer la condition nécessaire pour que la nouvelle administration puisse gouverner.", "Distinguer le soutien constitutionnel du gouverneur de la confiance accordée par le Parlement."],
  interpretationCautions: ["Le texte est une traduction française d’un montage de passages de la même lettre; les […] marquent chaque coupure.", "Le mot Parlement renvoie ici principalement à la confiance de la majorité de l’Assemblée élue.", "Ne pas conclure qu’Elgin crée seul le gouvernement responsable."],
  pedagogicalUses: ["Interpréter le principe de confiance parlementaire à partir du point de vue d’Elgin.", "Expliquer le rôle du gouverneur dans la formation d’un ministère responsable.", "Comparer une correspondance privée à l’avis officiel des nominations du 11 mars 1848."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_GEORGE_BROWN_COALITION_SPEECH_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-007",
  title: "George Brown justifie la formation de la Grande Coalition",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["causal_connections", "relationships_between_facts"],
  historicalDate: "14 juin 1864",
  creator: "George Brown, député du Canada-Ouest",
  holdingInstitution: "Débats parlementaires de la Province du Canada; transcription diffusée par le Macdonald-Laurier Institute",
  sourceUrl: "https://macdonaldlaurier.ca/speech-on-formation-of-the-great-coalition-june-14-186/",
  sourceLocator: "Discours de George Brown sur la formation de la Grande Coalition, 14 juin 1864; passages sur les difficultés entre les deux sections, la succession des crises ministérielles et l’alliance entre anciens adversaires.",
  assetUrl: "https://macdonaldlaurier.ca/speech-on-formation-of-the-great-coalition-june-14-186/",
  rightsStatement: "Discours parlementaire de 1864 dans le domaine public; traduction française d’un montage d’extraits. Les coupures sont signalées par […].",
  transcription: "Depuis dix ans, je me suis opposé aux honorables députés d’en face de la manière la plus hostile qu’on puisse imaginer. […] En raison des difficultés entre le Haut et le Bas-Canada, il était absolument impossible de gouverner ce pays dans la paix, l’harmonie et l’efficacité. […] Une élection a suivi l’autre; une crise ministérielle a suivi l’autre, sans apporter de solution aux difficultés du gouvernement. […] L’alliance qui s’est formée […] a été provoquée par l’extrême urgence de l’impasse presque atteinte dans nos affaires […] afin de trouver une solution à ces difficultés.",
  accessibleDescription: "Traduction-adaptation d’un discours dans lequel George Brown relie l’impasse entre les deux sections de la Province du Canada à la nécessité de former une coalition entre anciens adversaires.",
  historicalContext: "En juin 1864, le gouvernement Taché–Macdonald est défait lors d’un vote de confiance. Après plusieurs années d’instabilité ministérielle, George Brown accepte de collaborer avec des adversaires politiques afin de former la Grande Coalition et de rechercher une nouvelle organisation constitutionnelle.",
  observationGuide: ["Repérer les difficultés qui empêchent les gouvernements de durer.", "Identifier ce que Brown présente comme la réponse à la crise.", "Distinguer les intérêts partisans de l’objectif constitutionnel attribué à la coalition."],
  interpretationCautions: ["Le texte est une traduction française qui réunit plusieurs passages du même discours; les […] signalent les coupures.", "Brown défend sa propre décision politique et cherche à la justifier devant l’Assemblée.", "La Grande Coalition ouvre la recherche d’une solution constitutionnelle, mais elle ne constitue pas encore la Confédération."],
  pedagogicalUses: ["Établir le lien causal entre l’instabilité ministérielle et la Grande Coalition.", "Interpréter le point de vue de George Brown sur le dépassement des divisions partisanes.", "Expliquer pourquoi la coalition est présentée comme une réponse exceptionnelle à une crise politique."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_REBELLION_LOSSES_ACT_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-010",
  title: "La loi autorise l’indemnisation des pertes de 1837-1838",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["causal_connections", "establish_facts", "causes_and_consequences"],
  historicalDate: "25 avril 1849",
  creator: "Parlement de la Province du Canada",
  holdingInstitution: "British North American Legislative Database · Université du Nouveau-Brunswick",
  sourceUrl: "https://bnald.lib.unb.ca/legislation/act-provide-indemnification-parties-lower-canada-whose-property-was-destroyed-during",
  sourceLocator: "12 Victoria, chapitre 58, préambule et articles I-II; texte sanctionné le 25 avril 1849.",
  assetUrl: "https://bnald.lib.unb.ca/sites/default/files/UnC.1849.ch_.58.pdf",
  rightsStatement: "Loi de 1849 dans le domaine public; traduction française d’un montage du préambule et des articles I-II. Les coupures sont signalées par […].",
  transcription: "Les pertes […] résultant de la destruction totale ou partielle, injuste, inutile ou gratuite des habitations, bâtiments, biens et effets des habitants […] doivent être payées et indemnisées; toutefois, aucune personne reconnue coupable de haute trahison […] ne pourra recevoir d’indemnité pour les pertes subies pendant ou après ladite Rébellion […]. Il sera permis au gouverneur en conseil d’autoriser l’émission de débentures […] aux personnes auxquelles une somme aura été accordée en compensation des pertes visées par la présente loi.",
  accessibleDescription: "Montage d’extraits de la loi de 1849 précisant les pertes indemnisables, l’exclusion des personnes reconnues coupables de haute trahison et le financement des compensations.",
  historicalContext: "Le ministère La Fontaine-Baldwin fait adopter cette loi pour indemniser certaines pertes matérielles subies au Bas-Canada pendant les Rébellions. Lord Elgin lui accorde la sanction royale le 25 avril 1849; cette décision déclenche une violente réaction d’opposants.",
  observationGuide: ["Identifier les pertes que la loi permet d’indemniser.", "Repérer qui est explicitement exclu de l’indemnisation.", "Relier l’adoption et la sanction de la mesure à la réaction des opposants."],
  interpretationCautions: ["Le document est une traduction française d’un montage de dispositions de la même loi; les […] marquent les coupures.", "La loi n’accorde pas automatiquement une indemnité à toutes les personnes ayant participé aux Rébellions.", "Distinguer l’adoption de la loi par le Parlement de sa sanction par le gouverneur."],
  pedagogicalUses: ["Nommer la mesure controversée de 1849.", "Relier la loi d’indemnisation aux émeutes et à l’incendie du Parlement.", "Vérifier dans le texte même de la loi que les personnes reconnues coupables de haute trahison sont exclues."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_DOUBLE_MAJORITY_DEBATE_DOCUMENT = {
  schemaVersion: 1, id: "GR-T-011", title: "Les députés débattent de la double majorité", kind: "newspaper", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["gouvernement-responsable"], operationIds: ["causal_connections", "relationships_between_facts"],
  historicalDate: "19 mai 1858", creator: "Députés de l’Assemblée législative de la Province du Canada", holdingInstitution: "The Globe; transcription des débats diffusée par PrimaryDocuments.ca",
  sourceUrl: "https://primarydocuments.ca/province-of-canada-legislative-assembly-double-majority-globe-version-19-may-1858/", sourceLocator: "Débat de l’Assemblée législative sur la double majorité, compte rendu du Globe, 19 mai 1858; interventions de Sicotte et précédents cités de Hincks et Macdonald.", assetUrl: "https://primarydocuments.ca/province-of-canada-legislative-assembly-double-majority-globe-version-19-may-1858/",
  rightsStatement: "Débat parlementaire et journal de 1858 dans le domaine public; traduction française d’un montage d’extraits. Les coupures sont signalées par […].",
  transcription: "Aucun ministère ne pouvait souhaiter davantage obtenir une majorité dans les deux sections de la Province. […] M. Hincks avait déclaré qu’il ne se serait pas cru justifié de demeurer au Cabinet avec ses collègues lorsqu’il ne pouvait commander une majorité des députés du Haut-Canada. […] M. Macdonald avait dit qu’après le vote défavorable des députés du Haut-Canada, il ne pouvait plus, avec convenance et dans l’intérêt public, conserver son siège au Cabinet.",
  accessibleDescription: "Montage d’un débat de 1858 montrant que la perte d’une majorité dans une section pouvait pousser des ministres à quitter le Cabinet.", historicalContext: "Le débat oppose les défenseurs de la double majorité à ceux d’une majorité unique dans l’ensemble de la Chambre. Les exemples cités montrent toutefois la pression politique exercée sur un ministère qui perd l’appui d’une section.",
  observationGuide: ["Repérer les deux majorités recherchées.", "Identifier la conséquence d’un vote défavorable dans une section.", "Relier cette exigence à la fragilité des ministères."], interpretationCautions: ["Le document réunit des passages du même débat; les […] marquent les coupures.", "La double majorité demeure une pratique contestée plutôt qu’une règle écrite absolue.", "Le compte rendu du Globe constitue une transcription journalistique des débats."], pedagogicalUses: ["Expliquer la double majorité.", "Relier la perte d’un appui sectionnel à une démission ministérielle."], version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_MINISTRY_DEFEAT_1858_DOCUMENT = {
  schemaVersion: 1, id: "GR-T-012", title: "Une défaite en Chambre provoque la démission du ministère", kind: "newspaper", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["gouvernement-responsable"], operationIds: ["causal_connections", "establish_facts"], historicalDate: "29 juillet 1858", creator: "Assemblée législative de la Province du Canada; correspondant du Montreal Herald", holdingInstitution: "Montreal Herald; reproduction diffusée par PrimaryDocuments.ca",
  sourceUrl: "https://primarydocuments.ca/province-of-canada-legislative-assembly-defeat-and-resignation-of-the-ministry-6th-parl-1st-sess-29-july-1858/", sourceLocator: "« Provincial Parliament. Defeat and Resignation of the Ministry », Montreal Herald, 30 juillet 1858; séance du 29 juillet.", assetUrl: "https://primarydocuments.ca/province-of-canada-legislative-assembly-defeat-and-resignation-of-the-ministry-6th-parl-1st-sess-29-july-1858/",
  rightsStatement: "Compte rendu parlementaire de 1858 dans le domaine public; traduction française d’un montage d’extraits. Les coupures sont signalées par […].", transcription: "La Chambre avait déclaré que la décision ne devait pas être mise à exécution […]. Certains honorables députés sur lesquels le gouvernement comptait habituellement avaient voté contre lui […]. Il ne restait donc d’autre voie que de démissionner. […] M. Brown fut appelé par Son Excellence à onze heures et entreprit de former une administration.",
  accessibleDescription: "Compte rendu d’une défaite parlementaire suivie de la démission du ministère et d’une tentative de former une nouvelle administration.", historicalContext: "En juillet 1858, une défaite importante sur la question du siège du gouvernement entraîne la démission du ministère Macdonald-Cartier. Le bref ministère Brown-Dorion qui lui succède est lui-même rapidement défait.", observationGuide: ["Repérer le vote qui affaiblit le gouvernement.", "Identifier sa conséquence immédiate.", "Observer qu’un autre chef est ensuite appelé à former un ministère."], interpretationCautions: ["Les […] signalent les coupures dans le même compte rendu.", "Le vote formel de confiance ultérieur n’efface pas l’effet politique de la première défaite.", "Un seul épisode illustre l’instabilité sans expliquer à lui seul toute la période."], pedagogicalUses: ["Relier une défaite en Chambre à une démission.", "Illustrer la succession rapide des ministères."], version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_SECTIONAL_DIFFICULTIES_1864_DOCUMENT = {
  schemaVersion: 1, id: "GR-T-013", title: "George Brown décrit l’aggravation des difficultés entre les deux sections", kind: "newspaper", status: "ready-for-review",
  periodIds: ["1840-1896"], knowledgeHeadingIds: ["gouvernement-responsable"], operationIds: ["causal_connections", "relationships_between_facts"], historicalDate: "14 mars 1864", creator: "George Brown, député du Canada-Ouest", holdingInstitution: "Débats de l’Assemblée législative; transcription diffusée par PrimaryDocuments.ca",
  sourceUrl: "https://primarydocuments.ca/province-of-canada-legislative-assembly-scrapbook-debates-constitutional-changes-8th-parl-2nd-sess-14-march-1864/", sourceLocator: "Débats sur les changements constitutionnels, 14 mars 1864; motion de George Brown et dépêche citée devant l’Assemblée.", assetUrl: "https://primarydocuments.ca/province-of-canada-legislative-assembly-scrapbook-debates-constitutional-changes-8th-parl-2nd-sess-14-march-1864/",
  rightsStatement: "Débat parlementaire de 1864 dans le domaine public; traduction française d’un montage d’extraits. Les coupures sont signalées par […].", transcription: "De très graves difficultés se présentent maintenant dans la conduite du gouvernement du Canada de manière à respecter les souhaits de sa nombreuse population. […] Des différences existent au point d’empêcher une assimilation parfaite et complète des vues des deux sections. […] La nécessité de remédier à une situation qui s’aggrave d’année en année […] a convaincu les conseillers de la représentante de Sa Majesté de rechercher un moyen de supprimer ces difficultés.",
  accessibleDescription: "Extraits cités au Parlement en 1864 décrivant l’aggravation des désaccords entre les deux sections et la nécessité d’une solution constitutionnelle.", historicalContext: "Brown demande la création d’un comité chargé d’étudier les difficultés constitutionnelles de la Province. Le document établit le passage de l’impasse sectionnelle à la recherche d’un nouveau régime.", observationGuide: ["Relever la nature sectionnelle des difficultés.", "Repérer leur aggravation dans le temps.", "Identifier la recherche d’un remède constitutionnel."], interpretationCautions: ["Le montage conserve l’ordre des passages et indique les coupures par […].", "Brown cite une dépêche antérieure pour soutenir sa motion.", "Le texte prépare une solution constitutionnelle sans former encore la Grande Coalition."], pedagogicalUses: ["Relier les divisions sectionnelles à l’impasse politique.", "Montrer pourquoi une solution constitutionnelle est recherchée en 1864."], version: "1.0", approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_METCALFE_RESIGNATION_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-002",
  title: "Metcalfe refuse de céder la prérogative de la Couronne",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["changes_and_continuities", "differences_and_similarities"],
  historicalDate: "28 novembre 1843",
  creator: "Charles Theophilus Metcalfe, gouverneur général de la Province du Canada",
  holdingInstitution: "Journaux de l’Assemblée législative de la Province du Canada; transcription reproduite par Project Gutenberg Canada",
  sourceUrl: "https://www.gutenberg.ca/ebooks/leacock-baldwin/leacock-baldwin-00-h-dir/leacock-baldwin-00-h.html",
  sourceLocator: "Chapitre VII, « The Metcalfe Crisis », réponse officielle de Metcalfe aux ministres démissionnaires, paragraphes 1106-1119.",
  assetUrl: "https://www.gutenberg.ca/ebooks/leacock-baldwin/leacock-baldwin-00-h-dir/leacock-baldwin-00-h.html",
  rightsStatement: "Document officiel de 1843 dans le domaine public; traduction-adaptation française rédigée pour Socrato.",
  transcription: "Je rencontrai le Conseil, sachant que ses membres démissionneraient puisque je refusais de revenir sur ma décision. Les propositions qui m’étaient présentées auraient constitué, selon moi, un abandon de la prérogative de la Couronne. Comme je répondais chaque fois par la négative, on me déclara : « Alors, nous devons démissionner. »",
  accessibleDescription: "Extrait textuel dans lequel Metcalfe relie son refus de céder une partie de l’autorité du gouverneur à la démission de ses ministres.",
  historicalContext: "En novembre 1843, Metcalfe refuse de s’engager à consulter systématiquement le Conseil exécutif avant les nominations. La Fontaine, Baldwin et la plupart des ministres démissionnent, puisqu’ils estiment ne pas pouvoir être responsables devant l’Assemblée sans être consultés sur les décisions du gouvernement.",
  observationGuide: ["Repérer le motif du refus de Metcalfe.", "Identifier la conséquence politique de son refus.", "Relier la prérogative de la Couronne au pouvoir exercé personnellement par le gouverneur."],
  interpretationCautions: ["Le document original est rédigé à la troisième personne au nom du gouverneur; l’extrait élève a été transposé à la première personne.", "Le texte est une traduction-adaptation abrégée et non une transcription intégrale.", "Présenter la démission comme la conséquence d’un désaccord constitutionnel, et non d’un simple conflit personnel."],
  pedagogicalUses: ["Expliquer la crise Metcalfe à partir du point de vue du gouverneur.", "Comparer l’exercice du pouvoir du gouverneur en 1843 et en 1849."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_ELGIN_NON_INTERVENTION_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-003",
  title: "Elgin maintient une position constitutionnelle de non-intervention",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["changes_and_continuities", "differences_and_similarities"],
  historicalDate: "mars-avril 1849",
  creator: "James Bruce, lord Elgin, gouverneur général de la Province du Canada",
  holdingInstitution: "Correspondance Elgin-Grey; transcription des lettres et journaux de lord Elgin par Project Gutenberg",
  sourceUrl: "https://www.gutenberg.org/cache/epub/10610/pg10610.html",
  sourceLocator: "Chapitre IV, section « Rebellion Losses Bill », passages sur la neutralité du gouverneur, la dissolution du Parlement et la sanction de la loi.",
  assetUrl: "https://www.gutenberg.org/cache/epub/10610/pg10610.html",
  rightsStatement: "Correspondance de 1849 dans le domaine public; traduction-adaptation française rédigée pour Socrato.",
  transcription: "Je maintins ma position constitutionnelle en écoutant avec respect toutes les protestations contre la mesure, sans toutefois intervenir dans le débat. Dissoudre un Parlement élu seulement un an auparavant parce qu’il avait adopté, à une forte majorité, une loi présentée par le gouvernement aurait été injustifiable. Je devais laisser la majorité parlementaire gouverner.",
  accessibleDescription: "Extrait textuel dans lequel Elgin explique pourquoi il refuse d’intervenir contre une loi adoptée par la majorité parlementaire.",
  historicalContext: "En 1849, le ministère La Fontaine-Baldwin fait adopter une loi visant à indemniser certaines personnes dont les biens ont été détruits pendant les Rébellions. Malgré les pétitions et les pressions qui lui demandent de dissoudre le Parlement ou de réserver la loi, Elgin la sanctionne et respecte ainsi la majorité parlementaire.",
  observationGuide: ["Repérer les moyens d’intervention qu’Elgin refuse d’utiliser.", "Identifier le rôle accordé à la majorité parlementaire.", "Comparer cette attitude avec celle de Metcalfe en 1843."],
  interpretationCautions: ["Le texte est une traduction-adaptation assemblée à partir de plusieurs passages rapprochés de la correspondance d’Elgin.", "La non-intervention ne signifie pas que le gouverneur perd ses pouvoirs formels.", "Elgin sanctionne la loi malgré son caractère controversé; il ne se prononce pas ici en faveur de chacune de ses dispositions."],
  pedagogicalUses: ["Montrer comment Elgin applique le gouvernement responsable.", "Distinguer la conservation des pouvoirs formels du gouverneur de leur nouvel usage constitutionnel."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_CANADIEN_PARLIAMENT_FIRE_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-004",
  title: "Le Canadien raconte l’émeute et l’incendie du Parlement",
  kind: "newspaper",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["causes_and_consequences", "establish_facts"],
  historicalDate: "27 avril 1849",
  creator: "Correspondant du journal Le Canadien à Montréal",
  holdingInstitution: "Bibliothèque et Archives nationales du Québec",
  sourceUrl: "http://collections.banq.qc.ca/ark:/52327/1910543",
  sourceLocator: "Le Canadien, 27 avril 1849, « Lettre XXXVII », correspondance datée de Montréal, 26 avril 1849.",
  assetUrl: "http://collections.banq.qc.ca/ark:/52327/1910543",
  rightsStatement: "Journal de 1849 dans le domaine public; extrait abrégé et reformulé en français moderne pour Socrato. Les coupures sont signalées par […].",
  transcription: "À sa sortie du Parlement, Lord Elgin reçoit des œufs et d’autres projectiles lancés par des opposants. […] Le soir, une foule en colère se dirige vers le Parlement. Les émeutiers lancent des pierres dans les fenêtres, forcent les députés à quitter la salle, puis entrent dans l’édifice et détruisent le mobilier. […] Peu après, des témoins affirment avoir vu des émeutiers mettre le feu au bâtiment. Les flammes se propagent très rapidement en raison des conduites de gaz et de la grande quantité de livres et de documents présents dans l’édifice.",
  accessibleDescription: "Extrait de journal reformulé relatant l’attaque contre Lord Elgin, l’invasion du Parlement de Montréal et le déclenchement de l’incendie.",
  historicalContext: "Le 25 avril 1849, Lord Elgin sanctionne la loi d’indemnisation adoptée par la majorité parlementaire. Des opposants à cette décision se rassemblent, envahissent le Parlement de Montréal et y mettent le feu.",
  observationGuide: ["Identifier la personne attaquée à la sortie du Parlement.", "Repérer les étapes qui transforment la manifestation en émeute.", "Relier les gestes des émeutiers au déclenchement de l’incendie."],
  interpretationCautions: ["Le texte est une reformulation en français moderne, et non une transcription mot à mot.", "Les […] signalent des passages retirés entre les segments retenus.", "Le journal Le Canadien appuie les réformistes et condamne les émeutiers tories."],
  pedagogicalUses: ["Déterminer la cause politique des émeutes et de l’incendie.", "Reconstituer la succession des événements à partir d’un témoignage journalistique contemporain."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_METCALFE_ELGIN_DOCUMENTS = [
  RESPONSIBLE_GOVERNMENT_ELGIN_MINISTRY_APPOINTMENTS_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_ELGIN_GREY_MINISTRY_LETTER_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_GEORGE_BROWN_COALITION_SPEECH_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_REBELLION_LOSSES_ACT_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_DOUBLE_MAJORITY_DEBATE_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_MINISTRY_DEFEAT_1858_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_SECTIONAL_DIFFICULTIES_1864_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_METCALFE_RESIGNATION_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_ELGIN_NON_INTERVENTION_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_CANADIEN_PARLIAMENT_FIRE_DOCUMENT,
] as const;
