import type { HistoricalDocumentRecord } from "./historical-document.ts";

export const RESPONSIBLE_GOVERNMENT_ELGIN_MINISTRY_APPOINTMENTS_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-005",
  title: "Elgin nomme le ministère La Fontaine–Baldwin",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["establish_facts", "causal_connections", "relationships_between_facts"],
  historicalDate: "11 mars 1848",
  creator: "Bureau du secrétaire de la Province du Canada, sous l’autorité de lord Elgin",
  holdingInstitution: "Bibliothèque et Archives Canada · Gazette du Canada",
  sourceUrl: "https://central.bac-lac.gc.ca/.item?app=cangaz&id=cgc_p1-1_v000_n337_t000_000_18480311_p00000&op=pdf",
  sourceLocator: "Gazette du Canada, no 337, 11 mars 1848, p. 5186 du volume numérisé (page 3 du PDF), rubrique « Nominations ».",
  assetUrl: "https://central.bac-lac.gc.ca/.item?app=cangaz&id=cgc_p1-1_v000_n337_t000_000_18480311_p00000&op=pdf",
  rightsStatement: "Publication officielle canadienne de 1848 appartenant au domaine public; reproduction numérique de Bibliothèque et Archives Canada. La transcription française est régularisée pour faciliter la lecture.",
  transcription: "Son Excellence le gouverneur général a fait les nominations suivantes : l’honorable Louis-Hippolyte La Fontaine, membre du Conseil exécutif de la Province du Canada et procureur général pour l’ancienne province du Bas-Canada; l’honorable Robert Baldwin, membre du Conseil exécutif de la Province du Canada et procureur général pour l’ancienne province du Haut-Canada.",
  accessibleDescription: "Avis officiel bilingue annonçant la nomination de Louis-Hippolyte La Fontaine et de Robert Baldwin au Conseil exécutif de la Province du Canada le 11 mars 1848.",
  historicalContext: "Après la victoire de la majorité réformiste aux élections de 1848 et la défaite du ministère conservateur à l’Assemblée, lord Elgin demande à La Fontaine et Baldwin de former un nouveau ministère. L’avis officiel confirme leur nomination au Conseil exécutif, étape concrète de la mise en pratique du gouvernement responsable.",
  observationGuide: ["Repérer l’autorité qui annonce les nominations.", "Identifier les fonctions confiées à La Fontaine et Baldwin.", "Relier la composition du Conseil exécutif à la majorité réformiste de l’Assemblée."],
  interpretationCautions: ["L’avis confirme les nominations, mais n’explique pas à lui seul le principe du gouvernement responsable.", "Ne pas présenter Elgin comme l’unique auteur de la réforme : la majorité électorale et la lutte des réformistes sont essentielles.", "La Fontaine et Baldwin représentent les deux sections de la Province du Canada."],
  pedagogicalUses: ["Établir le rôle de lord Elgin dans la formation du ministère de 1848.", "Relier la victoire électorale des réformistes à leur entrée au Conseil exécutif.", "Montrer comment le gouvernement responsable se met en place par une pratique politique concrète."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_ELGIN_GREY_MINISTRY_LETTER_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-006",
  title: "Elgin explique la formation du ministère La Fontaine–Baldwin",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["relationships_between_facts", "establish_facts"],
  historicalDate: "17 mars 1848",
  creator: "James Bruce, lord Elgin, gouverneur général de la Province du Canada",
  holdingInstitution: "Bibliothèque et Archives Canada; collection Elgin–Grey publiée par la Société Champlain",
  sourceUrl: "https://primarydocuments.ca/la-collection-elgin-grey-1846-1852-vol-1/?lang=fr",
  sourceLocator: "Elgin à Grey, lettre privée, Montréal, 17 mars 1848, The Elgin-Grey Papers, vol. 1, p. 135; passage sur la démission du ministère et la formation d’une nouvelle administration.",
  assetUrl: "https://primarydocuments.ca/wp-content/uploads/2018/04/ElginGreyV11937-1.pdf",
  rightsStatement: "Lettre de 1848 dans le domaine public; traduction-adaptation française abrégée préparée pour Socrato à partir de l’édition de 1937.",
  transcription: "Les anciens ministres ont remis leur démission. J’ai alors fait venir La Fontaine et Baldwin. Je leur ai indiqué qu’ils pouvaient former une administration capable de mériter et de conserver la confiance du Parlement et compter sur mon soutien constitutionnel.",
  accessibleDescription: "Extrait adapté d’une lettre dans laquelle lord Elgin raconte à lord Grey comment il a invité La Fontaine et Baldwin à former une administration soutenue par le Parlement.",
  historicalContext: "Le ministère conservateur est défait à l’Assemblée après les élections de 1848 et remet sa démission. Elgin rencontre ensuite La Fontaine et Baldwin, chefs de la majorité réformiste, afin qu’ils forment une administration possédant la confiance parlementaire.",
  observationGuide: ["Identifier les personnes qu’Elgin fait venir après la démission du ministère.", "Repérer la condition nécessaire pour que la nouvelle administration puisse gouverner.", "Distinguer le soutien constitutionnel du gouverneur de la confiance accordée par le Parlement."],
  interpretationCautions: ["Le texte est une traduction-adaptation abrégée, et non une transcription française originale.", "Le mot Parlement renvoie ici principalement à la confiance de la majorité de l’Assemblée élue.", "Ne pas conclure qu’Elgin crée seul le gouvernement responsable."],
  pedagogicalUses: ["Interpréter le principe de confiance parlementaire à partir du point de vue d’Elgin.", "Expliquer le rôle du gouverneur dans la formation d’un ministère responsable.", "Comparer une correspondance privée à l’avis officiel des nominations du 11 mars 1848."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_GEORGE_BROWN_COALITION_SPEECH_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-007",
  title: "George Brown justifie la formation de la Grande Coalition",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["causal_connections", "relationships_between_facts"],
  historicalDate: "14 juin 1864",
  creator: "George Brown, député du Canada-Ouest",
  holdingInstitution: "Débats parlementaires de la Province du Canada; transcription diffusée par le Macdonald-Laurier Institute",
  sourceUrl: "https://macdonaldlaurier.ca/speech-on-formation-of-the-great-coalition-june-14-186/",
  sourceLocator: "Discours de George Brown sur la formation de la Grande Coalition, 14 juin 1864; passages sur les difficultés entre les deux sections, la succession des crises ministérielles et l’alliance entre anciens adversaires.",
  assetUrl: "https://macdonaldlaurier.ca/speech-on-formation-of-the-great-coalition-june-14-186/",
  rightsStatement: "Discours parlementaire de 1864 dans le domaine public; traduction-adaptation française abrégée préparée pour Socrato.",
  transcription: "Depuis plusieurs années, les difficultés entre le Canada-Est et le Canada-Ouest rendent presque impossible un gouvernement paisible et efficace. Les élections et les crises ministérielles se succèdent sans apporter de solution durable. La crise actuelle justifie que d’anciens adversaires dépassent leurs divisions politiques et forment une coalition. Cette alliance ne vise pas des intérêts personnels ou ordinaires : elle doit permettre de régler les difficultés entre les deux sections et de rechercher une solution constitutionnelle juste pour chacune d’elles.",
  accessibleDescription: "Traduction-adaptation d’un discours dans lequel George Brown relie l’impasse entre les deux sections de la Province du Canada à la nécessité de former une coalition entre anciens adversaires.",
  historicalContext: "En juin 1864, le gouvernement Taché–Macdonald est défait lors d’un vote de confiance. Après plusieurs années d’instabilité ministérielle, George Brown accepte de collaborer avec des adversaires politiques afin de former la Grande Coalition et de rechercher une nouvelle organisation constitutionnelle.",
  observationGuide: ["Repérer les difficultés qui empêchent les gouvernements de durer.", "Identifier ce que Brown présente comme la réponse à la crise.", "Distinguer les intérêts partisans de l’objectif constitutionnel attribué à la coalition."],
  interpretationCautions: ["Le texte est une traduction-adaptation qui réunit plusieurs passages rapprochés du discours.", "Brown défend sa propre décision politique et cherche à la justifier devant l’Assemblée.", "La Grande Coalition ouvre la recherche d’une solution constitutionnelle, mais elle ne constitue pas encore la Confédération."],
  pedagogicalUses: ["Établir le lien causal entre l’instabilité ministérielle et la Grande Coalition.", "Interpréter le point de vue de George Brown sur le dépassement des divisions partisanes.", "Expliquer pourquoi la coalition est présentée comme une réponse exceptionnelle à une crise politique."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_METCALFE_RESIGNATION_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-002",
  title: "Metcalfe refuse de céder la prérogative de la Couronne",
  kind: "law-or-official-text",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["changes_and_continuities", "differences_and_similarities"],
  historicalDate: "28 novembre 1843",
  creator: "Charles Theophilus Metcalfe, gouverneur général de la Province du Canada",
  holdingInstitution: "Journaux de l’Assemblée législative de la Province du Canada; transcription reproduite par Project Gutenberg Canada",
  sourceUrl: "https://www.gutenberg.ca/ebooks/leacock-baldwin/leacock-baldwin-00-h-dir/leacock-baldwin-00-h.html",
  sourceLocator: "Chapitre VII, « The Metcalfe Crisis », réponse officielle de Metcalfe aux ministres démissionnaires, paragraphes 1106-1119.",
  assetUrl: "https://www.gutenberg.ca/ebooks/leacock-baldwin/leacock-baldwin-00-h-dir/leacock-baldwin-00-h.html",
  rightsStatement: "Document officiel de 1843 dans le domaine public; traduction-adaptation française rédigée pour Socrato.",
  transcription: "Je rencontrai le Conseil, sachant que ses membres démissionneraient puisque je refusais de revenir sur ma décision. Les propositions qui m’étaient présentées auraient constitué, selon moi, un abandon de la prérogative de la Couronne. Comme je répondais chaque fois par la négative, on me déclara : « Alors, nous devons démissionner. »",
  accessibleDescription: "Extrait textuel dans lequel Metcalfe relie son refus de céder une partie de l’autorité du gouverneur à la démission de ses ministres.",
  historicalContext: "En novembre 1843, Metcalfe refuse de s’engager à consulter systématiquement le Conseil exécutif avant les nominations. La Fontaine, Baldwin et la plupart des ministres démissionnent, puisqu’ils estiment ne pas pouvoir être responsables devant l’Assemblée sans être consultés sur les décisions du gouvernement.",
  observationGuide: ["Repérer le motif du refus de Metcalfe.", "Identifier la conséquence politique de son refus.", "Relier la prérogative de la Couronne au pouvoir exercé personnellement par le gouverneur."],
  interpretationCautions: ["Le document original est rédigé à la troisième personne au nom du gouverneur; l’extrait élève a été transposé à la première personne.", "Le texte est une traduction-adaptation abrégée et non une transcription intégrale.", "Présenter la démission comme la conséquence d’un désaccord constitutionnel, et non d’un simple conflit personnel."],
  pedagogicalUses: ["Expliquer la crise Metcalfe à partir du point de vue du gouverneur.", "Comparer l’exercice du pouvoir du gouverneur en 1843 et en 1849."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_ELGIN_NON_INTERVENTION_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-003",
  title: "Elgin maintient une position constitutionnelle de non-intervention",
  kind: "other",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["changes_and_continuities", "differences_and_similarities"],
  historicalDate: "mars-avril 1849",
  creator: "James Bruce, lord Elgin, gouverneur général de la Province du Canada",
  holdingInstitution: "Correspondance Elgin-Grey; transcription des lettres et journaux de lord Elgin par Project Gutenberg",
  sourceUrl: "https://www.gutenberg.org/cache/epub/10610/pg10610.html",
  sourceLocator: "Chapitre IV, section « Rebellion Losses Bill », passages sur la neutralité du gouverneur, la dissolution du Parlement et la sanction de la loi.",
  assetUrl: "https://www.gutenberg.org/cache/epub/10610/pg10610.html",
  rightsStatement: "Correspondance de 1849 dans le domaine public; traduction-adaptation française rédigée pour Socrato.",
  transcription: "Je maintins ma position constitutionnelle en écoutant avec respect toutes les protestations contre la mesure, sans toutefois intervenir dans le débat. Dissoudre un Parlement élu seulement un an auparavant parce qu’il avait adopté, à une forte majorité, une loi présentée par le gouvernement aurait été injustifiable. Je devais laisser la majorité parlementaire gouverner.",
  accessibleDescription: "Extrait textuel dans lequel Elgin explique pourquoi il refuse d’intervenir contre une loi adoptée par la majorité parlementaire.",
  historicalContext: "En 1849, le ministère La Fontaine-Baldwin fait adopter une loi visant à indemniser certaines personnes dont les biens ont été détruits pendant les Rébellions. Malgré les pétitions et les pressions qui lui demandent de dissoudre le Parlement ou de réserver la loi, Elgin la sanctionne et respecte ainsi la majorité parlementaire.",
  observationGuide: ["Repérer les moyens d’intervention qu’Elgin refuse d’utiliser.", "Identifier le rôle accordé à la majorité parlementaire.", "Comparer cette attitude avec celle de Metcalfe en 1843."],
  interpretationCautions: ["Le texte est une traduction-adaptation assemblée à partir de plusieurs passages rapprochés de la correspondance d’Elgin.", "La non-intervention ne signifie pas que le gouverneur perd ses pouvoirs formels.", "Elgin sanctionne la loi malgré son caractère controversé; il ne se prononce pas ici en faveur de chacune de ses dispositions."],
  pedagogicalUses: ["Montrer comment Elgin applique le gouvernement responsable.", "Distinguer la conservation des pouvoirs formels du gouverneur de leur nouvel usage constitutionnel."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_CANADIEN_PARLIAMENT_FIRE_DOCUMENT = {
  schemaVersion: 1,
  id: "GR-T-004",
  title: "Le Canadien raconte l’émeute et l’incendie du Parlement",
  kind: "newspaper",
  status: "ready-for-review",
  periodIds: ["1840-1896"],
  knowledgeHeadingIds: ["gouvernement-responsable"],
  operationIds: ["causes_and_consequences", "establish_facts"],
  historicalDate: "27 avril 1849",
  creator: "Correspondant du journal Le Canadien à Montréal",
  holdingInstitution: "Bibliothèque et Archives nationales du Québec",
  sourceUrl: "http://collections.banq.qc.ca/ark:/52327/1910543",
  sourceLocator: "Le Canadien, 27 avril 1849, « Lettre XXXVII », correspondance datée de Montréal, 26 avril 1849.",
  assetUrl: "http://collections.banq.qc.ca/ark:/52327/1910543",
  rightsStatement: "Journal de 1849 dans le domaine public; extrait abrégé et reformulé en français moderne pour Socrato. Les coupures sont signalées par […].",
  transcription: "À sa sortie du Parlement, Lord Elgin reçoit des œufs et d’autres projectiles lancés par des opposants. […] Le soir, une foule en colère se dirige vers le Parlement. Les émeutiers lancent des pierres dans les fenêtres, forcent les députés à quitter la salle, puis entrent dans l’édifice et détruisent le mobilier. […] Peu après, des témoins affirment avoir vu des émeutiers mettre le feu au bâtiment. Les flammes se propagent très rapidement en raison des conduites de gaz et de la grande quantité de livres et de documents présents dans l’édifice.",
  accessibleDescription: "Extrait de journal reformulé relatant l’attaque contre Lord Elgin, l’invasion du Parlement de Montréal et le déclenchement de l’incendie.",
  historicalContext: "Le 25 avril 1849, Lord Elgin sanctionne la loi d’indemnisation adoptée par la majorité parlementaire. Des opposants à cette décision se rassemblent, envahissent le Parlement de Montréal et y mettent le feu.",
  observationGuide: ["Identifier la personne attaquée à la sortie du Parlement.", "Repérer les étapes qui transforment la manifestation en émeute.", "Relier les gestes des émeutiers au déclenchement de l’incendie."],
  interpretationCautions: ["Le texte est une reformulation en français moderne, et non une transcription mot à mot.", "Les […] signalent des passages retirés entre les segments retenus.", "Le journal Le Canadien appuie les réformistes et condamne les émeutiers tories."],
  pedagogicalUses: ["Déterminer la cause politique des émeutes et de l’incendie.", "Reconstituer la succession des événements à partir d’un témoignage journalistique contemporain."],
  version: "1.0",
  approvedAt: null,
} as const satisfies HistoricalDocumentRecord;

export const RESPONSIBLE_GOVERNMENT_METCALFE_ELGIN_DOCUMENTS = [
  RESPONSIBLE_GOVERNMENT_ELGIN_MINISTRY_APPOINTMENTS_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_ELGIN_GREY_MINISTRY_LETTER_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_GEORGE_BROWN_COALITION_SPEECH_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_METCALFE_RESIGNATION_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_ELGIN_NON_INTERVENTION_DOCUMENT,
  RESPONSIBLE_GOVERNMENT_CANADIEN_PARLIAMENT_FIRE_DOCUMENT,
] as const;
